### ISSUE TITLE
Vagrant builds' json have the wrong URL

### ISSUE THREAD

**Issue by iaguis** [flatcar/Flatcar#1]
The generated files for vagrant builds include a json file that describes the box and includes its URL.

The generated URL is wrong, since it doesn't point to where the file actually is.

For example, in https://alpha.release.flatcar-linux.net/amd64-usr/1722.0.0/flatcar_production_vagrant.json, the `url` field should be `https://alpha.release.flatcar-linux.net/amd64-usr/1722.0.0/flatcar_production_vagrant.box` but it's not.

**Comment by chrskhl** [comment]
Can we fix this before release?
Or at least manually patch it for each release?

**Comment by chrskhl** [comment]
@iaguis we have done this manually for the most recent releases, right?

**Comment by iaguis** [comment]
> @iaguis we have done this manually for the most recent releases, right?

Yes

**Comment by dongsupark** [comment]
What happens here is like this:

The function `download_image_url()` in release_util.sh [simply assumes](https://github.com/flatcar-linux/scripts/blob/2a42e8b2928e9d36d775991946657445ba3c7294/build_library/release_util.sh#L234) that the input variable `download_root` include `gs://builds.release.core-os.net/alpha` in `GS_RELEASE_ROOT` of resource variables. That's true only for [Container Linux](https://github.com/coreos/jenkins-os/blob/master/resources/com/coreos/profiles/alpha.json). In case of [Flatcar Linux](https://github.com/kinvolk/jenkins-secret/blob/master/resources/com/coreos/profiles/flatcar-alpha.json), the `download_root` is actually `gs://flatcar-jenkins/alpha`.

What we should do here is to check for `flatcar-jenkins` in `download_root`. If it's true, we should reconstruct the `download_path` as `<channel name>.release.flatcar-linux.net/...`.
Also we should change `http` to `https` to be used for Flatcar servers.

Doing that, we will not need to run `fix_vagrant.sh` for every release.

**Comment by dongsupark** [comment]
https://github.com/flatcar-linux/scripts/pull/8 was reviewed and merged.
Thanks for review, Iago!

**Comment by dongsupark** [comment]
Fixed.
We can close this issue.
