### ISSUE TITLE
Flatcar Container Linux release cycle / cadence

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#100]
**Description**
Establish a regular release cycle and create public documentation of the Flatcar Container Linux release cadence for Alpha, Beta, Stable channels.

**Impact**
Releases happen at a regular cadence, and users can rely on regular updates.

**Comment by vbatts** [comment]
this is done

**Comment by cespo** [comment]
Hi @vbatts ,
Could you point me to the public documentation page?

**Comment by vbatts** [comment]
hey @cespo!

Looking back at this, I closed this after we had concluded internal coordination on the release cadence, but we did not formally post anything public about this cadence.
It seems that the most logical spot for this would be https://github.com/kinvolk/flatcar#release-process, but maybe also somewhere on https://kinvolk.io/docs/flatcar-container-linux/latest/ ...

I'll open an issue requesting updates to the docs for this.
