### ISSUE TITLE
Fresh rebuild of flatcar VM fails to boot because docker.socket is not found by ignition

### ISSUE THREAD

**Issue by elafontaine** [flatcar/Flatcar#1004]
## Description

I will continue to document my finding throughout the day, but at the moment we have an image that we have uploaded to 3 site and are unable to boot a new machine because the docker.socket service file doesn't exist (and so ignition can't disable it).  

The message we get on the console is the following (see image);
![image](https://user-images.githubusercontent.com/3026004/233131525-a27ebb4a-8d09-48db-adfb-b0483e09b982.png)

When booting without any ignition configuration, we do get the docker.socket unit available and started.  The thing is that it's not a recommended setup for production environment for getting containers to be started at boot (as per flatcar own recommendation);
https://www.flatcar.org/docs/latest/container-runtimes/getting-started-with-docker/#permanently-running-a-container

NOTE; The upgrade of already running instances worked flawlessly, it's only when we try to do a "rebuild" of the server from our openstack.

## Impact

Can't deploy freshly machines with this image.  Need to deploy with an older image and apply updates.

## Environment and steps to reproduce

1. **Set-up**: Deploy a new VM with the openstack image and pass it the systemd unit configuration for docker.socket
```
systemd:
  units:
    -  name: "docker.socket"
        enabled: false
```
2. **Task**: Let the VM boot
3. **Action(s)**: No Action made
4. **Error**: ![image](https://user-images.githubusercontent.com/3026004/233131525-a27ebb4a-8d09-48db-adfb-b0483e09b982.png)

## Expected behavior

Have the docker.socket unit deactivated like suggested in the documentation

## Additional information

Relevant information for our configuration; 
```
systemd:
  units:
    -  name: "docker.socket"
        enabled: false
```
We used the image from https://stable.release.flatcar-linux.net/amd64-usr/3510.2.0/flatcar_production_openstack_image.img.bz2  (https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_openstack_image.img.bz2 ) as we are running in an openstack Queens

I will keep you posted on our findings, but please do let us know if you get the issue as well or are able to reproduce, we are concern that this could be an issue from our side.

We have also try downloading the image again and compared our checksums with the one we have, no issues found there.

We will start using the old image to spawn our machine and trigger the update.

**Comment by elafontaine** [comment]
Edited to fit the bug template (I found it after).

**Comment by tormath1** [comment]
Hello @elafontaine and thanks the report,

comparing the current Stable with the previous one, I noticed this:

new stable-3510.2.0:
```
bash-5.1# systemctl --root=/sysroot disable docker.socket
Failed to disable unit, unit docker.socket does not exist.
bash-5.1# echo $?
1
```

previous stable-3374.2.5
```
bash-5.1# systemctl --root=/sysroot disable docker.socket
Failed to disable unit, unit docker.socket does not exist.
bash-5.1# echo $?
0
```

as Ignition relies on the `systemctl ... disable docker.socket` command (see: [exec/util/unit.go#L163-L166](https://github.com/coreos/ignition/blob/6e542868f1cceb81bd779836a9f2ab23b004a23d/internal/exec/util/unit.go#L163-L166)) I would assume it's the point of failure.

One workaround would be to manually add the preset:
```yaml
storage:
  files:
    - path: /etc/systemd/system-preset/30-docker.preset
      contents:
        inline: disable docker.socket
```

OTOH It seems that `docker.socket` is **always** enabled by Torcx so I'm not 100% sure this documentation (disable docker.socket) is still relevant.

**Comment by elafontaine** [comment]
Good catch Mathieu.   I think you might be onto something.  Thanks for the feedback.

So probably we should transform this ticket to change the documentation.  My tests yesterday also indicate to me that the docker socket is always started, so not sure how relevant this is to address then.

**Comment by tormath1** [comment]
@elafontaine I think it's extremely relevant, I opened a follow-up issue on Ignition side to decide how to treat deactivation of non-existing units - the unit actually exists but not in the initramfs as it's loaded later by Torcx

**Comment by tormath1** [comment]
Documentation PR has been merged let's close this in favor of https://github.com/coreos/ignition/issues/1614. Thanks for the report!
