### ISSUE TITLE
No installation guidance for Hyper-V

### ISSUE THREAD

**Issue by jrose-qualys** [flatcar/Flatcar#1009]
Hello,
We need some details on the best practices for installation of Flatcar Container Linux on Hyper-V.
- how to gain support for VHDX disks
- how to support Hyper-V Live MIgration (in the same way that open-vm-tools will allow Flarcar to support VMWare Vmotion).

Hyper-V being a Microsoft product, and Kinvolk being bought by Microsoft, you should have direct access to Hyper-V developers who can help make Flatcar on Hyper-V a seamless proposition.

Regards
Joe

**Comment by fsdrw08** [comment]
any updates? coreos had already support hyper-v

**Comment by jepio** [comment]
Just looked at this. The ignition support for Hyper-V is in alpha right now.

We need the following to make it work:
- [x] docs
- [x] We need to switch the generated img over to vhdx
- [x] We should consider using a different compression that is more Windows friendly.
- [x] We need the hv_utils module in the initramfs to get ignition to work
- [x] powershell script to make it easy for people to try this out

**Comment by jrose-qualys** [comment]
Hi Jeremi,
     Regarding the HyperV support, there’s a list of things needed :

  *    VHDX support is long overdue and we’re often asked for this by customers who want to use dynamic disks ..they cannot do this today
  *   In testing vSCSI driver (4 channels, 8 disks per channel on SCSI ID 0-7) did not work, so our customers have been limited to vIDE and 2 disks only.
  *   HyperV live migration support would allow a live Qualys QGS appliance running on Flatcar then HyperV hosting to be moved without any shutdown/ restart operation… similar to vmotion on VMware .

      Many thanks.

Regards
Joe

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ader1990** [comment]
Hello @jrose-qualys,

Adding the VHDX support would be rather easy, as it is just a quick fix.

An important question would be if you also still need the VHD image at the same time, or we can remove it the VHD and offer just VHDX?

Thank you.

**Comment by jrose-qualys** [comment]
Hi Adrian,
                It would be useful to have both.

                Key with HyperV is being able to use VHDX and Gen2 VMs – currently this does not work.

                Customers complain about the VHD fixed disks – the time taken to format, especially with iSCSI storage, is quite long. – 20-30 mins sometimes.

Appliance with VHD fixed disks, Gen1 VMs                       working
Appliance with VHDX dynamic disks, Gen1 VMs            failed
Appliance with VHDX dynamic disks, Gen2 VMs            failed (no VHD option)

                My big concern is support for VHDX and Gen2 as Gen1+VHD may disappear from new releases, such as Windows Server 2025 with HyperV service, either at GA release or later, e.g. 26H1 release.

                Many thanks.

Regards
Joseph Rose
Technical Product Manager @ Qualys

From: Adrian Vladu ***@***.***>
Date: Monday, 25 March 2024 at 13:22
To: flatcar/Flatcar ***@***.***>
Cc: Joseph Rose ***@***.***>, Mention ***@***.***>
Subject: Re: [flatcar/Flatcar] No installation guidance for Hyper-V (Issue #1009)

Hello @jrose-qualys [github.com]<https://urldefense.com/v3/__https:/github.com/jrose-qualys__;!!Pw1rFClp!uj6gVbTet1S3WaLRmlMjowayTWF9oCnE7RA0wBAHCDPb0tVMrJ-ZdTaSmktVyr5OeSrftISSqNFDouNYO56Nbrs$>,

Adding the VHDX support would be rather easy, as it is just a quick fix.

An important question would be if you also still need the VHD image at the same time, or we can remove it the VHD and offer just VHDX?

Thank you.

**Comment by ader1990** [comment]
> Just looked at this. The ignition support for Hyper-V is in alpha right now.
> 
> We need the following to make it work:
> 
> * [ ]  docs
> * [ ]  We need to switch the generated img over to vhdx
> * [ ]  We should consider using a different compression that is more Windows friendly.
> * [ ]  We need the hv_utils module in the initramfs to get ignition to work
> * [ ]  powershell script to make it easy for people to try this out

`We need the hv_utils module in the initramfs to get ignition to work` - implemented by https://github.com/flatcar/bootengine/pull/92
`We need to switch the generated img over to vhdx` - work in progress by https://github.com/flatcar/scripts/pull/1791

**Comment by ader1990** [comment]
Hello @jrose-qualys,

You can find a .vhdx image built here: https://bincache.flatcar-linux.net/images/amd64/9999.9.9+ader1990-hyperv-vhdx-support/, using the PR code from https://github.com/flatcar/scripts/pull/1791.

Image direct download link: https://bincache.flatcar-linux.net/images/amd64/9999.9.9+ader1990-hyperv-vhdx-support/flatcar_production_hyperv_vhdx_image.vhdx.bz2.

Please let us know if the image works in your environment.
Currently, the image is not secure boot signed and it needs Secure Boot to be disabled when used with a Gen2 Hyper-V VM.

Thank you.

**Comment by ader1990** [comment]
> Just looked at this. The ignition support for Hyper-V is in alpha right now.
> 
> We need the following to make it work:
> 
> * [ ]  docs
> * [x]  We need to switch the generated img over to vhdx
> * [ ]  We should consider using a different compression that is more Windows friendly.
> * [x]  We need the hv_utils module in the initramfs to get ignition to work
> * [ ]  powershell script to make it easy for people to try this out

VHDX support is merged, as well as the introduction of the hv_utils module in initrd.
https://github.com/flatcar/scripts/pull/1791
https://github.com/flatcar/bootengine/pull/92

Docs will include the powershell script to try out Flatcar on Hyper-V:
https://github.com/flatcar/flatcar-website/pull/315

**Comment by jrose-qualys** [comment]
Hi,
                It’s good to see HyperV receiving some attention.

                As part of the move to VHDX, can we also ensure:

  *   Live migration support is there, just as you do for openvm-tools and libvirtd on KVM ?
  *   vSCSI disk support provides 4 channels of 8 devices, which is much more scalable than vIDE, which is all that has so far worked , in the testing that Qualys has done, internally and with customers

Since HyperV is Microsoft’s hypervisor, the support needs to be on par with VMWare 😊

Regards
Joseph Rose
Technical Product Manager @ Qualys

From: Adrian Vladu ***@***.***>
Date: Tuesday, 9 April 2024 at 15:32
To: flatcar/Flatcar ***@***.***>
Cc: Joseph Rose ***@***.***>, Mention ***@***.***>
Subject: Re: [flatcar/Flatcar] No installation guidance for Hyper-V (Issue #1009)

Just looked at this. The ignition support for Hyper-V is in alpha right now.

We need the following to make it work:

  *   docs
  *   We need to switch the generated img over to vhdx
  *   We should consider using a different compression that is more Windows friendly.
  *   We need the hv_utils module in the initramfs to get ignition to work
  *   powershell script to make it easy for people to try this out

VHDX support is merged, as well as the introduction of the hv_utils module in initrd.
flatcar/scripts#1791 [github.com]<https://urldefense.com/v3/__https:/github.com/flatcar/scripts/pull/1791__;!!Pw1rFClp!rxAL7qocZIKWYhguVvISJachKL0MkMrxKpjeQW5aD5VAF93iApyZJRtL_-zfPfbTvLvAf8ARILMlTR1X1J05_UU$>
flatcar/bootengine#92 [github.com]<https://urldefense.com/v3/__https:/github.com/flatcar/bootengine/pull/92__;!!Pw1rFClp!rxAL7qocZIKWYhguVvISJachKL0MkMrxKpjeQW5aD5VAF93iApyZJRtL_-zfPfbTvLvAf8ARILMlTR1Xm53bfzY$>

Docs will include the powershell script to try out Flatcar on Hyper-V:
flatcar/flatcar-website#315 [github.com]<https://urldefense.com/v3/__https:/github.com/flatcar/flatcar-website/pull/315__;!!Pw1rFClp!rxAL7qocZIKWYhguVvISJachKL0MkMrxKpjeQW5aD5VAF93iApyZJRtL_-zfPfbTvLvAf8ARILMlTR1XqCHPGWg$>

**Comment by ader1990** [comment]
Hello, the Hyper-V images and the documentation have been created. Also, the hyper-v daemons are now included in the Hyper-V image too.

Please let us know if there are any issues or improvements required to close the issue.

Thanks,
Adrian

**Comment by ader1990** [comment]
Closing this issue, as the documentation and required improvements were merged.
