### ISSUE TITLE
add regex support to the jq status

### ISSUE THREAD

**Issue by samm-git** [flatcar/Flatcar#101]
**Current situation**

As a flatcar user i would like to use regex capabilities of the JQ tool. However, it is not possible because it was built without ONIGURUMA library support

```
echo '["xabcd", "ABC"]'| jq '.[] | test("a b c # spaces are ignored"; "ix")'
jq: error (at <stdin>:1): jq was compiled without ONIGURUMA regex libary. match/test/sub and related functions are not available.
```

**Impact**

It is not possible to use JQ regexp functionality, which prevents me from using filtering or search in jq. Also it makes many shell recipes not compatible with the Flatcar linux.

**Ideal future situation**

JQ is linked with ONIGURUMA. Test should pass:

```
$ echo '["xabcd", "ABC"]'| jq '.[] | test("a b c # spaces are ignored"; "ix")'
true
true
```

**Implementation options**

Build jq with regex support (see https://github.com/flatcar-linux/portage-stable/blob/flatcar-master/app-misc/jq/jq-1.5-r2.ebuild), using static or dynamic link option.

**Additional information**
If you think its a good change which will be accepted - i can work on the PR. And thank you very much for keeping container linux up and running!

**Comment by dongsupark** [comment]
Commented in the PR: https://github.com/flatcar-linux/coreos-overlay/pull/320#issuecomment-620513858

**Comment by samm-git** [comment]
@dongsupark i think we can close this ticket, just short q, do you know any ETA when it would come to alpha->beta->stable builds?

**Comment by dongsupark** [comment]
Yes, we are working on new releases, starting from a new Alpha.
After that, a new Beta release will follow.
Not sure exactly when. We will keep you informed.
