### ISSUE TITLE
Where to find latest manifests?

### ISSUE THREAD

**Issue by a-v-kovtun-mipt-95** [flatcar/Flatcar#1013]
Usually I use https://github.com/kinvolk/manifest.git project to build Flatcar Linux. For example, I use https://github.com/kinvolk/manifest/blob/flatcar-stable-3227.2.2/release.xml to build version 3227.2.2. Now I can`t find the same for latest release 3510.2.1. Could you help me?

**Comment by dongsupark** [comment]
Release manifests are being updated on https://github.com/flatcar/scripts.
e.g. https://github.com/flatcar/scripts/blob/stable-3510.2.1/sdk_container/.repo/manifests/version.txt

**Comment by pothos** [comment]
The way of building changed, we don't use cork anymore but use a Docker wrapper script:
https://www.flatcar.org/docs/latest/reference/developer-guides/sdk-modifying-flatcar/

**Comment by a-v-kovtun-mipt-95** [comment]
I tried to build version 3227.2.2 with a cork. I faced with issue below. Could you help me with it?
![image](https://user-images.githubusercontent.com/34024533/236450528-b3d9056a-d470-4db4-83f8-d2aa86be4d54.png)

**Comment by tormath1** [comment]
Hello @a-v-kovtun-mipt-95, as mentioned by @pothos - Flatcar does not use `cork` anymore to build Flatcar:
> The way of building changed, we don't use cork anymore but use a Docker wrapper script:

Any chance to give a try with the documentation: https://www.flatcar.org/docs/latest/reference/developer-guides/sdk-modifying-flatcar/#getting-started ?

**Comment by pothos** [comment]
I'll close now but feel free to continue the discussion
