### ISSUE TITLE
Access to update servers from behind firewall

### ISSUE THREAD

**Issue by twendt** [flatcar/Flatcar#102]
**Description**
We are trying to run Flatcar behind a firewall. Is there a list of IPs available somewhere that are required for the update engine?

**Impact**

Update not working due to missing firewall rules.

**Environment and steps to reproduce**
Setup Flatcar behind a firewall and try to update.

**Expected behavior**
If we could retrieve the list of IPs used by the update servers, then we would be able to configure the firewall correctly.

**Additional information**
Something like github is using would be great: https://api.github.com/meta

**Comment by pothos** [comment]
The update server is available through AWS load balancers in various regions. We don't expect the load balancers to change their IP address in the near future unless we change the whole setup. There is no status page yet where we would announce those changes and display the current state.

Depending on your region (here from eu-central-1 area), you can see the IP addresses as follows:
```
dig @8.8.8.8 public.update.flatcar-linux.net
public.update.flatcar-linux.net. 59 IN	CNAME	nebraska-lb-746246376.eu-central-1.elb.amazonaws.com.
nebraska-lb-746246376.eu-central-1.elb.amazonaws.com. 59 IN A 52.29.154.92
nebraska-lb-746246376.eu-central-1.elb.amazonaws.com. 59 IN A 35.157.50.22
nebraska-lb-746246376.eu-central-1.elb.amazonaws.com. 59 IN A 3.120.160.92
```

**Comment by twendt** [comment]
Thanks for the update.

What about `update.release.flatcar-linux.net`, that seems to be the bigger issue in our case since that only returns a single IP, but that IP changes between requests. My understanding from the logs is, that both addresses are used during the update process.

I ran a test over night by resolving the name every 10 seconds and got the following list of IPs:
```
147.75.84.217
147.75.82.50
147.75.82.34
```

**Comment by pothos** [comment]
The caching servers are also up to three per region. Unfortunately the AWS DNS mechanism for them is different and you will get only one IP address for each query. So yes, querying until you see that the responses are stable would work. But again, they can change in the future.

**Comment by pothos** [comment]
I filed an issue for a status page: https://github.com/flatcar-linux/Flatcar/issues/105

**Comment by twendt** [comment]
That is great, thank you very much.

I think you can close this issue then.
