### ISSUE TITLE
Parse/decode CrAU protobuf format

### ISSUE THREAD

**Issue by wrl** [flatcar/Flatcar#1025]
- [x] Decode and read the CrAU update format. (https://github.com/flatcar/ue-rs/pull/8)
- [x] Deal with 2 different versions of update payloads.
   (A script for decoding the payload is available in [update_engine](https://github.com/flatcar/update_engine/blob/flatcar-master/decode_payload), which deals with 2 different formats of the protobuf header, i.e. the 2 signature vs 1 signature case (2 is prod key, 1 is dev key). (https://github.com/flatcar/ue-rs/pull/9)

**Comment by dongsupark** [comment]
PR https://github.com/flatcar/ue-rs/pull/8

**Comment by dongsupark** [comment]
PR https://github.com/flatcar/ue-rs/pull/9
