### ISSUE TITLE
rustfmt configuration

### ISSUE THREAD

**Issue by wrl** [flatcar/Flatcar#1026]
* Come up with a minimal `rustfmt.toml` to consistently run `rustfmt` on [ue-rs](https://github.com/flatcar/ue-rs) whenever possible.
* Ideally, create a GitHub Actions workflow in ue-rs to run rustfmt on each open PR.

**Comment by dongsupark** [comment]
Wrote the description, assigned myself.

**Comment by dongsupark** [comment]
PR https://github.com/flatcar/ue-rs/pull/4
