### ISSUE TITLE
Signature Verification

### ISSUE THREAD

**Issue by wrl** [flatcar/Flatcar#1027]
Full implementation depends on #1025 but initial work on the crypto code does not.

Would be possible to use OpenSSL (via the [openssl crate](https://lib.rs/crates/openssl)) update-engine does, but there's also the [RSA crate](https://lib.rs/crates/rsa) which provides a pure-Rust implementation of signing and verification. I think the RSA crate is the better idea to start with, and we should only resort to OpenSSL if the RSA crate doesn't work for us.

**Comment by dongsupark** [comment]
A draft PR https://github.com/flatcar/ue-rs/pull/7

**Comment by dongsupark** [comment]
PR https://github.com/flatcar/ue-rs/pull/7 was merged.
