### ISSUE TITLE
Azure cloud-init support

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#103]
**Current situation**
Azure shows that cloud-init/Cloud-Config is not supported for the current Flatcar CL offers. In general, a subset of is supported by Flatcar CL through coreos-cloudinit.

In the _Advanced_ tab during VM creation:
_Cloud init: Cloud init is a widely used approach to customize a Linux VM as it boots for the first time. You can use cloud-init to install packages and write files or to configure users and security. Learn more
The selected image does not support cloud init._

**Impact**
Users may think that cloud-init is not supported and not know how to specify the userdata (the same was as an Ignition config).

**Ideal future situation**
The warning that cloud-init is not supported disappears.

**Additional information**
This is a known problem for Azure and they will enable it for more OS offers soon.

**Comment by tormath1** [comment]
I think we can close it now. The helper is now saying:
> If your image supports cloud-init, custom-data will be processed by cloud-init.
