### ISSUE TITLE
Flatcar arm64 running on QEMU (kvm enabled) does not have video output when using VNC

### ISSUE THREAD

**Issue by ader1990** [flatcar/Flatcar#1030]
I am trying to run a flatcar arm64 image on qemu-kvm (accel = kvm) with VNC console configured - VNC console just shows "Display output is not active" after the grub2 boots the kernel.

With Flatcar (tried every release channel flatcar_production_qemu_uefi_[image.img.bz](http://image.img.bz/)2), I see the bootloader menu - grub version 2.02, then the boot process seems to continue as expected -- but the VNC console just shows "Display output is not active".

This looks to be a Linux configuration issue, anyone happen to know what are the missing flags or maybe I can try a special linux cmdline param to test?

For example, Ubuntu works with no issues (so there is not a problem on my setup).

I have seen that in your [flatcar_production_qemu_uefi.sh](https://alpha.release.flatcar-linux.net/arm64-usr/current/flatcar_production_qemu_uefi.sh) script, you are suggesting to run with -nographic, which works great for its purpose, but I would like to use VNC.

Here are the reproduction steps (on an Ubuntu 22.04 ARM64 AMPERE ALTRA):

```
# under root
dd if=/dev/zero of=flash0.img bs=1M count=64
dd if=/dev/zero of=flash1.img bs=1M count=64

# tried with the flatcar provided bootloaders, same issue. secureboot was disabled.
dd if=/usr/share/qemu-efi-aarch64/QEMU_EFI.fd of=flash0.img conv=notrunc

wget https://lts.release.flatcar-linux.net/arm64-usr/current/flatcar_production_qemu_uefi_image.img.bz2
bzip2 -d ./flatcar_production_qemu_uefi_image.img.bz2

qemu-system-aarch64 -smp 4 -m 4096 -k en-us \
       -device usb-ehci -device usb-kbd -device usb-mouse -usb \
       -netdev user,id=vnet,hostfwd=:127.0.0.1:0-:22 -device virtio-net-pci,netdev=vnet \
       -drive file=flatcar_production_qemu_uefi_image.img,if=none,id=drive0,cache=writeback -device virtio-blk,drive=drive0,bootindex=0 \
       -drive file=flash0.img,format=raw,if=pflash -drive file=flash1.img,format=raw,if=pflash  -cpu host \
       -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0 \
       --vnc 0.0.0.0:1 \
       -machine virt,accel=kvm,gic-version=host -device virtio-gpu-pci
```

**Comment by pothos** [comment]
Sounds like the virtio GPU is the problem, maybe Flatcar doesn't have the driver? Does the VNC feature also work with another emulated graphics card?

**Comment by pothos** [comment]
Maybe you can also test this with the amd64 image on your laptop to see the differences with arm64.

**Comment by ader1990** [comment]
> Maybe you can also test this with the amd64 image on your laptop to see the differences with arm64.

I do not think the same drivers / config options for the linux kernel apply -- as usually there are different config trees. Do you happen to know where the flatcar-arm64 linux kernel config is to compare with a working Ubuntu kernel?

Thank you.

**Comment by ader1990** [comment]
From the running flatcar with -nographic:

```
grep -ira virtio config
CONFIG_BLK_MQ_VIRTIO=y
CONFIG_VIRTIO_VSOCKETS=m
CONFIG_VIRTIO_VSOCKETS_COMMON=m
CONFIG_NET_9P_VIRTIO=m
CONFIG_VIRTIO_BLK=m
CONFIG_SCSI_VIRTIO=m
CONFIG_VIRTIO_NET=m
CONFIG_VIRTIO_CONSOLE=m
CONFIG_HW_RANDOM_VIRTIO=y
CONFIG_VIRTIO=y
CONFIG_VIRTIO_MENU=y
CONFIG_VIRTIO_PCI=y
CONFIG_VIRTIO_PCI_LEGACY=y
CONFIG_VIRTIO_BALLOON=m
CONFIG_VIRTIO_INPUT=m
CONFIG_VIRTIO_MMIO=y
CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES=y
# CONFIG_RPMSG_VIRTIO is not set
# CONFIG_VIRTIO_FS is not set
# CONFIG_CRYPTO_DEV_VIRTIO is not set

```

From the Ubuntu:

```
grep -ira virtio /boot/config-5.15.0-71-generic
CONFIG_BLK_MQ_VIRTIO=y
CONFIG_VIRTIO_VSOCKETS=m
CONFIG_VIRTIO_VSOCKETS_COMMON=m
CONFIG_BT_VIRTIO=m
CONFIG_NET_9P_VIRTIO=m
CONFIG_ARM_SCMI_TRANSPORT_VIRTIO=y
CONFIG_VIRTIO_BLK=m
CONFIG_SCSI_VIRTIO=m
CONFIG_VIRTIO_NET=m
CONFIG_CAIF_VIRTIO=m
CONFIG_VIRTIO_CONSOLE=y
CONFIG_HW_RANDOM_VIRTIO=m
CONFIG_I2C_VIRTIO=m
CONFIG_GPIO_VIRTIO=m
CONFIG_DRM_VIRTIO_GPU=m
CONFIG_SND_VIRTIO=m
CONFIG_VIRTIO=y
CONFIG_VIRTIO_PCI_LIB=y
CONFIG_VIRTIO_MENU=y
CONFIG_VIRTIO_PCI=y
CONFIG_VIRTIO_PCI_LEGACY=y
CONFIG_VIRTIO_VDPA=m
CONFIG_VIRTIO_PMEM=m
CONFIG_VIRTIO_BALLOON=y
CONFIG_VIRTIO_INPUT=m
CONFIG_VIRTIO_MMIO=y
CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES=y
CONFIG_VIRTIO_DMA_SHARED_BUFFER=m
CONFIG_VIRTIO_IOMMU=y
CONFIG_RPMSG_VIRTIO=m
CONFIG_VIRTIO_FS=m
CONFIG_CRYPTO_DEV_VIRTIO=m

```

**Comment by ader1990** [comment]
The main difference would be the CONFIG_DRM_VIRTIO_GPU -- I suppose it is worth a try?

**Comment by pothos** [comment]
Yes, you can add it here https://github.com/flatcar/scripts/tree/main/sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files to the common config. Filing a PR will give you a link to the built image after some time where you can test it. Otherwise, you can check https://www.flatcar.org/docs/latest/reference/developer-guides/sdk-modifying-flatcar/ for building on your own.
