### ISSUE TITLE
Extend Flatcar quickstart guide

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#1036]
Mathieu has created a tutorial which could be reused by extending the quickstart guide.

**Comment by tormath1** [comment]
Tutorial is located here: https://github.com/tormath1/flatcar-tutorial

I was planning to define a new section in the Flatcar documentation.
```
# Tutorial
## Overview
## Discovering
## Provisioning
## Deploying
## Updating
```

What do you think?
