### ISSUE TITLE
scripts build and test: fix report generation, parallelisation

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#1046]
The build and test workflow and pr comment command dispatcher suffer a number of issues we want to fix:
- Currently only a single build can run. Job parallelisation needs to be extended.
- Also, the test report is not posted to the PR because the pr comment command dispatcher runs on a issue_command event instead of a pr event.

**Comment by pothos** [comment]
Here a symptom I just ran into with the current parallelization setting. The queued action for my PR got stopped with `Canceling since a higher priority waiting request for 'PR command build dispatcher-pr-command-main' exists`.

**Comment by gabriel-samfira** [comment]
IMO the current comment dispatch implementation is worth the extra workflow if we want to do some out-of-band ACLs for dispatching workflows for certain repositories.

For example, this is useful if we'll at some point create a ```maintainers``` repository with some files in it, where we grant certain github users access to trigger workflows on *some* repos but not others, or if we want to grant some users this ability without adding them to the org.

If we plan to allow only maintainers to use the comment dispatch, we could just enable approvals for all workflow runs and maintainers could just self-approve the workflow run from the github PR.

In the old implementation, concurrency was scoped to PRs. A subsequent push to the same PR would cancel the job for that PR. A different PR could run it's own job without waiting for a separate PR to finish. It appears that when dispatching manually or via comment, the scope is shared between PRs.

**Comment by t-lo** [comment]
Yupp, it's the PR ID in `concurrency:`; that changed since we're now acting on an `issue_comment` event. Same for the step that posted test results to PRs as comments - the PR id needs to be extracted differently (`github.event.issue.pull_request.number` instead of `github.event.pull_request.number`).

Work in progress here: https://github.com/flatcar/scripts/pull/846

What puzzles me is that I can't seem to cancel a workflow within a step anymore - https://github.com/flatcar/scripts/actions/runs/5088542507/jobs/9145076938 keeps running even though I've manually cancelled _and_ a follow-up https://github.com/flatcar/scripts/actions/runs/5088652410 is pending.
