### ISSUE TITLE
Propose a mechanism to enable sysext builds in the OS image build process

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#1052]
The OS image we currently produce is unsuitable as a base for building Flatcar specific sysext images: it lacks package information and portage configuration. During the image build process our low-level build automation removes this information from the OS image to keep it lean.

In order to build sysext images suitable for running on a specific OS release, the image build needs to be extended to produce artifacts retaining this information.

Part of the work is already in progress here: https://github.com/flatcar/scripts/pull/858

This issue builds on that work with the aim to make it more generally usable for all future Flatcar / version specific sysext builds.

**Comment by t-lo** [comment]
@krishjainx wanted to look into this.

**Comment by krishjainx** [comment]
I think we can already close this since it's merged? @t-lo

**Comment by jepio** [comment]
Not until the build process produces docker/containerd sysexts that work.

**Comment by t-lo** [comment]
Good point, @jepio .
PR was merged and will be in Alpha-3654  (https://github.com/flatcar/scripts/pull/920).
Also, we're using `build_sysext` now to build the OEM sysexts (https://github.com/flatcar/scripts/pull/969).

**Comment by pothos** [comment]
The script is now used for both the OEMs as well as the inbuilt Docker+containerd sysext images.
