### ISSUE TITLE
[RFE] sshd default config should read drop-ins

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#1062]
## Current situation

Customization of the sshd config requires a modification of the original file. While this should work with a regular file we still didn't convert it back from being a symlink to `/usr`. But even with a regular file, this would mean losing auto updates.

## Impact

Customization is hard and loses auto updates.

## Ideal future situation

We have `Include /etc/ssh/sshd_config.d/*.conf` in the default config, so that users can use drop-ins as on, e.g., Fedora.

## Implementation options

While at it, also stop using a symlink and instead install the default to /etc (or if the default under /usr works, use that and have nothing in /etc).

**Comment by tormath1** [comment]
FWIW Gentoo has recently made the switch too:
* https://www.gentoo.org/support/news-items/2023-05-11-openssh.html 
* https://github.com/gentoo/gentoo/commit/51642f0e13ab03de8a6c3fc729185f96b1618200

**Comment by dongsupark** [comment]
Moved to backlog
