### ISSUE TITLE
A New Modern Variant of FlatCar.

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [flatcar/Flatcar#1071]
The current variant is Docker/Podman/Pods/Distrobox ONLY "default". Many globally including myself would like to see more LXC/LXD inclusion. Read about it here... "https://thenewstack.io/flockport-time-to-start-all-over-again-and-return-to-lxc-containers/"

I will share some git repos that will make having an LXC/LXD variant of Flatcar with supporting tools to make Flatcar more Agnostic-Universal for all Mainline & Downstream Linux Distros.

https://github.com/ashos/ashos

https://github.com/skiffos/SkiffOS

AshOS + SkiffOS will replace the current mechanism Flatcar uses & allow cross architecture & cross-distro building.

https://github.com/lxc/distrobuilder

https://github.com/marbetschar/tins

Adding Distrobuilder to Tins would allow everything to be graphical done without needing to touch the terminal/command line. Which means adding both AshOS & SkiffOS & Distrobuilders CLI to the backend of Tins.

Also, here is a resource for turning CLI to user-friendly GUI.

https://towardsdatascience.com/how-to-transform-your-command-line-app-into-a-user-friendly-gui-98c207564324

The impact would be making Flatcar more noticeable & stand out & become more widely used & mainstream-popular. It would allow both developers & ricing communities & users-alike to contribute in general to OSS/FOSS.

**Comment by t-lo** [comment]
Hello,

I agree there's benefit in an LXC spin - we're already planning to consider LXC integration in due time as part of our Sysext initiative (roadmap item https://github.com/flatcar/Flatcar/issues/548),

If I understand correctly your proposal includes replacing the Flatcar OS filesystem layout, build system, distro base, and update system, as well as changing its scope from being a headless, fully automated OS to presenting a GUI to users for interactively managing workloads on individual nodes.

> The impact would be making Flatcar more noticeable & stand out & become more widely used & mainstream-popular. It would allow both developers & ricing communities & users-alike to contribute in general to OSS/FOSS.

It would replace anything and everything Flatcar uses, is, and provides to its users as of today. It remains unclear how that would make it more widely used as no justification is provided to these bold claims.

I'll close this issue as out of scope / invalid.
