### ISSUE TITLE
are we pointing to the right place for kubernetes downloads?

### ISSUE THREAD

**Issue by ahrkrak** [flatcar/Flatcar#1076]
I see on https://www.flatcar.org/docs/latest/container-runtimes/getting-started-with-kubernetes/ we refer to downloads from https://storage.googleapis.com/kubernetes-release but it looks like those aren't the official kubernetes download links, and we should be using dl.k8s.io as the link (see https://kubernetes.io/releases/download/)
Don't want to update directly as there may be a good reason for the original link, but someone who knows for sure might want to check this! :-)

**Comment by tormath1** [comment]
Thanks for the heads-up @ahrkrak, it's actually a redirection:
```
$ curl --head https://dl.k8s.io/v1.27.2/bin/linux/amd64/kubectl
HTTP/2 302
server: nginx
date: Tue, 13 Jun 2023 12:30:37 GMT
content-type: text/html
content-length: 138
location: https://storage.googleapis.com/kubernetes-release/release/v1.27.2/bin/linux/amd64/kubectl
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```

**Comment by ahrkrak** [comment]
ok... I had thought it might be like the recent registry move, where they have a common domain that resolves to different cloud providers depending on where you pull from. are you sure that's not the case? seems like we should use the canonical URLs.
