### ISSUE TITLE
Podman support

### ISSUE THREAD

**Issue by dadux** [flatcar/Flatcar#109]
**Current situation**
Cannot run a container without having either containerd or crio daemon running.

**Ideal future situation**
Have the ability to run podman. 

Hi,

Is there any plans on having podman shipped with Flatcar ? 

Containerd / CRI-O makes a lot of sense when you're running something to orchestrate your containers, Kubernetes namely. 

But I'd love to use flatcar outside of my Kubernetes environments too, and starting containers directly from a `systemd` unit without having to start `containerd`, and then interract with the daemon with ctr or crictl.

**Comment by pothos** [comment]
Hello,

thank you for creating this issue. There were some plans to include it in Flatcar Edge first but it's not yet on the roadmap.

**Comment by t-lo** [comment]
Hello @dadux ,

thank you very much for your request. We are still in the process of establishing community interaction in-depth, and have recently (literally minutes ago) added guidelines for requesting new packages to be included in the OS image.

Could I please bug you to go through https://github.com/flatcar-linux/Flatcar#requesting-new-packages and re-create your request with the new issue type that we just added (and close this issue)? This would be really helpful for a focused discussion on Podman.

**Comment by dadux** [comment]
Closing , opened a new package requests : https://github.com/flatcar-linux/Flatcar/issues/112
