### ISSUE TITLE
[RFE] Build and ship Docker sysext

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#1092]
## Current situation

Docker is shipped via Torcx.

## Impact

Shipping Docker with torcx increases boot time (docker tarball needs to be decompressed) and memory usage at runtime (torcx uses a tmpfs for docker binaries). Torcx is deprecated and in maintenance mode, posing a potential security risk.

## Ideal future situation

Docker is build as a sysext and included in the base OS image (and update tarball).

## Additional information

This issue depends on #1091 and requires #1093 to be implemented to be feature complete (end-end-dependency).

@krishjainx wanted to look into this.

**Comment by krishjainx** [comment]
Can work on this once https://github.com/flatcar/scripts/pull/920 is merged
