### ISSUE TITLE
New Package Request: systemd-journal-remote

### ISSUE THREAD

**Issue by jhaprins** [flatcar/Flatcar#1107]
**Package name and purpose**
systemd-journal-remote provides the ability to send journald messages to a remote journald server.

- Package upstream repo: https://www.freedesktop.org/software/systemd/man/systemd-journal-remote.service.html
- Gentoo ebuild: https://packages.gentoo.org/packages/acct-user/systemd-journal-remote

**Impact of adding this package to the Flatcar OS image**

The package improves on the following core values:
  - [ * ] Secure by default
  - [ * ] Always up to date
  - [ * ] Improve container experience
  - [ * ] Operate at scale / automation / telemetry

The package will increase the image size by: <1 MBytes.

How might this package increase the attack surface:
- Only the central logging server needs to have ports open so the flatcar hosts can send the logging to the remote server.

**Benefits of adding this package**
Adding this package to the flatcar image will make sure that we can send the logging of the flatcar hosts to a central location for failure analysis and this will in turn result in the option to lock the flatcar images more down because we don't need to analyse log files locally on the worker nodes.

**Additional information**
[ Please add any information that does not fit into any of the above sections here ]

**Comment by pothos** [comment]
It's already there. We could add some docs at the Flatcar side but upstream docs should already be enough, or? (See https://github.com/flatcar/Flatcar/issues/990 for quick pointers but it's basically all upstream stuff, nothing Flatcar-specific)

**Comment by pothos** [comment]
Closing in favor of https://github.com/flatcar/Flatcar/issues/990 which has the pending task to improve the docs
