### ISSUE TITLE
Add docs for systemd-sysupdate

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#1129]
## Current situation

systemd-sysupdate is an experimental new part of systemd for partition and extension updates. So far it landed in Flatcar Alpha but there are only upstream docs.

## Impact

This  makes it hard to Flatcar users to quickly see how to use this.

## Ideal future situation

A part of the Flatcar sysext docs should show how to use systemd-sysupdate with Ignition examples.

## Implementation options

The current-symlink setting should be used and because we don't want to clutter `/etc/extensions/` with the version-suffixed images, we better store all versioned images of one extension in its folder, and set up a `/etc/extensions/NAME.raw` symlink to the current version in that folder.

**Comment by tormath1** [comment]
Documentation example: https://github.com/flatcar/sysext-bakery#consuming-the-published-images

**Comment by pothos** [comment]
First docs are in: https://www.flatcar.org/docs/latest/provisioning/sysext/#updating-custom-sysext-images
I think we should extend this a bit to use sysupdate components, otherwise the version can't be controlled well if two extensions should be updated.

**Comment by tormath1** [comment]
@pothos do you think it could be something interesting for the upstream to have a `systemd-sysupdate@.{service,timer}` ?

**Comment by pothos** [comment]
Interesting idea. As alternative one could also work with `ExecStartPre=` drop-ins for the component updates and a `ExecStartPost=` drop-in to issue `systemctl restart systemd-sysext systemd-confext`.

**Comment by tormath1** [comment]
Using `ExecStartPre=` drop-ins for each components won't avoid the `ExecStart=` to be executed from the `systemd-sysupdate.service` :thinking:

**Comment by pothos** [comment]
Yes, I've added a `noop.conf` file now to silence the error message.

**Comment by pothos** [comment]
We should test the new update daemon service and see if that works for us.

**Comment by pothos** [comment]
> Yes, I've added a `noop.conf` file now to silence the error message.

Another trick we could do is to symlink the service and timer units with a new name and use a drop-in to overwrite `ExecStart=`. But I kind of like to have only one timer/service to trigger for everything, and no custom unit names that people first have to learn about.

**Comment by pothos** [comment]
PR https://github.com/flatcar/flatcar-docs/pull/329
