### ISSUE TITLE
New Package Request: lbzip2

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#113]
**Package name and purpose**
lbzip2 is a drop in replacement for bzip2 with support for multithreading.

It's already used in the SDK but not in the final Flatcar image.
- Package upstream repo: https://github.com/kjn/lbzip2
- Gentoo ebuild: third_party/portage-stable/app-arch/lbzip2/lbzip2-2.5.ebuild

**Impact of adding this package to the Flatcar OS image**
- [x] This package meets the requirements of Flatcar Container Linux’ new package guidelines: https://github.com/flatcar-linux/Flatcar/blob/master/adding-new-packages.md

- The package improves on the following core values:
  - [X] Secure by default
  - [X] Always up to date

The package will increase the OS image by: 0.2 MBytes depending on whether bzip2 is removed it can be less.

The package will potentially increase Flatcar’s attack surface:
- no

**Benefits of adding this package to the Flatcar OS image**

With lbzip2 `flatcar-install` can unpack the image faster (10 seconds instead of 32 seconds on my machine).

We can either consider to remove the bzip2 package at the same time, or keep it and have `flatcar-install` prefer lbzip2 over bzip2.

**Additional information**

Current progress:
- [x] lbzip2 added to SDK
- [x] lbzip2 added to [OS image](https://github.com/kinvolk/coreos-overlay/blob/main/coreos-base/coreos/coreos-0.0.1.ebuild)
- [x] [flatcar-install](https://github.com/kinvolk/init/blob/flatcar-master/bin/flatcar-install) uses lbzip2 if present, falls back on bzip2 if not
- [x] Update coreos-init git tag to include the changes in flatcar-install

**Comment by t-lo** [comment]
We appear to have lbzip2 in the SDK but not in the OS image. I've updated the summary and added a checklist of "done"s and "todo"s.

**Comment by pothos** [comment]
https://github.com/kinvolk/coreos-overlay/pull/1221 is merged which adds lbzip2 to the image. The bzip2 binary is still the original single-thread bzip2 and not a symlink but flatcar-install uses lbzip2 if detected.
