### ISSUE TITLE
[RFE] Use qcow2 compressed format in place of additional compressed layer

### ISSUE THREAD

**Issue by tuxtof** [flatcar/Flatcar#1135]
## Current situation

actual released image in qcow2 format are then compressed with gzip or bzip2

## Impact

this situation don't allow direct use/import of the image URL with tools
because we need to download it first , uncompresse it and next import it

## Ideal future situation

we need to use inline compressed qcow2 format to distribute qcow2 file

## Implementation options

qemu-image convert -O qcow2 -c ...... allow that

**Comment by krishjainx** [comment]
I would like to work on this even though I've completed my internship. Can you please assign me to it? @pothos 
Thanks

**Comment by tuxtof** [comment]
Yes please it will be wonderful

**Comment by pothos** [comment]
Good idea, thanks. We would have to introduce this as additional artifact because people would still expect that the .bz2 file also is there.
Edit: Previous discussion on how to generate both artifacts: https://github.com/flatcar/Flatcar/issues/791#issuecomment-1168486922

**Comment by dongsupark** [comment]
PR https://github.com/flatcar/scripts/pull/1132 was merged. Will be included in the next Alpha (probably as well as other channels).
Thanks.
