### ISSUE TITLE
[Docs] Consider updating references to Apache container

### ISSUE THREAD

**Issue by bgilbert** [flatcar/Flatcar#1137]
The `coreos/apache` container image was 8 years old and based on Ubuntu 12.04.  That seemed dangerous to keep around, so I've deleted it.

The Flatcar docs inherited two references to that container, in the [Docker](https://github.com/flatcar/flatcar-docs/blob/main/docs/container-runtimes/getting-started-with-docker.md) and [systemd](https://github.com/flatcar/flatcar-docs/blob/main/docs/setup/systemd/getting-started.md) getting-started guides.  The systemd one still mentions it.  The Docker one has been updated to use `flatcar/apache`, which doesn't exist, but the doc also says that the name is a placeholder.

I don't know if you want to update those references to point to a container that's maintained, or leave them as is, but FYI they're dead links as of now.

**Comment by pothos** [comment]
Thank you for checking!

Maybe `docker.io/nginx` is a good replacement because it's used in the quickstart guide already.
