### ISSUE TITLE
locksmithd ignores REBOOT_STRATEGY in /etc/coreos/update.conf after update from coreos

### ISSUE THREAD

**Issue by marcelo-herrera-sp** [flatcar/Flatcar#114]
**Description**

Updating /etc/coreos/update.conf to REBOOT_STRATEGY=off isn't being honored by locksmithd

Seems to honor  /usr/share/coreos/update.conf 

Might work with /etc/flatcar/update.conf 

Is this intended? 

**Impact**

locksmithd will reboot a machine even when configured not to

**Environment and steps to reproduce**

1. **Set-up**: Flatcar VERSION=2345.3.1
2. **Task**: update-engine background run
3. **Action(s)**:  locksmothd - Reboot planned
4. **Error**: N/A

**Expected behavior**
Expected 
`-- Reboot --
Apr 24 18:05:44 ops-376 systemd[1]: Started Cluster reboot manager.

Apr 24 18:05:44 ops-376 locksmithd[749]: Reboot strategy is "off" - locksmithd is exiting.

Apr 24 18:05:44 ops-376 systemd[1]: locksmithd.service: Succeeded.
-- Reboot --`

**Additional information**
`-- Logs begin at Thu 2018-08-16 23:26:36 UTC, end at Mon 2020-05-11 22:30:53 UTC. --

May 11 22:30:17 ops-376 systemd[1]: Started Cluster reboot manager.

May 11 22:30:18 ops-376 locksmithd[829]: No configured reboot window

May 11 22:30:18 ops-376 locksmithd[829]: locksmithd starting currentOperation="UPDATE_STATUS_IDLE" strategy="reboot"

core@ops-376 ~ $ cat /etc/coreos/update.conf 
GROUP=stable
REBOOT_STRATEGY=off
core@ops-376 ~ $ cat /usr/share/coreos/update.conf 
SERVER=https://public.update.flatcar-linux.net/v1/update/
GROUP=stable`

Tested after: 
` sudo mount --bind /etc/coreos/update.conf /usr/share/coreos/update.conf `
and things look better

**Comment by pothos** [comment]
Thanks for reporting. With a fresh Flatcar CL install you would have `/etc/coreos` as symlink to the new `/etc/flatcar` folder. I think the best would be to modify the update script to create this symlink in the end.

**Comment by pothos** [comment]
I created a PR with a fix here: https://github.com/flatcar-linux/docs/pull/84
