### ISSUE TITLE
Port DigitalOcean OEM away from the base Ignition

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#1142]
## Current situation

The DigitalOceam OEM setup uses a base Ignition file that gets merged with the user-passed Ignition config.
Currently the only action is to enable `coreos-metadata-sshkeys@.service`.

## Impact

The setup writes state to the rootfs that is not updated.

## Ideal future situation

We don't use the base/default Ignition approach but have a unit in the generic image that enables/runs/depends-on `coreos-metadata-sshkeys@.service` with a condition for `KernelCommandLine=coreos.oem.id=digitalocean` or `KernelCommandLine=flatcar.oem.id=digitalocean`.

## Additional information

We could also create a sysext image but that does not make much sense, we already ship `KernelCommandLine=` OEM units in the base image and the initrd.

A migration action is not really needed for this limited case. But if, we could do it live in flatcar-postinst based on the current and next version being ≥ the major version that introduces the change.

**Comment by tormath1** [comment]
Closed by https://github.com/flatcar/scripts/pull/1197
