### ISSUE TITLE
Port AWS and OpenStack OEM setup to systemd-sysext image

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#1145]
The EC2-compat OEM setup is currently used for AWS and OpenStack and brightbox.

As was already done for the Azure OEM setup in https://github.com/flatcar/Flatcar/issues/769 we want to port the AWS setup over to systemd-sysext to benefit from updates.
A benefit of sysext images is that they can have a strict coupling to the Flatcar VERSION_ID which enables to use dynamical linking to save space and make the OEM tool packages simpler.
The base Ignition configuration is not needed anymore because the sysext's OEM files already become part of the /usr hierarchy and systemd services there can get started through an `Upholds=` drop-in. For the `/etc/eks/bootstrap.sh`, `/etc/amazon/ssm/amazon-ssm-agent.json`, `/etc/amazon/ssm/seelog.xml` files we probably need a helper systemd unit that sets up symlinks to the file in the sysext image.
The migration action has to be defined in the update_engine flatcar-postinst hook like it was done for Azure.

For OpenStack we don't ship any software and only use enable same `coreos-metadata-sshkeys@.service` unit as for Digital Ocean and Equinix Metal. Therefore, we should cover this from the base image as suggested in https://github.com/flatcar/Flatcar/issues/1142, also because users often use the QEMU image as base and set the OEM it in GRUB for OpenStack.

For brightbox we could continue to use the old setup and also check what the current support state for it is.

In the end, this means that we split the EC2-compat OEM package.

**Comment by tormath1** [comment]
Closed by https://github.com/flatcar/scripts/pull/1197
