### ISSUE TITLE
Error: update failed

### ISSUE THREAD

**Issue by EugenKon** [flatcar/Flatcar#1151]
## Description

I am trying to upgrade my CoreOS

```
$ uname -a
Linux www 4.1.6-coreos-r1 #2 SMP Wed Sep 2 04:16:15 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux

 $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=766.3.0
VERSION_ID=766.3.0
BUILD_ID=
PRETTY_NAME="CoreOS 766.3.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

## Impact

```
$ sudo ./flatcar-update --to-version "$VER" --to-payload flatcar_production_update.gz --force-flatcar-key
Bind-mounting /usr/share/update_engine/update-payload-key.pub.pem
Forcing update...
Error: update failed
```

## Environment and steps to reproduce

I follow instruction described here https://www.flatcar.org/docs/latest/migrating-from-coreos/update-from-container-linux/

## Expected behavior

Updated CoreOS -> FlatCar

**Comment by pothos** [comment]
Can you share the output of `journalctl -u update-engine --no-pager` (the last ~100 lines should be enough)?

**Comment by EugenKon** [comment]
Sorry, I prepared it, but did not attached.

[update.log](https://github.com/flatcar/Flatcar/files/12264557/update.log)

**Comment by pothos** [comment]
Ok, can you first update to an older Flatcar version like 2765.2.6? https://update.release.flatcar-linux.net/amd64-usr/2765.2.6/

**Comment by pothos** [comment]
Later versions don't provide the kernel anymore in the /usr partition for use with syslinux. I think you can try to migrate the machine by setting `BOOT/coreos/vmlinuz-A` instead of `BOOT/syslinux/vmlinuz.A` (same for `B`) in the boot loader and then remove the `cros_legacy` kernel parameter, reboot and then attempt the update to the latest version. Since I haven't tried it, it may not work.

**Comment by EugenKon** [comment]
@pothos We also noticed, that `fleetctl` was removed from distribution. Are there migration guides available for moving from `freelctl` to `kubernetes`?

**Comment by jepio** [comment]
`fleetctl` was removed from CoreOS in 2017, before Flatcar was created.

There is no straightforward migration. Depending on your needs you may be happy with systemd units starting docker containers (https://www.flatcar.org/docs/latest/setup/systemd/getting-started/#unit-file) or you may have to search the web for a kubernetes tutorial/guide.

**Comment by EugenKon** [comment]
@jepio Thanks

**Comment by EugenKon** [comment]
Found this documentation is useful in migrating from 'cloud-config': https://www.flatcar.org/docs/latest/provisioning/cl-config/from-cloud-config/

**Comment by dongsupark** [comment]
Thanks for the report.
It would be great to update the systems to newer Flatcar versions and test it again.
