### ISSUE TITLE
Unable to install nvidia-drivers on Flatcar Container Linux by Kinvolk stable 3033.2.2

### ISSUE THREAD

**Issue by Roshnichauhan1** [flatcar/Flatcar#1162]
## Description

Trying to install nvidia driver on a GCP VM in europe-west2b , GPU is Nvidia Tesla T4, OS is Flatcar Container Linux by Kinvolk stable 3033.2.2 , 5.10.96-flatcar.

## Impact
I've tried to use nvidia toolkit and followed this document. https://gitlab.com/nvidia/container-images/driver/-/tree/master/flatcar
The output of lsmod | grep -i nvidia is :

nvidia_modeset 1228800 0
nvidia_uvm 1130496 0
nvidia 34078720 17 nvidia_uvm,nvidia_modeset
i2c_core 81920 3 nvidia,psmouse,i2c_piix4

But when I try to run docker run --runtime=nvidia nvidia/cuda:11.7.1-base-ubuntu22.04 nvidia-smi
it gives the error
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #1:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli.real: container error: cgroup subsystem devices not found: unknown.
ERRO[0000] error waiting for container: context canceled

Instead of building and using the docker image I tried to use the docker image from nvidia repo
docker pull nvcr.io/nvidia/driver:460.32.03-5.10.25-flatcar
docker run -d --privileged --pid=host --name nvidia-driver nvcr.io/nvidia/driver:460.32.03-5.10.25-flatcar
Output is:
========== NVIDIA Software Installer ==========
Starting installation of NVIDIA driver version 460.32.03 for Linux kernel version 5.10.25-flatcar
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...
Checking NVIDIA driver packages...
Installing the Flatcar development environment on the filesystem /usr/src/nvidia-460.32.03/kernel...
parse error: Invalid numeric literal at line 1, column 10
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...

I tried to use the latest flatcar and another nvidia driver but got same error
========== NVIDIA Software Installer ==========
Starting installation of NVIDIA driver version 460.73.01 for Linux kernel version 5.15.122-flatcar
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...
Checking NVIDIA driver packages...
Installing the Flatcar development environment on the filesystem /usr/src/nvidia-460.73.01/kernel...
parse error: Invalid numeric literal at line 1, column 10
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...

Since the OS is flatcar linux tried to install nvidia driver using the ignition file but could not find any relevant document for the same.
My aim is to install nvidia drivers on flatcar linux OS

## Environment and steps to reproduce

1. Launch a GCP Vm with base OS as Flatcar Container Linux by Kinvolk stable 3033.2.2 , 5.10.96-flatcar  and GPU is Nvidia Tesla T4,
2. Once the VM is ready followed this document. https://gitlab.com/nvidia/container-images/driver/-/tree/master/flatcar to download nvidia toolkit and then install nvidia-drivers 
3. After successful installation run the nvidia-smi command to verify the versions.
  a. [ requested the start of a new pod or container ]
  b.docker run --name nvidia --gpus all <container-id>

4. **Error**: 
docker run --runtime=nvidia nvidia/cuda:11.7.1-base-ubuntu22.04 nvidia-smi

docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #1:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli.real: container error: cgroup subsystem devices not found: unknown.
ERRO[0000] error waiting for container: context canceled

docker run --name nvidia --gpus all 7a6929004bb6
docker: Error response from daemon: could not select device driver “” with capabilities: [[gpu]].
ERRO[0000] error waiting for container: context canceled

## Expected behavior

$ docker run --runtime=nvidia nvidia/cuda:11.0-base nvidia-smi

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   30C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by jepio** [comment]
The nvidia driver container does not support Flatcar very well. Have you tried the built-in support for Nvidia drivers we ship in Flatcar? https://www.flatcar.org/docs/latest/setup/customization/using-nvidia/.

**Comment by Roshnichauhan1** [comment]
> The nvidia driver container does not support Flatcar very well. Have you tried the built-in support for Nvidia drivers we ship in Flatcar? https://www.flatcar.org/docs/latest/setup/customization/using-nvidia/.

Yes tried that, using the latest flatcar image from projects/kinvolk-public/global/images/family/flatcar-stable the driver version in /usr/share/flatcar/nvidia-metadata is 525.105.17 I did not change the version and as per the document you mentioned generated the part to install driver and added it to the ignition file on my Vm:
 {
	"filesystem": "root",
        "path": "/etc/flatcar/nvidia-metadata",
        "contents": {
          "compression": "",
          "source": "data:,NVIDIA_DRIVER_VERSION%3D525.105.17%0A"
        },
        "mode": 420
      }

Once the VM came up I tried to run:
sudo systemctl restart nvidia
Failed to restart nvidia.service: Unit nvidia.service not found.

 nvidia-smi
-bash: nvidia-smi: command not found

**Comment by jepio** [comment]
I just saw that you’re using flatcar version 3033. This support wasn’t included in that version yet.

Would you mind giving current stable a try?

________________________________

**Comment by Roshnichauhan1** [comment]
@jepio  Earlier I was trying with 3033 but then switched to Stable 3510.2.6. The commands and output I shared yesterday were from the version 3510.

**Comment by jepio** [comment]
I'm sorry - I just saw that the nvidia driver installation was only added to all platforms in flatcar 3637, which is only part of the alpha channel at this time.

Could you please try that.

**Comment by Roshnichauhan1** [comment]
> I'm sorry - I just saw that the nvidia driver installation was only added to all platforms in flatcar 3637, which is only part of the alpha channel at this time.
> 
> Could you please try that.

@jepio But the document https://www.flatcar.org/docs/latest/setup/customization/using-nvidia/ does not mention anywhere that the support started in 3637, 
also as per the document this file /usr/share/flatcar/nvidia-metadata does contain the nvidia driver version in both flatcar 3033 and 3510

**Comment by sayanchowdhury** [comment]
@Roshnichauhan1 Until recently, the NVIDIA support was limited to the AWS and Azure. With the PR https://github.com/flatcar/scripts/pull/932, we extended the support to the rest of the Cloud providers. The document used to have a mention but was removed when the scripts PR was merged https://github.com/flatcar/flatcar-docs/pull/325. I'll update the documentation with the relevant information you raised.

To answer you next question, even though we used to ship the metadata file, the previous versions of Flatcar did not ship the supporting service & installation files (only present in AWS and Azure), and hence the automatic installation of the NVIDIA drivers won't happen. The scripts PR also addresses this issue. I would recommend you to test your setup on the latest Alpha.

**Comment by Roshnichauhan1** [comment]
> @Roshnichauhan1 Until recently, the NVIDIA support was limited to the AWS and Azure. With the PR [flatcar/scripts#932](https://github.com/flatcar/scripts/pull/932), we extended the support to the rest of the Cloud providers. The document used to have a mention but was removed when the scripts PR was merged [flatcar/flatcar-docs#325](https://github.com/flatcar/flatcar-docs/pull/325). I'll update the documentation with the relevant information you raised.
> 
> To answer you next question, even though we used to ship the metadata file, the previous versions of Flatcar did not ship the supporting service & installation files (only present in AWS and Azure), and hence the automatic installation of the NVIDIA drivers won't happen. The scripts PR also addresses this issue. I would recommend you to test your setup on the latest Alpha.

@sayanchowdhury Thank you for the clarification! I tested using the latest alpha (3689.0.0) and it worked as expected.

**Comment by sayanchowdhury** [comment]
Created a PR in the docs https://github.com/flatcar/flatcar-docs/pull/332

Closing this issue. Feel free to re-open the issue if needed.
