### ISSUE TITLE
Correct RemainsAfterExit=true to be RemainAfterExit=true in nvidia.service

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#1169]
## Description

In the new Alpha the unit setting `RemainsAfterExit=true` is ignored for `nvidia.service` and should be corrected to `RemainAfterExit=true` in `/usr/lib/systemd/system/nvidia.service`

## Impact

Maybe it's causing problems if the service runs again when triggered as dependency

**Comment by sayanchowdhury** [comment]
I've been working on the nvidia-drivers migration to latest version. I will fix it along with that PR.
