### ISSUE TITLE
Run Flatcar update test in GitHub Action PR CI

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#1172]
## Current situation

The regular update test was using the nightly payload from bincache and after seeing this issue it is now skipped:
https://github.com/flatcar/scripts/blob/6bec600278c863c7bf5e2755db10e491b7225f18/ci-automation/vendor-testing/qemu_update.sh#L30

## Impact

While possible to test for each PR it is not done

## Ideal future situation

The GitHub Action copies the artifact from the build step over to the right location (either directly to the location expected by `if [ -f "${QEMU_UPDATE_PAYLOAD}" ] ; then` or change the logic there to find it and copy it over). Also remove the TODO comment.
https://github.com/flatcar/scripts/blob/6bec600278c863c7bf5e2755db10e491b7225f18/ci-automation/vendor-testing/qemu_update.sh#L30

**Comment by pothos** [comment]
Seems this is already implemented but the variable setting didn't work and Thilo will fix it. The TODO linked here can be removed.

**Comment by t-lo** [comment]
This has been addressed recently by making it possible to pre-initialise the qemu update test variable that stores the location of the update payload: https://github.com/flatcar/scripts/blob/contrib/torcx-deprecation-docker-sysext/ci-automation/ci-config.env#L71 .
