### ISSUE TITLE
Flatcar crashes in VM when hot adding cpu

### ISSUE THREAD

**Issue by Winnie81** [flatcar/Flatcar#119]
Guest OS with Flatcar 2345.3.0 crashes when hot adding cpu.

Test Environment:
    ESXi: 6.7GA

Steps to reproduce:
1. Create a Flatcar vm. "Enable CPU Hot Add" is checked by default.
2. Power on it then hot add cpu.
3. Execute "for a in /sys/devices/system/cpu/cpu*/online; do echo "1" > "$a"; done" to bring CPU up.

This issue couldn't be reproduced with 2466.0.0(alpha build).

**Comment by pothos** [comment]
Hello,
thanks for reporting.
So this is a kernel issue – how did the crash look like?
Where you able to reproduce it with the latest Stable or Beta releases?

**Comment by Winnie81** [comment]
This issue has been fixed in 2512.2.0. Thanks.

**Comment by richardzuidhof** [comment]
I had this issue but it turned out to be related to the kernel module sysdigcloud_probe
