### ISSUE TITLE
switch rkt from ACI fetch to docker:// fetch from quay.io

### ISSUE THREAD

**Issue by vbatts** [flatcar/Flatcar#121]
**Description**

@josephschorr let me know that quay.io intends to deprecate the API for the ACI conversation (ASAP)

**Impact**

the affects a few places, namely https://github.com/flatcar-linux/mantle/, but likely other places as well.

This does not have to be as invasive as switching from `rkt` to `docker`, but just forcing `rkt` to pull using the docker registry API. (maybe even just prefix the image name with `docker://`)

**Comment by josephschorr** [comment]
Quay JIRA ticket: https://issues.redhat.com/browse/PROJQUAY-714

**Comment by pothos** [comment]
Here is the upstream PR for `coreos-overlay`: https://github.com/coreos/coreos-overlay/pull/3949/files

**Comment by pothos** [comment]
Cherry-picked for Flatcar: https://github.com/flatcar-linux/coreos-overlay/pull/366

**Comment by pothos** [comment]
It was part of the 2512.2.0 Stable release:

> Changes:
> - Fetch container images in docker format rather than ACI by default in etcd-member.service, flanneld.service, and kubelet-wrapper
>
