### ISSUE TITLE
Release Flatcar Container Linux Alpha 3760.0.0, Beta 3745.1.0, Stable 3602.2.1, LTS-2023 3510.3.1, LTS-2022 3033.3.18

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#1216]
The release of the following Flatcar Container Linux version is planning 19th October 2023

- Alpha 3760.0.0
- Beta 3745.1.0
- Stable 3602.2.1
- LTS-2023 3510.3.1
- LTS-2022 3033.3.18

## 1. Preparation

Owner:

- [x] A. Go/No-Go [hackmd doc](https://hackmd.io/team/flatcar) created from HackMD template for test tracking and release notes: (update the link here)
- [x] B. All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems.
- [x] C. Check that the kernel PR are merged for the channel(s) to be released.

## 2. Build

Owner: @sayanchowdhury / @tormath1 

- [x] A. Branched off the `main` branch (only for new major).
- [x] B. Tagged all the build branches.
- [x] C. Started the Jenkins builds, post the links into this issue as comment.

### i. The Go/No-Go Meeting

Owner: @sayanchowdhury / @tormath1 

- [x] A. Test status captured in the HackMD document.
- [x] B. All tests are Green.
- [x] C. Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None`.
- [x] D. QA: Checked the diff for image file list, packages, and image size in the `container/image_changes` job output.
- [x] E. Conduct Matrix Go/No Go meeting (inc. release notes review).

### ii. Artifacts goes public

Owner: @tormath1

- [x] A. Created the Release Notes on the `scripts` repo for the respective tags on GitHub as GitHub Releases.
- [x] B. Ran the `container/release` Release job.
- [x] C. Images uploaded with `copy-to-origin.sh`.
- [x] D. Symlink to "current" updated with `set-symlink.sh`.
- [x] E. Website updated with `./update-flatcar-versions.sh` and PR merged. (https://github.com/flatcar/flatcar-website/pull/281)

### iii. Payload

Owner: @tormath1

- [x] A. Update payload signed/uploaded.
- [x] B. Release package published in Nebraska (Prerequisite: 3.ii.E should marked done).

### iv. Cloud Marketplace & Cluster API

Owner:

- A. Azure
    - [x] Offers updated and started publishing.
    - [x] Sent the offers to publish to Live.

- B. GCP
    - [ ] Offer deployment package uploaded to Google Bucket & submit for verification.
    - [ ] Offer Publish

- C. Cluster API for new Stable
  - [ ] Azure: Manually run `./azure-sig.sh` to create New Shared Community Gallery Images
    ~~[ ] OpenStack: [documentation](https://gist.github.com/tormath1/acbae5c6cd12420bb8ea137e25655c99)~~

## 4. Announcements

Owner: @tormath1 

- [x] A. Sent announcement to Mailing Lists
- [x] B. Sent Tweet out to Twitter, and Toot out to Mastodon
- [x] C. Brief version announcement in slack (k8s slack #flatcar) and the Flatcar Matrix channel

**Comment by sayanchowdhury** [comment]
Go/No Meeting it was decided to put the release on hold. This is because there is a issue identified during testing with Stable/LTS-2023 kernel and Cilium which is expected to be fixed in the next Kernel release. 

The plan as of now is the wait till next week for the new kernel and then start new builds for the affected channels.

**Comment by tormath1** [comment]
Builds:
* alpha: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/1136/cldsv/
* beta: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/2751/cldsv/
* stable: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/2792/cldsv/
* LTS 2023: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/2793/cldsv/
* LTS 2022: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/2753/cldsv/
