### ISSUE TITLE
Azure images are out-of-date - kinvolk:flatcar-container-linux-free:stable-gen2:3602.2.0 not found

### ISSUE THREAD

**Issue by bignay2000** [flatcar/Flatcar#1218]
## Description

Microsoft Azure Market place has out of date versions of Flatcar from Jun 21, 2023 releases.  

## Impact

Running into an ignition boot error with 3510.2.3 when trying to deploy an Azure Gen2 VM with multiple disks.  Thinking this might be fixed in the latest stable version as my butane configuration works on Proxmox with EFI BIOS & VMWare ESXi platforms. 

## Environment and steps to reproduce

Log into Azure
List available images from Kinvolk:
`az vm image list --all -p kinvolk -f flatcar -s stable`

Latest image for stable is out of date - 3510.2.3 from Jun 21, 2023

{
    "architecture": "x64",
    "offer": "flatcar_pro",
    "publisher": "kinvolk",
    "sku": "stable-gen2",
    "urn": "kinvolk:flatcar_pro:stable-gen2:3510.2.3",
    "version": "**3510.2.3**"
  }

## Expected behavior

Latest stable 3602.2.0 should be available.

## Additional information

Querying the image of 'kinvolk:flatcar-container-linux-free:stable-gen2:3602.2.0' failed for an error '(NotFound) Artifact: VMImage was not found.
Code: NotFound
Message: Artifact: VMImage was not found.'. Configuring plan settings will be skipped
Querying the image of 'kinvolk:flatcar-container-linux-free:stable-gen2:3602.2.0' failed for an error '(NotFound) Artifact: VMImage was not found.
Code: NotFound
Message: Artifact: VMImage was not found.'. Configuring plan settings will be skipped
(NotFound) Artifact: VMImage was not found.
Code: NotFound
Message: Artifact: VMImage was not found.

**Comment by bignay2000** [comment]
https://github.com/flatcar/Flatcar/issues/1196

**Comment by tormath1** [comment]
Hello @bignay2000, I'm quoting @t-lo from a message posted on #flatcar Slack channel:
> We are aware of this issue and are in constant conversation with the Azure Marketplace team. Newer releases cause issues with the Marketplace validation process by triggering a problem on the Marketplace side. We're working with the team to resolve these problems and we're making progress.

Let's keep the issue open for referencing purpose.

**Comment by dongsupark** [comment]
After conversation with Azure Marketplace team for multiple weeks, we finally published marketplace images of Alpha 3732.0.0, Beta 3602.1.6, Stable 3510.2.8. (https://github.com/flatcar/Flatcar/issues/1181)
We are now able to start publishing next versions, including Stable 3602.2.0.

**Comment by sayanchowdhury** [comment]
@bignay2000 Just a question, are you still using Flatcar Pro. All the features of Flatcar Pro has been moved to the base image Flatcar, and we do intend to deprecate the offer over the next few days. Will it be possible for you to move your deployments to one of the other offers? If you need help, do let us know.

**Comment by bignay2000** [comment]
Just checked and very happy to see the lastest stable.

az vm image list --all -p kinvolk -f flatcar -s stable

{
    "architecture": "x64",
    "offer": "flatcar-container-linux-free",
    "publisher": "kinvolk",
    "sku": "stable-gen2",
    "urn": "kinvolk:flatcar-container-linux-free:stable-gen2:3602.2.1",
    "version": "**3602.2.1**"
  },

**Comment by bignay2000** [comment]
> @bignay2000 Just a question, are you still using Flatcar Pro. All the features of Flatcar Pro has been moved to the base image Flatcar, and we do intend to deprecate the offer over the next few days. Will it be possible for you to move your deployments to one of the other offers? If you need help, do let us know.

I am using "flatcar-container-linux-free" so I think this is not "Flatcar Pro"

**Comment by bignay2000** [comment]
> > @bignay2000 Just a question, are you still using Flatcar Pro. All the features of Flatcar Pro has been moved to the base image Flatcar, and we do intend to deprecate the offer over the next few days. Will it be possible for you to move your deployments to one of the other offers? If you need help, do let us know.
> 
> I am using "flatcar-container-linux-free" so I think this is not "Flatcar Pro"

I am a bit confused @sayanchowdhury , should be using this URN instead?:

{
    "architecture": "x64",
    "offer": "flatcar-container-linux",
    "publisher": "kinvolk",
    "sku": "stable-gen2",
    "urn": "kinvolk:flatcar-container-linux:stable-gen2:3602.2.1",
    "version": "3602.2.1"
  },
