### ISSUE TITLE
Flatcar does not boot into updated version

### ISSUE THREAD

**Issue by CodeEighty8** [flatcar/Flatcar#122]
**Flatcar does not boot into updated version**

I am trying to upgrade my flatcar deployment from the current stable version (2345.3.1) to the current beta version (2411.1.1) via the Omaha protocol. I am using coreroller for the rollout mechanism. During this upgrade rollout, the OS on 2345.3.1 successfully downloads the new update (i.e. version 2411.1.1) 
```
May 19 17:51:03 localhost update_engine[2575]: I0519 17:51:03.514751  2575 update_attempter.cc:316] Update successfully applied, waiting to reboot.
May 19 17:52:47 localhost update_engine[2575]: I0519 17:52:47.786886  2575 prefs.cc:51] certificate-report-to-send-update not present in /var/lib/update_engine/prefs
May 19 17:52:47 localhost update_engine[2575]: I0519 17:52:47.786928  2575 prefs.cc:51] certificate-report-to-send-download not present in /var/lib/update_engine/prefs
May 19 17:52:47 localhost update_engine[2575]: I0519 17:52:47.786934  2575 update_attempter.cc:131] Not updating b/c we already updated and we're waiting for reboot, we'll ping Omaha instead
```

and reboots but stops during the boot cycle with the following error :
![image](https://user-images.githubusercontent.com/7677904/82368359-ec328e80-9a32-11ea-8e97-956668f6c5b1.png)

On pressing enter, it will show the GRUB menu with :
![image](https://user-images.githubusercontent.com/7677904/82368460-1a17d300-9a33-11ea-876a-d454e3238676.png)

On selecting "Flatcar default" it will boot back into 2345.3.1 version and the whole cycle repeats.

**Impact**

 I am not able to roll out upgrades to my flatcar deployments. 

**Environment and steps to reproduce**

1. **Set-up**:  The OS is deployed on VMWare Vsphere 
2. **Task**: upgrade the os versions
3. **Action(s)**: As described in the above paragraph
4. **Error**: Screenshot 1

**Expected behavior**
Os upgrades to 2411.1.1 version 

**Additional information**
Now if I understand it right, from this document, https://docs.flatcar-linux.org/os/manual-rollbacks/ `USR-A` with UUID `7130c94a-213a-4e5a-8e26-6cce9662f132` is the active partition and points to the current version, in my case `2345.3.1`

And also from `grub.cfg`,
```
function gptprio {
    # TODO: device name is no longer needed, should make it optional...
    gptprio.next -d usr_device -u usr_uuid
    if [ $? -ne 0 -o -z "$usr_uuid" ]; then
        echo
        echo "Reading or updating the GPT failed!"
        echo "Please file a bug with any messages above to Flatcar:"
        echo " https://issues.flatcar-linux.org"
        abort
    fi

    set gptprio_cmdline="@@MOUNTUSR@@=PARTUUID=$usr_uuid"
    if [ "$usr_uuid" = "7130c94a-213a-4e5a-8e26-6cce9662f132" ]; then
        set gptprio_kernel="/flatcar/vmlinuz-a"
    else
        set gptprio_kernel="/flatcar/vmlinuz-b"
    fi
}
``` 
So from the rollback document and `grub.cfg` during upgrade rollout and subsequent reboot the UUID will be set to one other than `7130c94a-213a-4e5a-8e26-6cce9662f132`. Hence, GRUB is trying to point to `/flatcar/vmlinuz-b`, which it is not able to find. On inspecting the `/boot` partition, I do not see `/flatcar/vmlinuz-b` in `/boot/flatcar/` but in ` /boot/coreos/`. 
```
core@localhost ~ $ sudo su
localhost core # cd /boot/flatcar/
localhost flatcar # ls
grub  vmlinuz-a
localhost flatcar # cd ../coreos/
localhost coreos # ls
first_boot  vmlinuz-b
```
Also hopefully this info helps:
```
core@localhost ~ $ sudo cgpt show /dev/sda
       start        size    part  contents
           0           1          Hybrid MBR
           1           1          Pri GPT header
           2          32          Pri GPT table
        4096      262144       1  Label: "EFI-SYSTEM"
                                  Type: EFI System Partition
                                  UUID: 15F4D856-29DA-4F9D-BDFB-93CEA0FC7748
                                  Attr: Legacy BIOS Bootable
      266240        4096       2  Label: "BIOS-BOOT"
                                  Type: BIOS Boot Partition
                                  UUID: 757841A0-7143-4BB6-AD13-03F795C6B11F
      270336     4194304       3  Label: "USR-A"
                                  Type: Alias for coreos-rootfs
                                  UUID: 7130C94A-213A-4E5A-8E26-6CCE9662F132
                                  Attr: priority=2 tries=0 successful=1
     4464640     4194304       4  Label: "USR-B"
                                  Type: Alias for coreos-rootfs
                                  UUID: E03DD35C-7C2D-4A47-B3FE-27F15780A57C
                                  Attr: priority=1 tries=0 successful=0
     8658944      262144       6  Label: "OEM"
                                  Type: Alias for linux-data
                                  UUID: 8F99D006-4F26-46D2-A567-B6FAC073BB61
     8921088      131072       7  Label: "OEM-CONFIG"
                                  Type: CoreOS reserved
                                  UUID: FE8334B2-114A-4074-95DF-0030E3F70293
     9052160    29913055       9  Label: "ROOT"
                                  Type: CoreOS auto-resize
                                  UUID: 1C0A563E-E727-4D3D-8920-B0D09FBA7982
    38965215          32          Sec GPT table
    38965247           1          Sec GPT header
```
Kindly let me know if any further information is required. Any help here is much appreciated.

**Comment by pothos** [comment]
Thanks for the details. I will try to reproduce it soon but I have some initial thoughts which could help you:

Have you updated this machine from CoreOS Container Linux?
Normally `/boot/coreos` only exists on migrated machines because that's what GRUB expects (which is not migrated).
As soon as `/boot/coreos` exists, the new kernel binary will be stored there on update. If the machine wasn't migrated, do you remember creating this folder to `touch /boot/coreos/first_boot`? That could be the mistake because it should be `touch /boot/flatcar/first_boot`.

**Comment by pothos** [comment]
Seems you didn't migrate the machine because `/boot/flatcar/grub` exists.

I can add a patch to the update process to only prefer `/boot/coreos` if `/boot/coreos/vmlinuz*` exists as well. This would make it resilient against an accidental `mkdir /boot/coreos; touch /boot/coreos/first_boot`.

**Comment by CodeEighty8** [comment]
@pothos thank you very much for your inputs. This image was not upgraded from coreos. I take the base flatcar image and add my own patches to build my one version of the OS image, although, I do not add `/boot/coreos` path exclusively. Nevertheless, I will dig through the build process again and get back.

**Comment by CodeEighty8** [comment]
@pothos I see that `/boot/coreos` is already preferred over `/boot/flatcar` from this commit https://github.com/flatcar-linux/update_engine/commit/b20bd3d13cbe06d717195ddfe621c80c14493012

**Comment by pothos** [comment]
Yes, that's why as soon as this folder got created on your machine, the update process assumed that the machine is migrated from CoreOS and needs its kernel stored there.

**Comment by pothos** [comment]
The changes are merged and will go into the next releases. Until then, please move the kernel binary to the `/boot/flatcar/` folder and remove the `/boot/coreos` folder.
