### ISSUE TITLE
docker and containerd packages information are missing from `flatcar_production_image_packages.txt`

### ISSUE THREAD

**Issue by tormath1** [flatcar/Flatcar#1260]
## Description

In the latest release, it has been noticed that `docker` and `containerd` version information are missing from the release page (https://www.flatcar.org/releases#alpha-release)

Following recent sysext changes, Docker and Containerd are now sysext images so the packages information are located here: https://alpha.release.flatcar-linux.net/amd64-usr/current/rootfs-included-sysexts/containerd-flatcar_packages.txt but should be available here too: https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_production_image_packages.txt

## Expected behavior

Having packages information in both files.

## Additional information

https://github.com/flatcar/scripts/commit/89555ed2bd3d35d39d9d1dc5794f8d2d0e1790c3 seems to be a good base for investigation

**Comment by pothos** [comment]
Maybe we should change our website script to use the new files instead.

**Comment by tormath1** [comment]
@pothos yes, this is how it has been noticed the first time (see: https://github.com/flatcar/flatcar-website/pull/288) (docker and  containerd are missing on the alpha release preview)

**Comment by t-lo** [comment]
If it is easier then we could also just use the SBOM JSON (or the licenses JSON) - these include all packages, base OS and sysexts.

Alternatively, I could add generation of additional contents and packages inventory files with all sysexts' contents included if that helps.

**Comment by pothos** [comment]
For readers, the license JSON file is named `flatcar_production_image_licenses.json` and holds all info.

With more systemd-sysext layers in the future I think it's good to have separate files - maybe we can generate separate package files for the docker and containerd sysexts? We could also provide a unified one if there is need for that but since the concatenation is easy and we have the JSON files I would say it's enough.

**Comment by pothos** [comment]
Ah, my mistake, forgot that the docker/containerd package files are in the subfolder, all good:
https://alpha.release.flatcar-linux.net/amd64-usr/current/rootfs-included-sysexts/containerd-flatcar_packages.txt
https://alpha.release.flatcar-linux.net/amd64-usr/current/rootfs-included-sysexts/docker-flatcar_packages.txt

**Comment by t-lo** [comment]
Fixed by https://github.com/flatcar/flatcar-linux-release-info/pull/29 which just got merged.
