### ISSUE TITLE
[RFE] Update kernel in main to linux-6.6

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#1266]
## Current situation

We are on the previous LTS kernel in main.

## Ideal future situation

We update main to include the 6.6 kernel.

**Comment by jepio** [comment]
I'd suggest we time it similarly to other LTS kernel transitions: wait until a couple minor releases of 6.6.y have happened (10,15,20 depending on timing) and plan ahead for how best to make this work with channel transitions. We just switched alpha to 6.1.y in June.

**Comment by t-lo** [comment]
> I'd suggest we time it similarly to other LTS kernel transitions: wait until a couple minor releases of 6.6.y have happened (10,15,20 depending on timing) and plan ahead for how best to make this work with channel transitions. We just switched alpha to 6.1.y in June.

We could consider cycling 6.1 through one Stable major release before switching to 6.6 - i.e. merge this only after releasing the December (or even January) Alpha, depending on what we aim to base our next Stable on (I think ue-rs has a few pending items but otherwise we should be good feature-wise).

On the other hand I feel we shouldn't keep the PR pending for too long; there's momentum in this contribution which we would impede by parking it for months.
