### ISSUE TITLE
Dependency github.com/coreos/yaml uses LGPL-3.0 with linking exception - switch to go-yaml 

### ISSUE THREAD

**Issue by miao0miao** [flatcar/Flatcar#1271]
Project should consider whether it can switch to using https://github.com/go-yaml/yaml (from which [github.com/coreos/yaml](http://github.com/coreos/yaml) was forked), since go-yaml/yaml has relicensed to the more permissive license option Apache-2.0 AND MIT. Note that coreos/yaml was archived and unmaintained as of 2021.

**Comment by tormath1** [comment]
From a quick search (https://github.com/search?q=org%3Aflatcar%20github.com%2Fcoreos%2Fyaml&type=code), these software rely on `coreos/yaml`:
* coreos-cloudinit
* mantle (pulled in by coreos-cloudinit dependency)
