### ISSUE TITLE
Atom feeds are invalid

### ISSUE THREAD

**Issue by samm-git** [flatcar/Flatcar#128]
**Description**

Feed [www.flatcar-linux.org/releases-feed/releases-stable.xml](https://www.flatcar-linux.org/releases-feed/releases-stable.xml) is not passing validation. 

**Impact**

It is not possible to add feed to Slack, probably due to validation errors.

**Environment and steps to reproduce**

Open [w3c feed validator](https://validator.w3.org/feed/check.cgi). Paste URL of the stable feed (see https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.flatcar-linux.org%2Freleases-feed%2Freleases-stable.xml). It will multiply errors.  Also this feed cannot be added to slack (see [Add RSS feeds to Slack](https://slack.com/intl/en-cz/help/articles/218688467-Add-RSS-feeds-to-Slack?eu_nc=1)).

**Expected behavior**

No errors, passed validation

**Additional information**

Looks like that other feeds (tested with alpha) having same issue.

**Comment by dongsupark** [comment]
Thanks for the bug report.
Last week we fixed the validation errors in the atom feed.
It should work well now.
