### ISSUE TITLE
Kernel 5.7: backport a crypto/algapi bug fix

### ISSUE THREAD

**Issue by dongsupark** [flatcar/Flatcar#129]
**Current situation**
Since Kernel 5.6, we have seen occasional lockup issues in Linux Kernel, as described in a [bug tracker](https://bugzilla.kernel.org/show_bug.cgi?id=207159). The bug [fix](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.7.y&id=f6f785bdf6043f9a37fad5ffeaf5bb53e5b8afe2) has been included in mainline Kernels, since 5.7.6.

We should probably backport the bug fix to our Edge Kernel, 5.7.6.

**Comment by pothos** [comment]
Here it is the fix for the issue: https://lkml.kernel.org/linux-crypto/20200604185253.5119-1-ebiggers@kernel.org/ The patch you linked seems to be something else or is it also related?

**Comment by dongsupark** [comment]
The patch `crypto: algboss - don't wait during notifier callback` looks also like a bug fix.
Not sure which fixes what. (or both?)

**Comment by dongsupark** [comment]
The fix is included in Kernel v5.7.6.
Update the title and the description.

**Comment by pothos** [comment]
Can we close this as the next release will use the kernel with the fix?

**Comment by dongsupark** [comment]
ok
