### ISSUE TITLE
Docs: Running on Azure does not replace VM

### ISSUE THREAD

**Issue by TimoKramer** [flatcar/Flatcar#1299]
Hi,
I am running your example from your docs enhanced with some more networking etc. When I am changing the yaml-template it does not recreate the VM. So essentially changes are not applied since Flatcar does not apply changes without recreating the instance. I am not very familiar with Terraform but I need a way to force recreation on change and the docs should be having that as well.

**Comment by TimoKramer** [comment]
My bad, used user_data instead of custom_data

**Comment by pothos** [comment]
The providers all behave differently… ideally one could say with a property whether it should update in place or reprovision.
For reprovisioning you can model this in terraform with `triggers = {` and maybe also `depends_on = [`.
