### ISSUE TITLE
MMC driver not loaded in releases after 3602 with kernel 6.1

### ISSUE THREAD

**Issue by pysen** [flatcar/Flatcar#1300]
## Description

The mmc_block driver is no longer part of kernel 6.1 in Flatcar releases from 3619 and later. 

## Impact

I'm currently unable to update eMMC based nodes post 3602 as they are unable to find the operating system drive installed to an eMMC drive.
The error printed in the console is:
`Warning: /dev/disk/by-label/ROOT does not exist`

## Environment and steps to reproduce

1. Install Flatcar 3602 to any hardware with eMMC drive slot and start the upgrade. 

## Expected behavior

The update is successful and able to boot with kernel 6.1.

## Additional information

On Flatcar releases with kernel 5.15 the following drivers are loaded:

```
lsmod | grep mmc
mmc_block              57344  4
mmc_core              200704  4 sdhci,cqhci,mmc_block,sdhci_pci
```

Trying to load them on kernel 6.1.66 returns a FATAL error for `mmc_block` while `mmc_core` is able to load. 

Manually trying to load them on later kernels work (Archlinux 6.6 for example) so they most likely have been omitted in the upgrade from 5.15 -> 6.1 of Flatcar's kernel.

**Comment by pothos** [comment]
Thanks for the report, do you want to do a PR adding `CONFIG_MMC_BLOCK=m` to https://github.com/flatcar/scripts/blob/main/sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/commonconfig-6.6? We can also do a backport.

**Comment by pysen** [comment]
@pothos I added it in https://github.com/flatcar/scripts/pull/1510

**Comment by pothos** [comment]
It looks like the config setting is already there, at least on Beta, Alpha, and main: `zcat /proc/config.gz |grep CONFIG_MMC_BLOCK= → CONFIG_MMC_BLOCK=m`

```
Flatcar Container Linux by Kinvolk beta 3760.1.1 for QEMU
core@localhost ~ $ sudo -s
localhost /home/core # lsmod | grep mmc
localhost /home/core # modprobe mmc_block
localhost /home/core # modprobe mmc_core
localhost /home/core # lsmod | grep mmc
mmc_block              57344  0
mmc_core              208896  1 mmc_block
```

For Alpha I also tried it on arm64

**Comment by pothos** [comment]
It also works on the latest Stable:
```
Flatcar Container Linux by Kinvolk stable 3602.2.3 for QEMU
core@localhost ~ $ sudo -s
localhost /home/core # lsmod | grep mmc
localhost /home/core # modprobe mmc_block
localhost /home/core # modprobe mmc_core 
localhost /home/core # lsmod | grep mmc
mmc_block              57344  0
mmc_core              200704  1 mmc_block
```

**Comment by pothos** [comment]
Ah, it's missing in the initrd, that seems to be your problem

**Comment by pysen** [comment]
It was always available on the 3602 releases (what is currently running on the nodes) but any upgrade after that is missing `mmc_block`. How can we make sure it is available in the initrd for those releases as well?

**Comment by pothos** [comment]
I've created a PR, to test it we need to update the git reference in the bootengine ebuild file, see comments on your PR

**Comment by pothos** [comment]
Picked for Beta and Alpha

**Comment by pysen** [comment]
@pothos Thanks for the quick feedback to my issue, once the next beta release is out I will confirm that the mmc_block driver is in the initrd.
