### ISSUE TITLE
[RFE] Flatcar should support DRM and Virtio GPU

### ISSUE THREAD

**Issue by retpolanne** [flatcar/Flatcar#1304]
## Current situation

I'm currently using Flatcar on QEMU for Aarch64 on Packer. Packer sends boot commands through a VNC connection and it doesn't know how to send data to the VM somehow else. In order to change the password so we can access SSH, we need to send boot commands to the machine, even if we're trying to use ignition. [1] 

The virt machine on QEMU doesn't implement graphics, so it's not possible to use boot commands, unless we use the option `-device virtio-gpu` on QEMU - grub shows up but once kernel is booted we get no display due to CONFIG_DRM and CONFIG_DRM_VIRTIO_GPU not being set on the kernel. 

## Impact

Can't use Flatcar with Packer on QEMU aarch64.

## Ideal future situation

Be able to use Flatcar with Packer on QEMU aarch64. 

## Implementation options

Add these configs CONFIG_DRM and CONFIG_DRM_VIRTIO_GPU to the kernel for the qemu ARM 64 image build. 

## Additional information

[1] https://github.com/flatcar/flatcar-packer-qemu/blob/f710f2fbfa0b67076f63e550e003a0188cd2e0e5/flatcar-linux.json#L29

**Comment by pothos** [comment]
To solve your problem I would rather recommend to use an Ignition config that sets up SSH, or have a step that mounts the image and prepares it with the given SSH key by copying it over.

But anyway I would recommend you to look for alternatives: Using Packer creates state in the image that is hard to get rid off and can be a source of bugs. More to read here: https://www.flatcar.org/docs/latest/installing/customizing-the-image/customize-the-image/

**Comment by ader1990** [comment]
Hello,

This issue has already been addressed by https://github.com/flatcar/Flatcar/issues/1030 and fixed by https://github.com/flatcar/scripts/commit/c76e969d47edde66a9a1c7c8a1ab231cd18cfd3b.

This patch has landed first in [alpha-3637.0.0](https://github.com/flatcar/scripts/releases/tag/alpha-3637.0.0), maybe we should backport it to stable too?

Current stable is 3602.2.3.

@retpolanne what version are you now using?

Thank you.

**Comment by retpolanne** [comment]
Hey @ader1990, I was using flatcar current stable.

**Comment by ader1990** [comment]
@retpolanne beta or alpha should already have the required patch, but the flatcar current stable does not have it.

**Comment by ader1990** [comment]
Update: according to the release planning, the new stable that is going to be released in a few days from now, is going to be: 3760.2.0, which should contain the fix.

https://github.com/orgs/flatcar/projects/7/views/8?pane=issue&itemId=47547563

**Comment by ader1990** [comment]
Hello @retpolanne,

The stable version which was upated last week contains the necessary fix (3760.2.0).

Thank you,
Adrian

**Comment by retpolanne** [comment]
@ader1990 yay! It worked :) Don't forget `-device virtio-gpu -device virtio-keyboard` on qemu or packer.
