### ISSUE TITLE
How to use the intel iGPU ?

### ISSUE THREAD

**Issue by xh116** [flatcar/Flatcar#1306]
## Current situation

I am running flatcar in homelab, works well.  recently planning to use it as media server, seems it doesn't support intel iGPU. 

## Impact
for Plex/Emby/Jellyfin, which require GPU for transcoding, but intel iGPU driver not installed.
 
 Any idea to install that?

**Comment by ader1990** [comment]
Hello,

can you please provide the output of this command ```lspci -vvv |grep -i graphic```?

I have a Raptor Lake CPU, and in my case the output is "UHD Graphics 770", which needs ```CONFIG_DRM_I915=m```.
https://cateee.net/lkddb/web-lkddb/DRM_I915.html

Thanks,
Adrian

**Comment by xh116** [comment]
```
lspci -vvv |grep -i graphic
03:00.0 VGA compatible controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Integrated Graphics Controller (rev 0b) (prog-if 00 [VGA controller])
	Subsystem: Intel Corporation Apollo Lake [HD Graphics 505]
```
I have older one, It is recognized by default.
but folder of `/dev/dri` is empty, which means it has no driver.

**Comment by Superpiffer** [comment]
I have the same problerm with a different CPU:
```
lspci -vvv |grep -i graphic
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 500 (rev 0b) (prog-if 00 [VGA controller])
        Subsystem: Intel Corporation HD Graphics 500
```

No i915 module and no /dev/dri. I prefer not to build the module...

**Comment by r0bb10** [comment]
Same here with Alder Lake iGPU.

```
lspci -vvv |grep -i graphic
06:10.0 VGA compatible controller: Intel Corporation Alder Lake-N [UHD Graphics] (prog-if 00 [VGA controller])
        Subsystem: Intel Corporation Alder Lake-N [UHD Graphics]

**Comment by ader1990** [comment]
Hello,

I will make a PR with the required changes, which will trigger a github action that will build a Flatcar image with the new kernel.
Would it be possible that you download and test the resulting Flatcar image on your environments?

Thanks.

**Comment by xh116** [comment]
> Hello,
> 
> I will make a PR with the required changes, which will trigger a github action that will build a Flatcar image with the new kernel. Would it be possible that you download and test the resulting Flatcar image on your environments?
> 
> Thanks.

Thank you for the effort. I did a test on ESXi 8.0 update 2 (install by [flatcar-install](https://raw.githubusercontent.com/flatcar-linux/init/flatcar-master/bin/flatcar-install) script ). 
<img width="468" alt="image" src="https://github.com/user-attachments/assets/53048a4d-849f-45f4-a2d9-a54dbf43ddfa">
It is running. 

But when I add pci deivce (iGPU passthrough), It is stucked on booting.  
<img width="468" alt="image" src="https://github.com/user-attachments/assets/47c264a6-220b-4387-94ee-d4c69b4b531e">

It maybe problem with ESXi , if someone else could do a test on a physical machine will be better.

**Comment by ader1990** [comment]
Hello @xh116,

Currently I do not have a hardware env to test it either, help is welcome on that part.

Saw a similar issue documented here -> https://forum.proxmox.com/threads/vm-with-mediated-i915-gpu-fails-to-start-failed-to-find-vbios-tables.101756/ with this linked document that might bring some more clarity:
https://3os.org/infrastructure/proxmox/gpu-passthrough/igpu-split-passthrough/#linux-virtual-machine-igpu-passthrough-configuration

Most likely, in the virtualized scenario, there are extra steps to be done, like enabling iommu.

Thanks.

**Comment by r0bb10** [comment]
> Hello,
> 
> I will make a PR with the required changes, which will trigger a github action that will build a Flatcar image with the new kernel. Would it be possible that you download and test the resulting Flatcar image on your environments?
> 
> Thanks.

Hi!

I have to build the dev image and test it (on proxmox).

Alder Lake supports VF up to 7 virtual displays, just the host (in this case proxmox) should have iommu enabled and the kernel module loaded, the vm should have the same driver as the host. Like described here https://github.com/strongtz/i915-sriov-dkms the flatcar vm should only have a grub parameter set `i915.enable_guc=3` but it's only needed in a scenario with SRIOV enabled. Maybe build the module from the github repo and include it in flatcar? Shoul be backward compatible with everything older anyway.

As soon as i can i will test the dev image and report back.

**Comment by xh116** [comment]
> Hello @xh116,
> 
> Currently I do not have a hardware env to test it either, help is welcome on that part.
> 
> Saw a similar issue documented here -> https://forum.proxmox.com/threads/vm-with-mediated-i915-gpu-fails-to-start-failed-to-find-vbios-tables.101756/ with this linked document that might bring some more clarity: https://3os.org/infrastructure/proxmox/gpu-passthrough/igpu-split-passthrough/#linux-virtual-machine-igpu-passthrough-configuration
> 
> Most likely, in the virtualized scenario, there are extra steps to be done, like enabling iommu.
> 
> Thanks.


Hi @ader1990  
I just tested on PVE 8.2.2.
It is working now ! 
![QQ_1727807218703](https://github.com/user-attachments/assets/5c80ef04-43cc-4264-851e-33864f7abb27)
When it will be available in Beta or Alpha Channel to get updated every month ?

**Comment by savely-krasovsky** [comment]
I would reopen that, since PR still not merged.

**Comment by Kribbage** [comment]
Yeah, same issue on UHD graphics 630 still.

**Comment by savely-krasovsky** [comment]
@Kribbage it was merged, but I guess it will be in Alpha branch soon.

**Comment by tomalta** [comment]
> > Hello [@xh116](https://github.com/xh116),
> > Currently I do not have a hardware env to test it either, help is welcome on that part.
> > Saw a similar issue documented here -> https://forum.proxmox.com/threads/vm-with-mediated-i915-gpu-fails-to-start-failed-to-find-vbios-tables.101756/ with this linked document that might bring some more clarity: https://3os.org/infrastructure/proxmox/gpu-passthrough/igpu-split-passthrough/#linux-virtual-machine-igpu-passthrough-configuration
> > Most likely, in the virtualized scenario, there are extra steps to be done, like enabling iommu.
> > Thanks.
> 
> Hi [@ader1990](https://github.com/ader1990) I just tested on PVE 8.2.2. It is working now ! ![QQ_1727807218703](https://github.com/user-attachments/assets/5c80ef04-43cc-4264-851e-33864f7abb27) When it will be available in Beta or Alpha Channel to get updated every month ?

Is it possible to install the i915 guest DKMS in Flatcar and have the iGPU VF working or you're talking about a pre-compiled module for Flatcar?

**Comment by xh116** [comment]
> > > Hello [@xh116](https://github.com/xh116),
> > > Currently I do not have a hardware env to test it either, help is welcome on that part.
> > > Saw a similar issue documented here -> https://forum.proxmox.com/threads/vm-with-mediated-i915-gpu-fails-to-start-failed-to-find-vbios-tables.101756/ with this linked document that might bring some more clarity: https://3os.org/infrastructure/proxmox/gpu-passthrough/igpu-split-passthrough/#linux-virtual-machine-igpu-passthrough-configuration
> > > Most likely, in the virtualized scenario, there are extra steps to be done, like enabling iommu.
> > > Thanks.
> > 
> > 
> > Hi [@ader1990](https://github.com/ader1990) I just tested on PVE 8.2.2. It is working now ! ![QQ_1727807218703](https://github.com/user-attachments/assets/5c80ef04-43cc-4264-851e-33864f7abb27) When it will be available in Beta or Alpha Channel to get updated every month ?
> 
> Is it possible to install the i915 guest DKMS in Flatcar and have the iGPU VF working or you're talking about a pre-compiled module for Flatcar?

Sorry I didn't test much.
but I’m currently running Flatcar Alpha on bare metal, with NFS shares from TrueNAS mounted for Emby and Scrypted, everything is working smoothly. It’s a great OS choice for a homelab now.

**Comment by mikekuzak** [comment]
@xh116 
Hey how did you get it to work on PVE ? I tried this: 
https://3os.org/infrastructure/proxmox/gpu-passthrough/igpu-split-passthrough/#proxmox-configuration-for-gvt-g-split-passthrough

/dev/dri is still not visible in the VM. I'm running latest Flatcar beta and Proxmox VE 8.4.11. Some ppl said it's working on bare metal but not virtual.

**Comment by tomalta** [comment]
I have a 7 VF setup on my system and tried to install Flatcar Beta 4372.1.0, since seems to integrate the i915 drivers.
But setting it up with the legacy BIOS in Proxmox returns me this error when initializing the virtual device

```
[    4.207562] i915 0000:00:10.0: [drm] Found ALDERLAKE_P (device ID 46a6) display version 13.00 stepping D0
[    6.210426] i915 0000:00:10.0: [drm] *ERROR* Device is non-operational; MMIO access returns 0xFFFFFFFF!
[    6.213713] i915 0000:00:10.0: [drm] *ERROR* Device initialization failed (-5)
[    6.213972] i915 0000:00:10.0: probe with driver i915 failed with error -5
```

I've red through the documentation that UEFI is not supported so I stuck with fx440, passed the host CPU to the system and the system boots anyway.

I've been using the VFs without any issues for a while now so it's not a Proxmox issuue. Am I too out of the beaten path?
