### ISSUE TITLE
[RFE] Publish official Kubevirt images

### ISSUE THREAD

**Issue by lukasmrtvy** [flatcar/Flatcar#1358]
## Current situation

Flatcar does not work ( officially ) in Kubevirt and other platforms based on Kubevirt ( https://github.com/harvester/harvester ), because of the missing `flatcar.oem.id=kubevirt` parameter in grub.

## Impact

Mid

## Ideal future situation

Official Kubevirt images are published

## Implementation options

X

## Additional information

Images based on https://github.com/kubernetes-sigs/image-builder/ are working correctly

**Comment by tormath1** [comment]
@lukasmrtvy would you be interested to implement this by yourself? Here's an example with Scaleway: https://github.com/flatcar/scripts/pull/1683

**Comment by ader1990** [comment]
Hello, the official production image works (example: https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_production_image.bin.bz2), leveraging the coreos-cloudinit fallback implementation.

I think you mean adding support for Ignition to work with Flatcar deployed as a KubeVirt VM, which will be required as an oem image.

@lukasmrtvy The Kubevirt CDI helper usually supports .gz or .xz implementation, do you have a preference for the compression format?

Some documentation would be needed to give an example workflow though, with both Ignition and the coreos-cloudinit. Also to mention that Flatcar supports only cloudInitConfigDrive data source: https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#data-sources

Thank you,
Adrian Vladu
