### ISSUE TITLE
nvidia-driver: detection of nvidia devcies

### ISSUE THREAD

**Issue by heilerich** [flatcar/Flatcar#1364]
## Description

The nvidia.service uses `lspci | grep -i "${NVIDIA_PRODUCT_TYPE}")"` [here](https://github.com/flatcar/scripts/blob/da5844e796511a515193fe9c742bbce8e3935cdf/sdk_container/src/third_party/coreos-overlay/x11-drivers/nvidia-drivers/files/bin/setup-nvidia#L139) to detect the presence of nvidia devices. Not all Nvidia GPUs include their product type in the name that lspci outputs.

Changing the product type to something else that matches the devices breaks the download link for the driver files.

## Impact

Nvidia driver will not be installed on machines that need the driver.

## Expected behavior

Maybe just use `lspci | grep -i NVIDIA`. This is already happening in other places in the install script.

## Additional information

Flatcar 3815.2.0

**Comment by jepio** [comment]
Make sense.

Could you share examples of NVIDIA_PRODUCT_TYPE where this is needed?

**Comment by heilerich** [comment]
I think we might need two variables, one for the 'driver type' and one for identifying the devices. Currently, the NVIDIA_PRODUCT_TYPE variable is used for both.

For example:
- We have a setup that uses RTX Datacenter GPUs such as RTX 6000, Quadro and the like. There we would have to grep the lspci output for something like 'NVIDIA' or 'RTX'. Those devices use the tesla driver.
- There are many other cards out there, where this is true. The only system I have access to right now from this computer in fact uses a *Tesla* L40 but still shows up as `3D controller: NVIDIA Corporation AD104GL [L4] (rev a1)` in lspci.
- Some of our Datacenter GPUs show up with the string 'tesla' in lspci and can use the tesla driver. In this case the current script works. But if one would have to use the open driver e.g. for some legal reason, one would still have to grep for 'tesla' but use 'XFree86' in the driver URL.

So maybe two variables `NVIDIA_DEVICE_FILTER` and `NVIDIA_DRIVER_TYPE` are more sensible?

**Comment by jepio** [comment]
Can you check if the proposed function catches all of the cases that you listed above:
```
function is_nvidia_probe_required() {
  # Vendor: NVIDIA, Class: VGA compatible controller
  if [[ -n "$(lspci -d 10de:*:0300)" ]]; then
    return 0
  fi
  # Vendor: NVIDIA, Class: 3D controller
  if [[ -n "$(lspci -d 10de:*:0302)" ]]; then
    return 0
  fi
  return 1
}
is_nvidia_probe_required && echo "correct"
```
That should be generic enough and leave the user to only have to worry about the driver type to deploy.

**Comment by heilerich** [comment]
I have tested on systems containing RTX 2000, RTX 4000, RTX 6000 series consumer grade and datacenter GPUs as well as with Tesla A100 and L40 GPUs. Worked everywhere.

**Comment by jepio** [comment]
I'll close this since it's going to be part of the next set of releases.
