### ISSUE TITLE
VMtools can't get correct guestID for Flatcar 3760&3815 on ESXi 7.0.3

### ISSUE THREAD

**Issue by Winnie81** [flatcar/Flatcar#1365]
guestID returned from vmtools is empty for Flatcar 3760&3815 on ESXi 7.0.3, and it should be other5xLinux64Guest.
On ESXi 8.0, guestID could be got as expected other6xLinux64Guest.

vim-cmd vmsvc/get.guest 1
Guest information:

(vim.vm.GuestInfo) {
   toolsStatus = "toolsOk", 
   toolsVersionStatus = "guestToolsUnmanaged", 
   toolsVersionStatus2 = "guestToolsUnmanaged", 
   toolsRunningStatus = "guestToolsRunning", 
   toolsVersion = "12389", 
   toolsInstallType = "guestToolsTypeOpenVMTools", 
   toolsUpdateStatus = (vim.vm.GuestInfo.ToolsUpdateStatus) null, 
   guestId = "", 
   guestFamily = "linuxGuest", 
   guestFullName = "Linux 6.1.77-flatcar Flatcar Container Linux by Kinvolk 3815.2.0 3815.2.0 2024-02-12-2039 Flatcar Container Linux by Kinvolk 3815.2.0 (Oklo) cpe:2.3:o:flatcar-linux:flatcar_linux:3815.2.0:*:*:*:*:*:*:*", 
......
}

**Comment by jepio** [comment]
hi @Winnie81: do you know where the guestId comes from? Is it a value in the ovf file or is it something that the guest pushes to the hypervisor? Do you know where this needs to be fixed?

**Comment by Winnie81** [comment]
> hi @Winnie81: do you know where the guestId comes from? Is it a value in the ovf file or is it something that the guest pushes to the hypervisor? Do you know where this needs to be fixed?

Hi, Please ignore it, and it is not a issue for OS. Sorry for the inconvenience. Thanks.

**Comment by jepio** [comment]
@Winnie81 a user reported this: https://github.com/flatcar/Flatcar/issues/1370. Is there a way for us to control what gets pushed as guestFullName from within the guest? We can't remove fields from /etc/os-release but some of them are redundant.

**Comment by Winnie81** [comment]
> Is there a way for us to control what gets pushed as guestFullName from within the guest?

I'll discuss it with our dev. Thanks.
