### ISSUE TITLE
passwordHash is being ignored +autologin

### ISSUE THREAD

**Issue by zeph** [flatcar/Flatcar#1366]
or better... going through the https://www.flatcar.org/docs/latest/installing/bare-metal/raspberry-pi/ guide I can get a raspberry pi4 running FlatCar... I can ssh into the host, give I provided a key... but, if I try to access on the tty, even though I provided `passwordHash` in the configuration, the `core` user gets denied access

I tried several methods of hash creation and stumbled on the error as well of the wrong `password_hash` key (I had it as result of searching for documentation looking for "butane" and password hash), that won't be reflected in the `/etc/shadow` ... the used methods are: 
 - `mkpasswd --method=sha-512` directly on the running FlatCar instance (WILL BE IGNORED)
    ref: https://github.com/coreos/container-linux-config-transpiler/pull/125#pullrequestreview-82653630
 - running a docker container (cannot find the reference anymore) (WILL BE IGNORED)
 
 right now stumbled on https://www.flatcar.org/docs/latest/provisioning/config-transpiler/examples/#generating-a-password-hash
 
 latest... I wanted to wait to submit this ticket... given i got the ref above... I generated a hash via the python method... copied the `config.json` file directly on the OEM partition, overriding the `config.ign` file... given the hash seemed to be the only difference
> WARN: 1st time testing FlatCar over the weekend, I have no idea if there are other
 things involved during the image flashing process that I shall be aware of

...I ended up with a system that is doing "auto login" leaving me with a shell open on keyboard (not even asking for the password)
 
 extra searching on the topic... https://www.flatcar.org/docs/latest/installing/cloud/vmware/#disablingenabling-autologin  apparently it is a known "feature" https://github.com/flatcar/Flatcar/issues/396 ...but I don't get why it enabled itself now that I set a different hash (I leave the ticket here as a +1 not to the next one stumbling on this... maybe I'll self close it)

**Comment by zeph** [comment]
as mentioned, closing... as this seems to be a well documented topic, but a minefield in case of 1st testing

**Comment by zeph** [comment]
reopening... once disabled the autologin, fiddling with the kernel parameters... the hash seems still to be an invalid one

**Comment by zeph** [comment]
p.s. I can ssh login, I see the hash... no wait, it is a completely different one in `$ sudo cat /etc/shadow`

(I'm doing also a full re-flashing of the SD card once again... 
is `Ignition` config file applied during the boot? or is this a `flatcar-install` related deliverable?)

**Comment by zeph** [comment]
RTFM answer to myself... https://www.flatcar.org/docs/latest/provisioning/ignition/#ignition-only-runs-once

**Comment by tormath1** [comment]
Hi @zeph so what is the actual issue? How can we help you?

**Comment by zeph** [comment]
@tormath1 I tried several hashes, but none seems to be working as documented... I get to a keyboard in front of running instance with Flatcar but I cannot login... the only 2 option that worked to get access where the autologin (that suddenly took place, in an unexpected manner) and ssh-ing into the instance (via the authorized_key) 

I've been testing the setup using raspberry pi4 machines... 
I'm bringing up a QEMU setup to validate if I'm doing something wrong

p.s. I do see the hash inside `/etc/shadow` so, at this point I wonder if I have to fiddle with `pam.d` modules

**Comment by tormath1** [comment]
@zeph can you try generating your password hash with `openssl passwd -6`? 

EDIT: I just tried with `podman run -ti --rm quay.io/coreos/mkpasswd --method=sha-512` and that works too. Here's my configuration:
```yaml
---
version: 1.1.0
variant: flatcar
passwd:
  users:
    - name: core
      # foo
      # openssl passwd -6
      # podman run -ti --rm quay.io/coreos/mkpasswd --method=sha-512
      password_hash: $6$sn3ZSJJJln5JkAZb$VDTKzLpCyjlEe7Kh0DKjOnEawkkOoi0tOKVbcCv0FIWSf3u9Y1p1I5YdJJ5L8uDmmMvO2CBlmJZNdxFuekjjE1
kernel_arguments:
  should_not_exist:
    - 'flatcar.autologin'
```

Note: `yescrypt` method won't work as we don't build shadow `--with-yescrypt`

**Comment by zeph** [comment]
@tormath1 I'm missing a bit of information somewhere
... I tried the hash generated by that docker based method and still i got a mismatch

I see you use Butane based config and transpiling to Ignition... I need to start using that too, and `qemu` indeed helps, as the dumping into an SD card was really really taking lots of time to iterate with these tryouts... closing for now, must be an error on my side

for instance I see that the starting qemu image/file is changing at each boot, and I see the note in the `flatcar_production_qemu.sh` related to already booted nodes...
```
Options:
    -i FILE     File containing an Ignition config
                (needs \"-append 'flatcar.first_boot=1'\" for already-booted or PXE images)
```
so, if I make changes to the Ignition file, they are not being reflected in the image unless I pass that param
(or I start each time from a "virgin" downloaded image... which is what I'm doing right now with a copy)

**Comment by tormath1** [comment]
@zeph that is correct. Ignition configuration is applied once and only once from the initramfs. If you want to modify your Ignition configuration, it's better to start from a fresh image.
If you are new to Flatcar: welcome and I would recommend you to follow this tutorial: https://www.flatcar.org/docs/latest/tutorial/ you can also join our Matrix channel or Slack channel to have direct interaction with Flatcar users to help you in your learning.

**Comment by zeph** [comment]
p.s. thanks for the follow up @tormath1
