### ISSUE TITLE
[Question] is Locksmithd able to check components have stared up correctly ? 

### ISSUE THREAD

**Issue by mikekuzak** [flatcar/Flatcar#1367]
Hi, 

We are running a K8s cluster with 3 ETCD nodes and 3 Worker nodes on Flatcar. The Worker nodes have the flatcar-reboot-operator installed. 

The whole cluster upgraded from 3760.2.0 to 3815.2.0 and the Docker daemon failed to start up. The reason for that was an old config we had in daemon.json. 

failed to start daemon: error initializing graphdriver: overlay2: unknown option overlay2.override_kernel_check: overlay2
```
{
 "log-driver": "json-file",
 "log-opts": {
   "max-size": "30m",
   "max-file": "5"
 },
 "storage-driver": "overlay2",
 "storage-opts": [
   "overlay2.override_kernel_check=true"
 ]
}
```

Removing ``` "overlay2.override_kernel_check=true"``` fixed the issue. 
The problem we are having is the fact that all flatcar nodes did upgrade successful from a point of view of the OS. As mentioned the
ETCD nodes have locksmithd setup and restart at a specific time. So what happened, is Flatcar was restarted. The Locksmithd daemon came up and released the lock I guess, but docker didn't start up, then the next box continued with the upgrade, and we ending up with no ETCD up. 

Is there any good solution to make sure the boxes are not being bounced until docker is up ? I guess for the worker nodes the flatcar-operator would prevent a reboot of the next box if the previous didn't come up ? 

Thanks for any advise and feedback.

**Comment by jepio** [comment]
hi @mikekuzak,
you should be able to add services you require to be running post-update as dependencies of update-engine (https://www.flatcar.org/docs/latest/setup/debug/manual-rollbacks/#automated-rollbacks).

Locksmithd has an `After=update-engine.service` requirement, so this should make sure locksmith does not let more nodes update if the required services don't start post-update.

**Comment by mikekuzak** [comment]
I guess this should do the trick

```
 cat /etc/systemd/system/locksmithd.service.d/10-dependency-dockerd.conf

[Unit]
Requires=docker.service
After=docker.service
After=update-engine.service
```

![image](https://github.com/flatcar/Flatcar/assets/18675587/49cce5c8-bc01-4f37-8c09-20d63bd185f1)

I won't solve the problem to check if ETCD container is up without writing another systemd script checking for that .. but it's better than before I guess.

**Comment by jepio** [comment]
The drop-in should be on the `update-engine.service` instead of `locksmithd.service` so that the update is not considered "successful" too.
