### ISSUE TITLE
Update: keyutils to keyutils-1.6.2+ (currently 1.6.1)

### ISSUE THREAD

**Issue by Starblade42** [flatcar/Flatcar#1372]
**Name:** keyutils
**Action Needed:** update to >= 1.6.2

## Summary

Keyutils 1.6.1 does not follow Azure File mounts if they experience rebalancing and an accompanying update to their DNS entry. If this happens with keyutils 1.6.1 the node will report "Host is Down" until it is rebooted, or the pod is scheduled on a node that did not mount the Azure File before the rebalance. This occurs in all shipping versions of Flatcar that I know of.

Azure documentation: [DNS issues with live migration of Azure storage accounts](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/files-troubleshoot-linux-smb#dns-account-migration)

Azure File mounts for PVCs in Kubernetes will sometimes experience re-balancing. The underlying storage location and DNS record are updated when this happens. In keyutils-1.6.1 which is currently installed in Flatcar, this results in a `Host is Down` message. The old host is no longer serving the Azure File mount, and keyutils has a bug that won't follow the new DNS entry.

If this is the right place to be looking, it looks like Keyutils 1.6.3 is the current version. https://packages.gentoo.org/packages/sys-apps/keyutils

**Comment by Starblade42** [comment]
Thank you!

**Comment by tormath1** [comment]
Hello @Starblade42, `keyutils` has been updated to 1.6.3 in all Flatcar channels. It will be available in the next release that should arrive in the next week. Let us know if it solves your issue!
