### ISSUE TITLE
Wrong path for ignition config.ign in custom OEM

### ISSUE THREAD

**Issue by FedericoHeichou** [flatcar/Flatcar#1376]
Here https://www.flatcar.org/docs/latest/installing/bare-metal/booting-with-pxe/#adding-a-custom-oem is written that the path for ignition config.ign in custom OEM is `usr/share/oem`.  
But the config was not loaded.  
After debugging in the flatcar with `journalctl --all` I found out that the correct location was `usr/lib/ignition/base.d` (and other subdirs).  
I used the current stable channel.

**Comment by pothos** [comment]
Thanks, sounds like this part here should still use `/usr/share/oem`:
https://github.com/flatcar/bootengine/blob/a85e1977b29dbe8315733dbe1b1ab3ab84d039a2/dracut/30ignition/ignition-setup.sh#L19
```
pxe)
    # OEM directory in the initramfs itself
    src=/oem
```

Created a PR https://github.com/flatcar/bootengine/pull/88

**Comment by FedericoHeichou** [comment]
Wow, so fast. Huge thanks.  
I'm new to Flatcar, do you know how much time should pass before a new stable is tagged with this commit? Otherwise, I can easily go with the workaround and use the dst path directly like I did yesterday

**Comment by pothos** [comment]
A bugfix release should be out in around 2 weeks.

**Comment by pothos** [comment]
Will close already while we wait for the release
