### ISSUE TITLE
Systemd: Issue while getting hostname with “%H” unit file parameter.

### ISSUE THREAD

**Issue by ethicalmohit** [flatcar/Flatcar#138]
**Description**

systemd is not able to get the value of the %H in the unit file parameter and getting localhost instead.

```
        After=systemd-hostnamed.service
        ExecStart=/usr/bin/docker run --name logspout --hostname logspout \
                                --env SYSLOG_HOSTNAME=%H \
```

**Impact**

There are a certain services that are dependent on the system hostname. Like log forwarding service. If it's not able to get the correct hostname and push logs with "localhost" as hostname then it's very difficult to tell the exact machine in dynamic inventory like AWS ec2.

**Environment and steps to reproduce**

1. **Set-up**: AWS EC2 
2. **Task**: Getting hostname value in systemd service with "%H".
3. **Action(s)**: In a systemd service.
4. **Error**: Setting localhost as the hostname.

**Expected behavior**
It should get the hostname of the EC2 instance instead of the localhost.

**Comment by pothos** [comment]
I'll just quickly note what I responded in the mailing list:

_I didn't have time to look into it in detail yet but you I think should set the hostname via Ignition by either writing directly to `/etc/hostname` or creating a service that runs this:_
`coreos-metadata --cmdline --hostname /etc/hostname`

_and then depend on that service with `Requires=`, `After=`.
That said, I didn't try it out but this is something which should be done by default._

**Comment by echomohit** [comment]
I did it with a custom systemd unit service by fetching hostname from the AWS EC2 instance metadata service.
