### ISSUE TITLE
toolbox: Mounted snapshots are being gc'ed which bricks the toolbox

### ISSUE THREAD

**Issue by daMupfel** [flatcar/Flatcar#1399]
## Description

This is the related issue to PR https://github.com/flatcar/toolbox/pull/9. I wasn't sure if toolbox PRs will directly be looked up or if you guys want an issue to track it.

The toolbox uses ctr under the hood if available. The 'ctr image mount' command by default adds a 1 day lease on the created snapshot that is mounted as the upperdir. Therfore the snapshot will be gc'ed and the toolbox not function correctly anymore as the upperdir does not longer exist.

## Impact

The toolbox bricking itself which requires an unmount to fix it.

## Environment and steps to reproduce

When ctr is available on the host.

1. Create a toolbox and edit some files
2. Wait for a day
3. Toolbox is now broken

## Expected behavior

The toolbox to work.

## Additional information

Can be found with PR: https://github.com/flatcar/toolbox/pull/9

**Comment by jepio** [comment]
HI @daMupfel, I saw your PR but it's been a busy time, sorry for not getting back to you with a review. I'll post my question there.

**Comment by daMupfel** [comment]
No worries, just wasn't sure if you guys prefer to have a tracking issue for it, since not much is happening in the toolbox repo in general :).

Thank you very much for looking at this! 

Regards,

David

**Comment by jepio** [comment]
Merged and backported to all channels. Will be released in april.

**Comment by daMupfel** [comment]
Thank you very much :) :pray:!
