### ISSUE TITLE
multiple OEM-GCE container get started on GCE when using non-Google DNS

### ISSUE THREAD

**Issue by HeikoOnnebrink** [flatcar/Flatcar#14]
Issue was already filed on CoreOS repo, but no progress there (see https://github.com/coreos/bugs/issues/2601 )

Hope the reference to original issue is fine .. otherwise I will copy over all the details here .. 

Today I retested the problem using latest Flatcar Linux 2303.3.1 and problem does still reproduce.
I hoped that https://github.com/flatcar-linux/coreos-overlay/pull/69 might have fixed it but it had no impact.

Hope to find here someone to have a look .. (thx in advance !!)

**Comment by t-lo** [comment]
@HeikoOnnebrink  We will consider merging this fix with the next upcoming Stable.

**Comment by HeikoOnnebrink** [comment]
@t-lo  I saw that 2303.4.0 was release today but see no reference to the above bug fix.
May I assume above fix did not make it into 2303.4.0?

**Comment by pothos** [comment]
We missed it in the release notes, sorry. Now they are fixed: https://www.flatcar-linux.org/releases/

I will close this issue now, but please reopen if you have any problems.

Thanks for the bug report!
