### ISSUE TITLE
Cannot fetch kernel sources for kernel module installation

### ISSUE THREAD

**Issue by maxbischoff** [flatcar/Flatcar#140]
**Description**

When following the documentation in https://docs.flatcar-linux.org/os/kernel-modules/#prepare-a-flatcar-container-linux-development-container, `emerge -gKv coreos-sources` fails to read packages from the portage binhost. The binhost points to a coreos-repository for which no recent releases exist.

<details><summary>log</summary>

```
$ emerge -gKv coreos-sources


!!! Error fetching binhost package info from 'http://builds.developer.core-os.net/boards/amd64-usr/2345.3.1/pkgs/'
!!! HTTP Error 404: Not Found



!!! Error fetching binhost package info from 'http://builds.developer.core-os.net/boards/amd64-usr/2345.3.1/toolchain/'
!!! HTTP Error 404: Not Found


These are the packages that would be merged, in order:

Calculating dependencies -Unable to unshare: EPERM
 \Unable to unshare: EPERM
 |Unable to unshare: EPERM
 /Unable to unshare: EPERM
 |Unable to unshare: EPERM
 \Unable to unshare: EPERM
 /Unable to unshare: EPERM
 -Unable to unshare: EPERM
 \Unable to unshare: EPERM
 -Unable to unshare: EPERM
 |Unable to unshare: EPERM
... done!

emerge: there are no binary packages to satisfy "coreos-sources".

emerge: searching for similar names...
emerge: Maybe you meant any of these: sys-kernel/coreos-modules, coreos-base/coreos-dev, coreos-base/coreos-au-key?
```
</details>

**Impact**

This bugs stops me from setting up my installation pipeline for custom kernel modules.

**Environment and steps to reproduce**

1. **Set-up**: flatcar development image v2345.3.1, imported and run as docker image following the approach of https://github.com/BugRoger/coreos-developer-docker
2. **Task**: download of the kernel sources, `emerge -gKv coreos-sources`
3. **Action(s)**:
  a. start the custom flatcar developer image
  b. run `emerge-gitclone`
  c. `emerge -gKv coreos-sources`
4. **Error**: `emerge` could not find any binary packages to satisfy "coreos-sources"  

**Expected behavior**
Expected `coreos-sources` to be fetched.

**Comment by pothos** [comment]
Hello,
please use the latest version where this is fixed:
https://www.flatcar-linux.org/releases/#release-2512.2.0

```
Bug fixes:
Use the correct BINHOST URLs in the development container to download binary packages
```

**Comment by maxbischoff** [comment]
Thanks, I missed that one!
