### ISSUE TITLE
"kola" test automation still uses deprecated Equinix Metal "facilities" automation

### ISSUE THREAD

**Issue by vielmetti** [flatcar/Flatcar#1408]
## Description

[ 1 paragraph concisely describing the bug ]

The "kola" component of "mantle" is automation for cloud resource provisioning. It 
currently uses a deprecated "facility" parameter for provisioning resources in Equinix
Metal which is replaced by a current "metro" parameter.

## Impact

[ 1 sentence detailing the impact this bug is creating for you ]

When this feature is soon taken offline, "kola" jobs will fail. They currently
generate a warning at the API level.

## Environment and steps to reproduce

1. **Set-up**: Flatcar testing on Equinix Metal
2. **Task**: Noticed during provisioning by our automation tooling
3. **Action(s)**: 
  a. Provision a new resource using "kola", which appears to be invoked by Jenkins
4. **Error**: 
 a. Our automation throws a warning message

## Expected behavior

If the "metro" option is used instead of "facility", all will be well.

## Additional information

Link to line of code where this is found:

https://github.com/flatcar/mantle/blob/e9d31a22cb584746ed9bd8dba2567d7028bf1826/cmd/kola/kola.go#L191 

kola description

https://github.com/flatcar/mantle/blob/flatcar-master/README.md#kola

deprecation notice

https://deploy.equinix.com/developers/docs/metal/locations/facilities/

**Comment by tormath1** [comment]
For historical purpose, here's the message on Slack:
> Hello Ed and thanks for the heads-up. We are using metro parameter in our CI since 2022 see here:
>
>  * https://github.com/flatcar/mantle/commit/8bb47f54272ae18ea28bc0d7b1f61df3257d9514
>  * https://github.com/flatcar/scripts/blob/a5336c651a40ce5d08c8b8df771b6434c95ddf42/ci-automation/vendor-testing/equinix_metal.sh#L42
>
> What you shared here: https://github.com/flatcar/mantle/blob/e9d31a22cb584746ed9bd8dba2567d7028bf1826/cmd/kola/kola.go#L191 is just used for debugging purposes but I'll update it for consistency sake.
