### ISSUE TITLE
Remove expired AddTrust CA

### ISSUE THREAD

**Issue by MichaelSchroll** [flatcar/Flatcar#141]
**Description**

AddTrust_External_Root.pem is the [Sectigo Root CA](https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020) which expired on May 30, 2020. For certs which are signed by multiple chained roots, curl will return an error.

**Impact**

A base install produces SSL errors due to this cert being included; and must be removed with:
```
rm /etc/ssl/certs/AddTrust_External_Root.pem
update-ca-certificates
```
It would be convenient to not have to do this cleanup on each fresh install.

**Environment and steps to reproduce**

1. **Set-up**: Flatcar stable 2512.2.0
2. **Task**: curl https://downloads.activestate.com
3. **Action(s)**: Same as above
4. **Error**: `curl: (60) SSL certificate problem: certificate has expired
`
or as seen in curl -v -k 
```
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify result: certificate has expired (10), continuing anyway.
```

**Expected behavior**
curl ignores an expired chained cert.

**Additional information**
N/A

**Comment by t-lo** [comment]
Interesting, this affects a number of certs:
```
core@flatcar & for pem in /etc/ssl/certs/*.pem; do openssl x509 -in $pem -text | awk -v file="$pem" '/Not After/{ if ($7 < 2021) print file ":" $0}'; done
/etc/ssl/certs/AddTrust_External_Root.pem:            Not After : May 30 10:48:38 2020 GMT
/etc/ssl/certs/AddTrust_Low-Value_Services_Root.pem:            Not After : May 30 10:38:31 2020 GMT
/etc/ssl/certs/AddTrust_Public_Services_Root.pem:            Not After : May 30 10:41:50 2020 GMT
/etc/ssl/certs/AddTrust_Qualified_Certificates_Root.pem:            Not After : May 30 10:44:50 2020 GMT
/etc/ssl/certs/ApplicationCA_-_Japanese_Government.pem:            Not After : Dec 12 15:00:00 2017 GMT
/etc/ssl/certs/Buypass_Class_2_CA_1.pem:            Not After : Oct 13 10:25:09 2016 GMT
/etc/ssl/certs/Certplus_Class_2_Primary_CA.pem:            Not After : Jul  6 23:59:59 2019 GMT
/etc/ssl/certs/DST_ACES_CA_X6.pem:            Not After : Nov 20 21:19:58 2017 GMT
/etc/ssl/certs/Deutsche_Telekom_Root_CA_2.pem:            Not After : Jul  9 23:59:00 2019 GMT
/etc/ssl/certs/GeoTrust_Global_CA_2.pem:            Not After : Mar  4 05:00:00 2019 GMT
/etc/ssl/certs/Microsec_e-Szigno_Root_CA.pem:            Not After : Apr  6 12:28:44 2017 GMT
/etc/ssl/certs/PSCProcert.pem:            Not After : Dec 25 23:59:59 2020 GMT
/etc/ssl/certs/Staat_der_Nederlanden_Root_CA_-_G2.pem:            Not After : Mar 25 11:03:10 2020 GMT
/etc/ssl/certs/TURKTRUST_Certificate_Services_Provider_Root_2007.pem:            Not After : Dec 22 18:37:19 2017 GMT
/etc/ssl/certs/TÜBİTAK_UEKAE_Kök_Sertifika_Hizmet_Sağlayıcısı_-_Sürüm_3.pem:            Not After : Aug 21 11:37:07 2017 GMT
/etc/ssl/certs/UTN_USERFirst_Email_Root_CA.pem:            Not After : Jul  9 17:36:58 2019 GMT
/etc/ssl/certs/UTN_USERFirst_Hardware_Root_CA.pem:            Not After : Jul  9 18:19:22 2019 GMT
```

Turns out our [ca-certificates](https://github.com/kinvolk/coreos-overlay/blob/main/app-misc/ca-certificates/ca-certificates-3.27.1-r1.ebuild) package uses a Mozilla bundle release from 2016 (3.27.1). We should upgrade to 3.69 or newer (if available), see https://ftp.mozilla.org/pub/security/nss/releases/.

**Comment by pothos** [comment]
Update to 3.69.1 was done in https://github.com/flatcar-linux/coreos-overlay/pull/1355
