### ISSUE TITLE
Upgrade from 3510.2.8 to 3815.2.0 does not create /etc/extensions/containerd-flatcar.raw symlink

### ISSUE THREAD

**Issue by richardzuidhof** [flatcar/Flatcar#1414]
## Description

After upgrading from release 3510.2.8 to 3815.2.0 the symlinks for containerd/dockerd in /etc/extensions are not created. From 3760.2.0 to 3815.2.0 this issue does not occur.

## Impact

After some automated upgrades containerd fails to start

## Environment and steps to reproduce

1. **Set-up**: Running Flatcar 3510.2.8 on Vmware
2. **Task**: Updating to https://update.release.flatcar-linux.net/amd64-usr/3815.2.0/flatcar_production_update.gz using the update-engine
3. **Action(s)**: Update and reboot
4. **Error**: After reboot containers would not start because no container engines were running

## Expected behavior

When updating to the latest release of Flatcar that uses sysext images the required symlinks should be always be created

## Additional information

Please add any information here that does not fit the above format.

**Comment by pothos** [comment]
I couldn't reproduce this from a fresh VM, can you share more about the setup?

**Comment by pothos** [comment]
Maybe `/etc/extensions/` already existed and had a different mode or other differences that prevent the symlinks from the underlay to show up.
During the update to 3815.2.0 the `overlay.opaque` attr is already cleared if it had existed, that shouldn't be the problem.

**Comment by richardzuidhof** [comment]
Very strange indeed. I can not reproduce it anymore either.
