### ISSUE TITLE
open-vm-tools log file fills up with useless messages

### ISSUE THREAD

**Issue by neilmayhew** [flatcar/Flatcar#142]
**Description**

`/var/log/vmware-vmsvc.log` and it's rotated backups contain many MB of repeated messages:

```
[2020-06-16T07:04:45.456Z] [ warning] [guestinfo] GetDiskInfo: ERROR: Partition name buffer too small
[2020-06-16T07:04:45.456Z] [ warning] [guestinfo] Failed to get disk info.
```

These appear every 30s.

**Impact**

This wastes space in `/var/log`.

**Environment and steps to reproduce**

1. **Setup**: Flatcar stable release which uses `open-vm-tools` 10.3.0.5330
2. **Task**: Normal operation
3. **Action(s)**: Leave it running for several days
4. **Error**: `/var/log/vmware-vmsvc.log` grows large and contains nothing but repeated messages

**Expected behavior**
No errors from `GetDiskInfo` in the log.

**Additional information**
This is fixed in version 11 of `open-vm-tools` which is now in the Alpha channel.

See:
* https://github.com/vmware/open-vm-tools/issues/346
* https://blog.jpboyce.org/2019/12/08/vra-8-getdiskinfo-error-partition-name-buffer-too-small/

**Comment by dongsupark** [comment]
Is it still an issue?
Stable 2605.5.0 or newer has open-vm-tools 11.1.5, which should already have the bug fix against the issue.

**Comment by neilmayhew** [comment]
It is an issue until the root cause of #199 is fixed since existing installations that self-upgrade to 2605.5.0 will still have an older version of `open-vm-tools`. However, when that happens the tools won't work at all and there won't be any further log messages, so I think it's appropriate to close this issue and leave #199 open.
