### ISSUE TITLE
netpref license gets the wrong license from upstream

### ISSUE THREAD

**Issue by miao0miao** [flatcar/Flatcar#1459]
## Description
[netperf](https://github.com/flatcar/scripts/blob/main/sdk_container/src/third_party/portage-stable/licenses/netperf) gets the license from upstream. 
The license is pulled from http://www.netperf.org/ - the website is down.
It moved to Github https://github.com/HewlettPackard/netperf and uses the MIT license

**Comment by ader1990** [comment]
The License is still correct, as the Gentoo upstream and Flatcar still use the 2.7.0 tar.gz sources. See: https://github.com/flatcar/scripts/blob/main/sdk_container/src/third_party/portage-stable/net-analyzer/netperf/netperf-2.7.0-r3.ebuild#L9C10-L9C31

**Comment by t-lo** [comment]
I think we should update to the one that switched to the MIT license; the one we're shipping cannot be used for commercial purposes. Either we update or we switch to something more modern (and better maintained) entirely, e.g. `fio`.

**Comment by ader1990** [comment]
> I think we should update to the one that switched to the MIT license; the one we're shipping cannot be used for commercial purposes. Either we update or we switch to something more modern (and better maintained) entirely, e.g. `fio`.

We could fork the repo under the Flatcar umbrella, create a tag and a release on Github so that the sources can be retrieved and then move it from portage stable to overlay?

**Comment by ader1990** [comment]
The best way would be though to +1 this issue https://github.com/HewlettPackard/netperf/issues/75?

**Comment by jepio** [comment]
I pushed a PR that can be used as a reference showing how to package a fixed commit of netperf: https://github.com/flatcar/scripts/pull/2015

Please feel free to take over, I don't really have the time to follow up on this.

**Comment by jepio** [comment]
Thilo found that netperf is part of production images, but only the devcontainer. It's better to drop.

**Comment by t-lo** [comment]
Gentoo upstream is now shipping an ebuild of the latest github state: https://github.com/gentoo/gentoo/blob/6f42017f1c4cb1ff42618a097f87fceffbdf1ad3/net-analyzer/netperf/netperf-2.7.0_p20210121.ebuild#L10

It's unstable (masked), but we could import that and unmask it for Flatcar. Ships with MIT license.
