### ISSUE TITLE
public.update.flatcar-linux.net not available

### ISSUE THREAD

**Issue by ghost** [flatcar/Flatcar#146]
**Description**

I have tried to upgrade from CoreOS to Flatcar using the documentation at https://docs.flatcar-linux.org/os/update-from-container-linux/ and it turns out that the server public.update.flatcar-linux.net cannot be reached. 

**Impact**

Cannot upgrade from CoreOS to Flatcar.

**Environment and steps to reproduce**

1. **Set-up**:
```
$ uname -a
Linux transac 4.19.123-coreos flatcar-linux/docs#1 SMP Fri May 22 19:21:11 -00 2020 x86_64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz GenuineIntel GNU/Linux
```
2. **Task**:
```
$ sudo update_engine_client -update
I0622 09:00:56.318991  9501 update_engine_client.cc:247] Initiating update check and install.
I0622 09:00:56.320199  9501 update_engine_client.cc:252] Waiting for update to complete.
LAST_CHECKED_TIME=0
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_IDLE
NEW_VERSION=0.0.0
NEW_SIZE=0
E0622 09:01:01.905836  9501 update_engine_client.cc:190] Update failed.
```
```
$ ping public.update.flatcar-linux.net
PING nebraska-lb-746246376.eu-central-1.elb.amazonaws.com (18.157.55.186) 56(84) bytes of data.
^C
--- nebraska-lb-746246376.eu-central-1.elb.amazonaws.com ping statistics ---
12 packets transmitted, 0 received, 100% packet loss, time 11275ms
```
3. **Action(s)**: Executing the steps in update-to-flatcar.sh

4. **Error**: 
E0622 09:01:01.905836  9501 update_engine_client.cc:190] Update failed.

**Expected behavior**
public.update.flatcar-linux.net should be reachable and respond to to update requests

**Additional information**

I am not sure, if it is a temporary problem with the upgrade server, or if it has been moved to another location. Please update documentation if the later is the case.

**Comment by t-lo** [comment]
Hello @helma 

thank you for reporting this issue. We are currently investigating an issue with our update server; we will keep you posted on our progress.

I've moved this issue to the top-level *Flatcar* project which we use to track all Flatcar related issues at a central location.

Please note that the server will not respond to ICMP requests. If you like to validate whether the server is reachable please issue HTTPS POST requests, e.g.
```shell
$ curl -XPOST -I https://public.update.flatcar-linux.net/v1/update
HTTP/2 200
date: Mon, 22 Jun 2020 10:13:30 GMT
content-type: text/xml
content-length: 0
```

**Comment by t-lo** [comment]
Update: We identified the root cause and have found a work-around. Updates should now work as expected.

We'll leave this issue open for tracking until we addressed the root cause and can remove the work-around.

**Comment by ghost** [comment]
Thanks a lot for your quick response! I can confirm that the work-around is working at the moment and that the update from CoreOS works as expected.
