### ISSUE TITLE
Latest `stable` `3815.2.3` release not on azure market place.

### ISSUE THREAD

**Issue by ericgraf** [flatcar/Flatcar#1469]
## Description

Latest `stable` `3815.2.3` release not available on azure market place.

related conversation: https://fromm.social/@thilo/112610173791849857
related issue: https://github.com/flatcar/Flatcar/issues/1450

## Impact

We are not able to use the latest flatcar stable image on azure.

## Environment and steps to reproduce

Simply follow docs https://www.flatcar.org/docs/latest/installing/cloud/azure/. 

The docs are also incorrect stating the latest available 3815.2.3 when only 3815.2.2 is available. 

## Expected behavior

The latest stable to be available to use.

## Additional information

Please add any information here that does not fit the above format.

**Comment by tormath1** [comment]
Thanks for opening this, we are working on it.

**Comment by tormath1** [comment]
@ericgraf FYI some Flatcar offers have started to be published on Azure.

**Comment by ericgraf** [comment]
Image is now available. @tormath1 Thank you for doing that. 

Do you know if future releases will be automatically added again?

**Comment by tormath1** [comment]
@ericgraf most of the release is done automatically (including marketplace publishing (like AWS or Azure)) - but we still need to deal with APIs changes, requirements, etc. It's not perfect and we will continue to invest effort to adapt.

When such an issue occurs, we usually communicate on the issue tracker (example: https://github.com/flatcar/Flatcar/issues/1425#issuecomment-2102633295).

If it's good for you, feel free to close the issue and thanks again for raising this.
