### ISSUE TITLE
Setting static route using systemd-networkd kills networking

### ISSUE THREAD

**Issue by kaplan-michael** [flatcar/Flatcar#147]
**Description**

Adding file 10-static.network to /etc/systemd/network/ with example content 
`[Route]`
`Gateway=192.168.122.1`
`Destination=172.16.0.0/24`
prevents IP assignment using DHCP

**Impact**

On reboot or `sudo systemctl restart systemd-networkd` IP address is not assigned therefore losing connection to the machine.

**Environment and steps to reproduce**

1. have flatcar running on qemu vm
2. have IP assigned using DHCP
3. add static route file to  /etc/systemd/network/
4. restart networking using `sudo systemctl restart systemd-networkd`
5. Lost connection to the machine

**Expected behavior**
Add file with static route. restart networking and have static route working

**Additional information**
adding route using ip route add works fine

**Comment by pothos** [comment]
Hi,

you have to add this as well to your file:

```
[Network]
DHCP=yes
```

Maybe systemd assumes that static assignments are used as soon as you specify a route entry. You can file an upstream bug if this is also reproducible in other distributions. If it isn't we may add this special case to the docs.

**Comment by kaplan-michael** [comment]
Hi, 

I will try this.
I can try to reproduce it in other distributions

**Comment by kaplan-michael** [comment]
Hey, with a small modification it worked for me.
Pasting here if anybody has the same problem and closing. Thanks @pothos 
```
[Match]
Name=eth0

[Network]
DHCP=yes

[Route]
Gateway=192.168.122.1
Destination=172.16.0.0/24
GatewayOnlink=yes
```
