### ISSUE TITLE
parse-ip-for-networkd fails when running against the pxe ramdisk

### ISSUE THREAD

**Issue by bobveznat** [flatcar/Flatcar#148]
I'm referencing this code:
https://github.com/flatcar-linux/bootengine/blob/8043da392dea21dbcaac57256d7c0a78e270bc53/dracut/03flatcar-network/parse-ip-for-networkd.sh#L73

We have a pxe boot environment that doesn't use DHCP (it's crazier than you think). Everything is statically configured from the firmware we run on the NICs down. We use the ip= kernel command line option to propagate network config through the layers during boot.

However, in the flatcar pxe ramdisk there's no /etc/systemd/network directory. This means that parse-ip-for-networkd can't generate it's output files.

Might I suggest a `mkdir -p $(basename $_net_file)` be inserted as line 74?

We worked around the issue by putting the directory into the pxe ramdisk.

**Comment by pothos** [comment]
Hello,
thanks a lot for reporting!
Yes, would also be good to see if this affected non-PXE environments the whole time…
A simple `mkdir` may work or we have a look again if something changed which lead to this.

**Comment by pothos** [comment]
This is merged now and will be included in future releases of all channels (but not the Alpha that is released this week).

**Comment by bobveznat** [comment]
Looks perfect, thank you!

**Comment by pothos** [comment]
Do you need the PXE image files now to test it? I made a manual build of Stable with this fix and can share it if you want.

**Comment by pothos** [comment]
By the way, testing with PXE boots in QEMU works with this script https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_pxe.sh
but you always need to specify the first boot flag. Including the static IP configuration it would be:
```
./flatcar_production_pxe.sh -curses -append 'flatcar.first_boot=1 flatcar.autologin ip=10.0.2.15::10.0.2.2:255.255.255.0::eth0:none:1.1.1.1:8.8.8.8 ignition.config.url=http://192.168.1.123:8000/my-ignition-config'
```

Edit: Adding `flatcar.autologin` also makes sense so that you can directly use the serial console.
