### ISSUE TITLE
/usr/bin/flatcar-update throwing errors when upgrading from 3815.2.0 on GCE vms

### ISSUE THREAD

**Issue by HarithaRamesh** [flatcar/Flatcar#1485]
## Description

I use flatcar in an airgapped system, so my mode of upgrade from 3760.2.0 was to run 
```
/usr/bin/flatcar-update -P flatcar/flatcar_production_update.gz -V 3815.2.0 -E flatcar/oem-gce.gz -A
```
Having downloaded the artifacts from https://update.release.flatcar-linux.net/amd64-usr. This works fine going from 3760.2.0 --> 3815.2.0 or 3760.2.0 --> 3815.2.3. However, I'm seeing errors when going from 3815.2.0 --> 3815.2.3 on GCE specifically

## Impact

I am not able to upgrade from 3815.2.0 in my airgapped environment on GCE VM. I have tested the 3815.2.0 --> 3815.2.3 path on vmware and azure, those seem to work with the respective oem-vmware.gz and oem-azure.gz files

## Environment and steps to reproduce

1. **Set-up**: This is a GCE flatcar OS machine on OS version 3815.2.0. No public internet access, I have downloaded the flatcar artifacts separately and put it on vm. 
2. **Task**: Trying to update flatcar OS to 3815.2.3
3. **Action(s)**: 
  a. Downloaded the artifacts from https://update.release.flatcar-linux.net/amd64-usr for 3815.2.3 
  b. Ran command with flatcar-update binary as such
  ```
  /usr/bin/flatcar-update -P flatcar/flatcar_production_update.gz -V 3815.2.3 -E flatcar/oem-gce.gz -A
  ```
4. **Error**: 
```
Forcing update...
2024/06/18 13:42:42 socat[9727] E write(6, 0x55892a72d000, 8192): Broken pipe
cat: write error: Broken pipe
```
I've also attached logs from the update-engine
<img width="1460" alt="Screenshot 2024-06-19 at 10 55 21 AM" src="https://github.com/flatcar/Flatcar/assets/7548567/d32cc4a1-0dda-481e-96b5-887a85108c55">

## Expected behavior
I expect it to run the update successfully like it does for VMware and Azure.

Successful run:
```
 /usr/bin/flatcar-update -P flatcar/flatcar_production_update.gz -V 3815.2.3 -E flatcar/oem-vmware.gz -A
Warning: found hardcoded GROUP=stable in /etc/flatcar/update.conf - make sure it fits the release channel you want to follow
Forcing update...
Setting SERVER=disabled in /etc/flatcar/update.conf
Done, please make sure to reboot either manually or through your reboot manager (check locksmithd/FLUO)
```

Is this an issue with oem-gce.gz in later flatcars?

**Comment by tormath1** [comment]
Hello @HarithaRamesh,

Before going further can you try again with the new release 3815.2.4 to see if you still have this behavior?

Looks like there is some timeout issue between socat and the update-engine.

**Comment by HarithaRamesh** [comment]
Ah, yes I tried again with the 3815.2.4 patch and that worked. Thank you!

**Comment by tormath1** [comment]
For what is worth, I tried to repro yesterday with ` /usr/bin/flatcar-update -P flatcar/flatcar_production_update.gz -V 3815.2.3 -E flatcar/oem-vmware.gz` and it worked fine.
It might be a transient issue. If it's ok with you, can you close this? Feel free to re-open if you are facing again this issue.

**Comment by HarithaRamesh** [comment]
Yes it was the GCE that was problematic, but the new patch works on all gce, vmware and azure, so I'm happy.
