### ISSUE TITLE
Release Flatcar Container Linux Alpha 4012.0.1 Beta 3975.1.1 Stable 3815.2.5 LTS 3510.3.5

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#1488]
The release of the following Flatcar Container Linux version is planning 02, July 2024.

- Alpha 4012.0.1
- Beta 3975.1.1
- Stable 3815.2.5
- LTS 3510.3.5

## 1. Preparation

Owner: @tormath1

- [x] A. Go/No-Go [hackmd doc](https://hackmd.io/team/flatcar) created from HackMD template for test tracking and release notes: https://hackmd.io/esv26YPbREaXYPmm0Jz8Fg?view
- [x] B. All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems.
- [x] C. Check that the kernel PR are merged for the channel(s) to be released.

## 2. Build

Owner: @tormath1

- [x] ~A. Branched off the `main` branch (only for new major).~
- [x] B. Tagged all the build branches.
- [x] C. Started the Jenkins builds, post the links into this issue as comment.

### i. The Go/No-Go Meeting

Owner: @sayanchowdhury 

- [x] A. Test status captured in the HackMD document.
- [x] B. All tests are Green.
- [x] C. Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None`.
- [x] D. QA: Checked the diff for image file list, packages, and image size in the `container/image_changes` job output.
- [x] E. Conduct Matrix Go/No Go meeting (inc. release notes review).

### ii. Artifacts goes public

Owner: @sayanchowdhury 

- [x] A. Created the Release Notes on the `scripts` repo for the respective tags on GitHub as GitHub Releases.
- [x] B. Ran the `container/release` Release job.
- [x] C. Images uploaded with `copy-to-origin.sh`.
- [x] D. Symlink to "current" updated with `set-symlink.sh`.
- [x] E. Website updated with `./update-flatcar-versions.sh` and PR merged.

### iii. Payload

Owner: @tormath1 

- [x] A. Update payload signed/uploaded.
- [x] B. Release package published in Nebraska (Prerequisite: 3.ii.E should marked done).

### iv. Cloud Marketplace & Cluster API

Owner:

- A. Azure (@sayanchowdhury)
    - [x] Offers updated and started publishing.
    - [x] Sent the offers to publish to Live.

- B. GCP (@t-lo)
    - [x] Offer deployment package uploaded to Google Bucket & submit for verification.
    - [x] Offer Publish

- C. Cluster API for new Stable
  - [ ] Azure: Manually run `./azure-sig.sh` to create New Shared Community Gallery Images
  - [ ] OpenStack: [documentation](https://gist.github.com/tormath1/acbae5c6cd12420bb8ea137e25655c99)

## 4. Announcements

Owner: @tormath1 

- [x] A. Sent announcement to Mailing Lists
- [x] B. Sent Tweet out to X (Twitter), and Toot out to Mastodon
- [x] C. Brief version announcement in slack (k8s slack #flatcar) and the Flatcar Matrix channel

**Comment by tormath1** [comment]
* alpha-4012.0.1: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/4232/cldsv/
* beta-39751.1: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/4233/cldsv/
* stable-3815.2.5: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/4234/cldsv/
* lts-3510.3.5: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/4235/cldsv/

**Comment by ericgraf** [comment]
@sayanchowdhury Looks like `3815.2.5` is not on `azure` similar to the last several times. Is there a plan to add it?

**Comment by tormath1** [comment]
@ericgraf we just released and submitted Flatcar releases to Azure for publishing. It usually takes a few hours / days to Azure to publish the changes.

**Comment by t-lo** [comment]
Submitted to GCP and started validation. ~Will check back later if it succeeded, otherwise publish tomorrow.~ Validation concluded, new release is now live on GCP.

**Comment by t-lo** [comment]
> @sayanchowdhury Looks like `3815.2.5` is not on `azure` similar to the last several times. Is there a plan to add it?

@ericgraf The Azure CoreVM offers `flatcar-container-linux-corevm` (which is arm64) and `flatcar-container-linux-corevm-amd64` have passed validation and are currently being published (==replicated across geo-regions). These offers should have the update available really soon.

The offers `flatcar-container-linux-free` and `flatcar-container-linux` are still undergoing Azure marketplace validation. We'll publish as soon as these have passed.

**Comment by sayanchowdhury** [comment]
The offer` flatcar-container-linux-free` passed the validation and has been published. The last `flatcar-container-linux` is getting published and should be soon available.
