### ISSUE TITLE
kubelet-wrapper not compatible with new hyperkube image from k8s 1.17

### ISSUE THREAD

**Issue by sfudeus** [flatcar/Flatcar#15]
In k8s 1.17, the hyperkube image was reworked and works slightly different than before. See https://github.com/kubernetes/kubernetes/pull/84662 and https://github.com/kubernetes/kubernetes/issues/81760. 

kubelet-wrapper in coreos calls the hyperkube image with `KUBELET_IMAGE_ARGS=${KUBELET_IMAGE_ARGS:---exec=/kubelet}`

This worked until 1.16, when hyperkube was a binary. 
With 1.17, hyperkube is a shell wrapper to call the correct binary (by argument). `/kubelet` is a symlink to that shell wrapper, but requiring an additional argument to select the right binary. Since `$0` is not considered, the whole symlinking does not make sense. 
When calling `kubelet`, the lookup resolves to /usr/local/bin/kubelet, which is the real binary and works. 

Of course this can be considered an upstream issue, looking at `$0` before would have done the trick. Nonetheless, setting `--exec=kubelet` or `--exec=/usr/local/bin/kubelet` works with 1.16 already. 

If I see that correctly in k/k master, they even got rid of the symlinks in /, so the intended way is to call the binaries in /usr/local/bin. Eventually, they want to get rid of the hyperkube image in general, favoring the specific docker images. Maybe the kubelet-wrapper should switch over to a kubelet image if possible.

**Comment by sfudeus** [comment]
The workaround for a user of course it to set 
`KUBELET_IMAGE_ARGS="--exec=/usr/local/bin/kubelet"`

**Comment by t-lo** [comment]
Hello Stephan,
Kubelet-wrapper depends on rkt, which is unmaintained. There are a number of other issues with kubelet-wrapper, causing other project to turn to alternatives (see e.g. https://github.com/poseidon/typhoon/commit/f1f4cd6fc02b0530cbcc8951ce1edb6e56bdca69 ). The number of projects using kubelet-wrapper appears to be low, too - with Typhoon moving away, Bootkube and Lokomotive seem to use it. There’s a [WIP branch of eksctl](https://github.com/weaveworks/eksctl/pull/1634), but the author, @alban, plans to move away from kubelet-wrapper, too.

Also, as you noted, updating to a new Kubernetes version requires changes in the way to call kubelet-wrapper. The solution you've described with --exec=/usr/local/bin/kubelet is also the one we use in Lokomotive (see [code](https://github.com/kinvolk/lokomotive-kubernetes/blob/25123442a162cd3eb482b4083e13f5de6b14bbc9/aws/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl#L104))

We are investigating the issue at hand with the intent to provide a fix. However, ultimately kubelet-wrapper is more of a legacy from CoreOS Container Linux, and given the problems and lack of active users, I would expect kubelet-wrapper to be dropped from Flatcar Container Linux in the long term. This would of course be announced separately.

**Comment by dharmab** [comment]
Note that [hyperkube is not longer officially supported by Kubernetes in 1.17](https://github.com/kubernetes/kubernetes/pull/85094).

Our team is moving away from hyperkube entirely towards the individual containers for each kubernetes process as a result.

**Comment by sfudeus** [comment]
@dharmab Not sure how exact the kubadm PR is, since the original plan was to move hyperkube out of tree, but now it still is in there, just with a shell wrapper and the dedicated go binaries. 
Do you by accident have a pointer for me where to find a kubelet image? I just found the control-plane ones ...

**Comment by der-eismann** [comment]
I think the new images are named according to their component, e.g. [gcr.io/google-containers/kube-apiserver-amd64](https://gcr.io/google-containers/kube-apiserver-amd64), but I didn't try them yet.

**Comment by sfudeus** [comment]
With the end of official hyperkube support (even out-of-tree) in k8s-1.19, this seems to be superfluous.

**Comment by pothos** [comment]
For the record, the binaries can be downloaded and run directly without Docker or rkt.
Here how to do it manually https://suraj.io/post/2021/01/kubeadm-flatcar/ but I would recommend to use Ignition remote references for that.

**Comment by sfudeus** [comment]
IMO the main issue with running kubelet natively on container linux is the fact that you might need additional binaries to run kubelet properly, e.g. for storage integration, which either need to be installed by native container linux means or could easily provided in the same image as the kubelet.
