### ISSUE TITLE
Enable kernel config CONFIG_IKHEADERS for Kernel >= 5.4

### ISSUE THREAD

**Issue by dongsupark** [flatcar/Flatcar#152]
Kernel 5.2 or newer has a kernel config [CONFIG_IKHEADERS](https://github.com/torvalds/linux/blob/435faf5c218a47fd6258187f62d9bb1009717896/init/Kconfig#L610-L617
). With the config enabled, it is possible to export kernel headers via `/sys/kernel/kheaders.tar.xz`. 
One of the use cases is [BCC tools](https://github.com/iovisor/bcc) that need to have access to kernel headers. With `CONFIG_IKHEADERS` enabled, BCC tools can be used without additional kernel headers in userspace.
For details, see https://github.com/kubernetes/minikube/issues/8556.

According to the commit message of [43d8ce9d65a5](https://github.com/torvalds/linux/commit/43d8ce9d65a54846d378545770991e65838981e0), the kernel config needs quite a small amount of additional kernel memory. So I suppose we can enable the option in beta, alpha (both 5.4) and edge (5.7).

/cc @alban

**Comment by iaguis** [comment]
Today I Learned. Cool!

**Comment by dongsupark** [comment]
https://github.com/flatcar-linux/coreos-overlay/pull/450

**Comment by dongsupark** [comment]
https://github.com/flatcar-linux/coreos-overlay/pull/450 was merged, so next releases will include the kernel config `CONFIG_IKHEADERS`.
