### ISSUE TITLE
Docker and containerd systemd units are being owned my UID 1000

### ISSUE THREAD

**Issue by snikhil1998** [flatcar/Flatcar#1525]
## Description

The systemd unit files `/usr/lib/systemd/system/docker.service`, `/usr/lib/systemd/system/docker.socket`, and `/usr/lib/systemd/system/containerd.service`, are being owned by UID 1000.

## Impact

Security checks are failing when testing our product.

## Environment and steps to reproduce

1. **Set-up**: Flatcar
2. **Task**: Standard testing

## Expected behavior

The systemd unit files `/usr/lib/systemd/system/docker.service`, `/usr/lib/systemd/system/docker.socket`, and `/usr/lib/systemd/system/containerd.service`, should be owned by `root` user (UID 0).

**Comment by jepio** [comment]
Thanks for bringing this to our attention, i've opened a PR and it'll be backported to all channels once merged.

**Comment by dongsupark** [comment]
It is already fixed in Stable 3975.2.1, Beta 4054.1.0, Alpha 4081.0.0.
Thanks.
