### ISSUE TITLE
Modify default settings for Flatcar ova

### ISSUE THREAD

**Issue by Winnie81** [flatcar/Flatcar#154]
**Current situation**
After deploy Flatcar ova in ESXi, hardware version of the vm is 11 and guest OS version is "Other 2.6x Linux64 (64 bit)"

**Ideal future situation**
Set minimum version of ESXi to be 6.5(hardware version 13).
Change GOS selection from “Other 2.6x Linux64 (64 bit)” to “Other 3.x or later Linux (64 bit)”

After those changes, some newer features will be available by default and  “Other 3.x or later Linux (64 bit)” matches Flatcar better.

**Comment by pothos** [comment]
I created a PR in https://github.com/flatcar-linux/scripts/pull/78
Is the `OperatingSystemSection ovf:id="100"` setting still correct then or does this also change? I tried to find a list of values but my search wasn't successful.

**Comment by pothos** [comment]
Thanks for reporting.
It's merged and will be part of all next releases.
