### ISSUE TITLE
[RFE] - Azure / KVP kernel daemon: OS data is not submitted to cloud control plane

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#1540]
## Description

We have been made aware by Azure folks that the HyperV KVP daemon does not reliably report the OS version to the Azure control plane. The respective code is here https://github.com/torvalds/linux/blob/master/tools/hv/hv_kvp_daemon.c#L428 and it appears to simply read `/etc/os-release` - which we ship.

## Impact

Users on Azure have a harder time debugging instance issues as Azure support is unable to get sufficient metadata from instances (e.g. to pull in OS / Flatcar support experts).

## Environment and steps to reproduce

Unfortunately the issue can only be reproduced with access to Azure internal telemetry. Azure will monitor this issue and report back timely.

From our side, deploy Flatcar on Azure.

## Expected behavior

OS metadata like name and version are reported to Azure.

## Additional information

If we don't ship the HyperV KVP daemon then we should turn this bug report into a feature request. Might be a low hanging fruit to add the kmod to the Azure OEM sysext.

**Comment by ader1990** [comment]
Hello, from the upstream Gentoo documentation, there is no such package (yet) in the Gentoo repository: https://wiki.gentoo.org/wiki/Hyper-V#Linux_guest_support

There are two options here: add the code (`make install` + services definitions) in the Azure OEM sysext or (the better way), define a new overlay package and use it, then upstream it to Gentoo.

Thanks.

**Comment by t-lo** [comment]
Good points! I've converted this issue to a feature request.

**Comment by t-lo** [comment]
Implemented in flatcar/scripts#2309; cherry-picked to all maintenance branches.
