### ISSUE TITLE
Unable to use static IP address before Ignition on VMWare

### ISSUE THREAD

**Issue by fwmsn** [flatcar/Flatcar#160]
**Description**
We are unable to use a static IP before Ignition following https://docs.flatcar-linux.org/ignition/network-configuration/#using-static-ip-addresses-with-ignition

**Impact**
Every provisioned Flatcar VM gets two leases from DHCP and we need them to get only one lease

**Expected behavior**
We create a template using an Ignition with the following grub.cfg
```
set linux_append="$linux_append ip=IP:::NETMASK::ens192:none"
set oem_id="vmware"
```
Once the template is created with that Ignition applied, we use that template to create Flatcar VMs that don't run DHCP before Ignition, and thus they only get one lease assigned to them.

**Notes**
We have tried many combinations of `ip=<ip>::<gateway>:<netmask>:<hostname>:<iface>:none[:<dns1>[:<dns2>]]`
with/without `<gateway>`,with/without `<hostname>`, with/without `<iface>`, with/without `<dns1>` and none of them have worked. 
The server always runs DHCP before Ignition and gets a lease

**Comment by pothos** [comment]
Hi,
thanks for reporting, this should be fixed in the new Beta release, can you please give it a try? https://www.flatcar-linux.org/releases/#release-2513.2.0

**Comment by fwmsn** [comment]
Hi,
I ran some tests and it worked like a charm!
Thank you so much for all your help.
I love Flatcar!
