### ISSUE TITLE
Add Pressure Stall Information into Kernel 

### ISSUE THREAD

**Issue by rikatz** [flatcar/Flatcar#162]
**Current situation**
Current Kernel version supports [PSI](https://www.kernel.org/doc/html/latest/accounting/psi.html), which might help system administrators to detect bottleneck in cpu, memory and io in a easy way.

This is just a ``CONFIG_PSI=y`` in the Kernel configuration, and can also be used by cgroups2

**Impact**
Make the bottleneck and latency detection easier.

Kernel will get a little bigger (new feature), and a new /proc/pressure directory will be created.

**Ideal future situation**
PSI Enabled by default

**Implementation options**
Change the kernel config to contain ``CONFIG_PSI=y``

**Additional information**

PTAL https://facebookmicrosites.github.io/psi/docs/overview

Thank you!!

**Comment by dongsupark** [comment]
Yeah, I remember that Johannes Weiner gave a talk about PSI last year at All Systems Go.
I think it is a well-designed feature, used by a fair amount of userspace tools.
:+1:

**Comment by dongsupark** [comment]
Filed a PR https://github.com/flatcar-linux/coreos-overlay/pull/638.

**Comment by rikatz** [comment]
Thank you!!
