### ISSUE TITLE
CNCF SIG-Runtime discussion/presentation(?)

### ISSUE THREAD

**Issue by raravena80** [flatcar/Flatcar#163]
**Description**

Hello Flatcar team,

I'm one of the co-chairs of the CNCF SIG-Runtime, we believe your project is very relevant to the cloud-native ecosystem and we think it would be great for you to present/discuss it at one of our meetings. Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://github.com/cncf/sig-runtime) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by margamanterola** [comment]
Hi!

We're always happy to discuss Flatcar with interested parties :)

What kind of presentation / discussion are you looking for exactly?

Thanks for reaching out!

**Comment by raravena80** [comment]
Hi @marga-kinvolk,

Thanks for replying! For example, a general overview of the project, its architecture, how it compares to other projects, where it fits into the cloud native ecosystem, etc.

Let me know if that works.

Thx!

**Comment by margamanterola** [comment]
Sure, yes. We can do that. We could be there for the September 3rd meeting.  A few more questions:
* How long a presentation should this be?
* Would you want us to present with slides, or just have a conversation?
* How many people from the Flatcar team would you want to have there?

**Comment by raravena80** [comment]
* How about 30 mins including questions? There might be another project looking at present that day too. 
* Up to you. It could be showing documentation too, but probably best to share something online.
* Also, up to you, the more the merrier 😄

**Comment by raravena80** [comment]
@marga-kinvolk just checking are we on-schedule for the upcoming meeting? Thanks!

**Comment by margamanterola** [comment]
Sure, I'll be there tomorrow (and maybe bring along some other colleague).

**Comment by margamanterola** [comment]
Closing as this has happened now.
