### ISSUE TITLE
qedf kernel module missing for iscsi

### ISSUE THREAD

**Issue by mikekuzak** [flatcar/Flatcar#165]
Flatcar Version 2512.2.1

We are trying to install Flatcar on our new kit. We are not able to see our storage through the  host bus adapter because the the HBA kernel module is absent. This does work with redhat. 

The old kit was working with Flatcar because it was using qla2xxx

**Comment by mikekuzak** [comment]
![image](https://user-images.githubusercontent.com/18675587/90251763-39f24380-de36-11ea-8b90-f82a4fca35d8.png)
This is with Red Hat

**Comment by t-lo** [comment]
Thank you for your request and please pardon the inconvenience while bringing up your new hardware with Flatcar Container Linux. We'll look into adding the kernel module.

**Comment by t-lo** [comment]
Modules [are included in Apha-2605](https://www.flatcar-linux.org/releases/#release-2605.0.0) (released last Thursday) and will undergo the regular stabilisation process.

I'll close this issue, please test with Alpha-2605 and re-open if you encounter any issues.
