### ISSUE TITLE
AWS C5A support

### ISSUE THREAD

**Issue by bryanlatten** [flatcar/Flatcar#166]
Hi Flatcar folks,
Looking to leverage Flatcar on the somewhat-new AWS c5a machines, which are AMD-based. Are these officially supported?

From the product page: 
https://aws.amazon.com/ec2/instance-types/

- 2nd generation AMD EPYC 7002 series processors running at frequencies up to 3.3 GHz
- Elastic Network Adapter (ENA) provides C5a instances with up to 20 Gbps of network bandwdith and up to 9.5 Gbps of dedicated bandwidth to Amazon EBS
- Powered by the AWS Nitro System, a combination of dedicated hardware and lightweight hypervisor
- With C5ad instances, local NVMe-based SSDs are physically connected to the host server and provide block-level storage that is coupled to the lifetime of the C5a instance

**Comment by vbatts** [comment]
Hi @bryanlatten 
These machines haven't gotten a full validation yet, but also have not had any issues reported yet (here or otherwise).
Nothing jumps out that seem like an issue.

I'll slate this for a review, and would love to hear your early experiences with this machine type.

**Comment by bryanlatten** [comment]
Thanks for the fast response @vbatts - I'll keep an eye on this ticket.

**Comment by vbatts** [comment]
looks like the `c5a.large` went through out test suite as a SUCCESS, while the `c5ad.large` reported a number of failed tests that do not seem isolated to particular components. We're investigating this further.

Update: switched the type names. thanks Kai for pointing out my error!

**Comment by pothos** [comment]
@vbatts the machine names are swapped

**Comment by pothos** [comment]
Closing as we don't have a failure report here. In general we can extend the number of instance types we run our release tests on. We did this for Equinix Metal by running a simple test on all recent instance types, could do so for AWS and other clouds, too.
Edit: Here is the open issue for that: https://github.com/flatcar-linux/Flatcar/issues/553
