### ISSUE TITLE
Kernel: Enable metacopy and redirect_dir in overlayfs

### ISSUE THREAD

**Issue by dongsupark** [flatcar/Flatcar#170]
**Current situation**
At the moment, Kernel module `overlay` enables its features, neither `metacopy` nor `redirect_dir`, as it is given so by default. According to the overlayfs developer [Amir Goldstein](https://linuxplumbersconf.org/event/7/contributions/639/attachments/501/969/Overlayfs-containers-lpc-2020.pdf) at LPC 2020, distros and container runtimes should enable both features for overlayfs.

We should do so, and go through the ordinary CI to see if there is any regression.

Kernel configs:

* metacopy: `CONFIG_OVERLAY_FS_METACOPY`
* redirect_dir: `CONFIG_OVERLAY_FS_REDIRECT_DIR`

See also https://github.com/amir73il/overlayfs/wiki .

**Comment by goochjj** [comment]
+1

**Comment by dongsupark** [comment]
Filed PR https://github.com/kinvolk/coreos-overlay/pull/691
