### ISSUE TITLE
docker service not starting

### ISSUE THREAD

**Issue by xeor** [flatcar/Flatcar#175]
**Description**

containerd/docker service not always starting after flatcar-upgrade

**Impact**

All nodes upgraded itself, but all of them came back in NotReady state, essentially killing the cluster.

**Environment and steps to reproduce**

1. **Set-up**: flatcar running rke
2. **Action(s)**: waiting for nodes to upgrade themself.
3. **Error**: docker-service and containerd service not running.
4. **fix**: Running `docker ps` on the node started the service automatic.
5. **observations**: docker.service is set to disabled. So this might be expected?

**Expected behavior**
flatcar would be able to do automatic upgrades without ending up with all workers in NotReady state

**Additional information**
I'm not sure if the issue here is that the docker service is not enabled, or if there are something else. Running docker commands starts everything up and the node will be `Ready`. This is probably some torcx magic, but it seams not working as it should.

**Comment by pothos** [comment]
Hello,
by default the Docker service is socket-activated but you can change it to run Docker directly after boot:
https://docs.flatcar-linux.org/os/getting-started-with-docker/#permanently-running-a-container

**Comment by xeor** [comment]
Thanks for the info, that was very helpful :) Maybe info about this should be a warning-label in the docs? I felt like I read everything, however, I did miss this crucial little part..
