### ISSUE TITLE
/dev/null permissions are wrong

### ISSUE THREAD

**Issue by dwagelaar** [flatcar/Flatcar#176]
**Description**

Since 20-Aug-2020, the access rights for /dev/null are set to crw-r--r-- instead of crw-rw-rw- every few hours. This happens on two Flatcar Container Linux stable releases:

- 2345.3.1
- 2512.3.0

**Impact**

Most shell scripts break when unable to write to /dev/null.

**Environment and steps to reproduce**

1. **Set-up**: VMWare ESX with six Flatcar Container Linux clusters, all of which are affected.
2. **Task**: The Flatcar Container Linux clusters all run a Docker Swarm.
3. **Action(s)**: nothing
4. **Error**: various failures due to /dev/null not being writable by non-root users

**Expected behavior**
/dev/null should be writable by everyone.

**Additional information**
Previously, we had a custom udev rule installed to work around https://github.com/coreos/bugs/issues/2437
This udev rule is no longer required, and has been removed. The /dev/null issue remains, however.
Reboots briefly fix the problem, which then returns after a number of hours.

**Comment by pothos** [comment]
Hello,

thank's for reaching out. I checked some of the servers we have running and didn't see this issue. Would be good if you can trace which process changes the permissions. I'll try to come up with instructions for doing it.

**Comment by dwagelaar** [comment]
We're doing this right now: https://access.redhat.com/solutions/1240813
When the issue hits again, I hope to know more.

**Comment by pothos** [comment]
I can't access the contents of the link you posted, but I would try it with this here:
```
docker run --privileged -v /usr/lib/modules:/usr/lib/modules -v /sys/kernel/debug:/sys/kernel/debug -v /sys/fs/bpf:/sys/fs/bpf --rm -it quay.io/iovisor/bpftrace bpftrace -e 'tracepoint:syscalls:sys_enter_fchmodat { if (str(args->filename)=="/dev/null" || str(args->filename)=="null" || str(args->filename)=="./null") {printf("%d %s %s\n", pid, comm, str(args->filename)); } }'
```
Yet, it will only print the process name and PID, not the parents.

Edit: It's more complicated:
You would also need to trace `sys_enter_chmod` and `sys_enter_fchmod`… but for `fchmod` it's not easy to find the path name.
Also @alban pointed out that `mknodat(..., mode, ...)` may have caused this.

**Comment by pothos** [comment]
You can try to watch for the modification with
```
docker run --privileged -v /dev:/dev --rm -it fedora sh -c 'dnf install -y inotify-tools && inotifywait -r -m -e attrib /dev/null'
```
and when a line is printed, dump the contents of a long running tracer, for example, some bpftrace commands like in the comment above or simply
```
 docker run --privileged --pid host --rm -it fedora sh -c 'dnf install -y perf && perf trace -a --expr '*chmod*,*mknod*''
```

**Comment by dwagelaar** [comment]
We eventually found it with a kernel audit rule:

`-w /dev/null -p a -k null-watch`

```
$ sudo journalctl -xef | grep null-watch
Sep 02 12:01:05 *** kernel: audit: type=1300 audit(1599040865.584:9617): arch=c000003e syscall=90 success=yes exit=0 a0=7fde40e35f38 a1=1a4 a2=7fde418a4c58 a3=0 items=1 ppid=41209 pid=41210 auid=500 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=20 comm="pypy" exe="/home/core/pypy/bin/pypy" subj=system_u:system_r:kernel_t:s0 key="null-watch"
Sep 02 12:01:05 *** audit[41210]: SYSCALL arch=c000003e syscall=90 success=yes exit=0 a0=7fde40e35f38 a1=1a4 a2=7fde418a4c58 a3=0 items=1 ppid=41209 pid=41210 auid=500 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=20 comm="pypy" exe="/home/core/pypy/bin/pypy" subj=system_u:system_r:kernel_t:s0 key="null-watch"
Sep 02 12:02:50 *** audit: EXECVE argc=3 a0="grep" a1="--colour=auto" a2="null-watch"
^C
$ ls -l /dev/null
crw-r--r--. 1 root root 1, 3 Sep  1 17:07 /dev/null
```

The process was /home/core/pypy/bin/pypy, which lead to an ansible playbook that was run every 24 hours.

That means the problem was not caused by Flatcar Container Linux. Thank you for thinking along with us!
