### ISSUE TITLE
New Package Request: [iPerf 3]

### ISSUE THREAD

**Issue by EthraZa** [flatcar/Flatcar#177]
iperf3: A TCP, UDP, and SCTP network bandwidth measurement tool

[ iperf is a tool for active measurements of the maximum achievable bandwidth on IP networks. It supports tuning of various parameters related to timing, protocols, and buffers. For each test it reports the measured throughput / bitrate, loss, and other parameters. ]

- Package upstream repo: https://github.com/esnet/iperf
- Gentoo ebuild: https://packages.gentoo.org/packages/net-misc/iperf

**Impact of adding this package to the Flatcar OS image**
- [X] This package meets the requirements of Flatcar Container Linux’ new package guidelines: https://github.com/flatcar-linux/Flatcar/blob/master/adding-new-packages.md

- The package improves on the following core values:
  - [X] Secure by default
  - [X] Always up to date
  - [X] Improve container experience
  - [X] Operate at scale / automation / telemetry

The package will increase the OS image by: 0.47 MBytes.
28000 iperf3
447696 libiperf.so.0

The package will potentially increase Flatcar’s attack surface:
- The service will be running only when necessary for measurement

**Benefits of adding this package to the Flatcar OS image**
- On Flatcar, we already have tools like ifconfig, ip and ethtool to be able to know the IPs, routes and auto-detected connection speed. Iperf would give us the ability to measure the real net speed on each device, direct in the host, without the docker in the middle with any limitations that may apply and difficult the net speed measument.

**Comment by pothos** [comment]
Hello,

I think iperf3 is a good candidate to be run in a container yet within the host network namespace to achieve your goal of running directly on the host:

```
docker run --rm -it --net host quay.io/kinvolk/iperf3 iperf3 --help
```

**Comment by EthraZa** [comment]
From Kirk (Flatcar):
```
xxx@kirk ~ $ docker run --rm -it --net host quay.io/kinvolk/iperf3 iperf3 -c spock
iperf3: error - unable to connect to server: Connection refused

xxx@kirk ~ $ docker run --rm -it --net host quay.io/kinvolk/iperf3 iperf3 -s
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
```

From Spock (still Ubuntu):
```
xxx@spock ~ $ iperf3 -c kirk
Connecting to host kirk, port 5201
[  4] local 192.168.0.113 port 34070 connected to 192.168.0.172 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   115 MBytes   961 Mbits/sec    0    542 KBytes
...
```
So I was able to test the Kirk's net speed as iperf server, but when all of my server become Flatcar, If I can't connect as iperf client, them I will not be able to test it again.

I tryed to just wget iperf3 into Kirk but I don't know how to tell it where to look for libiperf.so.0.

```
xxx@kirk ~ $ sudo wget -O /opt/bin/iperf3 https://iperf.fr/download/ubuntu/iperf3_3.1.3 && sudo chmod +x /opt/bin/iperf3 && sudo wget -O /opt/lib/libiperf.so.0 https://iperf.fr/download/ubuntu/libiperf.so.0_3.1.3 && sudo ldconfig -l /opt/lib/libiperf.so.0

xxx@kirk ~ $ iperf3
iperf3: error while loading shared libraries: libiperf.so.0: cannot open shared object file: No such file or directory
```
That's are the problens I'm having with iperf3 from Docker and I just thought that add 0.4MB to Flatcar would not be that much and would let things simple to me and probably others.

**Comment by pothos** [comment]
Why does it say `Connection refused`? Can you connect with `ncat` to the port?

**Comment by EthraZa** [comment]
Yes, ncat does indeed connect from kirk to spock, I can see it connecting on spock's iperf server. :-/

`xxx@kirk ~ $ ncat spock 5001
`

**Comment by pothos** [comment]
You can also try the toolbox if something is wrong with Docker containers.
https://docs.flatcar-linux.org/os/install-debugging-tools/
This gives you Fedora in a systemd-nspawn chroot where you can install iperf.

**Comment by EthraZa** [comment]
I didn't know about toolbox, I loved it.

I didn't find how to use .toolboxrc to use a local custom image, it seens to like just images it can download from some registry. But I let it download it's default fedora image, installed iperf3 and it just worked as client and server.

Thank you.

**Comment by pothos** [comment]
Happy to help, but I still wonder what the problem was with the container.

**Comment by EthraZa** [comment]
The best info so... after I successfully run iperf inside toolbox, I was showing off to a colleague the error iperf was given within docker and it just worked. After this one, I gave up for today!

**Comment by pothos** [comment]
Ok, thanks for the quick answers :)
