### ISSUE TITLE
[RFC] additional Reboot strategies needed?

### ISSUE THREAD

**Issue by vbatts** [flatcar/Flatcar#178]
for component: https://github.com/flatcar-linux/locksmith

**Current situation**
Looking at https://docs.flatcar-linux.org/os/update-strategies/
Most folks rely on `reboot`, because it's simplest and the default.
Next up, folks may set it to `off`, in order to reboot at their own will.
And then we have `etcd-lock` which allows adequate sophistication, but I venture that not many folks use this.

separately we have https://github.com/kinvolk/flatcar-linux-update-operator 

**Impact**
"best-practice" may appear as an exercise left up to the reader.

Hearing that some folks are rolling out their reboot orchestration is done with Ansible seems like a stretch, but doing what is familiar given the options.

**Ideal future situation**
intuitive, managable, low downtime, rollout of reboots

**Implementation options**

This might could even be a user document about different use-cases.

**Comment by pothos** [comment]
I've reworked the docs in this regard. In the near future we will also have fleetlock support which offers new ways like having a public service that we host and allows clients to do reboot coordination using a secret group name.
