### ISSUE TITLE
Question about coreos branding in file names paths

### ISSUE THREAD

**Issue by dharmab** [flatcar/Flatcar#18]
https://docs.flatcar-linux.org/os/migrate-from-container-linux doesn't mention the following branded files:

- `coreos-metadata.service`

- `/etc/coreos/update.conf`

- `/run/metadata/coreos`

Will these paths remain for backwards compatibility,  or will they be rebranded?

**Comment by pothos** [comment]
Hello,
thanks for asking.
`coreos-metadata.service` still has the same name but the other two were renamed. For `/etc/coreos/` there is a symlink so you should be fine but for `/run/metadata/coreos` the symlink was missing up to now and will be part of the next release.

**Comment by pothos** [comment]
The symlink was part of the stable release 2303.4.0.
