### ISSUE TITLE
RKT EndOfLive / Archiving - Any Plans on dropping and/or replacing it ?

### ISSUE THREAD

**Issue by bugre** [flatcar/Flatcar#180]
**Description**
Hi, 
Not sure this is the correct place, but as it's not a bug, i think it's better here..

Now a few months passed since announcement of RKT project EndOfLive / Archiving (https://github.com/rkt/rkt/issues/4024), would like to know if there is any plan to drop rkt from the FlatCar distro and/or replace it with the like of podman/libpod?

Thanks for your work on keeping 'coreOS' CL alive.

**Comment by pothos** [comment]
Hello,
it's still in use but limited to being a more advanced chroot and not to confine something. It will be replaced but that's not yet prepared. I guess the replacement depends on the context, sometimes Docker may do it, sometimes systemd-nspawn, and Podman also has many advantages. We will announce the deprecation when ready.

**Comment by bugre** [comment]
Halo @pothos , 

that means that for the short/medium term the stable version will have rkt included, correct?

Danke u. wünsche dir ein schönes Wochenende.
-wm

**Comment by pothos** [comment]
Yes, it won't disappear over night and we will make sure to announce the deprecation plan in the mailing list and in the release notes. Maybe even in the motd at the login prompt or when a rkt-using script is invoked like etcd/kublet/flannel-wrapper… not sure yet.
Thanks

**Comment by dongsupark** [comment]
Alpha 2857.0.0 removed rkt.
Please see https://groups.google.com/g/flatcar-linux-user/c/MeinndLqJO4 for details.
