### ISSUE TITLE
UEFI Boot Support for Bare Metal Installs

### ISSUE THREAD

**Issue by carpenike** [flatcar/Flatcar#187]
**Current situation**
Existing documentation indicates that UEFI boot support is not available and that the original CoreOS team did not have sufficient time to implement it prior to the acquisition by RedHat. 

**Impact**
The lack of UEFI boot support precludes the ability to boot from PXE with non-embedded NICs (a la 10GB PCIe). Also prevents usage of UEFI Secure Boot.

**Ideal future situation**
Enable support for UEFI boot on bare metal systems.

**Implementation options**
[ Optional: please provide one or more options for implementing the feature requested ]

**Additional information**
Appreciate you guys continuing on with the CoreOS philosophy! I'm looking to move my K8s installs over to flatcar from Ubuntu via the Typhoon tooling.

**Comment by carpenike** [comment]
One other thing I just discovered, newer, particularly embedded systems are being released without SCM/legacy BIOS support:

https://forum.odroid.com/viewtopic.php?t=33097

 https://www.anandtech.com/show/12068/intel-to-remove-bios-support-from-uefi-by-2020

Intel NUCs are having their legacy boot option removed by firmware update: https://community.intel.com/t5/Intel-NUCs/legacy-boot/td-p/585096?profile.language=en

**Comment by carpenike** [comment]
And it would appear that fedora-coreos does support UEFI: https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/

**Comment by margamanterola** [comment]
Hey Ryan,

We actually test UEFI on a few platforms and it works fine. It's possible that this is just a documentation issue and we need to update our docs to say that we support UEFI. Or maybe there's some specific use case that needs to get UEFI support and doesn't have it yet.

Did you encounter any specific issues trying to use UEFI? If yes, please detail your use case and the problems you encountered. If you assumed it wouldn't work because of the docs, then please try it out and let us know. Thanks!

**Comment by carpenike** [comment]
@marga-kinvolk, 

Great news!

I've been trying to get it to work with systems deployed via PXE/iPXE & Matchbox. System installs fine, but does not register as an available boot option within the UEFI firmware. Is there a particular switch that needs to be passed to the system for the UEFI install or should it auto-detect based on boot type?

**Comment by carpenike** [comment]
Here is the resultant partition table on the disk:

```
Disk /dev/nvme0n1: 223.6 GiB, 240057409536 bytes, 468862128 sectors
Disk model: KINGSTON SA1000M8240G
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 00000000-0000-0000-0000-000000000001

Device           Start     End Sectors  Size Type
/dev/nvme0n1p1    4096  266239  262144  128M EFI System
/dev/nvme0n1p2  266240  270335    4096    2M BIOS boot
/dev/nvme0n1p3  270336 2367487 2097152    1G unknown
/dev/nvme0n1p4 2367488 4464639 2097152    1G unknown
/dev/nvme0n1p6 4464640 4726783  262144  128M Linux filesystem
/dev/nvme0n1p7 4726784 4857855  131072   64M unknown
/dev/nvme0n1p9 4857856 9285631 4427776  2.1G unknown
```

**Comment by margamanterola** [comment]
Can you give more details on how you're doing the installation? What command are you using to install? Which image are you installing? 

Also, which channel are you using?  If you've tried stable, please also try the beta channel in case your issue is fixed with the upcoming update (the new version that's about to go to stable includes a ton of changes).

**Comment by carpenike** [comment]
Yup. Here's the config files that the system installs with. I'm using Beta channel, 2605.3.0.

profile:
```
{
        "id": "k8s-cached-flatcar-linux-install-h2-0",
        "ignition_id": "k8s-cached-flatcar-linux-install-h2-0.yaml.tmpl",
        "boot": {
                "kernel": "/assets/flatcar/2605.3.0/flatcar_production_pxe.vmlinuz",
                "initrd": [
                        "/assets/flatcar/2605.3.0/flatcar_production_pxe_image.cpio.gz"
                ],
                "args": [
                        "initrd=flatcar_production_pxe_image.cpio.gz",
                        "flatcar.config.url=http://matchbox.TLD:8070/ignition?uuid=${uuid}\u0026mac=${mac:hexhyp}",
                        "flatcar.first_boot=yes",
                        "console=tty0",
                        "console=ttyS0"
                ]
        }
}
```

ignition profile:

```
---
systemd:
  units:
    - name: installer.service
      enabled: true
      contents: |
        [Unit]
        Requires=network-online.target
        After=network-online.target
        [Service]
        Type=simple
        ExecStart=/opt/installer
        [Install]
        WantedBy=multi-user.target
    # Avoid using the standard SSH port so terraform apply cannot SSH until
    # post-install. But admins may SSH to debug disk install problems.
    # After install, sshd will use port 22 and users/terraform can connect.
    - name: sshd.socket
      dropins:
        - name: 10-sshd-port.conf
          contents: |
            [Socket]
            ListenStream=
            ListenStream=2222
storage:
  files:
    - path: /opt/installer
      filesystem: root
      mode: 0500
      contents:
        inline: |
          #!/bin/bash -ex
          curl --retry 10 "http://matchbox.TLD:8070/ignition?{{.request.raw_query}}&os=installed" -o ignition.json
          flatcar-install \
            -d /dev/nvme0n1 \
            -C beta \
            -V 2605.3.0 \
            -b http://matchbox.TLD:8070/assets/flatcar \
            -i ignition.json
          udevadm settle
          systemctl reboot
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDgWHeNLYHvFUf2XJnjgQ0jA+ZfcqY3JTQcEApTXl7lf1TagWvckoy57uA2Uifk5xct9G/IjoASWYy702yB8m6AWvYhdKBQ4wSnJRi587cuWYVUYLYns2qbEqejLIrKwo6SzSD3m3sg2xb0kpJQr1lA14WKhCnHQ7FSCmuNr3APbWeD7EvPfmwYcddVUVY6zbyjA8C04esSOWiekJTNKicKtolycrJZVgSCKaG68OeK7YioPiGCi7mbGteLSmoAsIrK/q18IUiY0aLgfuUINdO0FpfWcVkxjzdbPY1xWIcRDg4Tb4rfZjoTycVpnj8pwmpvfmspRcTpx7LgyLO8cwl"
```

**Comment by carpenike** [comment]
Could it be an issue with the partition table being placed on the drive? Getting these errors in the console before it reboots:

![IMG_2131](https://user-images.githubusercontent.com/1302442/93907336-3373a900-fccb-11ea-8ac0-652771e23504.jpeg)

**Comment by margamanterola** [comment]
You mentioned not seeing the image from the UEFI firmware... Do you see a GRUB menu when it reboots? I think our UEFI installations all go through GRUB. I don't think we've tested booting directly from the firmware.

**Comment by carpenike** [comment]
Hey @marga-kinvolk -- Doesn't get to a grub screen. I get a black screen post firmware.

**Comment by pysen** [comment]
I also ran into a similar problem with UEFI booting a bare-metal install of Flatcar-Linux (2705.1.0 & 2723.0.0, earlier release install fail completely) on Odroid-H2+ hardware. The installation was successful using PXE but once it had finished and tried to boot the installed Flatcar-Linux from the filesystem it fails with "Failed to Set MokListRT: Not Found".

I mounted the /boot partition from a livedisk and the efibootmgr entry regarding boot disk UUID and bootx64.efi file location looks to be correct.

**Comment by carpenike** [comment]
@pysen my device was also an h2

**Comment by pysen** [comment]
I was able to successfully boot my Odroid-H2+ with the latest 1.22 firmware and Flatcar-Linux Alpha 2723.0.0.

The issue with the "Failed to Set MokListRT: Not Found" is no longer present like it was on the previous 1.12 firmware that the board was delivered with. 
I was able to get rid of the MokListRT error on firmware 1.12 by adding a MOK following the Debian wiki instructions at https://wiki.debian.org/SecureBoot#MOK_-_Machine_Owner_Key but the boot process stalled at a black screen with a single underscore "_" symbol and not proceed to the grub menu.

The bios update files can be found on the Odroid [wiki](https://wiki.odroid.com/odroid-h2/hardware/h2_bios_update#bios_release) for anyone having this issue. 

@marga-kinvolk I believe this issue can be closed. 

EDIT: From my testing this is a hardware issue as the same exact PXE configuration & installation worked well in the QEMU based virtual machine with EFI enabled for me.

**Comment by jepio** [comment]
@carpenike This may have been a firmware issue - UEFI boot is supported on all platforms. What doesn't work is secure boot, unless you enroll our special keys in your firmware but there no guides to do so. We'll track secure boot here: #501. Closing, please reopen if needed.

**Comment by mister2d** [comment]
> @carpenike This may have been a firmware issue - UEFI boot is supported on all platforms. What doesn't work is secure boot, unless you enroll our special keys in your firmware but there no guides to do so. 

@jepio
I believe this issue should be re-opened. UEFI boot does not work when using the `flatcar_production_iso_image.iso` image on UEFI bare metal. In my case, a Dell PowerEdge R450 with Secure Boot disabled running Flatcar LTS 3033.3.0. Flatcar will only boot with the iso when I change the mode to standard BIOS.

Please don't confuse what works (PXE/iPXE bootstrapping) with installing a standalone Flatcar server and no supporting infrastructure. In some of my environments I intended to have the very first server run Flatcar. But I have to snowflake the box and run BIOS instead of UEFI.

**Comment by mister2d** [comment]
> I believe this issue should be re-opened. UEFI boot does not work when using the flatcar_production_iso_image.iso image on UEFI bare metal.

Just following up to my post because I witnessed some odd behavior. While the Flatcar `.iso` boots only with standard BIOS to perform a `flatcar-install`, I had to change BIOS back to UEFI in order to boot into installed instance.

**Comment by pysen** [comment]
This issue looks to be firmware related as it happened again on Odroid-h3+, issue opened on https://forum.odroid.com/viewtopic.php?f=173&t=46878&p=371199#p371199

**Comment by saulshanabrook** [comment]
I am also getting the `Failed to set MokListRT: Not Found` error trying to boot flatcar (installed the alpha) on my [Minisforum NPB7](https://store.minisforum.com/products/minisforum-nab6). If I enable secure boot, I get a different error (https://github.com/flatcar/Flatcar/issues/501#issuecomment-1583470286).

@pysen and @carpenike did you manage to get through this? Would you recommend looking for a firmware update? or manually adding a MOK file?

**Comment by jepio** [comment]
`Failed to set MokListRT: Not Found` message may appear during boot but this should not be a blocker. If you could create a separate issue for any boot issue you are seeing @saulshanabrook , that would be great.
