### ISSUE TITLE
How to get etcd / locksmith to work?

### ISSUE THREAD

**Issue by EthraZa** [flatcar/Flatcar#188]
I have Flatcar installed on bare metal. The problem is that it is booting in the midle of the day when we got an update. It happened 2 times already since I instaled Flatcar as the host.
I tryed to get it to boot at Sundays but it's ignoring it and, for the life of me, I can't find how to setup it in the docs.

My boss is about to force me to install Ubuntu as the host because, in his words - "I can't control when the Flatcar boots, it looks like Windows".

So, please, point me in the right direction, or to the right docs, if they exist. 
Thank you in advance.

I guess I got most of it from this docs: 
- https://docs.flatcar-linux.org/os/provisioning/
- https://github.com/coreos/container-linux-config-transpiler/blob/master/doc/examples.md

Where I got:
server.yml:
~~~
...

etcd:
    name:                        "{HOSTNAME}"
    advertise_client_urls:       "http://{PRIVATE_IPV4}:2379"
    initial_advertise_peer_urls: "http://{PRIVATE_IPV4}:2380"
    listen_client_urls:          "http://0.0.0.0:2379"
    listen_peer_urls:            "http://{PRIVATE_IPV4}:2380"
    initial_cluster:             "{HOSTNAME}=http://{PRIVATE_IPV4}:2380"
update:
    group: "stable"
locksmith:
    reboot_strategy: "etcd-lock"
    window_start:    "Sun 4:00"
    window_length:   "3h"
~~~

$ locksmithctl status
`Error initializing etcd client: client: etcd cluster is unavailable or misconfigured`

$ etcdctl cluster-health
```
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 127.0.0.1:2379: connect: connection refused
; error #1: dial tcp 127.0.0.1:4001: connect: connection refused

error #0: dial tcp 127.0.0.1:2379: connect: connection refused
error #1: dial tcp 127.0.0.1:4001: connect: connection refused
```

$ sudo systemctl restart etcd-member
```
Job for etcd-member.service failed because of unavailable resources or another system error.
See "systemctl status etcd-member.service" and "journalctl -xe" for details.
```

$ journalctl -xe
```
-- The job identifier is 65365 and the job result is done.
Sep 16 15:45:31 kirk.ghsix.com.br systemd[1]: etcd-member.service: Failed to load environment files: No such file or directory
Sep 16 15:45:31 kirk.ghsix.com.br systemd[1]: etcd-member.service: Failed to run 'start-pre' task: No such file or directory
Sep 16 15:45:31 kirk.ghsix.com.br systemd[1]: etcd-member.service: Failed with result 'resources'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The unit etcd-member.service has entered the 'failed' state with result 'resources'.
Sep 16 15:45:31 kirk.ghsix.com.br systemd[1]: Failed to start etcd (System Application Container).
-- Subject: A start job for unit etcd-member.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit etcd-member.service has finished with a failure.
-- 
-- The job identifier is 65365 and the job result is failed.
```

May be related (this coreos-metada does not exist):
$ ssh user@flatcar
```
Flatcar Container Linux by Kinvolk stable (2512.5.0)
Failed Units: 1
  coreos-metadata.service
```

**Comment by EthraZa** [comment]
Looks like it relates to #178

**Comment by vbatts** [comment]
@EthraZa since the machine is already provisioned, the locksmithd will respect environment variables for this window.
the `locksmithd.service` loads env variables from `/etc/flatcar/update.conf`.
If you add something like from https://github.com/flatcar-linux/locksmith#reboot-windows:
```
LOCKSMITHD_REBOOT_WINDOW_START="Thu 23:00"
LOCKSMITHD_REBOOT_WINDOW_LENGTH=1h30m
```
to that file, and restart locksmithd.service, it will load that schedule

**Comment by ahrkrak** [comment]
Also worth mentioning: you can install Nebraska locally (https://github.com/kinvolk/nebraska) and use that as your update server, in which you can define when updates are made available to hosts. For customers with a support subscription, Kinvolk also provides this as a managed service.

**Comment by EthraZa** [comment]
@vbatts 
The updater is ignoring the config...

$ cat /etc/flatcar/update.conf (or /etc/coreos/update.conf)
```
GROUP=stable
REBOOT_STRATEGY="etcd-lock"
LOCKSMITHD_REBOOT_WINDOW_START="Sun 4:00"
LOCKSMITHD_REBOOT_WINDOW_LENGTH="3h"
SERVER=https://public.update.flatcar-linux.net/v1/update/
```
I was under the impression that this configs are for locksmith and not the updater itself, because in the yml file it's under locksmith key tag.
So maybe the problem is the "etcd-lock"? If I change it to "reboot" do you think it will respect when to reboot to apply the update?

@ahrkrak 
This one is new to me. Will take a look, thank you.

**Comment by pothos** [comment]
Since you know when you want to reboot, you can remove the `etcd-lock` line and use the default `reboot` strategy. I guess combining both should also work but if you just have a small number of machines, it seems easier to allocate the hours manually.

P.S.: The `SERVER` and `GROUP` values are not needed there if they are the same as in `/usr/share/flatcar/update.conf`.

**Comment by EthraZa** [comment]
Ok, I have changed the REBOOT_STRATEGY to "reboot" so.
I'm just skeptical that the LOCKSMITHD_REBOOT_WINDOW_START will work since locksmithctl itself is returning an error.
Now lets wait for the next Flatcar update to see how it will act. 

ps. But I still think the docs are lacking more explanating about this. The docs are missing an etcd functional setup example and to be sincere, it is lacking a full and functional Container Config YML example.

**Comment by goochjj** [comment]
There's very little point in running ETCD if you're just trying to control a single machine's reboot behavior.  You'll always get a lock.  The only reason to use etcd-lock strategy is if you have a cluster of 2+ machines, and you don't want them all to reboot at the same time(i.e. 1 at a time, or 2 at a time)

This is spelled out here https://coreos.com/os/docs/latest/update-strategies.html. (for coreos, but also applies to flatcar)

The env variables are spelled out here https://github.com/coreos/locksmith#reboot-windows and further up in the readme.  And yes, every one of my machines have a reboot window defined and I highly recommend you define one as well.

After changing that conf file (which for flatcar is in /etc/flatcar, not /etc/coreos) you need to `systemctl restart locksmithd`


If you DO choose to go the etcd route, you can.
https://coreos.com/os/docs/latest/cluster-discovery.html

**Comment by pothos** [comment]
For completeness, the Flatcar docs are under https://docs.flatcar-linux.org/os/update-strategies/ and there is also FLUO for Kubernetes: https://github.com/kinvolk/flatcar-linux-update-operator/

**Comment by margamanterola** [comment]
BTW, Allan, we had a release on Tuesday. What happened? Did the fix work?

**Comment by EthraZa** [comment]
Wow! Thank you for warning me. I didn't know about the update yet because the server did not rebooted.
Now I'll get back to it at Sunday to see if it reboots at the configured time.
~~~
REBOOT_STRATEGY="reboot"
LOCKSMITHD_REBOOT_WINDOW_START="Sun 4:00"
LOCKSMITHD_REBOOT_WINDOW_LENGTH="2h"
~~~

For now, it's still at:
$ uname -r
`4.19.145-flatcar`

**Comment by EthraZa** [comment]
@pothos Thank you for pointing me the links. Dind't know abot FLUO, I'll take a look at it, but since I'm not running Kubernets, but Swarm mode, I don't know if it'll be useful right now.

About the Flatcar docs, beside the docs not leting it clear that an "etcd-lock" strategy would invalidate the rest of the config if etcd is not correct configured, I guess the biggest problem to me is that I was unable to get etcd running by following the Flatcar docs.
What I wold expect is, the docs stating this "reboot right way" behavior with "etcd-lock" when we have a missconfigured etcd or better yet, the "etcd-lock" strategy defaulting to "reboot" or "off" behavior when it's unable to access etcd server.

**Comment by goochjj** [comment]
@EthraZa I don't leave anything to chance, my monitoring looks at `update_engine_client -status` (which I suggest you run now).  This will tell you if it has found the update, applied it and it's just waiting for a reboot... Or if it hasn't even noticed yet.

You can also use -check_for_update or -update

If you wanted to be absolutely safe, do this:
1) Take note of which partition is active with `rootdev -s /usr`.  sda3 means USR-A, sda4 means USR-B.
2) `systemctl stop update-engine locksmithd`
 (at this point all updates/reboots are paused)
3) Wait until off hours, perhaps sometime Saturday.
4) Verify your update.conf and other settings.
5) `systemctl start update-engine locksmithd`
6) `update_engine_client -update`
7) See what happens when it finishes.  If it reboots immediately, or indicates it's going to wait 5 minutes because you're logged in - you know it didn't take the update window config parameters and you need to track that down.  You can go back to step 2 to stop the reboot if it hasn't happened yet.
8) If it indicates reboot required in the `update_engine_client -status`, then wait for your window to happen at 4am, and verify that works (probably the following morning)

When it reboots - if for whatever reason it DOESN'T recover/boot on it's own, note the USR-A or USR-B you found in step 1.  Reboot the machine and at the grub prompt, pick the one that is known good.   Disable the services (i.e. step 2).  Wait until you have time, and diagnose why it didn't work.

That's how I would do it - controlled, safe, off hours, limit risk.

**Comment by pothos** [comment]
`journalctl -u locksmithd -b 0` will also tell you when it would reboot once you configured the time window:
```
Sep 16 15:16:34 mynode systemd[1]: Started Cluster reboot manager.
Sep 16 15:16:35 mynode locksmithd[903]: Reboot window start is "Sat 23:00" and length is "1h"
Sep 16 15:16:35 mynode locksmithd[903]: Next window begins at 2020-09-19 23:00:00 +0000 UTC and ends at 2020-09-20 00:00:00 +0000 UTC
```

And after it downloaded an update `systemctl status locksmithd` will show when it reboots:
```
Sep 22 10:21:27 mynode locksmithd[903]: LastCheckedTime=1600770028 Progress=0 CurrentOperation="UPDATE_STATUS_UPDATED_NEED_REBOOT" NewVersion=2605.5.0 NewSize=526985413
Sep 22 10:21:26 mynode locksmithd[903]: Waiting for 108h38m33.022164243s to reboot.
```

**Comment by EthraZa** [comment]
You guys are right. Looks like it's indeed waiting for reboot.

$ systemctl status locksmithd
```
● locksmithd.service - Cluster reboot manager
   Loaded: loaded (/usr/lib/systemd/system/locksmithd.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2020-09-16 12:42:36 -03; 1 weeks 1 days ago
 Main PID: 1136 (locksmithd)
    Tasks: 8 (limit: 32767)
   Memory: 20.5M (limit: 32.0M)
   CGroup: /system.slice/locksmithd.service
           └─1136 /usr/lib/locksmith/locksmithd

Sep 22 06:54:34 kirk.ghsix.com.br locksmithd[1136]: LastCheckedTime=1600768052 Progress=0.9410640840641257 CurrentOperation="UPDATE_STATUS_DOWNLOADING" NewVersion=2605.5.0 NewSize=526985413
Sep 22 06:54:39 kirk.ghsix.com.br locksmithd[1136]: LastCheckedTime=1600768052 Progress=0.9510750784291633 CurrentOperation="UPDATE_STATUS_DOWNLOADING" NewVersion=2605.5.0 NewSize=526985413
Sep 22 06:54:42 kirk.ghsix.com.br locksmithd[1136]: LastCheckedTime=1600768052 Progress=0.9610860727942009 CurrentOperation="UPDATE_STATUS_DOWNLOADING" NewVersion=2605.5.0 NewSize=526985413
Sep 22 06:54:47 kirk.ghsix.com.br locksmithd[1136]: LastCheckedTime=1600768052 Progress=0.9710970671592384 CurrentOperation="UPDATE_STATUS_DOWNLOADING" NewVersion=2605.5.0 NewSize=526985413
Sep 22 06:54:53 kirk.ghsix.com.br locksmithd[1136]: LastCheckedTime=1600768052 Progress=0.981108061524276 CurrentOperation="UPDATE_STATUS_DOWNLOADING" NewVersion=2605.5.0 NewSize=526985413
Sep 22 06:54:55 kirk.ghsix.com.br locksmithd[1136]: LastCheckedTime=1600768052 Progress=0.9911190558893136 CurrentOperation="UPDATE_STATUS_DOWNLOADING" NewVersion=2605.5.0 NewSize=526985413
Sep 22 06:55:00 kirk.ghsix.com.br locksmithd[1136]: LastCheckedTime=1600768052 Progress=1 CurrentOperation="UPDATE_STATUS_DOWNLOADING" NewVersion=2605.5.0 NewSize=526985413
Sep 22 06:55:00 kirk.ghsix.com.br locksmithd[1136]: LastCheckedTime=1600768052 Progress=0 CurrentOperation="UPDATE_STATUS_FINALIZING" NewVersion=2605.5.0 NewSize=526985413
Sep 22 06:55:08 kirk.ghsix.com.br locksmithd[1136]: LastCheckedTime=1600768052 Progress=0 CurrentOperation="UPDATE_STATUS_UPDATED_NEED_REBOOT" NewVersion=2605.5.0 NewSize=526985413
Sep 22 06:55:08 kirk.ghsix.com.br locksmithd[1136]: Waiting for 117h4m51.216318738s to reboot.
```

$ journalctl -u locksmithd -b 0
```
(lots and lots of this one)...
Sep 22 06:52:54 kirk.ghsix.com.br locksmithd[1136]: Unlocking old locks failed: error setting up lock: Error initializing etcd client: client: etcd cluster is unavailable or misconfigured. Retrying in 5m0s.
...
Sep 22 06:54:47 kirk.ghsix.com.br locksmithd[1136]: LastCheckedTime=1600768052 Progress=0.9710970671592384 CurrentOperation="UPDATE_STATUS_DOWNLOADING" NewVersion=2605.5.0 NewSize=526985413
Sep 22 06:54:53 kirk.ghsix.com.br locksmithd[1136]: LastCheckedTime=1600768052 Progress=0.981108061524276 CurrentOperation="UPDATE_STATUS_DOWNLOADING" NewVersion=2605.5.0 NewSize=526985413
Sep 22 06:54:55 kirk.ghsix.com.br locksmithd[1136]: LastCheckedTime=1600768052 Progress=0.9911190558893136 CurrentOperation="UPDATE_STATUS_DOWNLOADING" NewVersion=2605.5.0 NewSize=526985413
Sep 22 06:55:00 kirk.ghsix.com.br locksmithd[1136]: LastCheckedTime=1600768052 Progress=1 CurrentOperation="UPDATE_STATUS_DOWNLOADING" NewVersion=2605.5.0 NewSize=526985413
Sep 22 06:55:00 kirk.ghsix.com.br locksmithd[1136]: LastCheckedTime=1600768052 Progress=0 CurrentOperation="UPDATE_STATUS_FINALIZING" NewVersion=2605.5.0 NewSize=526985413
Sep 22 06:55:08 kirk.ghsix.com.br locksmithd[1136]: LastCheckedTime=1600768052 Progress=0 CurrentOperation="UPDATE_STATUS_UPDATED_NEED_REBOOT" NewVersion=2605.5.0 NewSize=526985413
Sep 22 06:55:08 kirk.ghsix.com.br locksmithd[1136]: Waiting for 117h4m51.216318738s to reboot.
```

$ rootdev -s /usr
`/dev/sda4`

$ update_engine_client -status
```
I0924 14:26:18.351461 22313 update_engine_client.cc:237] Querying Update Engine status...
LAST_CHECKED_TIME=1600768052
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_UPDATED_NEED_REBOOT
NEW_VERSION=2605.5.0
NEW_SIZE=526985413
```

**Comment by goochjj** [comment]
Sounds like you're all set then!

**Comment by EthraZa** [comment]
It did work all right.

I have even changed the LOCKSMITHD_REBOOT_WINDOW_START to "Sun 12:00" and it worked like a charm and rebooted itself at sunday 12pm.

Since I'm good for now, I'm going to close this issue, but I know I will need to revisit it in the future, when I get more Flatcar Linuxes in the Swarm, to get etcd in a working state so the servers can use it to place a lock and reboot one at a time. I hope the Flatcar Linux etcd docs evolve a bit more till there.

Thank you all.
