### ISSUE TITLE
Update kubelet-wrapper, flannel-wrapper and etcd-wrapper to use docker instead of rkt

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#189]
**Current situation**

kubelet-wrapper, flannel-wrapper and etcd-wrapper use rkt for pulling images from dockerhub and for extracting image contents. rkt however is [retired upstream]([url](https://github.com/rkt/rkt/issues/4024)) and poses an increasing maintenance burden.

**Impact**

rkt and related binaries like actool cannot currently be removed from the Flatcar Container Linux OS image without sacrificing core functionality.

**Ideal future situation**

The wrapper scripts' dependency on rkt is largely for historical reasons; multiple other binaries shipped with the OS image implement the same functionality. A future state solving the issue would be to switch to a different binary in the wrapper scripts.

**Implementation options**

Use e.g. docker.

**Comment by vbatts** [comment]
prior work that can be rebased: https://github.com/kinvolk/lokomotive-kubernetes/pull/100/files

**Comment by pothos** [comment]
The parameters of the scripts are somehow tied to rkt. The scripts also sometimes suffered from incompatibility with all available kubelet and etcd versions. I suggest to remove them entirely or maintain them (using Docker) in an external repository where they can be pulled from with Ignition (`"contents": { "source": "http…"`) with version tags decoupled from the OS version.

**Comment by vbatts** [comment]
that is an option. lokomotive have worked around these wrappers alrighty. I do see merit in having a bootstrapper for etcd, since tools like locksmith are partially relying on it.

**Comment by der-eismann** [comment]
For the kubelet-wrapper I'd prefer a script that's downloading and running the native binary on the host like it's suggested in the [kubernetes docs](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl). There are no more official hyperkube images, so I don't really see a future for this.

**Comment by igcherkaev** [comment]
agree with @der-eismann 
kubelet-wrapper needs to be updated or a new wrapper added to maintain backwards compatibility, allowing users to choose which way they want to run kubelet.

Found this issue while upgrading from v1.17 to v1.18 running on flatcar linux.

**Comment by vbatts** [comment]
Good point 👍

**Comment by sfudeus** [comment]
I'd appreciate a natively running kubelet as well (to prevent problems with mount propagations), but I'd not like the kubelet binary being pulled by a wrapper at arbitrary times. We use ContainerLinux to have a more or less immutable installation, so IMHO the kubelet should be fetched and frozen upon node installation only, not ad-hoc.

**Comment by shift** [comment]
Just throwing this out there, what about running them via systemd-nspawn instead of docker?

**Comment by dongsupark** [comment]
Alpha 2857.0.0 removed rkt, using docker instead.
Please see https://groups.google.com/g/flatcar-linux-user/c/MeinndLqJO4 for details.
