### ISSUE TITLE
CoreOS End-of-life

### ISSUE THREAD

**Issue by mdgreenwald** [flatcar/Flatcar#19]
My apologies if this is an inappropriate forum for this issue. I am curious as to how CoreOS End-of-life on May 26, 2020 will impact Flatcar Linux since it appears that Flatcar is dependent on the upstream project. Thanks for any information or insights.

[https://coreos.com/os/eol/](https://coreos.com/os/eol/)

**Comment by dharmab** [comment]
From the flatcar FAQ:

>## What do you mean when you say Flatcar Container Linux is “independently built”?
>
>We mean that Flatcar Container Linux is not dependent on upstream binary artifacts, and is fully built from source. In fact, if CoreOS Container Linux disappeared tomorrow, it would have very little impact on the Flatcar Container Linux project.

I wonder if this applies to the documentation at https://coreos.com/os/docs/latest as well?

**Comment by mdgreenwald** [comment]
@dharmab Thanks for that reference. I did see that, but wanted to be 100% certain.

**Comment by mdgreenwald** [comment]
@dharmab Thanks for that reference. I did see that, but wanted to be 100% certain.

According to the CoreOS EOL notice: "Documentation will continue to exist for as long as is practical, to aid migration to other operating systems."[[1]](https://coreos.com/os/eol/)

**Comment by pothos** [comment]
Hello,

Flatcar Container Linux will function as independent distribution which includes the regular maintenance work like updating software versions and reacting to security vulnerabilities.
The beginning is made already and we will give an update about the process soon, but here some general info that I hope answers your questions.

In terms of distribution maintenance work we already do the necessary changes independently from CoreOS CL upstream in the Alpha and Edge channels. The Stable and Beta channels currently have the source code still synced from upstream CoreOS CL but we will do the independent maintenance for these channels, too, before CoreOS CL is not updated anymore.

Documentation can already be found on https://docs.flatcar-linux.org. We probably have to make a final comparison and check that all relevant content is captured.

For future information requests and discussions you can also consider using https://groups.google.com/forum/#!forum/flatcar-linux-user

Regards
