### ISSUE TITLE
/usr image size

### ISSUE THREAD

**Issue by goochjj** [flatcar/Flatcar#196]
**Description**
The /usr image is getting pretty close to the USR-A/USR-B partition sizes

/dev/mapper/usr   1007760   942388     13356  99% /usr

Is there a plan to expand the USR-A and USR-B partitions?

**Impact**
If the image gets much bigger it won't fit on existing systems

**Implementation options**
Possible options
1) Maybe combine 3+4 into one 2G partition and tack an additional one onto the end (as part of or before growfs steps)
2) Provide guidance (or a helper) to migrate a system from sda to sdb (or another disk) and make sda root-partition only
3) Provide guidance (or a helper) to migrate partitions 1-8 from sda to sdb (or another disk) and make sda root-partition only
4) Redeploy a base image and migrate i.e. w/ Ignition

**Comment by pothos** [comment]
Hello,
thanks for creating a ticket here for visibility. The plan is to reduce the content size by removing the unused Docker 1.12 torcx image and other deprecated or unneeded software.

This should address the problem for the mean time but as software binaries tend to grow larger and larger over the course of a few years we don't know yet what will happen later and if in the future we need to exclude some things from the base image and fetch them on demand as containers or any of the options you stated.

**Comment by goochjj** [comment]
If I choose to expand my partitions, will everything work? It looks like you're using partition labels.  Or is there something hardcoded somewhere for 1GB image sizes?

**Comment by goochjj** [comment]
If I read the initrd correctly, it should work because you use e2size to find the hash at the end of the filesystem.  But I guess it's not necessary or desired to do anything until the image requires it.  So I'll just wait I guess :-D

**Comment by goochjj** [comment]
Is there some place where you're discussing/identifying "deprecated/unused" software?
The docker 1.12 torcx only saves 27M

**Comment by goochjj** [comment]
I'd also recommend if expansion is in the future, changing the partition layout now for new deployments, before we need it, would be a great way to handle it.

**Comment by pothos** [comment]
I don't think we will change the disk layout soon. Having a hard limit of 1 GB helps to enforce the goal of aiming for a minimal but functional OS. I'm sure there are many areas where the we can reduce the content size.

**Comment by dongsupark** [comment]
As Alpha 2857.0.0 dropped rkt binaries, disk usage of the system partition has dropped significantly to 82%.

```
$ df -h /usr 
Filesystem       Size  Used Avail Use% Mounted on
/dev/mapper/usr  985M  761M  174M  82% /usr
```

Hopefully your concern was mostly addressed.
We will continuously keep an eye on the image size issue.

**Comment by dongsupark** [comment]
Will close, as the current Alpha and Beta have enough free space in /usr.
