### ISSUE TITLE
Override ID in /etc/os-release to work with Docker Machine

### ISSUE THREAD

**Issue by kinghuang** [flatcar/Flatcar#197]
**Current situation**

I used to use CoreOS with [docker/machine](https://github.com/docker/machine) and GitLab Runner for running GitLab CI/CD jobs. Docker Machine's CoreOS provisioner unfortunately only checks if `ID=coreos` in `/etc/os-release`, and not `ID_LIKE=coreos`. As a result, it is unable to launch machines with Flatcar AMIs.

**Impact**

I am unable to launch Flatcar Linux instances using Docker Machine.

**Ideal future situation**

The Docker Machine project is no longer accepting feature enhancements. But, I would still like to be able to use it to launch machines with Flatcar Linux.

**Implementation options**

Is there a way to customize /etc/os-release to say `ID=coreos`, so that Docker Machine will apply the coreos provisioner?

**Additional information**

[Docker Machine is now in maintenance mode](https://github.com/docker/machine/issues/4537)

**Comment by pothos** [comment]
Hello,

like other files that are outside of `/usr` you can create it through an Ignition config (or Container Linux Config YAML transpiled to Ignition JSON).

Something like this:
```
storage:
  files:
    - path: /etc/os-release
      filesystem: root
      mode: 0644
      contents:
        inline: |
          NAME="Flatcar Container Linux by Kinvolk"
          ID=coreos
          ID_LIKE=coreos
          VERSION=2512.5.0
          VERSION_ID=2512.5.0
          BUILD_ID=2020-09-14-1819
          PRETTY_NAME="Flatcar Container Linux by Kinvolk 2605.5.0 (Oklo)"
          ANSI_COLOR="38;5;75"
          HOME_URL="https://flatcar-linux.org/"
          BUG_REPORT_URL="https://issues.flatcar-linux.org"
          FLATCAR_BOARD="amd64-usr"
```
gets transpiled via `cat FILE | docker run --rm -i quay.io/coreos/ct:latest-dev`.

Not sure how to supply the config to Docker Machine as I don't know it well.

In case it's not possible you could also embed the config into the image by placing it in the OEM partition as `user.ign` (but you need the other OEM partition contents as well).

**Comment by kinghuang** [comment]
Thanks! I had it in my mind that I couldn't just write a file because it's symlinked into `/usr`. Adding that to my Ignition config worked perfectly. Docker Machine is treating the launched instance as CoreOS.
