### ISSUE TITLE
Make BPF tracing tools (bcc, bpftrace) easier to use in Flatcar

### ISSUE THREAD

**Issue by alban** [flatcar/Flatcar#198]
**Current situation**

BPF tracing tools bcc and bpftrace are difficult to use in Flatcar:
- the Docker command is complicated to remember and not documented
- toolbox does not work out of the box, flags have to be added manually
- it's not clear which container image to use, and which ones are up-to-date
- some bcc tools or bpftrace commands don't work and we don't have tests for them, so it's difficult to notice
  - execsnoop in toolbox does not currently work. Difficult for users to know if the problem is in Flatcar or in bcc
  - the first bpftrace one-liner does not currently work. Difficult for users to know if the problem is in Flatcar or in bpftrace

**Impact**
Difficult to use bcc and bpftrace

**Ideal future situation**

- [ ] The Flatcar documentation gives example how to use bcc and bpftrace via toolbox and via Docker. 
- [ ] The Flatcar documentation gives recommendations which container images to use
- [ ] Flatcar could provide a bcc alias to make it easier to remember the Docker command
- [ ] Toolbox could have more flags to make it work with bpf by default, see below
- [ ] We have bcc/bpftrace tests in Flatcar, so when something breaks we can either fix it in Flatcar, or report the bug in bcc/bpftrace upstream

**Implementation options**

https://github.com/flatcar-linux/toolbox/pull/3 was a first step but we still need more flags for lib-modules, debugfs and perf_event_open:

```
TOOLBOX_BIND="--bind=/:/media/root --bind=/usr:/media/root/usr
--bind=/run:/media/root/run --bind=/sys/fs/bpf:/sys/fs/bpf
--bind=/lib/modules:/lib/modules
--bind=/sys/kernel/debug:/sys/kernel/debug"
TOOLBOX_FLAGS="--system-call-filter=bpf --system-call-filter=perf_event_open"
```

Examples of aliases:
```
alias iovisor-bpftrace="docker run -ti --rm --privileged -v /lib/modules:/lib/modules -v /sys/fs/bpf:/sys/fs/bpf -v /sys/kernel/debug:/sys/kernel/debug --pid=host 
iovisor-bpftrace -e 'tracepoint:raw_syscalls:sys_enter { @[comm] = count(); }'
```

**Additional information**

https://groups.google.com/g/flatcar-linux-user/c/3beNeuNzGAA/m/-dFiYPnaAwAJ

**Comment by pothos** [comment]
We got bashrc aliases now for some bcc tools (using Docker)
