### ISSUE TITLE
Provide containerd-shim-runc-v1 binary 

### ISSUE THREAD

**Issue by invidian** [flatcar/Flatcar#201]
**Current situation**

Currently, when one tries to run `kubelet` with `--container-runtime=remote` and `--container-runtime-endpoint=unix:///run/docker/libcontainerd/docker-containerd.sock` flags, to use `containerd` directly as a container runtime for pods, instead of using default Docker, `kubelet` is not able to create any pods and prints the following errors:
```
E0926 21:56:47.799197    9738 kuberuntime_sandbox.go:69] CreatePodSandbox for pod "kube-proxy-f5972_kube-system(31ad14fb-fea3-46cb-8dce-7436816fb596)" failed: rpc error: code = Unknown desc = failed to create containerd task: runtime "io.containerd.runc.v1" binary not installed "containerd-shim-runc-v1": file does not exist: unknown
E0926 21:56:47.799211    9738 kuberuntime_manager.go:730] createPodSandbox for pod "kube-proxy-f5972_kube-system(31ad14fb-fea3-46cb-8dce-7436816fb596)" failed: rpc error: code = Unknown desc = failed to create containerd task: runtime "io.containerd.runc.v1" binary not installed "containerd-shim-runc-v1": file does not exist: unknown
E0926 21:56:47.799246    9738 pod_workers.go:191] Error syncing pod 31ad14fb-fea3-46cb-8dce-7436816fb596 ("kube-proxy-f5972_kube-system(31ad14fb-fea3-46cb-8dce-7436816fb596)"), skipping: failed to "CreatePodSandbox" for "kube-proxy-f5972_kube-system(31ad14fb-fea3-46cb-8dce-7436816fb596)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-proxy-f5972_kube-system(31ad14fb-fea3-46cb-8dce-7436816fb596)\" failed: rpc error: code = Unknown desc = failed to create containerd task: runtime \"io.containerd.runc.v1\" binary not installed \"containerd-shim-runc-v1\": file does not exist: unknown"
```

**Impact**
Unable to use CRI plugin for `containerd` as container runtime for Kubernetes clusters running on Flatcar Container Linux.

**Ideal future situation**
Flatcar default torcx profile should provide `containerd-shim-runc-v1` binary usable by kubelet.

**Comment by dongsupark** [comment]
True.
I have seen similar issues when testing Flatcar via image-builder for Cluster API.
It is not only about `containerd-shim-runc-v[12]`, but also necessary tools like `crictl`.

On the other hand, however, we need to figure out how we can make some free space in the production Flatcar image. At the moment ~95% of the system partitions are full.

**Comment by invidian** [comment]
Isn't `crictl` more for CRI-O? `containerd` can be interacted with `ctr` as far as I know. For CRI-O support, which would also be nice, I'd create separate feature request :)

**Comment by dongsupark** [comment]
Both `ctr` and `crictl` are possible for communication with `containerd`.
Anyway image-builder needs both `crictl` and `ctr`.

Well, anyway I suppose the runc-shim issue is more critical here, as you described.

EDIT: image-builder actually uses both crictl and ctr.

**Comment by dongsupark** [comment]
Filed a PR to add container-shim-runc-v* binaries to the torcx profile for Docker 19.03. https://github.com/flatcar-linux/coreos-overlay/pull/623

Though before doing that, we should first review and merge https://github.com/flatcar-linux/coreos-overlay/pull/622 to get some free space in production images.

**Comment by dongsupark** [comment]
https://github.com/flatcar-linux/coreos-overlay/pull/623 was merged, and it will be included in the next Alpha release.

**Comment by bikrambox** [comment]
I found that When Re-installing **docker** in AWS Amazon Linux 2 it just reinstalled Docker but when Installing Fresh Docker all Other dependencies Like **contained, runc** are installed with Docker, Therefore, Reinstallaling **containerd** resolved all the issues. 


`sudo yum reinstall containerd docker -y`


This will resolve it. No need to Copy-Paste them ( i.e. `cp containerd-shim-runc-v1 containerd-shim-runc-v2` )
