### ISSUE TITLE
Enable CONFIG_PSI kernel config flag

### ISSUE THREAD

**Issue by invidian** [flatcar/Flatcar#202]
**Current situation**
Despite running kernel 5.8.9, PSI information is not available.

```
$ ls -l /proc/pressure
ls: cannot access '/proc/pressure': No such file or directory
```

**Impact**
Having PSI is useful while debugging performance issues: https://unixism.net/2019/08/linux-pressure-stall-information-psi-by-example/

**Ideal future situation**
PSI should be available by default on all channels.

**Implementation options**
I guess setting `CONFIG_PSI` option should be sufficient?

**Comment by pothos** [comment]
Thanks for the report. Looks like it's a duplicate of https://github.com/flatcar-linux/Flatcar/issues/162 ;)

**Comment by invidian** [comment]
Ah, I didn't check it this time! :smile: Sorry for the noise.
