### ISSUE TITLE
Relabeling of content in /usr

### ISSUE THREAD

**Issue by hwaastad** [flatcar/Flatcar#204]
**Description**

stable version of flatcar >= 2605.5.0 does not work with rancher

**Impact**

It is not possible to create k8s clusters via rancher (custom cluster) or rke.
The last version working is 2512.5.0

**Environment and steps to reproduce**

1. **Set-up**: flatcar >=2605.5.0 running in vmware
2. **Task**: rke up --config cluster.yaml
3. **Action(s)**: 
4. **Error**: Relabeling of /usr fails

**Expected behavior**
k8s cluster should be working fine, but kube-proxy will not come up

**Additional information**
The error message shown:
```
Error response from daemon: error setting label on mount source '/usr/lib64/modules': relabeling content in /usr is not allowed]]
```
Upgrade from 25xx to 26xx in an existing cluster works fine.
There has been an issue with Fedora CoreOS (https://github.com/rancher/rke/issues/2194), but it does'nt seem to be exactly the same.
Are there any mitigation?

**Comment by vbatts** [comment]
@hwaastad are you using rancher v1.2.0?

**Comment by hwaastad** [comment]
@vbatts, yes. same issue on 1.1.7 and 1.2.0.
Issue is the same deploying custom clusters in rancher 2.4.7 and 2.4.8 (Have'nt had the guts yet to try out 2.5.0)

**Comment by vbatts** [comment]
let's see, I was just deploying rke 1.2.0 this morning, onto 2605.6.0 and not hitting this issue. I did encounter this and opened https://github.com/rancher/rke/pull/2214 to fix it.
Perhaps this could be due to creating it _from_ the Rancher UI? I'll have to investigate this.

The work around in the past had been to set SELinux to disabled (not just Permissive):
```shell
cat /etc/selinux/config | sed 's/^SELINUX=.*/SELINUX=disabled/' > /etc/selinux/xx
rm /etc/selinux/config
mv /etc/selinux/xx /etc/selinux/config
reboot
```

**Comment by mikekuzak** [comment]
@hwaastad You said the last working version was flatcar release 2512.5.0. There were are lot of changes in Rancher and Flatcar since then, Docker version has changed to 19.03.x, Kernel to 5.4.x, not sure is this a Rancher or Flatcar issue. Btw I have the same issue with Fedora CoreOS 32.xx and I'm not able to check Rancher 2.5 as it's not coming up at all :(

**Comment by hwaastad** [comment]
@vbatts and @mikekuzak, I think rke works fine. it was a etcd restore that did'nt work.(just a stress situation during havoc). And yes, issue exists on creating custom clusters on flatcar 2605.XX.
@mikekuzak , not sure myself, but since the same rancher deployment (2.4.8) work on 25xx, but an install of 2.4.8 on 26xx is failing, there must be a change but I cannot but I cannot see the reason.
Both 25xx and 26xx has permissive selinux, but I can try to disable to see if that works. I'll update

**Comment by hwaastad** [comment]
@vbatts, it seems that disabling selinux works on new cluster nodes. In my current situation it turns out that disabling selinux on existing servers has to be handled with care.

1. Existing rancher 2.4.8 (18.8) k8s automatically has bee upgraded to 2605.6.0, selinux permissive -> all OK
2. if any rancher upgrade happens, relabeling issues will occure
3. disabling selinux:
3.1 Cordon and remove node from cluster
3.2 Cleanup node
3.3 Disable selinux and reboot
4. Add node back to cluster

I've tried to disable selinux on a node running in the cluster, and rebooting but this is failing.

**Comment by straffalli** [comment]
Hello,
Any update on this issue? I have the same problem on rancher 2.4.8 and Flatcar 2605.6.0. It is mainly impacting kube-proxy on running clusters.

**Comment by vbatts** [comment]
I'm trying to narrow down the use case here. Specifically this is affecting https://github.com/rancher/rancher, when running on a flatcar host? (Not particularly when deploying rke itself)

**Comment by straffalli** [comment]
Yes exactly, we started to notice these troubles with Flatcar 26xx versions.

**Comment by pothos** [comment]
@hwaastad  @straffalli Can you try again with disabling SELinux through the kernel parameter `selinux=0`? This is the only way to really disable it.

**Comment by straffalli** [comment]
Hi, yes we disabled SELINUX in order to get it working. But now Rancher changed the way it works with OS like Flatcar or CoreOS  and they avoid the relabeling. So it should also work with Selinux enabled.

**Comment by pothos** [comment]
Thanks for the update, closing it then
