### ISSUE TITLE
unable to get build environment of the sdk on ubuntu 20.04

### ISSUE THREAD

**Issue by skshandilya** [flatcar/Flatcar#206]
**Description**

Sorry newbie here,
cork create fails to build the sdk environment

**Impact**

Not able to get started with building custom images

**Environment and steps to reproduce**
download the latest cork and run
 cork create
2020-10-07T17:39:49Z cork: Detecting SDK version
2020-10-07T17:39:52Z cork: Found SDK version 2643.0.0 from remote repo
2020-10-07T17:39:52Z cork: Downloading SDK version 2643.0.0
2020-10-07T17:39:56Z sdk: Unpacking SDK into /home/sanshand/flatcar/sdk/chroot
2020-10-07T17:42:47Z sdk: Unpacked
gpg: keybox '/home/sanshand/.repoconfig/gnupg/pubring.kbx' created
gpg: /home/sanshand/.repoconfig/gnupg/trustdb.gpg: trustdb created
gpg: key 16530D5E920F5C65: public key "Repo Maintainer <repo@android.kernel.org>" imported
gpg: key 67B7E448692B382C: public key "Conley Owens <cco3@android.com>" imported
gpg: Total number processed: 2
gpg:               imported: 2

fatal: Cannot get https://gerrit.googlesource.com/git-repo/clone.bundle
fatal: error [Errno -2] Name or service not known
fatal: cloning the git-repo repository failed, will remove '.repo/repo' 
2020-10-07T17:43:08Z cork: repo init failed: exit status 1

but I am able to reach and download the clone.bundle directly

**Comment by vbatts** [comment]
Hi @skshandilya, which version of cork are you using? `cork version`

**Comment by vbatts** [comment]
I just spun up a clean ubuntu 20.04 instance:
```shell
curl -OL https://github.com/flatcar-linux/mantle/releases/download/v0.15.1/cork-0.15.1-amd64
chmod +x cork-0.15.1-amd64
mv cork-0.15.1-amd64 /usr/local/bin/cork
apt update 
apt install -y git build-essential
adduser vbatts
usermod -aG sudo vbatts
```
log in again as the limited user (cork environment does not work correctly as `root`):
```shell
mkdir flatcar
cd flatcar
cork create
cork enter
```
The output rolled right through where yours errored out:
```
2020-10-07T18:56:53Z cork: Detecting SDK version 
2020-10-07T18:56:54Z cork: Found SDK version 2643.0.0 from remote repo
2020-10-07T18:56:54Z cork: Downloading SDK version 2643.0.0
2020-10-07T18:57:14Z sdk: Removing SDK at /home/vbatts/flatcar/chroot
2020-10-07T18:57:22Z sdk: Removed
2020-10-07T18:57:22Z sdk: Unpacking SDK into /home/vbatts/flatcar/chroot
2020-10-07T19:04:07Z sdk: Unpacked
gpg: keybox '/home/vbatts/.repoconfig/gnupg/pubring.kbx' created
gpg: /home/vbatts/.repoconfig/gnupg/trustdb.gpg: trustdb created
gpg: key 16530D5E920F5C65: public key "Repo Maintainer <repo@android.kernel.org>" imported
gpg: key 67B7E448692B382C: public key "Conley Owens <cco3@android.com>" imported
gpg: Total number processed: 2
gpg:               imported: 2

Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
repo: warning: Python 2 is no longer supported; Please upgrade to Python 3.6+.

... A new version of repo (2.8) is available.
... New version is available at: /mnt/host/source/.repo/repo/repo
... The launcher is run from: /usr/lib/python-exec/python2.7/repo
!!! The launcher is not writable.  Please talk to your sysadmin or distro
!!! to get an update installed.

repo: Updating release signing keys to keyset ver 2.3
Downloading manifest from https://github.com/flatcar-linux/manifest.git
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 7794 (delta 0), reused 1 (delta 0), pack-reused 7791
[...]
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (42/42), done.
Fetching projects:  89% (26/29) flatcar-linux/dockerremote: Total 2357 (delta 16), reused 31 (delta 9), pack-reused 2306
Fetching projects:  93% (27/29) flatcar-linux/initremote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 43 (delta 4), reused 6 (delta 0), pack-reused 33
Fetching projects: 100% (29/29), done.
Updating files: 100% (9150/9150), done.tcar-linux/nss-altfilesUpdating files:  95% (8702/9150)
Checking out projects: 100% (29/29), done.
Your sources have been sync'd successfully. Note that only the revisions for the coreos-overlay, scripts, and portage-stable repositories are relevant. Revisions for the other repositories are specified in the ebuild files.
repo sync has finished successfully.
```

It is my guess that possibly a network connection or dns resolution failed. Possibly the dns servers 8.8.8.8 and 8.8.4.4 are not reachable.
Try again with the flag `cork create --use-host-dns`
(i'm closing as this does not appear to be a widespread issue. Feel free to re-open if it continues to be an issue)

**Comment by skshandilya** [comment]
> Hi @skshandilya, which version of cork are you using? `cork version`

cork version
mantle/cork version 0.15.0+38-gdcd6f832

**Comment by skshandilya** [comment]
--use-host-dns worked

**Comment by vbatts** [comment]
@skshandilya oh good
