### ISSUE TITLE
tcsd.service starts up on a TPM 2.0 machine

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#208]
**Description**

For machines like the Equinix Metal `c3.small.x86` the `tcsd.service` unit is reported as failing on the login prompt. This is due to the implementation only working with TPM 1.2 devices while the newer machines are using TPM 2.0.

**Impact**

It is not only confusing but also causes the kola test suite to report errors.

**Environment and steps to reproduce**

1. **Set-up**: Boot the mentioned machine tyype
2. **Task**: Check the status of the `tcsd.service` and the output of `cat /sys/devices/platform/*/tpm/tpm0/tpm_version_major`
4. **Error**: Because the major version is `2` the service fails to start with `TCSD TDDL ioctl: (25) Inappropriate ioctl for device` and exit code `30`

**Expected behavior**
The service should not be started at all when TPM 2.0 is detetced.

**Additional information**
The service unit should be modified to check the content of `/sys/devices/platform/*/tpm/tpm0/tpm_version_major` and decide to skip execution.

**Comment by arianvp** [comment]
Fyi you could use https://www.freedesktop.org/software/systemd/man/systemd.unit.html#ConditionSecurity= to check the availability of tpm2

**Comment by pothos** [comment]
Thanks for the hint, the existing `ConditionPathExists=/dev/tpm0` combined with `ConditionSecurity=!tpm2` should match TPM 1.
