### ISSUE TITLE
Add favicon.ico to Flatcar website

### ISSUE THREAD

**Issue by invidian** [flatcar/Flatcar#209]
https://www.flatcar-linux.org/favicon.ico currently returns 404. It would be cool to have Flatcar logo there, so for example, release website is easy to find in bookmarks.

**Comment by tormath1** [comment]
Hi @invidian,

So `favicon.ico` stills return a 404 but there is an icon now:
![tmp AC9JJLrezW](https://user-images.githubusercontent.com/28657343/151558032-2d86b7be-a78c-4d59-be24-e0aba3bc0a67.png)

Let's close this one then, thanks !

**Comment by invidian** [comment]
Cool, thanks!
