### ISSUE TITLE
rngd failure on AWS ARM

### ISSUE THREAD

**Issue by vbatts** [flatcar/Flatcar#212]
**Description**

booting up 2661.0.0 on an AWS a1.medium shows a failure to initialize `rngd`.

**Impact**

random numbers :smile_cat: 

**Expected behavior**
normal boot

**Encountered behavior**
```shell
[...]
Oct 16 17:20:24 localhost rngd[276]: read error
Oct 16 17:20:24 localhost rngd[276]: read error
Oct 16 17:20:24 localhost rngd[276]: read error
Oct 16 17:20:24 localhost rngd[276]: No entropy sources working, exiting rngd
```

**Comment by dongsupark** [comment]
Can confirm that the failure happens on AWS ARM. (tested several months ago)
Removed the label `channel/alpha`, as all channels from Stable to Alpha now support ARM.

**Comment by jepio** [comment]
We are using a really old version of rng-tools, I'm updating it to a newer version which handles missing hwrng better.

**Comment by jepio** [comment]
These messages are now gone because we no longer have rngd in the images.
