### ISSUE TITLE
Enable power class supply support in Flatcar

### ISSUE THREAD

**Issue by ipochi** [flatcar/Flatcar#215]
**Current situation**
```
$ zcat /proc/config.gz | grep POWER_SUPPLY
# CONFIG_POWER_SUPPLY is not set
```
As seen in the output, support for power class supply is disabled.

I'd like to know the reasons behind its default behavior in Flatcar and discussions around enabling the said configuration and its impact.

**Impact**
`node_exporter` in Prometheus Operator scraps the metrics from different collectors, one of them about the power supply class from the location `/sys/class/powersupply`.

However on Flatcar the `node_exporter` pod throws error:
```
level=error ts=2020-10-16T20:43:19.526Z caller=collector.go:161 msg="collector failed"
name=powersupplyclass duration_seconds=0.000774391 err="could not get
power_supply class info: error obtaining power_supply class info: failed to list power
supplies at \"/host/sys/class/power_supply\": open /host/sys/class/power_supply: no such
file or directory"
```

**Ideal future situation**

Either the said configuration is enabled and there are no implications/side effects or there is discussion around the default behavior and why it is so ?

**Comment by dongsupark** [comment]
I am not sure why power supply has not been enabled.
I have just tried to search for the old coreos bug tracker, git logs etc., but no discussion about it.
Basically I think it is ok to add it to the Kernel, if the Kernel size does not get too much bigger.
If you think it is a small change, feel free to create a PR to update the [kernel config](https://github.com/flatcar-linux/coreos-overlay/blob/00fe4322a5a9bc52da44398fbd5e7130176f436e/sys-kernel/coreos-modules/files/commonconfig-5.8) .

**Comment by dongsupark** [comment]
Filed PR https://github.com/kinvolk/coreos-overlay/pull/691
