### ISSUE TITLE
New Package Request: [open-vm-tools 11.2.0]

### ISSUE THREAD

**Issue by johnwvmw** [flatcar/Flatcar#216]
**Package name and purpose**
The open-vm-tools 11.2.0 has been released.  Please update the open-vm-tools package(s) to 
- Package upstream repo: https://github.com/vmware/open-vm-tools/releases/tag/stable-11.2.0

**Impact of adding this package to the Flatcar OS image**
- [ x ] This package meets the requirements of Flatcar Container Linux’ new package guidelines: https://github.com/flatcar-linux/Flatcar/blob/master/adding-new-packages.md

This source update contains fixes for a couple of detected memory leaks, issues reported by Coverity and issues and pull requests submitted to https://github.com/vmware/open-vm-tools/.

The incremental changes that have gone into the 11.2.0 release are in the ChangeLog at https://github.com/vmware/open-vm-tools/blob/stable-11.2.0/open-vm-tools/ChangeLog

The package will increase the OS image by: [estimated] MBytes.

The package will potentially increase Flatcar’s attack surface:
- No anticipated changes here.  Memory leak corrections will reduce potential DOS issues.

**Benefits of adding this package to the Flatcar OS image**
The availability of open-vm-tools is essential for Flatcar containers to run on VMware hypervisors.

**Additional information**
[ Please add any information that does not fit into any of the above sections here ]

**Comment by dongsupark** [comment]
PR https://github.com/kinvolk/coreos-overlay/pull/681
