### ISSUE TITLE
Stable 2605.6.0 systemd log spam Failed to set up mount unit: Invalid argument

### ISSUE THREAD

**Issue by juliantaylor** [flatcar/Flatcar#218]
**Description**

In flatcar 2605.6.0 systemd spams the logs with following message:
Failed to set up mount unit: Invalid argument

The message was not present in that high rate in 2512.3.0

full message:

```
{"_UID":"0","_SOURCE_REALTIME_TIMESTAMP":"1603701224502087","_SELINUX_CONTEXT":"system_u:system_r:kernel_t:s0","CODE_FILE":"src/core/mount.c","_TRANSPORT":"journal","_PID":"1","_CAP_EFFECTIVE":"3fffffffff","_SYSTEMD_CGROUP":"/init.scope","__REALTIME_TIMESTAMP":"1603701224502791","_SYSTEMD_SLICE":"-.slice","_BOOT_ID":"5969ee0ff941417a816c90b60e0baf44","_SYSTEMD_UNIT":"init.scope","MESSAGE":"Failed to set up mount unit: Invalid argument","__CURSOR":"s=1098623013c143cc8025c60e308f1962;i=1e7f26;b=5969ee0ff941417a816c90b60e0baf44;m=375bef88d5;t=5b28ec9cff607;x=fd0a19da9429b7d4","_HOSTNAME":"kworker-fe-sandbox-iz1-bs003","SYSLOG_FACILITY":"3","CODE_LINE":"1681","PRIORITY":"4","_GID":"0","__MONOTONIC_TIMESTAMP":"237765626069","_EXE":"/usr/lib64/systemd/systemd","_COMM":"systemd","_MACHINE_ID":"35a1b0189c5d4ce09aeaef2fefad86f9","_CMDLINE":"/usr/lib/systemd/systemd --switched-root --system --deserialize 17","CODE_FUNC":"mount_setup_unit","SYSLOG_IDENTIFIER":"systemd"}
```

**Impact**

This produces several hundred gbs of logs in our ~250 node clusters

**Additional information**
The cause seems to be too long paths in mount units which systemd wants to create .mount files for which are too long.

E.g. some mounts on the system are longer than256 like:

`/var/lib/rkt/pods/run/25633007-13d0-41ad-8247-99e6755bfd2b/stage1/rootfs/opt/stage2/hyperkube/rootfs/var/lib/kubelet/pods/fd42b544-4b6d-493a-8d2f-6e8fb48f7e11/volumes/kubernetes.io~rbd/pvc-09736f94-fd6f-4a3d-9ff2-63af3ffa7fdd`

In systemd 246 rate limiting for these logs was added:
https://github.com/systemd/systemd/pull/15911

It may be good to cherry pick this patch to stable if the mount paths cannot be shortened.

**Comment by juliantaylor** [comment]
with flatcar 2605 and the newer systemd the message now looks like this:

```
Failed to generate valid unit name from path '/var/lib/rkt/pods/run/ef7f5aac-2a90-4213-9480-ac6d54e4a696/stage1/rootfs/opt/stage2/hyperkube/rootfs/var/lib/kubelet/pods/198aed74-22d4-4409-b531-ffd07c576362/volumes/kubernetes.io~secret/fluentd-platform-token-nf4hj', ignoring mount point: Invalid argument
```

and still occurs in pretty high frequency (about 15000 per hour from 60 hosts total with default systemd/journalctl settings)

**Comment by pothos** [comment]
Seems you are using `rkt` through `kubelet-wrapper` to run the kubelet. You can also use the binaries directly, see section 1.2 here: https://suraj.io/post/2021/01/kubeadm-flatcar/ for an example.

**Comment by pothos** [comment]
With a drop-in unit file (using prefix matching) one can lower the log level, example here for Docker: https://github.com/docker/for-linux/issues/679#issuecomment-1004955357

Closing it now (Edit: Also, we have systemd 249 which should have the log rate limit)
