### ISSUE TITLE
sda/sdb drives sometimes swap after update

### ISSUE THREAD

**Issue by mritalian** [flatcar/Flatcar#222]
Sometimes after updates, the sda drive (carrying the OS) and sdb (storing the data) end up swapped:  OS root is mounted from /dev/sdb, and my mnt-sdb1.mount unit fails.  On reboot, everything is ok.

**Impact**

This is a major problem; docker services depending on volume data from /mnt/sdb1 fail.

**Environment and steps to reproduce**

1.  Add a second drive to the VM, partition and format as ext4
2.  Create a suitable unit to mount it
3.  Wait for updates

**Expected behavior**

I would expect the secondary disk /dev/sdb to remain /dev/sdb, and the boot disk to remain /dev/sda consistently.

**Additional information**

This only started happening on flatcar.  It's not a 100% failure rate, or I'd be spending all day fixing it.  Probably like under 5%.  As an example: today an update was pushed.  So far only one of my hosts has failed this way.

On a bad boot:

Oct 28 16:45:20 localhost systemd-udevd[398]: Using default interface naming scheme 'v245'.
Oct 28 16:45:20 localhost kernel: sd 0:0:1:0: [sda] 1048576000 512-byte logical blocks: (537 GB/500 GiB)
Oct 28 16:45:20 localhost kernel: sd 0:0:0:0: [sdb] 17805312 512-byte logical blocks: (9.12 GB/8.49 GiB)
Oct 28 16:45:20 localhost kernel: sd 0:0:1:0: [sda] Write Protect is off
Oct 28 16:45:20 localhost kernel: sd 0:0:0:0: [sdb] Write Protect is off
Oct 28 16:45:20 localhost kernel: sd 0:0:1:0: [sda] Mode Sense: 31 00 00 00
Oct 28 16:45:20 localhost kernel: sd 0:0:0:0: [sdb] Mode Sense: 31 00 00 00
Oct 28 16:45:20 localhost kernel: sd 0:0:1:0: [sda] Cache data unavailable
Oct 28 16:45:20 localhost kernel: sd 0:0:0:0: [sdb] Cache data unavailable
Oct 28 16:45:20 localhost kernel: sd 0:0:1:0: [sd] Assuming drive cache: write through
Oct 28 16:45:20 localhost kernel: sd 0:0:0:0: [sdb] Assuming drive cache: write through
Oct 28 16:45:20 localhost kernel:  sdb: sdb1 sdb2 sdb3 sdb4 sdb6 sdb7 sdb9
Oct 28 16:45:20 localhost kernel:  sda: sda1
Oct 28 16:45:20 localhost kernel: sd 0:0:0:0: [sdb] Attached SCSI disk
Oct 28 16:45:20 localhost kernel: sd 0:0:1:0: [sda] Attached SCSI disk

Simply by rebooting the host:

Oct 28 17:13:27 localhost kernel: sd 0:0:0:0: [sda] 17805312 512-byte logical blocks: (9.12 GB/8.49 GiB)
Oct 28 17:13:27 localhost kernel: sd 0:0:1:0: [sdb] 1048576000 512-byte logical blocks: (537 GB/500 GiB)
Oct 28 17:13:27 localhost kernel: sd 0:0:0:0: [sda] Write Protect is off
Oct 28 17:13:27 localhost kernel: sd 0:0:1:0: [sdb] Write Protect is off
Oct 28 17:13:27 localhost kernel: sd 0:0:0:0: [sda] Mode Sense: 31 00 00 00
Oct 28 17:13:27 localhost kernel: sd 0:0:1:0: [sdb] Mode Sense: 31 00 00 00
Oct 28 17:13:27 localhost kernel: sd 0:0:0:0: [sda] Cache data unavailable
Oct 28 17:13:27 localhost kernel: sd 0:0:1:0: [sdb] Cache data unavailable
Oct 28 17:13:27 localhost kernel: sd 0:0:0:0: [sda] Assuming drive cache: write through
Oct 28 17:13:27 localhost kernel: sd 0:0:1:0: [sdb] Assuming drive cache: write through
Oct 28 17:13:27 localhost systemd-udevd[431]: Using default interface naming scheme 'v245'.
Oct 28 17:13:27 localhost kernel:  sda: sda1 sda2 sda3 sda4 sda6 sda7 sda9
Oct 28 17:13:27 localhost kernel:  sdb: sdb1
Oct 28 17:13:27 localhost kernel: sd 0:0:1:0: [sdb] Attached SCSI disk
Oct 28 17:13:27 localhost kernel: sd 0:0:0:0: [sda] Attached SCSI disk

**Comment by pothos** [comment]
I wouldn't recommend to use the sda or sdb names because they have a similar issue to using eth0 or eth1 instead of the persistent interface names. Luckily for disks it's easy to use symlinks, so I recommend to pick one scheme from `/dev/disk/by-*`.

**Comment by till** [comment]
@pothos Is there a way to retrieve these names at boot time? Or a programmatic way to use what you suggested? My systemd units currently depend on `/dev/sdbX`.

**Comment by jepio** [comment]
You can define the partition and filesystem labels when creating the partitions/filesystems through ignition. Also, depending on your env the disks may already have well defined paths. Check the examples here https://kinvolk.io/docs/flatcar-container-linux/latest/installing/bare-metal/booting-with-pxe/#installation or here https://kinvolk.io/docs/flatcar-container-linux/latest/installing/cloud/gcp/#additional-storage.

**Comment by ericb-summit** [comment]
The recipe is something like this.  At first boot, the disk order is correct, so you can rely on that to create an additional disk.  Change the `device` as needed.  And put a unique label for the partition.  This is all terraform, but pretty obvious how to translate this to ignition:

```
data "ignition_disk" "additional_disk" {
  device = "/dev/sdb" 
  wipe_table = false
  partition {
    number = 1
    start = 0
    size = 0
    label = "APP_DATA"
  }
}
```

Don't forget to initialize the partition

```
data "ignition_filesystem" "additional_disk" {
  mount {
      device = "/dev/disk/by-partlabel/APP_DATA"
      format = "ext4"
  }
}
```

Then you need an ignition unit for the disk mount, here is `mount.tpl` template:

```
[Unit]
Description = ${description}

[Mount]
What=${dev}
Where=${where}
Type=ext4

[Install]
WantedBy = multi-user.target
```
And the unit itself:
```
data "template_file" "additional_disk" {
  template  = file("${path.module}/files/mount.tpl")
  vars      = {
    dev = "/dev/disk/by-partlabel/APP_DATA"
    where = "/mnt/somewhere"
    description = "Whatever"
  }
}
```

A mount based on partlabel is 100% solid no matter how your disk or partition configuration changes.

**Comment by pothos** [comment]
Thanks for the good reply, I've also pointed this out in the docs now: https://github.com/flatcar-linux/flatcar-docs/pull/252

**Comment by mritalian** [comment]
Okay so, 1 year later, and this "issue" comes back to haunt me.  Originally the problem was on reboot and I agree dealing with arbitrary aliases like sda, sdb instead of immutables like labels is a bad idea.  Sorry for the long post, just want to be sure it's explained properly.

But... I now have this issue on firstboot.  What happens is we create a new vsphere VM from an OVA deployment; within the VM configuration, the first disk (as specified unit_number=0 in terraform, and as seen in the VM settings) is a virgin disk to be used for system, followed by other disks used for persistent storage (which are almost always already partitioned).  At firstboot, flatcar will initialize the system disk as it is virgin.  But sometimes, the system disk is no longer the first disk in order.  On firstboot, this is a Big Problem.

**Good failure:** Only system disk is virgin, but it doesn't come up as sda.  flatcar thankfully refuses to clobber non-ephemeral partition.  Simple reboot and firstboot completes ok.

**Bad failure:** Disks are all virgin and are initialized in wrong order.  System is provsioned in persistent store, data in ephemeral store.  When VM is recreated, OS refuses to boot, persistent data is lost.

Going back to the original issue.  I understand aliases like sda, sdb, etc.. are not safe.  But it would be nice to understand why it is non-deterministic, on the exact same type of VM on the same hypervisor on the same host, etc etc..   Also, so you're aware, I see no terraform / vsphere construct to mount by disk uuid ( terraform doesn't know have visibility into it ).  I will see if maybe I can use `/dev/disk/by-diskseq`.

I would say this happens like 1/5 times so is easily reproducible. 

Thanks

**Comment by pothos** [comment]
Yeah, my hope is that we get a way to refer to a disk in relation to something we know about this disk, e.g., if the EFI partition is on it. That would be something udev could set up as symlink. Another hope I have is to be able to express something like "not the OS disk" and similar in Ignition.

For the problem you describe: Retrying provisioning in this case is a bit ugly but that's basically the workaround.

**Comment by mritalian** [comment]
Ok.  `/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:XX:0` seems consistent, in that I see scsi-0:0:0:0 sometimes points to sda, sometimes sdb.  This is workable.  Just remember that [vmware uses id 7 for the controller](https://communities.vmware.com/t5/ESXi-Discussions/SCSI-0-7/td-p/1231627)

Since the non-deterministic behaviour comes from god knows where, and there's a simple consistent workaround I think we can just agree to never use /dev/sdX, ever.

**Comment by mritalian** [comment]
I worry a bit about how fragile `pci-0000:03:00.0-scsi-0:0:XX:0` is, especially the PCI ID, but as it's in ignition only, it would fail at firstboot, and always work thereafter.  So any future failure will not be in steady state but at deploy time.  I can live with that.

**Comment by pothos** [comment]
I think it's the kernel discovering hardware in parallel like it also does for network interfaces. For network interfaces the predictable naming scheme in udev fixes the problem. Using the by-path trick makes sense if you know your hardware setup.
