### ISSUE TITLE
AWS AMI: ami-0312c8ef72c898c8 in us-west-2 fails to boot

### ISSUE THREAD

**Issue by endzyme** [flatcar/Flatcar#223]
When running an AMI from us-west-2 using Flatcar-stable-2605.7.0 AMI (ID: ami-0312c8ef72c898c8e) the instance never boots. I've attached a screenshot of the host in AWS for the error. 
![image](https://user-images.githubusercontent.com/1903525/97517130-4593d780-195a-11eb-829d-64c29f1df678.png)

The error is `Wrong EFI loader signature`

**Impact**

Can't deploy instances with this AMI

**Environment and steps to reproduce**

1. Find the AMI in the UI
2. Launch an instance with all the default settings, using your own SSH keypair
3. Download a screenshot of the failed instance

**Expected behavior**

Ability to deploy instances

**Comment by vbatts** [comment]
Please try again with release 2661.0.0 or newer.

**Comment by vbatts** [comment]
(also, thanks for reporting the issue :smile_cat: )

**Comment by endzyme** [comment]
Using Flatcar-alpha-2661.0.0-hvm (075585003325/Flatcar-alpha-2661.0.0-hvm & ID: ami-0c7fa97342e18ae64) in us-east-1 I get the same error: see screenshot -- I'm using a t3.large in my scenario. Any clues as to why this might happen?

![image](https://user-images.githubusercontent.com/1903525/97518577-19c62100-195d-11eb-8cbe-532f271352e7.png)

**Comment by endzyme** [comment]
Ok - super interesting but it seems like it's some weirdness either with my config or with Amazon. I was able to book a server with no userdata, but I still saw the Wrong EFI loader signature message, it just boots past that in a few seconds. Not clear why this is inconsistent but likely something on my end. I'll keep digging into it.

**Comment by endzyme** [comment]
Going to close this and reopen until I can reliably reproduce.

**Comment by endzyme** [comment]
Found the problem - issue was definitely on my side and was two fold. One was that a new ignition policy did allow access to an s3 object, which appears to then just rerun ignition over and over (causing what appears to be a hung system). My initial issue is that this `Wrong EFI loader signature` is a red herring. It doesn't actually indicate a problem at all, and thus when I was testing without any ignition settings, I was not waiting long enough to get past this portion of the boot. Sorry for the trouble and thanks again!

**Comment by vbatts** [comment]
@endzyme nice find. Glad you found the culprit!
