### ISSUE TITLE
Document available settings for /etc/flatcar/update.conf file

### ISSUE THREAD

**Issue by invidian** [flatcar/Flatcar#224]
**Current situation**
Values in `/etc/flatcar/update.conf` file like `GROUP` or `SERVER` are currently not well documented and easily accesible.

**Ideal future situation**

Flatcar documentation website should have a page dedicated for updates configuration.

**Additional information**

As far as I see, searching for `GetConfValue` in https://github.com/flatcar-linux/update_engine/blob/ace0de561ee30d9665d82167ad493043a035e4af/src/update_engine/omaha_request_params.cc allows to find available options.

**Comment by vbatts** [comment]
opened https://github.com/kinvolk/flatcar-docs/pull/125
