### ISSUE TITLE
Membership errors in "Configuration Specification" Documentation caused by wrong indentation

### ISSUE THREAD

**Issue by hehongbo** [flatcar/Flatcar#23]
Hello team,
I'm referencing Flatcar Linux's documentation and I notice there're lots of membership errors in the documentation of [Configuration Specification](https://docs.flatcar-linux.org/container-linux-config-transpiler/doc/configuration/). 

Things like:
* `config` object should be a child of `ignition` object, not a sibling of it.
* under `config` object, `source` string and `verification` object should be children of `append` list, not siblings of it.
* under `verification` object inside `append` list, `function` string and `sum` string should be children of `hash` object, not siblings of it.

These errors seem to occur **every 2 levels**, Which I think were caused by indent settings in their markdown source file when migrating from [CoreOS's](https://coreos.com/os/docs/latest/configuration.html) documentation.

I was about to create a pull request to fix these errors but realized [there's no corresponding repository of documentation](https://github.com/flatcar-linux/Flatcar/issues/22) exists in GitHub as CoreOS does.
As RedHat finally decided to announce CoreOS Container Linux's [EOL](https://coreos.com/os/eol/), more users will consider migrating to Flatcar Linux, so it's great (or vital) to create a set of complete documentation of every component of Container Linux's documentation, as we don't know after it's EOL whether we can still access these resources from CoreOS's website.

**Comment by pothos** [comment]
Thanks for reporting!
Yes, the markdown files followed different (non-)standards and that is fixed now.

The repositories will be moved to the `flatcar-linux` GitHub organization so that PRs can be made.
