### ISSUE TITLE
[ignition] Add luks support

### ISSUE THREAD

**Issue by orbatschow** [flatcar/Flatcar#243]
# Feature Request #

## Environment ##

What hardware/cloud provider/hypervisor is being used to run Ignition?

Bare-metal

## Desired Feature ##

There doesn't seem to be a way to decrypt already existing LUKS block devices with ignition, this could be useful for scenarios where data decryption is needed in order to mount drives properly.

**Comment by shosti** [comment]
This looks like it’s been implemented upstream: https://github.com/coreos/ignition/pull/960

**Comment by jepio** [comment]
Indeed, its avaialable in upstream ignition v3 and @tormath1 has been working on getting this merged, so I would close this issue and track in https://github.com/flatcar-linux/Flatcar/issues/387 instead.
