### ISSUE TITLE
Support to write an image to run on Firecracker 

### ISSUE THREAD

**Issue by mazzy89** [flatcar/Flatcar#247]
**Current situation**

At the moment the script supports installing Flatcar OS only on device block

**Impact**

I would like to create rootfs image and use for instance for Firecracker VM https://github.com/firecracker-microvm/firecracker/blob/master/docs/rootfs-and-kernel-setup.md

**Ideal future situation**

**Implementation options**

Tune the condition here https://github.com/flatcar-linux/init/blob/flatcar-master/bin/flatcar-install#L360

**Additional information**

**Comment by t-lo** [comment]
Great work folks! I've captured all necessary steps in a gist: https://gist.github.com/t-lo/796057ca6383dbf00ddc9972f62d1a77
