### ISSUE TITLE
were these "Flatcar" images in GovCloud actually pushed by Flatcar?

### ISSUE THREAD

**Issue by weisjohn** [flatcar/Flatcar#257]
**Description**

Flatcar has a list of AMIs https://docs.flatcar-linux.org/os/booting-on-ec2/#choosing-a-channel
and there appear to be images in GovCloud West and East, but those AMIs are *not* listed on the site.

Those AMI names are `Flatcar-stable-2345.3.1-hvm` which are listed as Stable on Flatcar's site: https://www.flatcar-linux.org/releases/#stable-release

...but how do I actually trust or validate that image?

**Impact**

I can't move forward with Flatcar.

**Environment and steps to reproduce**

there is a Flatcar image in `us-gov-west-1`:
```bash
images=$(aws ec2 describe-images --region us-gov-west-1 --output json \
  --owners "775307060209" \
  --query "sort_by(Images, &CreationDate)[*].[CreationDate,Name,ImageId]")
ami=$(echo "$images" | jq -r '.[-1][2]')
echo $ami
# ami-07d8bb321f46b40dc
```

there is a Flatcar image in `us-gov-east-1`:
```bash
images=$(aws ec2 describe-images --region us-gov-east-1 --output json \
  --owners "775307060209" \
  --query "sort_by(Images, &CreationDate)[*].[CreationDate,Name,ImageId]")
ami=$(echo "$images" | jq -r '.[-1][2]')
echo $ami
# ami-09c5b2a64dcabf07e
```

 - Is that Owner ID correct?
 - And is that AMI actually produced by the project?

**Expected behavior**
I believe the project would list the AMIs in GovCloud.

**Additional information**

**Comment by jepio** [comment]
We don't publish images to GovCloud, if anyone wants them they'll need to upload them themselves.
