### ISSUE TITLE
Mounting Issue

### ISSUE THREAD

**Issue by KillahB33** [flatcar/Flatcar#258]
**Description**

So I am mounting drives from nfs unraid share. All of them are fine except for one mount that keeps unmounting.
I can remount it with a umount and then mount but it usually breaks a few hours later, I am restarting now but I am not sure how I go about diagnosing this and fixing it.
One not is that I am a transition from CoreOS, so I ran that mount fix that was posted a while back to get my mounts back.

**Impact**

Drive is unmounting

**Environment and steps to reproduce**

1. **Set-up**: Flatcar is running on a VM in ESXi, unraid drives are mounted, multiple containers referencing the drives but this is the only one that goes down.
2. **Task**: Honestly not sure, the only reason I figure it out is I am guessing LazyLibrarian is checking the drive the the container goes down, then I can't bring it back up cause that space isn't mounted.
3. **Action(s)**: I am guessing the drive is being used then unmounts, not seeing any errors on unraid either which is why I am 
4. **Error**: I get stale error if I just try to mount it, no errors if I do umount then mount

**Expected behavior**
Mounts stay mounted

**Comment by margamanterola** [comment]
Hey there! Thanks for using Flatcar and reporting this issue. Are you still experiencing it?

If you are, please note that it's not clear this is really a Flatcar issue. It sounds more like some daemon that you have running on your instance is unmounting the drive. Is there a reason you think Flatcar is at fault?

I'd suggest you use `journalctl` to look at the journal of the instance and see if you can figure out what's triggering the drive getting unmounted.

Cheers.

**Comment by KillahB33** [comment]
I switched to centOS cause I never got word back.

The reason I believe it was flatcar was because there was an issue with how flatcar did mounting after moving over from CoreOS and an updated happened that broke mounting, and it wasn't an issue until I switched from CoreOS to flatcar.

**Comment by margamanterola** [comment]
I see. Sad to hear that you went with CentOS. 

It's likely that the difference was due to either a newer kernel version or a newer systemd version, with different defaults.

I'm going to close this bug now, as we don't have enough information to do anything about it. Thanks!
