### ISSUE TITLE
Feedback from following running Flatcar on GCE

### ISSUE THREAD

**Issue by invidian** [flatcar/Flatcar#261]
While reproducing some issue on GCE, I had to create Flatcar instance there. I followed https://docs.flatcar-linux.org/os/booting-on-google-compute-engine/ and I found some areas for improvements:
- "Uploading an image" section could mention, that it will create the bucket for itself
- The uploader could create temporary bucket, create an image and then remove the bucket, simplifying the whole process
- `gcloud compute instances create flatcar1 flatcar2 flatcar3 --image-project flatcar-cloud --image-family flatcar-stable --zone us-central1-a --machine-type n1-standard-1 --metadata-from-file user-data=config.ign` command mentioned in the document does not play well with the upload image we recommend. When running that, I get following error:
```
$ gcloud compute instances create flatcar1 --image-project lokomotive-testing-240807 --image-family flatcar-stable --zone europe-west3-a --machine-type n1-standard-1
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - The resource 'projects/lokomotive-testing-240807/global/images/family/flatcar-stable' was not found
```

even though the image with such family exists in the project:
```
$ gcloud compute images list | grep -E '(NAME|flatcar)'
NAME                                                  PROJECT                    FAMILY                            DEPRECATED  STATUS
flatcar-stable                                        lokomotive-testing-240807  flarcar-linux                                 READY
```

This command failed as well:
```
$ gcloud compute instances create flatcar1 --image-project lokomotive-testing-240807 --image-family flatcar-linux --zone europe-west3-a --machine-type n1-standard-1
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - The resource 'projects/lokomotive-testing-240807/global/images/family/flatcar-linux' was not found
```

The command I used which worked:
```
gcloud compute instances create flatcar1 --image-project lokomotive-testing-240807 --image flatcar-stable --zone europe-west3-a --machine-type n1-standard-1
```

**Comment by margamanterola** [comment]
The page has been recently updated. We now have official images, so the uploading part is not the recommended way anymore, the commands to use the official images work out of the box.
