### ISSUE TITLE
auto-update mechanism doesn't explain the 2 reboots trick

### ISSUE THREAD

**Issue by rata** [flatcar/Flatcar#267]
Hi!

The other day I had to update flatcar and I asked why when running:

```
# update_engine_client -update
I0522 09:34:02.063482 86616 update_engine_client.cc:247] Initiating update check and install.
I0522 09:34:02.064754 86616 update_engine_client.cc:252] Waiting for update to complete.
LAST_CHECKED_TIME=1556272591
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_UPDATED_NEED_REBOOT
NEW_VERSION=2079.3.2
NEW_SIZE=399568805
I0522 09:34:07.145684 86616 update_engine_client.cc:194] Update succeeded -- reboot needed.
 # uname -a
Linux production-alpha-worker-0 4.19.25-flatcar kinvolk/flatcar-docs#1 SMP Mon Mar 11 22:05:05 -00 2019 x86_64 AMD EPYC 7401P 24-Core Processor AuthenticAMD GNU/Linux
```

It didn't show the latest update (2079.4.0). I was then explained that I need to reboot, that update will be installed, and then the latest update will be downloaded and if I reboot again, I'll be running the latest Flatcar Linux version.

I asked this after reading the docs, that I think don't mention it at all. It would be nice to explain this, I think.

What do you think?

**Comment by dongsupark** [comment]
TBH I have not thought about explaining it in docs, because that's basically how update-engine works. Probably its behavior was inherited from Container Linux, also from ChromeOS.
Anyway if you think we should explain more about that, feel free to add it.
Probably it should be added to https://docs.flatcar-linux.org/os/update-strategies/.

**Comment by rata** [comment]
@dongsupark ohh, makes sense. I've checked and they had an issue reported about this and they wanted to fix the update_engine_client to work like this, but they changed focus to fedora coreOS. See here: https://github.com/coreos/bugs/issues/1392

They even propose a better work around that 2 reboots here: https://github.com/coreos/bugs/issues/1392#issuecomment-224707301.

So, we may want to fix this in update_engine_client to take more ownsership of it, or even document some of the work arounds. So, I think this can be solved by two different ways:
 * Document the behaviour and work arounds
 * Change update_engine_client to not behave like this

It's not a priority for me right now, but I think it will be nice if we eventually fix this. Is it okay if I leave it open? Or how should we track these issues that are not a priority but, at least IMHO, nice to fix?

**Comment by invidian** [comment]
Nice workaround, that's good to know :smile:

**Comment by dongsupark** [comment]
I would say, let's document the [workaround](https://github.com/coreos/bugs/issues/1392#issuecomment-224707301).
Fixing update-engine would be not bad, but I suppose most users can live with the workaround.
