### ISSUE TITLE
docs: Rework Quickstart Guide content and most config examples

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#275]
**Current situation**
The Quickstart Guide is not very useful but is supposed to help users get familiar with Flatcar concepts and interactions. I would expect it to contain more explanations as done in https://kinvolk.io/docs/flatcar-container-linux/2605.7.0/reference/migrating-to-clcs/provisioning/ and a use case that is more realistic than running an etcd cluster.

**Impact**

**Ideal future situation**
Maybe choose the QEMU images as example scenario, and how to deploy an NGINX docker container

**Implementation options**

**Additional information**

**Comment by margamanterola** [comment]
100% agree with this. The "quickstart" is a terrible document full of pre-required knowledge and very cluster specific. Not a quickstart at all.

**Comment by pothos** [comment]
PR for the very first introduction example: https://github.com/flatcar-linux/flatcar-docs/pull/217

The provider "quickstart" sections need to be reworked still.

**Comment by pothos** [comment]
Done for for the provider sections: https://github.com/flatcar-linux/flatcar-docs/pull/222
