### ISSUE TITLE
docs: Image not rendered

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#276]
https://kinvolk.io/docs/flatcar-container-linux/2605.7.0/reference/migrating-to-clcs/provisioning/
does not show 
https://docs.flatcar-linux.org/os/img/ct-workflow.svg
as done in in https://docs.flatcar-linux.org/os/provisioning/ but only the _alt_ text.

**Comment by margamanterola** [comment]
I fixed this in my latest submission to the docs.
