### ISSUE TITLE
docs: Include Ignition specification

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#281]
**Current situation**
The Ignition docs like the specification are available under the original https://coreos.com/ignition/docs/latest/ location but not under https://kinvolk.io/docs/flatcar-container-linux/latest/

**Impact**
The user needs to know that the specification can be found under https://github.com/kinvolk/ignition/tree/flatcar-master/doc as markdown files

**Ideal future situation**
A rendered version is available under https://kinvolk.io/docs/flatcar-container-linux/latest/

**Implementation options**
Like container-linux-config-transpiler this can be a subproject but the URL would clash with the existing https://kinvolk.io/docs/flatcar-container-linux/latest/ignition/ coming from https://github.com/kinvolk/flatcar-docs/tree/main/docs/ignition

**Additional information**

**Comment by tormath1** [comment]
It's now available here: https://www.flatcar.org/docs/latest/provisioning/ignition/specification/
