### ISSUE TITLE
New Package Request: net-fs/samba-4.12.9-r1

### ISSUE THREAD

**Issue by tormath1** [flatcar/Flatcar#288]
**Package name and purpose**

Hi, `net-fs/samba` is already present on Flatcar with the version: `4.11.13-r1` ([ebuild](https://github.com/kinvolk/coreos-overlay/blob/9e7732bfdde5ef35013af2e75c6a7e461e5ac19d/net-fs/samba/samba-4.11.13-r1.ebuild)). The goal of this issue is to track its update to the latest stable version on Gentoo: `4.12.9-r1`.

for Flatcar:

- [Gentoo ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-fs/samba/samba-4.12.9-r1.ebuild)

**Impact of adding this package to the Flatcar OS image**  

- The package improves on the following core values:
  - [x] Secure by default
  - [x] Always up to date
  - [ ] Improve container experience
  - [ ] Operate at scale / automation / telemetry

The package will increase the image size by: `TBD` MBytes.

**Comment by tormath1** [comment]
I identified three new dependencies for this package:

- [dev-perl/Parse-Yapp](https://packages.gentoo.org/packages/dev-perl/Parse-Yapp)
- [dev-libs/icu](https://packages.gentoo.org/packages/dev-libs/icu)
- [sys-libs/liburing](https://packages.gentoo.org/packages/sys-libs/liburing)

This missing dependencies have been added to my fork of `portage-stable`. PR will come in time with the `samba` one.

**Comment by t-lo** [comment]
Good work with the missing dependencies! It's a good idea to bundle everything into a single PR.

**Comment by dongsupark** [comment]
Thanks for the work.
Samba 4.12.9 is included in Alpha 2783.0.0, and will be available also in other channels.

One remaining issue is that the new dependency libs like icu take more space in production images.
I am trying to figure out how we can minimize the deps.
Will soon create a new issue about that.
