### ISSUE TITLE
Stabilise current Alpha (2411.0.0) and Edge (2411.99.0) releases 

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#29]
Users encountered a number of failure modes in the current Alpha (2411.0.0) and Edge (2411.99.0) releases. This epic keeps track of all individual failure modes to be fixed.

Child issues:
- #24 systemd-hostnamed unit failed
- #26 docker can't start containers in 2411.0.0

**Comment by dongsupark** [comment]
Alpha 2430.0.0 and Edge 2430.99.0 were released with bug fixes.
So it is done.
