### ISSUE TITLE
2605.9.0 Breaks iSCSI - error loading shared libraries

### ISSUE THREAD

**Issue by matveybrant** [flatcar/Flatcar#293]
**Description**

After automatic update to 2605.9.0 from 2605.8.0, our solidfire pvcs will not mount, journalctl has following error:

iscsi_util.go:301] iscsi: could not read iface default error: iscsiadm: error while loading shared libraries: libisns.so.0: cannot open shared object file: No such file

**Impact**

Took some critical workloads offline as they could not mount their pvcs, had to roll back to previous versions

**Environment and steps to reproduce**

1. **Set-up**: Flatcar on bare metal
2. **Task**: Mount PVC (provisioned via Trident on SolidFire)
3. **Action(s)**: [ sequence of actions that triggered the bug, see example below ]
  a. Requested start of a new pod
  b. Container remains in ContainerCreating state 
4. **Error**: [describe the error that was triggered]
iscsi_util.go:301] iscsi: could not read iface default error: iscsiadm: error while loading shared libraries: libisns.so.0: cannot open shared object file: No such file

**Expected behavior**
Mount the volume and start the container

**Additional information**
We did migrate to flatcar from containerlinux via in-place upgrade earlier this year

so files seem to be present, not sure if these are the right locations:

ls /lib | grep libisn
libisns.so
libisns.so.0

ls /lib64/ | grep libisn
libisns.so
libisns.so.0

**Comment by surajssd** [comment]
Similar to https://github.com/kinvolk/Flatcar/issues/280

**Comment by pothos** [comment]
Can you run the `iscsiadm` binary on the host without this error? It sounds like the linked issue, which is due to mapping some host binaries into the container but in a broken way, can you check if this is the case?

**Comment by vbatts** [comment]
This may need an issue crosslinked with trident/SolidFire, where they are dynamic-linking to something on the host. This sounds like something that may need to be static-linked, or run in a container entirely

**Comment by t-lo** [comment]
I've validated the host `iscsiadm` runs successfully in stable-2605.9.0, i.e. there is no library issue with the command line tool shipped with Flatcar Linux. Is there a way for trident/SolidFire to use host binaries?

**Comment by matveybrant** [comment]
Hey folks, thanks for the responses.  After reading up a bit more it does indeed appear to be due to how our kubelet container is mounting iscsiadm (I believe trident/SF just uses kubelet's iscsadm).  We deployed this cluster a while back with poseidon/typhoon before we changed from container linux to flatcar, and we are still a few versions behind with k8s.  Is there a new best way to run iscsiadm in kubelet, or does the newest container no longer mount the host version or something?  We're running hyperkube in rkt on the hosts.  I can likely use the workaround linked in #280, but it would be good to know what the best practice is for this.  I also wanted to make sure this group was aware that this was a breaking change for us, I would guess we are not the only ones mounting iscsiadm in this way.

Just checked, and in fact it does look like typhoon is still mounting iscsiadm from the host: 
https://github.com/poseidon/typhoon/blob/a8b8a9b45462f0235c70c5a8d196c27ffc06fb20/bare-metal/flatcar-linux/kubernetes/cl/worker.yaml#L67

**Comment by pothos** [comment]
I think it's the wrong approach to copy things into the container even if the libraries were copied. The best way would be to either have the container have its own tools installed, or, leave the container and execute the binary in the host mount namespace (assuming `--privileged --pid host` you can invoke `nsenter -a -t 1` to leave the container). If the host binary should be copied, that works best if it is statically linked. This is not the case for Flatcar, so you have to calculate which libraries are needed through `ldd $(which iscsiadm) | grep -o /lib'[^ ]*' | sort -u` and hope it works.

**Comment by pothos** [comment]
In your linked example where indeed `--privileged --pid host` is used I think it would work to use a `iscsiadm` wrapper script in the container (but I don't know the details involved, just an idea):
```
#!/bin/sh
exec nsenter -a -t 1 iscsiadm "$@"
```

**Comment by dongsupark** [comment]
FYI a bit of background why iscsiadm was being used like that: https://github.com/poseidon/typhoon/issues/907#issuecomment-743024988
