### ISSUE TITLE
mdadm: migrate cron.weekly to systemd.timer

### ISSUE THREAD

**Issue by vbatts** [flatcar/Flatcar#295]
**Current situation**
in /etc, there is cron.weekly/mdadm, but it'll never get run. Switch it to systemd.timer instead

**Impact**
small surface of impact, but if mdadm is used, then `/usr/sbin/checkarray --cron --all --idle --quiet` isn't being run.

**Implementation options**
as a hack ... we might could land daily weekly and monthly timers, that just generically run whatever is in /etc/cron.{daily,weekly,monthly}/ folders

**Comment by pothos** [comment]
Ah, there is https://github.com/systemd-cron/systemd-cron but I didn't realize that it was separate from systemd and thus missing.

**Comment by t-lo** [comment]
So the task is to add a systemd timer unit to the [mdadm package](https://github.com/kinvolk/coreos-overlay/tree/main/sys-fs/mdadm) and to remove the cron file from that package in the process.

Sounds like a good first issue!

**Comment by aniruddha2000** [comment]
@t-lo Do I need to add the systemd timer in the [init](https://github.com/kinvolk/init/tree/flatcar-master/systemd/system) repo?

**Comment by pothos** [comment]
It should be part of the mdadm package itself, in the `files` folder.

**Comment by aniruddha2000** [comment]
Added mdadm(timer, service) in the [files](https://github.com/aniruddha2000/coreos-overlay/tree/aniruddha/add-mdadm-timer/sys-fs/mdadm/files) . I need a clarification that do I have to use [systemd_dounit](https://devmanual.gentoo.org/eclass-reference/systemd.eclass/index.html) to install the timer unit to the package and remove the mdadm.weekly file and it's reference in the ebuild file to remove the cron?

**Comment by pothos** [comment]
The timer unit needs an install section to be able to enable it:
```
[Install]
WantedBy=timers.target
```
Yes, `systemd_dounit` sounds good and removing the installation of the .weekly file.

**Comment by pothos** [comment]
Thanks @aniruddha2000 https://github.com/kinvolk/coreos-overlay/pull/1244 is merged
