### ISSUE TITLE
failed to download the sdk due to gpg error: openpgp: signature made by unknown entity

### ISSUE THREAD

**Issue by binchenX** [flatcar/Flatcar#299]
**Description**

[ 1 paragraph concisely describing the bug ]

I was following the [instruction](https://docs.flatcar-linux.org/os/sdk-modifying-coreos/) trying to download the sdk but failed due to gpg issue.

**Impact**

[ 1 sentence detailing the impact this bug is creating for you ]

Can't download the sdk and play around

**Environment and steps to reproduce**

1. **Set-up**: [ describe the environment Flatcar/Lokomotive/Nebraska etc was running in when encountering the bug; Platform etc. ]

➜  flatcar-linux gpg --keyserver keyserver.ubuntu.com --receive-keys 84C8E771C0DF83DFBFCAAAF03ADA89DEC2507883 
gpg: key E52F0DB391453C45: public key "Flatcar Application Signing Key <buildbot@flatcar-linux.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
➜  sdk ../cork create
2020-12-16T06:45:09Z cork: Detecting SDK version
2020-12-16T06:45:12Z cork: Found SDK version 2705.0.0 from remote repo
2020-12-16T06:45:12Z cork: Downloading SDK version 2705.0.0
2020-12-16T06:45:13Z cork: Download failed: openpgp: signature made by unknown entity: /home/nk/github.com/flatcar-linux/sdk/.cache/sdks/flatcar-sdk-amd64-2705.0.0.tar.bz2

2. **Task**: [ describe the task performing when encountering the bug ]
3. **Action(s)**: [ sequence of actions that triggered the bug, see example below ]
  a. [ requested the start of a new pod or container ]
  b. [ container image downloaded ]
4. **Error**: [describe the error that was triggered]
2020-12-16T06:45:13Z cork: Download failed: openpgp: signature made by unknown entity: /home/nk/github.com/flatcar-linux/sdk/.cache/sdks/flatcar-sdk-amd64-2705.0.0.tar.bz2
**Expected behavior**
[ describe what you expected to happen at 4. above but instead got an error ]
Be able to download the sdk and compile the image
**Additional information**
Please add any information here that does not fit the above format.

**Comment by dongsupark** [comment]
Thanks for creating the issue.

Recently the original [Flatcar docs](https://docs.flatcar-linux.org/os/sdk-modifying-coreos/) was moved to https://kinvolk.io/docs/.
So the URL you are referring to is outdated. The up-to-date version is actually on https://kinvolk.io/docs/flatcar-container-linux/latest/reference/developer-guides/sdk-modifying-flatcar/. 
And recently mantle [v0.15.2](https://github.com/kinvolk/mantle/releases/tag/v0.15.2) was released including bug fixes around cork, so please use the new version.

Can you please try again to run commands as described in the new docs?
```
curl -L -o cork https://github.com/kinvolk/mantle/releases/download/v0.15.2/cork-0.15.2-amd64
curl -L -o cork.sig https://github.com/kinvolk/mantle/releases/download/v0.15.2/cork-0.15.2-amd64.sig
curl -LO https://www.flatcar-linux.org/security/image-signing-key/Flatcar_Image_Signing_Key.asc
gpg --import Flatcar_Image_Signing_Key.asc
rm Flatcar_Image_Signing_Key.asc
gpg --verify cork.sig cork
chmod +x cork
mkdir -p ~/.local/bin
mv cork ~/.local/bin
export PATH=$PATH:$HOME/.local/bin
mkdir flatcar-sdk
cd flatcar-sdk
cork create
cork enter
```

**Comment by binchenX** [comment]
Thanks for your prompt response and with the new instruction I'm now be able to download the sdk. (I'm in the sdk unpack stage so I would consider the download is successful).
