### ISSUE TITLE
Release a mantle version

### ISSUE THREAD

**Issue by iaguis** [flatcar/Flatcar#3]
We have some changes in [mantle](https://github.com/flatcar-linux/mantle) diverging from upstream but we haven't released any version yet so people can, for example, download cork and set up Flatcar's SDK.

**Comment by dongsupark** [comment]
I created a new version of mantle: https://github.com/flatcar-linux/mantle/releases/tag/v0.11.2
So I suppose this issue can be closed.
(I'm not able to close it on my own)

**Comment by iaguis** [comment]
If it works let's close it!
