### ISSUE TITLE
Developer board specified in Developmental Container is not accessible 

### ISSUE THREAD

**Issue by riccardo32** [flatcar/Flatcar#300]
**Description**

the PORTAGE_BINHOST in the make.conf of Flatcar Developmental container specified is not accessible for latest Flatcar release  2605.9.0
uses
PORTAGE_BINHOST="https://storage.googleapis.com/flatcar-jenkins/boards/development/2605.9.0/pkgs/
￼https://storage.googleapis.com/flatcar-jenkins/boards/${BOARD}/${FLATCAR_VERSION_ID}/toolchain/"

**Impact**

Can not compile custom kernel modules as it is unable to get sources for the kernel

**Environment and steps to reproduce**

As per [ Building custom kernel modules instructions](https://docs.flatcar-linux.org/os/kernel-modules/)
the emerge -gKv coreos-sources

# emerge -gKv coreos-sources
is unable to access binhost_packages

```

Step 4/6 : RUN emerge -gKv coreos-sources  > /dev/null
 ---> Running in cc5ea26c9f2a
!!! Error fetching binhost package info from 'https://storage.googleapis.com/flatcar-jenkins/developer/boards/amd64-usr/2605.9.0/pkgs'
!!! HTTP Error 404: Not Found
!!! Error fetching binhost package info from 'https://storage.googleapis.com/flatcar-jenkins/developer/boards/amd64-usr/2605.9.0/toolchain'
!!! HTTP Error 404: Not Found
Unable to unshare: EPERM
Unable to unshare: EPERM

```
**Additional information**
Workaround is to edit the file and not use developer URL i.e.
PORTAGE_BINHOST=\"https://storage.googleapis.com/flatcar-jenkins/boards/amd64-usr/2605.9.0/pkgs
'https://storage.googleapis.com/flatcar-jenkins/boards/amd64-usr/2605.9.0/toolchain"

**Comment by pothos** [comment]
Hello,
thanks for reporting, this seems to be https://github.com/kinvolk/Flatcar/issues/298 which is fixed in the release done a few hours ago.

**Comment by riccardo32** [comment]
Apologies mustve missed that one.. thanks

**Comment by pothos** [comment]
No problem, thanks for reporting
