### ISSUE TITLE
Upgrade Package Request: systemd 247

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#301]
**Package name and purpose**  
systemd-247 was released last month. Flatcar Container Linux currently ships v246. This is a tracking issue to upgrade the systemd 

Package upstream repo & tags: 

- https://github.com/systemd/systemd
- https://github.com/systemd/systemd/releases/tag/v247
- https://github.com/systemd/systemd-stable/releases/tag/v247.2

Gentoo ebuild: 
- https://github.com/gentoo/gentoo/tree/master/sys-apps/systemd

**Comment by dongsupark** [comment]
systemd v247 is now available in Stable 2765.2.0, Beta 2765.1.0, and Alpha >= 2765.0.0.
