### ISSUE TITLE
iPXE booted tmpfs raspberry 8gb pi 4 has 50% root fs

### ISSUE THREAD

**Issue by matti** [flatcar/Flatcar#308]
Docs say that:

>rootfstype=btrfs: Use btrfs in RAM for the writable root filesystem. The filesystem will consume more RAM as it grows, up to a max of 50%. The limit isn’t currently configurable.

but when btrfs is not in use, then it looks liek root is still 50%

```
bash-4.3# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        3.3G     0  3.3G   0% /dev
tmpfs           3.5G     0  3.5G   0% /dev/shm
tmpfs           1.4G   25M  1.4G   2% /run
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
tmpfs           3.5G  686M  2.9G  20% /
...
```

```
bash-4.3# free -h
              total        used        free      shared  buff/cache   available
Mem:          7.0Gi       1.9Gi       3.5Gi       1.3Gi       1.5Gi       3.2Gi
Swap:            0B          0B          0B
```

**Comment by matti** [comment]
#227

**Comment by pothos** [comment]
The tmpfs has to have either a fixed size in MB or a size relative to the RAM size. Having up to 50% used for files is the default. You can still use more than 50% of the RAM as long as you don't fill the file system.
