### ISSUE TITLE
public place to ask/discuss queries regarding flatcar?

### ISSUE THREAD

**Issue by surajnarwade** [flatcar/Flatcar#31]
is there public slack/IRC for the synchronous conversation of issues regarding flatcar?

**Comment by alban** [comment]
There is #flatcar on IRC freenode.

**Comment by pothos** [comment]
And there is a user Google group and a dev Google group (which is not really used right now):

https://groups.google.com/forum/#!forum/flatcar-linux-user
https://groups.google.com/forum/#!forum/flatcar-linux-dev
