### ISSUE TITLE
Permissions error when creating a GCE instance template with an image family reference

### ISSUE THREAD

**Issue by ribbybibby** [flatcar/Flatcar#314]
**Description**

I can't seem to create a GCE managed instance template with a reference to the image family `flatcar-stable`. I get an unexpected permissions error.

**Impact**

Providing a managed instance template with a family, as opposed to a direct image reference like `flatcar-2605-10-0`, means that new instances will be created from the latest image. 

If I can't do that I need to provide a specific image and update the configuration myself with each update.

**Environment and steps to reproduce**

A quick way to produce this issue is with this `gcloud` command:
```
gcloud compute instance-templates create test-template --create-disk=image-family=flatcar-stable,image-project=kinvolk-public
```

**Expected behavior**
I would expect this error about missing networks:
```
ERROR: (gcloud.compute.instance-templates.create) Could not fetch resource:
 - The resource 'projects/<your project>/global/networks/default' was not found
 ```

But instead I get
```
ERROR: (gcloud.compute.instance-templates.create) Could not fetch resource:
 - Required 'compute.images.get' permission for 'projects/kinvolk-public/global/images/family/flatcar-stable'
```

**Additional information**
This previously worked with coreos. I believe the coreos images used to show up under the list of global 'public' images, which flatcar images don't seem to. Maybe that's relevant.

**Comment by margamanterola** [comment]
Thanks for reporting!

I tried this command, which ran successfully:
```
gcloud compute instances create flatcar1 --image-project kinvolk-public --image-family flatcar-stable --zone us-central1-a --machine-type n1-standard-1 
```

And then tried this other command which failed:
```
gcloud compute instance-templates create test-template --image-family=flatcar-stable --image-project=kinvolk-public
ERROR: (gcloud.compute.instance-templates.create) Could not fetch resource:
 - Required 'compute.images.get' permission for 'projects/kinvolk-public/global/images/family/flatcar-stable'
```

As you say, this might be because our images are not in the global list of public images, I'll ask our Google Cloud contacts for help.

**Comment by ribbybibby** [comment]
This is working for us now. Did anything change your side?

**Comment by sayanchowdhury** [comment]
@ribbybibby Given it's all working now, Can we close this issue?

**Comment by ribbybibby** [comment]
Yep, sure. Closed.
