### ISSUE TITLE
/etc/iscsi/initiatorname.iscsi is not generated on boot

### ISSUE THREAD

**Issue by ribbybibby** [flatcar/Flatcar#321]
**Description**

We recently rolled our on-prem cluster from 2605.7.0 -> 2605.11.0 and discovered that, contrary to [what is expressed in the docs](https://kinvolk.io/docs/flatcar-container-linux/latest/setup/storage/iscsi/), `/etc/iscsi/initiatorname.iscsi` is no longer generated on boot.

**Impact**

This broke the ability of affected nodes to mount pvcs via iscsi. We have had to generate it ourselves as a workaround.

**Environment and steps to reproduce**

Run Flatcar 2605.11.0 (stable) and note that `/etc/iscsi/initiatorname.iscsi` is not present on the system. Also observe that the `iscsid-initiatorname` service is not present:
```
Flatcar Container Linux by Kinvolk stable (2605.11.0)
Update Strategy: No Reboots
core@worker-10 ~ $ systemctl status iscsid-initiatorname.service
Unit iscsid-initiatorname.service could not be found.
```

Whereas it was in a 2605.7.0 system:
```
Flatcar Container Linux by Kinvolk stable (2605.7.0)
Update Strategy: No Reboots
core@worker-19 ~ $ systemctl status iscsid-initiatorname.service
● iscsid-initiatorname.service - iSCSI initiator name generator
     Loaded: loaded (/usr/lib/systemd/system/iscsid-initiatorname.service; static; vendor preset: disabled)
     Active: inactive (dead) since Mon 2020-11-02 11:30:52 UTC; 2 months 16 days ago
    Process: 946 ExecStart=/bin/sh -c echo InitiatorName=iqn.2016-04.com.flatcar.iscsi:$(</etc/machine-id) >/etc/iscsi/initiatorname.iscsi (code=exited, status=0/SUCCESS)
   Main PID: 946 (code=exited, status=0/SUCCESS)
```

**Expected behavior**
I would expect the `iscsid-initiatorname` service to be present and to create `/etc/iscsi/initiatorname.iscsi` on boot.

**Additional information**
I suspect this was dropped by [the update to open-iscsi 2.1.2](https://github.com/kinvolk/coreos-overlay/pull/682).

Comparing the [old version's ebuild file](https://github.com/kinvolk/coreos-overlay/blob/stable-2605.11.0/sys-block/open-iscsi/open-iscsi-2.0.873-r3.ebuild#L84) to [the new one](https://github.com/kinvolk/coreos-overlay/blob/stable-2605.11.0/sys-block/open-iscsi/open-iscsi-2.1.2.ebuild#L116-L124) leads me to believe that the issue lies there.

**Comment by t-lo** [comment]
Thank you for reporting this issue. This indeed appears to have been a miss when updating the package; please pardon the inconvenience. We are working on a fix and aim to include it in the next releases (we'll also cover https://github.com/kinvolk/Flatcar/issues/318).

As a temporary workaround please consider provisioning the [iscsi-initiatorname service file](https://github.com/kinvolk/coreos-overlay/blob/stable-2605.11.0/sys-block/open-iscsi/files/iscsid-initiatorname.service) via Ignition.

**Comment by margamanterola** [comment]
This was addressed in https://github.com/kinvolk/coreos-overlay/pull/791/, that updated the iscsi version to 2.1.3 and fixed the service units. Please note that the services are now called iscsi (instead of iscsid) and iscsi-init (instead of iscsi-initiatorname), as those are the upstream names.

This will be included in the upcoming set of releases for stable, beta and alpha.

**Comment by margamanterola** [comment]
The new flatcar releases with these fixes are in the process of getting published. Closing now. Thanks for reporting.
