### ISSUE TITLE
Clean up development manifest-builds tags

### ISSUE THREAD

**Issue by margamanterola** [flatcar/Flatcar#322]
**Description**

We currently have thousands of tags in the manifest-builds repo that were created for doing development builds.  These are the tags for actual (CoreOS or Flatcar) released versions:
```
manifest-builds$ git for-each-ref --format '%(refname:short)' refs/tags | grep '^v[0-9]' | wc -l
460
```

And these are the non-released versions:
```
manifest-builds$ git for-each-ref --format '%(refname:short)' refs/tags | grep -v '^v[0-9]' | wc -l
2996
```

These versions are created whenever we run a Jenkins build, be it a nightly build or a development build to try out a change.

**Impact**

This repo gets checked out during Jenkins jobs and having over three thousand tags to check out clobbers the output (repo prints one line per tag).

**Desired outcome**

We should clean-up old dev tags. I'd go with anything older than 15 days, as this is how long we keep other dev artifacts. I tried coming up with a one liner to do this, but doing it in bash is pretty horrible as it involves line-by-line processing, which is not great to do in bash. A python script could be quite straightforward, I think.

**Comment by dongsupark** [comment]
Totally agree. It is not only an issue of manifest-builds, but also other repos.
Anything older than 15 days sounds ok.
Not sure about how to implement.

**Comment by krnowak** [comment]
This could be a github action running once a week.

**Comment by sayanchowdhury** [comment]
Agreed this could be implemented via Github Actions. This could be low-hanging fruit.

**Comment by tormath1** [comment]
With the new CI, we don't use anymore this repo. Let's close this :)
