### ISSUE TITLE
Move /boot/coreos to /boot/flatcar after upgrade

### ISSUE THREAD

**Issue by mleklund** [flatcar/Flatcar#327]
**Description**

I would like to move /boot/coreos to /boot/flatcar after upgrade, also would like to update the menu, but I cannot find docs on how to do this.

**Impact**

No real impact, other than it hurts my feelings. 

**Environment and steps to reproduce**

1. Have a CoreOS server
2. run update-to-flatcar.sh
3. Be bothered in your soul that the menu still says CoreOS and that it is using /boot/coreos instead of /boot/flatcar.

**Expected behavior**
I really expected it to move the installer to /boot/flatcar, maybe keeping a /boot/coreos symlink pointing to /boot/flatcar.

**Additional information**
Might be somewhat related to https://github.com/kinvolk/Flatcar/issues/40

**Comment by pothos** [comment]
GRUB and it's config are not migrated, you would have to replace all this which is not an easy task to automate in the general case.

**Comment by mleklund** [comment]
Is there a hard way? Does not have to be something I automate at the moment.

**Comment by pothos** [comment]
Depending on how you boot Flatcar I guess you can replace the GRUB EFI binary for example and the grub.cfg.tar file. I did not try this myself.

**Comment by mleklund** [comment]
Thanks! I think I have it mostly figured out.
