### ISSUE TITLE
Flatcar vs CoreOS

### ISSUE THREAD

**Issue by alpana17** [flatcar/Flatcar#33]
How flatcar is different from CoreOS?
What extra features does it provide?

**Comment by rata** [comment]
Hi!

I think this blog post (the first paragraph shows what we've added) can help: https://kinvolk.io/blog/2020/02/flatcar-container-linux-enters-new-era-after-coreos-end-of-life-announcement/.

> Almost two years ago, we launched Flatcar Container Linux, a drop-in replacement for CoreOS Container Linux. Since then, we’ve made almost 200 releases, added an experimental edge channel, released the update server - Nebraska, (re-)introduced ARM support (which had been dropped by Red Hat), and introduced the Kinvolk Flatcar Container Linux Subscription.

Please note that there is also a FAQ: https://www.flatcar-linux.org/faq/ that maybe is useful for your concerns?

Does this answer the question? Or you were thinking about something else?
