### ISSUE TITLE
Local mirror of http://public.update.flatcar-linux.net/v1/update/

### ISSUE THREAD

**Issue by n-marciniak** [flatcar/Flatcar#333]
**Current situation**
Flatcar update required internet access. it is not always available even through a proxy server.
Non internet connected servers should be able to update from a locally hosted server
ie mirror of http://public.update.flatcar-linux.net/v1/update/

**Ideal future situation**
Make http://public.update.flatcar-linux.net/v1/update/ possible to be mirrored

**Implementation options**
rsync, http directory listing, ftp server

**Comment by pothos** [comment]
The URL you mentioned is for the update server API which can't be mirrored. You can mirror the image server and we have a script for that.

For running a local update server look into https://github.com/kinvolk/nebraska/ (use `-enable-syncer true -host-flatcar-packages true` but at least this part needs Internet access of course, without these options you would have to create the packages manually in the web UI).

**Comment by n-marciniak** [comment]
Thanks for clarification
