### ISSUE TITLE
tcsd doesn't start due to wrong permissions (affects 2605.9.0 and later)

### ISSUE THREAD

**Issue by margamanterola** [flatcar/Flatcar#335]
**Description**

In https://github.com/kinvolk/coreos-overlay/pull/684 we merged a patch to apply some security fixes to trousers. Unfortunately we didn't realize that part of what the patch did was enforce certain permissions on the files in /etc that are not the permissions that we ship.

**Impact**

Using tcsd requires manually fixing the ownership and permissions of /etc/tcsd.conf

**Environment and steps to reproduce**

1. **Set-up**: Deploy a machine with a TPM. Ideally, TPM 1.2 as that's what trousers supports.
    A c1.small.x86 server in Equinix Metal has a TPM available (although it's 2.0).
2. **Task**: Checkout the status of the tcsd service
3. **Action(s)**: `systemctl status tcsd`
4. **Error**:

```
$ systemctl status tcsd
● tcsd.service - TCG Core Services Daemon
     Loaded: loaded (/usr/lib/systemd/system/tcsd.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Fri 2021-01-29 10:25:24 UTC; 1min 59s ago
    Process: 1005 ExecStart=/usr/sbin/tcsd -f (code=exited, status=4)
   Main PID: 1005 (code=exited, status=4)

Jan 29 10:25:24 marga-test systemd[1]: Started TCG Core Services Daemon.
Jan 29 10:25:24 marga-test tcsd[1005]: TCSD ERROR: TCSD config file (/etc/tcsd.conf) must be user/group root/tss
Jan 29 10:25:24 marga-test systemd[1]: tcsd.service: Main process exited, code=exited, status=4/NOPERMISSION
Jan 29 10:25:24 marga-test systemd[1]: tcsd.service: Failed with result 'exit-code'.
```

**Expected behavior**
tcsd should start successfully when `/dev/tpm0` is present (and TPM1.2).

**Additional information**

These are the permissions now:
```
$ ls -l /etc/tcsd.conf 
-rw-------. 1 tss tss 7046 Nov 20  2019 /etc/tcsd.conf
```

The applied patch enforces that the file should be 0640 and root/tss. Changing the permissions to that allows tcsd to start, although it then fails because of the TPM version mismatch (I couldn't find a machine with TPM 1.2 to test that):

```
core@marga-test ~ $ sudo chown root.tss /etc/tcsd.conf 
core@marga-test ~ $ sudo chmod 0640 /etc/tcsd.conf
core@marga-test ~ $ sudo systemctl restart tcsd
core@marga-test ~ $ systemctl status tcsd
● tcsd.service - TCG Core Services Daemon
     Loaded: loaded (/usr/lib/systemd/system/tcsd.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Fri 2021-01-29 10:42:34 UTC; 6s ago
    Process: 1102 ExecStart=/usr/sbin/tcsd -f (code=exited, status=30)
   Main PID: 1102 (code=exited, status=30)

Jan 29 10:42:34 marga-test systemd[1]: Started TCG Core Services Daemon.
Jan 29 10:42:34 marga-test tcsd[1102]: TCSD TCS ERROR: TCS GetCapability failed with result = 0x1e
Jan 29 10:42:34 marga-test tcsd[1102]: TCSD resetting mode of /var/lib/tpm from 40755 to: 700
Jan 29 10:42:34 marga-test tcsd[1102]: TCSD TDDL ioctl: (25) Inappropriate ioctl for device
Jan 29 10:42:34 marga-test tcsd[1102]: TCSD TDDL Falling back to Read/Write device support.
Jan 29 10:42:34 marga-test systemd[1]: tcsd.service: Main process exited, code=exited, status=30/n/a
Jan 29 10:42:34 marga-test systemd[1]: tcsd.service: Failed with result 'exit-code'.
```

**Comment by pothos** [comment]
The fix will be part of the next releases (all of Alpha, Beta, Stable)

**Comment by boneshark1** [comment]
I found that I also had to edit /usr/local/etc/rc.d/tcsd and /usr/local/etc/rc.d/tpmd to alter permissions and defaults

tcsd:
tcsd_precmd()
{
        /usr/bin/install -d -m 0700 -o root -g _tss \             #changed owner  from _tss
            /var/run/tpm /var/run/ima /usr/local/var/lib/tpm
        /usr/sbin/chown root:_tss \
            /usr/local/etc/tcsd.conf
        /bin/chmod 0640 \                              #changed permissions like /usr/local/etc/tcsd.conf
            /usr/local/etc/tcsd.conf
}

load_rc_config $name

: ${tcsd_enable:="YES"}                  #changed to run tcsd
: ${tcsd_mode:="emulator"}           #changed to run emulator when no physical chip present


tpmd:
load_rc_config $name

: ${tpmd_enable:="NO"}
: ${tpmd_user:="root"}            #changed from _tss
: ${tpmd_group:="_tss"}

command_args="-o ${tpmd_user} -g ${tpmd_group}"

**Comment by pothos** [comment]
@boneshark1 are you talking about Flatcar Container Linux? There is no `/usr/local/etc/`.
