### ISSUE TITLE
docker restart flag not working correctly after locksmithd OS update 

### ISSUE THREAD

**Issue by HubertBos** [flatcar/Flatcar#336]
**Description**

When FlatCar has been updated by locksmithd docker engine is not starting(?) but all starts when someone ssh to machine 

**Impact**

Every stable release I need to ssh to all my machines 

**Environment and steps to reproduce**

1. A standard flatcar AWS machine with single locksmith coordinator 
2. Run docker image with the flag --restart=always 
3. Let locksmithd to reboot the machine
4. Let the system run for a bit and ssh to box

![image](https://user-images.githubusercontent.com/51697820/106382590-7bf94c80-63b8-11eb-93da-417abb3d6e11.png)

![image](https://user-images.githubusercontent.com/51697820/106382658-ef02c300-63b8-11eb-9994-18ade07e0876.png)

**Expected behavior**
Containers to automatically start without user to ssh to the machine.

**Comment by pothos** [comment]
There is documentation for this topic: https://kinvolk.io/docs/flatcar-container-linux/latest/container-runtimes/getting-started-with-docker/#permanently-running-a-container

You can enable the Docker service and disable the socket activation (on-demand start of Docker), to always have Docker running.

The preferred way however is to use systemd units:

```
[Unit]
Description=your container
Wants=docker.service
After=docker.service
[Service]
Type=simple
Restart=always
RestartSec=5s
TimeoutStartSec=0
ExecStartPre=-docker rm -f yourcontainer
ExecStartPre=docker run --name yourcontainer -d yourimage yourargs
ExecStart=docker logs -f yourcontainer
ExecStop=docker stop yourcontainer
ExecStopPost=docker rm yourcontainer
[Install]
WantedBy=multi-user.target
```

**Comment by HubertBos** [comment]
Hello

Thank you for an update, I will apply changes and update the ticket in next release.

**Comment by sayanchowdhury** [comment]
@HubertBos Closing this issue. Feel free to reopen if the issue persists.
