### ISSUE TITLE
Setting /etc/profile.env breaks PATH

### ISSUE THREAD

**Issue by Keithsc** [flatcar/Flatcar#337]
**Description**
If the file /etc/profile.env is created then the default PATH variable changes so that it doesn't include /opt/bin/ any more.

**Impact**
If I "touch" a /etc/profile.env file I am unable to execute anything in /opt/bin by just name alone and need to supply the full path.

**Environment and steps to reproduce**
Using a brand new Flatcar VM in azure, I echo the PATH then touch a /etc/profile.env, logout and back in again and echo out the path again...

core@myVM ~ $ env | grep PATH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/bin
core@myVM ~ $ sudo touch /etc/profile.env
..
Log out and back in again...
..
Last login: Mon Feb  1 10:17:16 UTC 2021 from 12.12.12.12 on pts/0
Flatcar Container Linux by Kinvolk stable (2605.11.0)
core@myVM ~ $ env | grep PATH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

**Expected behavior**
The two PATH variables are different, I was not expecting the PATH to change just because I created an empty /etc/profile.env file

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/bin
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

**Additional information**
I require a proxy to be set to be access to access the internet and have manually been setting it each time I login, So I decided to try setting the proxy in an "Container Linux Config (see Below)". I managed to get the proxy set using a CL file, but then discover that I was unable execute my docker-compose file unless I types the full path "/opt/bin/docker-compose".   I though it might have been something else that I had changed that caused this issue but eventually figured out that it was just the existence of the "profile.env" file that is causing the my PATH issue.

This is the example CL file that I am trying to use to set my proxy.
https://kinvolk.io/docs/flatcar-container-linux/latest/setup/systemd/environment-variables/

storage:
  files:
    - path: /etc/systemd/system.conf.d/10-default-env.conf
      filesystem: root
      mode: 0644
      contents:
        inline: |
          [Manager]
          DefaultEnvironment=HTTP_PROXY=http://192.168.0.1:3128
    - path: /etc/profile.env
      filesystem: root
      mode: 0644
      contents:
        inline: |
          export HTTP_PROXY=http://192.168.0.1:3128

**Comment by pothos** [comment]
Hello,
that topic is indeed difficult. There are various ways to define the environment (`/etc/environment`, `/etc/profile(.d)` etc) and it's all different depending on whether you have a login bash shell, use `sudo -s`, `su -`, or systemd services.

For systemd services the env is hardcoded anyway and you have to specify it through systemd units, as far as I know.

Since `/etc/profile.env` is documented it should probably not reset the PATH but it could also be that other files like `/etc/profile(.d/*)` or `/etc/environment` work better.

**Comment by Keithsc** [comment]
Thanks @pothos, Switching to using the /etc/environment file worked, the proxy settings are working correctly and my PATH var still includes /opt/bin.

  - owner: root:root
    path: /etc/environment
    append: true
    content: |
          export http_proxy=http://proxy.server.address:3128
          export https_proxy=http://proxy.server.address:3128
