### ISSUE TITLE
New Package Request: update qemu to latest version 

### ISSUE THREAD

**Issue by margamanterola** [flatcar/Flatcar#338]
**Package name and purpose**  

Qemu is one of our main VM emulation components. We're still using version 5.0. Version 5.2 includes significant updates:  https://www.qemu.org/2020/12/08/qemu-5-2-0/

- Package upstream repo: https://gitlab.com/qemu-project/qemu
- Latest Gentoo ebuild: https://github.com/gentoo/gentoo/blob/master/app-emulation/qemu/qemu-5.2.0-r2.ebuild

**Impact of adding this package to the Flatcar OS image**  
None, this is only part of the SDK.

The package will increase the image size by:  0 MB, as it's not part of the shipped image.

How might this package increase the attack surface:
- This shouldn't increase the attack surface, as it's just an updated version.

**Benefits of adding this package**  
- There's a quite long list of features added to 5.2 that we would want to include. It might help with some virtualization issues we see during tests.

**Comment by pothos** [comment]
> Impact of adding this package to the Flatcar OS image / The package will increase the image size by: TODO MBytes.

Zero because it's not part of the image

But I hope it will help with the soft lockups we see while running tests

Edit: Of course we can change our mind and include QEMU in the image, probably with libvirtd. At least for the binary translation helpers I had created an issue: https://github.com/kinvolk/Flatcar/issues/205

**Comment by dongsupark** [comment]
> There's a quite long list of features added to 5.2 that we would want to include. It might help with some virtualization issues we see during tests.

All right, good to know. Let's update to 5.2.
We were already thinking about updating qemu to 5.1 due to security issues, but so far had no chance to do so. As it is not part of production images, has been a rather lower priority.

**Comment by dongsupark** [comment]
PR https://github.com/kinvolk/coreos-overlay/pull/964 was merged,
qemu 5.2 will be included in Alpha 2857.0.0.
