### ISSUE TITLE
Release process for flatcar

### ISSUE THREAD

**Issue by alpana17** [flatcar/Flatcar#34]
Currently, flatcar is released in parallel to CoreOS
As CoreOS EOL has been declared, how do flatcar plans to keep providing Images?

**Comment by rata** [comment]
I think this blog post might answer this: https://kinvolk.io/blog/2020/02/flatcar-container-linux-enters-new-era-after-coreos-end-of-life-announcement/. And also check this (for the `What do you mean when you say Flatcar Container Linux is “independently built”?` question) https://www.flatcar-linux.org/faq/.

tl;dr (from the blog post): 
> Almost two years ago, we launched Flatcar Container Linux, a drop-in replacement for CoreOS Container Linux. Since then, we’ve made almost 200 releases, added an experimental edge channel, released the update server - Nebraska, (re-)introduced ARM support (which had been dropped by Red Hat), and introduced the Kinvolk Flatcar Container Linux Subscription.
> (...)
> For Flatcar Container Linux, this means the Kinvolk team will be continuing maintenance and development completely independent of upstream CoreOS. This is something for which we’ve been anticipating and preparing for some time. We have formed a strong OS and Security team, led by Thilo Fromm, previously technical project manager responsible for AWS’s internal Linux efforts. That team is already building and testing the edge and alpha channels with updated packages and kernels compared with upstream CoreOS. Those updates will flow into the other channels following the usual alpha → beta → stable progression.

Does this asnwer the question? :)
