### ISSUE TITLE
flatcar image with open-vm-tools + cloud-init metadata from openstacks' metadata_urls

### ISSUE THREAD

**Issue by Finkregh** [flatcar/Flatcar#340]
**Current situation**
We are running Openstack for management and vSphere/ESXi as hypervisor.
The openstack flatcar image does get cloud-init data from the usual metadata_urls but does not have open-vm-tools installed.
The vmware flatcar image does try to get cloud-init data from somewhere else (config-drive? i'll have a look at the logs if that it important) and fails but does have open-vm-tools installed.

**Impact**
If we select one of the images we loose certain functions.

**Ideal future situation**
An image with cloud-init getting data from openstacks' metadata_url AND open-vm-tools installed.

**Implementation options**
Create an image with both options OR make the vmware images' cloud-init also try the metadata_url.

**Additional information**
asked on twitter before and had a quick chat (thanks)
https://twitter.com/fink_/status/1356191173426208772
cc @pothos

**Comment by pothos** [comment]
Do you have a way of specifying VMware guestinfo variables for the instances?
You should use the VMware images (e.g., ova) and set the `guestinfo.ignition.config.url` to point to the OpenStack metadata URL.
Here are the details: https://kinvolk.io/docs/flatcar-container-linux/latest/installing/cloud/vmware/
Noteworthy is that the Ignition with VMware can only use DHCP, do you have DHCP?
(There are kernel parameters to specify a static IP address but you can't set them via `guestinfo` variables).

**Comment by Finkregh** [comment]
Thanks for the quick reply.

I think we could get there, but we'd have to automate that for every new VM with a flatcar image.
I suspect that this will not happen as it would require some engineering effort.

An easy way out would be a mixed image with vmware-tools+metadata from openstack :)

**Comment by pothos** [comment]
You could modify the flatcar image you use by embedding a default `config.ign`  ignition file on the OEM partition which contains a `replace` directive to point to the openstack URL:
`{ "ignition": { "version": "2.1.0", "config": { "replace": { "source": "http://..." } } } }`

**Comment by Finkregh** [comment]
Thanks, that looks like a solution for us.
I'll close the ticket and eventually add a note with the commands/script that we used. You can then use it in your docs if you like.

**Comment by Finkregh** [comment]
somehow this did not work as expected and i cant find something pointing to errors in the oem-ignition file...
I added the file via guestfish:

```bash
guestfish --rw -a flatcar_production_vmware_image.vmdk <<EOF
run
mount /dev/sda6 /
write "/base/user.ign" "{ \"ignition\": { \"version\": \"2.1.0\", \"config\": { \"replace\": { \"source\": \"http://169.254.169.254:80/\" } } } }"
umount /
EOF
```
That did create this file: `/usr/share/oem/base/user.ign`

**Comment by pothos** [comment]
Thanks for sharing. Can you try again using `/config.ign` instead? And I think the URL would be `http://169.254.169.254:80/latest/meta-data`, or?

**Comment by Finkregh** [comment]
Yes, the URI was of course wrong. Do you mean `partition6/config.ign` or `partition3/config.ign`?

I tried to put it in `partition6` and now have a loop starting some services. As i get new logs every few seconds i cant scroll up. `systemd.debug-shell`, `earlyprink` and `console` did also not work to get logs to ttyS0.
https://kinvolk.io/docs/flatcar-container-linux/latest/provisioning/ignition/boot-process/ sadly also did not help. Is there some documentation on how to debug the boot process?


edit: i tried to put it in `partition3` but could not mount it for modification. The kernel said `couldn't mount RDWR because of unsupported optional feature`. tune2fs told me about `Filesystem features:      ext_attr resize_inode dir_index filetype sparse_super large_file FEATURE_R24 FEATURE_R25 FEATURE_R26 FEATURE_R27 FEATURE_R28 FEATURE_R29 FEATURE_R30 FEATURE_R31`, i suspect that is why i could not mount it.

**Comment by pothos** [comment]
Partition 6 is correct. Hm, having it loop means that Ignition runs into some problem either when accessing `http://169.254.169.254:80/latest/meta-data` or when processing its contents. The logs should go to the serial console with someting like `console=ttyS1 earlyprintk=serial,ttyS1` (use `ttyS1,57600n8` or similar depending on your hardware), is it blank for you?

**Comment by pothos** [comment]
Closing but feel free to ask follow up questions
