### ISSUE TITLE
Package Update Request: multipath-tools

### ISSUE THREAD

**Issue by ffilippopoulos** [flatcar/Flatcar#341]
**Package name and purpose**
Flatcar comes with an old multipath-tools version `multipath-tools v0.6.4 (03/11, 2016)` thats is already a few years old. A lot of the modern kubernetes csi volume drivers rely on multipathd for operations (for example we are currently using netapp/trident which does multipathd calls to determine which dm to mount).

Most recent version appears to be `0.8.5` (https://github.com/opensvc/multipath-tools/tags)

**Impact of adding this package to the Flatcar OS image**
This is just for a version bump so it shouldn't have a considerable impact on the Flatcar OS image

**Benefits of adding this package to the Flatcar OS image**
Kubernetes csi drivers could take advantage of up to date multipath-tools.

**Comment by dongsupark** [comment]
Thanks for creating the issue.
multipath-tools 0.8.5 is now included in Alpha 2801.0.0.
It will be available in other channels in the future.
