### ISSUE TITLE
Dead link to examples in /provisioning/config-transpiler/getting-started/

### ISSUE THREAD

**Issue by Kenevist-admin** [flatcar/Flatcar#344]
The link in the last sentence  to the examples is https://kinvolk.io/docs/flatcar-container-linux/latest/provisioning/config-transpiler/getting-started/examples but it should be https://kinvolk.io/docs/flatcar-container-linux/latest/provisioning/cl-config/examples/

**Comment by margamanterola** [comment]
Thanks for the report, I'll take care of this.
