### ISSUE TITLE
Support Docker 20.10

### ISSUE THREAD

**Issue by mback2k** [flatcar/Flatcar#348]
**Current situation**
Docker version 20.10 is not yet available (not even optional) for Flatcar, but would bring a bunch load of new features, see:
https://docs.docker.com/engine/release-notes/#20100

**Impact**
Missing out on new features, especially around using devices from within services.

**Ideal future situation**
I would propose to have Docker version 20.10 available as an optional torcx package, but still default to the more stable 19.03 for now.

**Comment by pothos** [comment]
Hi,
you can follow this guide to run a custom version through Ignition:
https://kinvolk.io/docs/flatcar-container-linux/latest/container-runtimes/use-a-custom-docker-or-containerd-version/
Maybe some adjustments are needed but the first thing to do is switching a newer version in the `url: https://download.docker.com/linux/static/stable/x86_64/docker-19.03.14.tgz` line.

**Comment by mback2k** [comment]
Thanks for the information, but are there plans for Docker 20.10 availability in Flatcar?

**Comment by sayanchowdhury** [comment]
There is ongoing work-in-progress PR on Docker 20.10 support in Flatcar https://github.com/kinvolk/coreos-overlay/pull/931

**Comment by jepio** [comment]
Docker 20.10 is in Flatcar v2969.0.0.
