### ISSUE TITLE
Rss feed for new releases?

### ISSUE THREAD

**Issue by davidgibbons** [flatcar/Flatcar#35]
New convert from CoreOS here,

We usually use a rss -> slack feed to see when new releases are available eg: https://coreos.com/releases/releases-alpha.json

Is this something you plan on supporting as well?

**Comment by pothos** [comment]
Caddy can serve JSON if it is asked to do so in the HTTP request:
`curl -H "Accept: application/json" https://stable.release.flatcar-linux.net/amd64-usr/`
This will give a list of release versions (but also includes the `current` release).

You can also watch this file for a version change:
https://stable.release.flatcar-linux.net/amd64-usr/current/version.txt

**Comment by pothos** [comment]
Hello,
we've added these files now in a compatible way (but not yet placed links on the website).

**Comment by pothos** [comment]
Ctrl-Enter was causing a post too early accidentally.
The links are as follows:
for all releases combined (there is a `current` entry pointing to the current stable release):
https://www.flatcar-linux.org/releases-json/releases.json
and for each channel (also with a `current` entry):
https://www.flatcar-linux.org/releases-json/releases-stable.json
https://www.flatcar-linux.org/releases-json/releases-beta.json
https://www.flatcar-linux.org/releases-json/releases-alpha.json
https://www.flatcar-linux.org/releases-json/releases-edge.json

**Comment by pothos** [comment]
@dhaines, I think, asked on IRC about this, too.

**Comment by pothos** [comment]
The JSON feed links are shown now: https://www.flatcar-linux.org/releases/
