### ISSUE TITLE
sshd@.service should not log to syslog

### ISSUE THREAD

**Issue by vbatts** [flatcar/Flatcar#350]
found in my journal:
```
Feb 11 05:18:38 <REDACTED> systemd[1]: /usr/lib/systemd/system/sshd@.service:8: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
```
Found in even the latest 2783.0.0 release, `/usr/lib/systemd/system/sshd@.service`:
```ini
[Unit]
Description=OpenSSH per-connection server daemon
After=syslog.target auditd.service

[Service]
ExecStart=-/usr/sbin/sshd -i -e
StandardInput=socket
StandardError=syslog
```

The `systemd.exec` man page says:
>        StandardError=
>           Controls where file descriptor 2 (stderr) of the executed processes is connected to. The available options are identical to those of StandardOutput=, with some exceptions: if set to inherit the file descriptor used for standard output is duplicated for standard error, while fd:name will use a default file descriptor name of "stderr".
>
>           This setting defaults to the value set with DefaultStandardError= in systemd-system.conf(5), which defaults to inherit. Note that setting this parameter might result in additional dependencies to be added to the unit (see above).

Proposing to remove that `StandardError=syslog` line.

**Comment by ravish0007** [comment]
In latest alpha 2920.0.0 release, StandardError is set to journal

**Comment by ArkaprabhaChakraborty** [comment]
Hi, I'm new to this community, can I get some directions on how to work on this issue? or is this one solved?

**Comment by t-lo** [comment]
Fixed in 2905. https://github.com/kinvolk/coreos-overlay/commit/8b69d294ac9885bfa2b7ae89534fefd94ccee0c4
