### ISSUE TITLE
[Minor] Documentation formatting issue

### ISSUE THREAD

**Issue by nathanielhourt** [flatcar/Flatcar#351]
Looking at https://kinvolk.io/docs/flatcar-container-linux/latest/provisioning/ignition/network-configuration/ in the "Using static IP addresses with Ignition" section, it seems that two different formats are being described, but the way it's written is a bit confusing unless you already understand that. The two "This format" paragraphs are not initially clear as to what "This" they are referring to.

This could be ameliorated by adding a subheading on each of them saying "The Expanded Format" and "The Condensed Format" or the like, which would make it more obvious on the first pass that there are two alternative (exclusive?) formats being described and that those two paragraphs/examples are describing them and how they are different.
![Screenshot_20210225_003038](https://user-images.githubusercontent.com/271977/109113025-2d15ad00-7701-11eb-854b-8f3586eb8247.png)

Admittedly, this is a fairly nitpicky complaint, and as such can be regarded as low-priority.

**Comment by pothos** [comment]
Yes, the first is suggesting that they could be individual parameters but only the second one is correct as far as I know.

**Comment by nathanielhourt** [comment]
Ahh, I was just going to put together a PReq for this, but before I do... are you saying the first format no longer works?

**Comment by pothos** [comment]
Ok, tried it and it works (it generates a `/etc/systemd/network/10-dracut-cmdline-99.network` for the initramfs), so all good, maybe I used it wrong last time

**Comment by pothos** [comment]
(tested with adding `rd.break=pre-mount rd.shell` to the kernel arguments in the GRUB menu of the qemu image)

**Comment by nathanielhourt** [comment]
OK, I made the edit [here](https://github.com/kinvolk/flatcar-docs/compare/main...nathanhourt:patch-1?short_path=b1ef021#diff-b1ef02131cf4a282e4c8ed3f596ce12148c6bb35d3e90050ac30382b4b0863ae) -- should I PReq that to `main` or a different branch?

**Comment by pothos** [comment]
yes, to `main`

Maybe you can say there that the simple format is just for a single device while the other is suited for multiple interfaces

**Comment by nathanielhourt** [comment]
Hmm, perhaps it would be clearer to name them "Single-Interface Format" and "Multi-Interface Format" rather than "Expanded" and "Comprehensive"? What do you think?

**Comment by pothos** [comment]
Yes, sounds good
