### ISSUE TITLE
It appears that since v2765.2.0 port 53 is gripped by systemd-resolve and what was previously using port 53 will now fail

### ISSUE THREAD

**Issue by cdemers** [flatcar/Flatcar#357]
**Description**

Some of our machines run a dns server in a docker container, bound to port 53. Since v2765.2.0 port 53 seems to be held by _systemd-resolve_ and what was previously using port 53 will now fail to start (complaining that port 53 is already attributed).

I'm pretty certain that _2605.12.0_ didn't have _systemd-resolve_ starting up by default and grabbing onto port 53.

On version _2605.12.0_:

```
# netstat -atupn
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9323          0.0.0.0:*               LISTEN      805/dockerd
tcp        0      0 127.0.0.1:42865         0.0.0.0:*               LISTEN      772/containerd
tcp6       0      0 :::30053                :::*                    LISTEN      1015/docker-proxy
tcp6       0      0 :::53                   :::*                    LISTEN      1096/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      1/systemd
tcp6       0    692 10.139.5.20:22          10.139.4.57:60990       ESTABLISHED 1/systemd
tcp6       0      0 10.139.5.20:22          10.139.4.57:52882       ESTABLISHED 1/systemd
udp        0      0 10.139.5.20:68          0.0.0.0:*                           642/systemd-network
udp6       0      0 :::30053                :::*                                1027/docker-proxy
udp6       0      0 :::53                   :::*                                1111/docker-proxy
```

On version _2765.2.0_:

```
# netstat -atupn
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9323          0.0.0.0:*               LISTEN      820/dockerd
tcp        0      0 127.0.0.1:45391         0.0.0.0:*               LISTEN      787/containerd
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      698/systemd-resolve
tcp6       0      0 :::30053                :::*                    LISTEN      1013/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      1/systemd
tcp6       0    868 10.139.4.20:22          10.139.4.57:52783       ESTABLISHED 1/systemd
udp        0      0 127.0.0.53:53           0.0.0.0:*                           698/systemd-resolve
udp        0      0 10.139.4.127:68         0.0.0.0:*                           661/systemd-network
udp        0      0 10.139.4.20:68          0.0.0.0:*                           661/systemd-network
udp6       0      0 :::30053                :::*                                1025/docker-proxy
```

**Impact**

As _2605.12.0_, anything using port 53 on the main interface will fail if you dont stop _systemd-resolve_.

**Environment and steps to reproduce**

Simply using `netstat -lnt` on a _2605.12.0_ and _2765.2.0_ version will show used ports.

**Other information**

As I dont control the full deployment chain I can't be absolutely certain that the problem is not on our side, but I did my best to validate what I posted here.

**Comment by pothos** [comment]
Hello,
this is a new feature, relevant for split DNS and more things that systemd-resolved offers. It was introduced in https://kinvolk.io/flatcar-container-linux/releases/#release-2748.0.0 and not present in the old Stable release. If you have to use the localhost port 53 for something else, you can disable the stub listener by appending `DNSStubListener=no` to `/etc/systemd/resolved.conf`.

In the future `/etc/resolv.conf` will likely be a symlink to the stub resolver file (127.0.0.53) but currently we had to wait with the switch because of some problem.

**Comment by cdemers** [comment]
Ah, I suspected it might actually be a feature and not a bug, I was not certain as we only looked at the Flatcar release notes and didn't realize the extent of the upgrade.  It seems Flatcar has become a pretty dynamic distribution and we need to adapt. Thanks for your answer.

**Comment by pothos** [comment]
New features are introduced in the new major release versions like 1234.0.0. They first enter the Alpha channel and you can find the changes there before they hit the Stable channel a couple of weeks later (with an increased minor version like 1234.3.0):
https://kinvolk.io/flatcar-container-linux/releases/#alpha-release

**Comment by cdemers** [comment]
Agreed, I understand well how the release channels work. Still, in our situation, I'm not sure we can realistically run and monitor multiple channels on all our various server types (in this occurence our two DNS), maybe we are not a big enough company. Thanks again for having taken the time to followup.

**Comment by endzyme** [comment]
Why would these changes not be listed in the release notes on the stable channel. The release notes should note _any_ changes between the previous version of the stable channel and the next immediate release in the stable channel. The fact it's completely missing in the release notes is a huge red flag. Is there a process for you all internally to bubble these up more clearly so someone doesn't have to dig through the Alpha release channel changelog to determine what might have changed?

**Comment by margamanterola** [comment]
Historically, CoreOS only published the release notes only for the changes within a major.minor version, and not the whole set of changes comparing a version to the previous version on that channel, and we've kept that tradition. We'll take your feedback into account and decide whether we should do this differently in the future.  Thanks.
