### ISSUE TITLE
Nonfunctional change breaks automation

### ISSUE THREAD

**Issue by endzyme** [flatcar/Flatcar#358]
**Description**

We rely on the contract of releases existing at `https://www.flatcar-linux.org/releases-json/releases-stable.json`, but as of the latest release all the URLs appear to have been changed to `https://kinvolk.io/flatcar-container-linux/releases-json/releases-stable.json`. If you're planning a change like that can it please be mentioned in the release nodes as a non-functional change? Also, it appears the old URL still serves content, but does not have the latest release, which is confusing because there is a newer release on the releases site than on the old releases json URL. Please either kill it or keep it up to date.

**Comment by pothos** [comment]
We have updated the old URL now again but it will be removed or redirected soon (but it turns out people often don't make use of `curl -L` and need manual intervention anyway…).

**Comment by endzyme** [comment]
Thank you!
