### ISSUE TITLE
New Package Request: BIRD

### ISSUE THREAD

**Issue by judexzhu** [flatcar/Flatcar#363]
**Package name and purpose**  
The BIRD Internet Routing Daemon. I believe most people like me will use flatcar-linux as Kubernetes nodes, and consider using cilium + Bird for the Kubernetes network topology.

https://docs.cilium.io/en/v1.9/gettingstarted/bird/#using-bird-to-run-bgp

Currently, I cannot find a proper way to enable bird service on flatcar-linux(please correct me if I'm wrong.)

for Flatcar:

- Package upstream repo:  https://launchpad.net/~cz.nic-labs/+archive/ubuntu/bird
- Gentoo ebuild: https://packages.gentoo.org/packages/net-misc/bird

- The package improves on the following core values:
  - [x] Secure by default
  - [x] Always up to date
  - [x] Improve container experience
  - [x] Operate at scale / automation / telemetry

The package will increase the image size by: 3 MBytes. 

How might this package increase th attack surface:
- [ e.g. new ports open, new services running, etc. ] new services running

**Benefits of adding this package**  
BGP network router daemon

**Comment by dghubble** [comment]
BIRD is a containerizable application like any other. Flatcar should probably add additional requirements for package proposals for why something truly must be on-host.

**Comment by judexzhu** [comment]
@dghubble You're right. I did more research later. bird can be a containerizable application. 
Calico use bird inside their node agent.
although I cannot find an official bird docker image, there is a good example from "Pier Carlo Chiodi"

https://github.com/pierky/dockerfiles/blob/master/bird/2.0.7/Dockerfile

For anyone who might have the same need to run bird on Flatcar-Linux, I wrote a systemd file for example

/etc/systemd/system/bird.service
```
[Unit]
Description=Bird BGP Daemon
After=docker.service
Requires=docker.service

[Service]
TimeoutStartSec=0
Restart=always
ExecStartPre=-/usr/bin/docker kill %n
ExecStartPre=-/usr/bin/docker rm %n
ExecStartPre=/usr/bin/docker pull pierky/bird:2.0.7
ExecStart=/usr/bin/docker run --rm \
    --name %n \
    -v /etc/bird:/etc/bird:rw \
    --network host \
    pierky/bird:2.0.7
ExecStop=-/usr/bin/docker stop %n
[Install]
WantedBy=multi-user.target
```

I might also write my own dockerfile with nonroot user and CAP_NET_*  capabilities later

> https://bird.network.cz/?get_doc&v=20&f=bird-1.html#ss1.4

I also chat with the cilium team, they said they plan to include the BGP function like metallb into cilium in the next 1.10 version too.

So I'm going to close this request and thanks a lot for your help
