### ISSUE TITLE
Include Amazon Root CAs in Flatcar's trust store

### ISSUE THREAD

**Issue by amayausky** [flatcar/Flatcar#365]
**Current situation**
Flatcar does not currently include Amazon Trust Services' CAs in its trust store. It does, however, contain the necessary Starfield CAs to support the upcoming S3/CloudFront CA migration as referenced in this [blog post](https://aws.amazon.com/blogs/storage/reminder-amazon-s3-and-amazon-cloudfront-migrating-service-certificates-to-amazon-trust-services-starting-march-23-2021/).

**Impact**
No current impact as the S3/CloudFront migration will continue to work with the Starfield CAs since the new root provided by Amazon is cross-signed with Starfield. But as Amazon continues to roll out new CAs across its services, there could be disruptions if that cross-signing has not occurred as referenced in this [blog post](https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/). 

**Ideal future situation**
In addition to the currently supported Starfield CAs, the Amazon CAs will also be included in Flatcar's trust store.

**Additional information**

These root CAs are widely supported in other OS's:

- Microsoft Windows versions, that have updates installed, from January 2005, Windows Vista, Windows 7, Windows Server 2008, and newer versions
- Mac OS X 10.4 with Java for Mac OS X 10.4 Release 5, Mac OS X 10.5 and newer versions
- Red Hat Enterprise Linux 5 (March 2007), Linux 6, and Linux 7 and CentOS 5, CentOS 6, and CentOS 7
- Ubuntu 8.10
- Debian 5.0
- Amazon Linux (all versions)
- Java 1.4.2_12, Java 5 update 2, and all newer versions, including Java 6, Java 7, and Java 8

Some additional links:

- https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/
- https://aws.amazon.com/blogs/storage/reminder-amazon-s3-and-amazon-cloudfront-migrating-service-certificates-to-amazon-trust-services-starting-march-23-2021/
- https://www.amazontrust.com/repository/

**Comment by tormath1** [comment]
On recent Alpha: 
```
$ ls /usr/share/ca-certificates/ | grep -i amazon
Amazon_Root_CA_1.pem
Amazon_Root_CA_2.pem
Amazon_Root_CA_3.pem
Amazon_Root_CA_4.pem
```

Amazon Root CAs are presents. :)

**Comment by jepio** [comment]
We ship the Mozilla NSS store, and started regularly updating since October 2021. The Amazon certs are included now.
