### ISSUE TITLE
configure failure of mit-krb5 on arm64

### ISSUE THREAD

**Issue by dongsupark** [flatcar/Flatcar#369]
**Description**

During the cross-toolchains builds, `app-crypt/mit-krb5` fails during configure, like:
```
checking for constructor/destructor attribute support... configure: error: Cannot test for constructor/destructor support when cross compiling
```

The issue does not happen when installing mit-krb5 with a normal `emerge-arm64-usr` command.
It only happens when building cross toolchains via `build_toolchains`.

Tried updating mit-krb5 to 1.18.3-r3 and 1.19.1, but no luck.

It fails when trying [run a cross-compiled binary](https://github.com/krb5/krb5/blob/krb5-1.18.2-final/src/aclocal.m4#L1609).
In case of normal package installation, during stages of build_package or later, the arm64 toolchains are already in place under `/build/arm64-usr`. So it is possible to simply link the binary against `/lib64/ld-linux-aarch64.so.1`.
However, during the build_toolchains stage, the file `/lib64/ld-linux-aarch64.so.1` simply does not exist yet.
I suspect it is inherently error-prone for the configure script of mit-krb5 to try to run a binary like that.
I am not sure how the whole code has worked so far.

I see a few options.

* Patch mit-krb5 in Gentoo, so it could ignore the error. i.e. `s/AC_MSG_ERROR/AC_MSG_WARN/`
* Explicitly set `krb5_cv_attr_constructor_destructor=yes` in the configure script, like done in https://github.com/cockroachdb/cockroach/pull/48132 . However, it does not seem to work in case of Gentoo.
* Fix the issue in the upstream mit-krb5. Not sure how.

**Comment by pothos** [comment]
The `QEMU_LD_PREFIX` variable is set to `/build/arm64-usr/`. If that folder is not existing at that point, we can try to set something else (wherever the libraries are). Actually I think these compiler tests don't make so much sense to run at all with a standard GCC, and disabling sounds the better option.

**Comment by dongsupark** [comment]
Huh, since we merged https://github.com/kinvolk/flatcar-scripts/pull/126 to break the dep loop in the toolchain, the mit-krb5 build failure does not happen any more.
Kind of strange, not completely sure.
Anyway I will reopen this issue when the build failure happens again.
