### ISSUE TITLE
Can't upload 2345.3.0 as a custom image on Digital Ocean

### ISSUE THREAD

**Issue by johananl** [flatcar/Flatcar#37]
When trying to upload Flatcar 2345.3.0 to Digital Ocean as a custom image, the upload stays at "pending" for a while, then an error is shown saying the image couldn't be decompressed.

Decompressing the image locally seems to work. Uploading 2303.4.0 to Digital Ocean also works.

### Scripts

```
cat ./upload_image
```

```bash
#!/bin/bash

set -euo pipefail

id=$(curl -s -X POST \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
    -d "{
        \"name\": \"flatcar_$FLATCAR_VERSION\",
        \"url\": \"https://stable.release.flatcar-linux.net/amd64-usr/$FLATCAR_VERSION/flatcar_production_digitalocean_image.bin.bz2\",
        \"distribution\": \"Unknown\",
        \"region\": \"fra1\"}" \
    "https://api.digitalocean.com/v2/images" | jq '.image.id')

echo "Upload started. Image ID: $id"
```

```
cat ./check_image
```

```bash
#!/bin/bash

set -euo pipefail

curl -s -X GET \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
    "https://api.digitalocean.com/v2/images/$IMAGE_ID" | jq '.'
```

### Bad Case

```
export DIGITALOCEAN_TOKEN=xxxxxxxx
export FLATCAR_VERSION=2345.3.0
./upload_image
```

```
Upload started. Image ID: 60173630
```

```
export IMAGE_ID=60173630
./check_image
```

```
{
  "image": {
    "id": 60173630,
    "name": "flatcar_2345.3.0",
    "distribution": "Unknown",
    "slug": null,
    "public": false,
    "regions": [],
    "created_at": "2020-03-05T14:43:36Z",
    "min_disk_size": null,
    "type": "custom",
    "size_gigabytes": null,
    "description": "",
    "tags": [],
    "status": "pending",
    "error_message": ""
  }
}
```

**After a while...**

```
./check_image
```

```
{
  "image": {
    "id": 60173630,
    "name": "flatcar_2345.3.0",
    "distribution": "Unknown",
    "slug": null,
    "public": false,
    "regions": [],
    "created_at": "2020-03-05T14:43:36Z",
    "min_disk_size": null,
    "type": "custom",
    "size_gigabytes": null,
    "description": "",
    "tags": [],
    "status": "deleted",
    "error_message": "We had a problem decompressing your file. This typically happens if the archive is corrupt or contains multiple files. Please try decompressing the file locally and uploading the uncompressed image, or recompressing using gzip or bzip2."
  }
}
```

### Good Case

Same as the bad case with the following change:

```
export FLATCAR_VERSION=2303.4.0
```

**Comment by pothos** [comment]
This image was uploaded and tested on DO during the release process, and I can also decompress and run in in QEMU, so not sure what suddenly changed.

**Comment by pothos** [comment]
Maybe we hit a timeout in DO because the bzip2 file takes ages to decompress.

**Comment by pothos** [comment]
I recompressed it with `gzip -9` (it was just ~20 MB larger) and uploaded it manually without problems.

**Comment by pothos** [comment]
Another idea may be to approach them to use lbzip2/lbunzip2 for decompression.

**Comment by jepio** [comment]
Maybe DO fixed something on their backend, or our hosting has changed the duration of the transfer relative to the decompression - but I can't reproduce this today. I tried with the latest images (3033.2.1) and with (2345.3.0), in various regions (sfo3/fra1) and have had only success. I'm using the `doctl` utility.

I'm adding a PR to docs (https://github.com/flatcar-linux/flatcar-docs/pull/204) to mention the possibility that it might fail and a possible solution with gzipping.
