### ISSUE TITLE
Documentation for Vagrant produces failed results on select hardware, TSC watchdog issue

### ISSUE THREAD

**Issue by goshlanguage** [flatcar/Flatcar#370]
Hi Kinvolk maintainers, 

First, thank you for your contributions to the community. 

I wanted to have a suitable local environment for testing changes to our flatcar environment, so when I saw [this article outlining flatcar on vagrant](https://kinvolk.io/docs/flatcar-container-linux/latest/installing/vms/vagrant/), I was glad to see solutions for this already exist. 

However, when following the documentation on my 2019 Macbook pro 16" (2.6Ghz 6-core i7/16GB ram), the first VM fails to come up completely. A look at the console reveals an issue with the TSC, "tsc: Marking TSC unstable due to clocksource watchdog". 

While I did find [linux kernel bug reports for this generation of CPU](https://bugzilla.kernel.org/show_bug.cgi?id=203183), I suspect this was patched in the kernel. For this reason, I tried several versions of flatcar, including `v2605.09`, `v2605.12`, and `v2801.01`, anticipating it to be patched in the latest version. Oddly, if I drop the vCPUs to 1, the OS comes up fine. If I run this vagrant on an older model CPU (2015 Macbook 15" Haswell/Crystalwell), it also comes up as expected.

Sorry for my ignorance, but how can I tell which patches Flatcar takes from upstream, or is there a way for me to see if a patch such as [this](https://lkml.org/lkml/2019/4/8/322) has been pulled in? I would imagine that I am not the only person to use flatcar on this CPU type, so I'm hoping this would be a valuable contribution.

**Comment by margamanterola** [comment]
We are using pretty much the kernel as provided by upstream, we have only a couple of small local patches that are located [here](https://github.com/kinvolk/coreos-overlay/tree/main/sys-kernel/coreos-sources/files/5.10).

So, to answer your question, you need to track whether that patch is applied in the latest upstream releases or not.

This is the `check_system_tsc_reliable` function in the `arch/x86/kernel/tsc.c` file in the latest 5.10 kernel:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch/x86/kernel/tsc.c?h=v5.10.25#n1180

It doesn't look like it has the patch you linked to applied and indeed neither the mailing list thread nor the bugzilla bug seem to indicate that this patch was applied.

I agree that it is somewhat surprising that some kind of patch for this CPU type hasn't been applied upstream, but this seems to be out of the flatcar scope.

Thanks.

**Comment by goshlanguage** [comment]
Thank you @marga-kinvolk for your explanation and support.
