### ISSUE TITLE
Flatcar sometimes won't boot after installation or after upgrade on VMware

### ISSUE THREAD

**Issue by mrdima** [flatcar/Flatcar#379]
**Description**

Once every while when we deploy a new VM or when we upgrade Flatcar to the latest version, the operating system doesn't boot anymore. This happens on 2 different VMware environments...one with vCloud Director, one with vRealize as frontends. We  only have access to the frontends offered.
Hard to give an estimate, I think it's less than 3% of the occurrences that this happens.
We're not sure if the non-booting during initial deployment and upgrade are actually the same issue
We're really wondering if we are the only ones to experience this.

**Impact**

When the operating system doesn't boot anymore, there's also no fallback anymore and basically you will need to recreate the machine or restore it from a snapshot if you have one and retry the update or redeploy. This is time consuming and very impractical.

**Environment and steps to reproduce**

1. VMware vSphere
2. Deploy from template flatcar_production_vmware_ova.ova with an ignition, we're using terraform to talk to the vcloud director or vrealize API to do this.
3. Upgrade flatcar linux using a manual procedure, wait for the upgrade to have finished successfully and reboot
4. **Error**: Operating system not found / continuously trying to booting from NICs instead of harddisk

**Expected behavior**
OS boots

**Additional information**
We investiged one VM not booting after an upgrade and found out that the total sda partition table was gone (so no more sda1, sda2, sda3, sda4 etc), so we expect that at least the upgrade does something which causes the partition table to be deleted, not synced properly or whatever. We do have a 10 second delay build in before we reboot the machine after a successful update.

**Comment by jepio** [comment]
The partition table gets touched during an update, to adjust the gpt partition priorities. This should be an atomic operation at the sector level (either old or new partition table present). A reboot also sync the disks, so nothing should be lost.

> We do have a 10 second delay build in before we reboot the machine after a successful update.
This is intersting. How is your update_engine configured? Normally locksmith waits 5 minutes after an update before it triggers a reboot. Do you trigger manual updates and then do your own reboot?

Do you have anything captured from the serial console right before this happens?

I'd also be curious to find out what disk interface you use (pvscsi?). Would you mind trying the emulated nvme interface and seeing if that reduces the occurrence rate?

**Comment by mrdima** [comment]
For me I think I found the culprit. We have an ignition with in it a part which formats the 2nd disk, which we eventually mount on /var/lib/docker
    "filesystems": [
      {
        "mount": {
          "device": "/dev/sdb",
          "format": "xfs",
          "label": "EPHEMERAL",
          "wipeFilesystem": true
        },
        "name": "ephemeral"
      }

The problem is that there is no guarantee that during boot, /dev/sdb is actually the second disk. Sometimes the disknames are swapped...just a feature of linux enumeration I guess, so the root might be /dev/sdb and the second disk /dev/sda...and when that happens it formats the root/boot disk and everything is gone. It would be nice to be able to prevent this. Changing "/dev/sdb" to:  "/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:1:0", seems to have a more stable effect but still it's not 100% proof....it's actually strange that it even seems to help, but hey :).

So I see some thumbs ups on this case but I don't know if they're doing something similar. For me personally I think this can be closed. If there are known ways around this disk swapping and formatting disks I'd love to hear it though.
Will leave it open for comments for now and close later...

**Comment by pothos** [comment]
The trick is to use `/dev/sdb` or similar only for the initial partitioning step and from there on you use stable reference, e.g., the partition label as reference for filesystem formatting, and the filesystem label for mounting.

**Comment by mrdima** [comment]
Yes, we use labels for mount reference but that doesn't help fix this issue. It can happen that on first boot, the /dev/sdb is already swapped to /dev/sda, (and so /dev/sdb is the boot disk with all flatcar partitions) then what?

**Comment by pothos** [comment]
Right, in that case Ignition has no good mechanisms to express this and you would need to retry the provisioning step… Would be nice to have a better matching logic in `storage: disks: device:`, e.g., here the expression could be `/dev/sd*` if `/dev/disk/by-label/EFI-SYSTEM` does not point to it. For now you would need to shift this logic into a separate systemd service.
