### ISSUE TITLE
Document how to build a custom image

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#38]
While Ignition allows to download files/binaries from a remote location and store them somewhere (except `/usr`), this download phase can be avoided if the files are provided as part of a custom image.

We should publish how to modify the image and how to install a modified image with `flatcar-install`. Decide which image types to use because some cases like PXE images may be more involved.

- [x] Create document on how to build custom images
- [ ] Add documentation on using flatcar-install to update an existing installation with the image created

**Comment by t-lo** [comment]
We're 50% there: https://kinvolk.io/docs/flatcar-container-linux/latest/reference/developer-guides/sdk-modifying-flatcar/

We now need to add documentation to https://github.com/kinvolk/flatcar-docs/tree/main/docs/reference/developer-guides on how to host that image and use `flatcar-install` to update existing installations.

Updated the issue accordingly to reflect progress.

**Comment by tormath1** [comment]
I think the last remaining items is done here: https://www.flatcar.org/docs/latest/installing/bare-metal/installing-to-disk/. @pothos OK to close this issue ?

**Comment by pothos** [comment]
The item I wanted to address is now done with
https://www.flatcar.org/docs/latest/installing/customizing-the-image/customize-the-image/
(this wasn't about building from source but customizing a release image).

The follow up about using it with flatcar-install is a minor issue and it's half documented as @tormath1 showed.
Yes, ok to close.
