### ISSUE TITLE
DefaultTasksMax is 15% regardless of documentation

### ISSUE THREAD

**Issue by hasso** [flatcar/Flatcar#382]
**Description**

The problem seems to be that 0007-core-use-max-for-DefaultTasksMax.patch in
coreos-overlay/sys-apps/systemd/files does nothing actually – it defines DEFAULT_TASKS_MAX_PERCENTAGE and DEFAULT_USER_TASKS_MAX_PERCENTAGE, but these are not used in anywhere.

**Comment by sayanchowdhury** [comment]
Thanks for filing the issue. A fix has been merged and deployed across all the channels. https://github.com/kinvolk/coreos-overlay/pull/971

Please upgrade to the latest version and verify if the fix works. Feel free to open the issue, if the issues persist.
