### ISSUE TITLE
How to setup flatcar build environment of c++ projects 

### ISSUE THREAD

**Issue by comphilip** [flatcar/Flatcar#383]
**Current situation**
[tmux](https://github.com/tmux/tmux) is not included in flatcar container linux. While the tool is very useful for me for administration and troubleshooting. I want to build static-link tmux on my own.

I cannot found document how to setup c++ build environment for flatcar container linux. So I build tmux in ubuntu and debian docker image, the built tmux runs well in ubuntu and debian, but exit immediately in flatcar.

Not finding very useful information after debug log turned on.

**Impact**
It is helpful for developers to migrate tools that may be not famous but valuable to themselves.

**Ideal future situation**
It is better to have docker build environment image.

**Comment by pothos** [comment]
Hi,
here is a workaround to use tmux in the toolbox:
https://kinvolk.io/docs/flatcar-container-linux/latest/setup/debug/install-debugging-tools/#spawn-a-toolbox-with-tmux-in-the-background
