### ISSUE TITLE
IPv6 address auto-configuration doesn't work on AWS EC2 instances

### ISSUE THREAD

**Issue by akolosov-a** [flatcar/Flatcar#384]
**Description**
Flatcar Linux doesn't configure IPv6 address on AWS EC2 instances with IPv6 address assignment enabled.

**Impact**
AWS EC2 instances running Flatcar Linux don't have IPv6 connectivity.

**Environment and steps to reproduce**

1. **Set-up**: Flatcar Linux 2765.2.2 on an AWS EC2 instance with IPv6 enabled.
2. **Task**: Running an IPv6-enabled Kubernetes node using Flatcar Linux in AWS.
3. **Action(s)**:
  a. Create an AWS EC2 instance with IPv6 enabled using the latest stable Flatcar Linux AMI.
  b. SSH to the node and check if it has IPv6 connectivity by pinging some IPv6 destination with `ping6`
  c. Check if the node has a global IPv6 address configured with `ip -6 addr show dev eth0`
4. **Error**: No IPv6 connectivity on the node:
```bash
$ ping6 ipv6.google.com
connect: Network is unreachable

$ ip -6 addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    altname enp0s5
    altname ens5
    inet6 fe80::1027:3cff:feab:dcb/64 scope link
       valid_lft forever preferred_lft forever
```

**Expected behavior**
Interface is configured with IPv6 address assigned to the node by AWS and IPv6 connectivity works out of the box.

**Additional information**
1. The workaround for the issue is to explicitly enable IPv6 Router Advertisement on the interface via drop-in for the default networkd unit:
```bash
$ sudo tee /etc/systemd/network/zz-default.network.d/ipv6-fix.conf <<EOF
[Network]
IPv6AcceptRA=true
EOF

$ sudo systemctl restart systemd-networkd

$ ip -6 addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
...
    inet6 2600:1f18:46ab:af01:e69a:2cb9:8448:ff79/128 scope global dynamic noprefixroute
...

$ ping6 -c1 ipv6.google.com
PING ipv6.google.com(iad23s63-in-x0e.1e100.net) 56 data bytes
64 bytes from iad23s63-in-x0e.1e100.net: icmp_seq=1 ttl=110 time=0.903 ms

--- ipv6.google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.903/0.903/0.903/0.000 ms
```
2. The latest version of Flatcar Linux where IPv6 address auto-configuration worked fine was 2605.10.0. After that version we have jumped over to the latest 2765.2.x where it stopped working out of the box.

**Comment by oliwer** [comment]
This is certainly linked to #397.

**Comment by amasover** [comment]
This is broken in Stable, but still works on LTS (testing on Azure).

**Comment by x4e-jonas** [comment]
```
[Network]
IPv6AcceptRA=true
```
This didn't work for me in #397.

Systemd 249 announced a bunch of DHCP related fixes. I can give it a try once there is an alpha/beta.

**Comment by akunszt** [comment]
Adding the `IPv6AcceptRA=yes` worked for me on `Flatcar Container Linux by Kinvolk beta 3033.1.1 for Amazon EC2` using systemd 249.
I created `/etc/systemd/network/50-eth.network` with the contents below.
```
[Network]
DHCP=yes
IPv6AcceptRA=yes

[Match]
Name=eth*

[DHCP]
UseMTU=true
UseDomains=true
```

**Comment by x4e-jonas** [comment]
Yes, I was about to post this too in #397 but I first run into a second issue: https://github.com/systemd/systemd/issues/18996

I took me some time to notice this was still broken in stable until 3033.2.0 that was just released now.

**Comment by sayanchowdhury** [comment]
PR [#1589](https://github.com/flatcar-linux/coreos-overlay/pull/1589) and [#1587](https://github.com/flatcar-linux/coreos-overlay/pull/1587) also fixes the RAs for the address assignment and they should be available in the next set of releases.

**Comment by pothos** [comment]
Ok, merged this now and it should work in the next Alpha release
