### ISSUE TITLE
Missing binaries in releases of ct

### ISSUE THREAD

**Issue by Beetix** [flatcar/Flatcar#385]
**Description**

Although mentioned in the README the binaries are missing in releases of ct

**Impact**

Unable to run ct without compiling (or docker)

**Environment and steps to reproduce**

1. **Set-up**: ct v0.9.0
2. **Task**: Download binary from release
3. **Action(s)**: 
  a. `curl -L https://github.com/flatcar-linux/container-linux-config-transpiler/releases/download/v0.9.0/ct-v0.9.0-x86_64-unknow-linux-gnu -o /tmp/ct-v0.9.0-x86_64-unknow-linux-gnu`
  b. `cat /tmp/ct-v0.9.0-x86_64-unknow-linux-gnu`
4. **Error**: `Not found`

**Expected behavior**
Expected ct binary

**Additional information**

**Comment by bobhenkel** [comment]
In addition the helper script that is in the README that points to a public signing key at a coreos link no longer exists. The link is https://coreos.com/dist/pubkeys/app-signing-pubkey.gpg. Everything coreos.com is forwarded to openshift.com landing page.

**Comment by tormath1** [comment]
Hi @Beetix, 

Thanks for raising the issue - the missing binaries are back in the latest v0.9.1 [release](https://github.com/kinvolk/container-linux-config-transpiler/releases/tag/v0.9.1) :tada:
