### ISSUE TITLE
NFS not mounted at boot

### ISSUE THREAD

**Issue by Beetix** [flatcar/Flatcar#386]
**Description**

I am trying to mount a NFS but it is not mounted at boot

**Impact**

Missing mount at boot

**Environment and steps to reproduce**

1. **Set-up**: Flatcar 2765.2.2
Container Linux config:
```
systemd:
  units:
    - name: mnt-nfs.mount
      enable: true
      contents: |
        [Unit]
        Before=remote-fs.target
        [Mount]
        What=10.0.0.1:/srv/nfs
        Where=/mnt/nfs
        Type=nfs
        [Install]
        WantedBy=remote-fs.target
```
2. **Task**: Running Flatcar image
3. **Action(s)**: Boot Flatcar image
4. **Error**: No mount
```
core@localhost ~ $ sudo systemctl status mnt-nfs.mount
● mnt-nfs.mount - /mnt/nfs
     Loaded: loaded (/etc/systemd/system/mnt-nfs.mount; disabled; vendor preset: enabled)
     Active: inactive (dead)
      Where: /mnt/nfs
       What: 10.0.0.1:/srv/nfs
```

**Expected behavior**
NFS mounted

**Additional information**
Mounting works once logged in when issuing `systemctl start mnt-nfs.mount`

**Comment by pothos** [comment]
Was the image was booted once already? The service is disabled which I think means that the `enabled: true` did not work because it was not the first boot, read https://kinvolk.io/docs/flatcar-container-linux/latest/provisioning/ignition/boot-process/#reprovisioning

**Comment by Beetix** [comment]
> Was the image was booted once already? The service is disabled which I think means that the `enabled: true` did not work because it was not the first boot, read https://kinvolk.io/docs/flatcar-container-linux/latest/provisioning/ignition/boot-process/#reprovisioning

Yes it was but I created a file under `/boot/flatcar/first_boot` for reprovisioning as mentioned in the link you gave

**Comment by pothos** [comment]
Yes, and that is not enough because Ignition handles `vendor preset: enabled` but if you want to enable the service after the very first boot, you need to create the symlink manually with Ignition as written in the link.

**Comment by Beetix** [comment]
> Yes, and that is not enough because Ignition handles `vendor preset: enabled` but if you want to enable the service after the very first boot, you need to create the symlink manually with Ignition as written in the link.

Ah... I missed that, excuse me. Thanks for your help!

**Comment by pothos** [comment]
No problem. The same thing can also happen when the image is cloned after being booted (and more bad things like having the same `/etc/machine-id` etc).
