### ISSUE TITLE
Changing Docker Version on Flatcar

### ISSUE THREAD

**Issue by mikekuzak** [flatcar/Flatcar#389]
Hi,

Does the possibility of changing the Docker version still exists in Flatcar ? 
For CoreOS this was the way to go:

https://support.coreos.com/hc/en-us/articles/360005202674-Update-Docker-on-CoreOS-using-torcx

**Comment by pothos** [comment]
Torcx is still around but here is another way which is more accessible: https://kinvolk.io/docs/flatcar-container-linux/latest/container-runtimes/use-a-custom-docker-or-containerd-version/
Currently it has the problem that you need to invoke the binary at the right path (or setup the PATH) but in the future one could use systemd-sysext for an overlay on /usr.
