### ISSUE TITLE
No virtio_network interface when running via Firecracker

### ISSUE THREAD

**Issue by bzub** [flatcar/Flatcar#39]
We've been running Flatcar via qemu/KVM for some time without issue and I wanted to try the same thing with firecracker/KVM. In both cases we use the `flatcar_production_pxe.vmlinuz` for kernel and `flatcar_production_pxe_image.cpio.gz` for initrd/root.

On a VM booted with qemu I get a network interface:
```
$ sudo ethtool -i eth0
driver: virtio_net
version: 1.0.0
firmware-version:
expansion-rom-version:
[...]
```

But with firecracker, which I believe should use the same KVM virtual hardware, there's only a loopback interface and the kernel doesn't seem to detect the network interface, so `virtio_net` is never loaded. Anyone know why that might happen?

I will post a script I use to reproduce this (run flatcar via firecracker) soon to help troubleshoot.

**Comment by bzub** [comment]
For example, using [flatcar_firecracker.sh](https://gist.github.com/bzub/821190de5a58cf2e93e9cc01def89831):

```sh
cat <<EOF >/tmp/flatcar_firecracker_vm.json
{
  "boot-source": {
    "kernel_image_path": "/tmp/flatcar/vmlinux",
    "initrd_path": "/tmp/flatcar/initramfs",
    "boot_args": "ipv6.disable=1 flatcar.autologin console=tty0 console=ttyS0"
  },
  "drives": [],
  "machine-config": {
    "vcpu_count": 2,
    "mem_size_mib": 10240,
    "ht_enabled": false
  },
  "network-interfaces": [
    {
      "iface_id": "eth0",
      "guest_mac": "AA:FC:00:00:00:01",
      "host_dev_name": "tap0@enp6s0"
    }
  ]
}
EOF

sudo VM_CONFIG=/tmp/flatcar_firecracker_vm.json ./flatcar_firecracker.sh start
```

From inside the VM:
```
core@localhost ~ $ sudo ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
```

**Comment by bzub** [comment]
To support running Flatcar via Firecracker some adjustments might be needed to the kernel config, as I have successfully done it by using the kernel documented in Firecracker's [Getting Started](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md) docs.

https://github.com/firecracker-microvm/firecracker/blob/master/resources/microvm-kernel-config

**Comment by pothos** [comment]
Thanks for the detailed report, that's very helpful! We will need to compare it to our kernel config, try if it works and then see if that's something for the Edge channel or the regular channels.

**Comment by t-lo** [comment]
Hi @bzub ,

reading the kernel config recommendation you've referenced it appears that everything is compiled into the kernel, there are no kernel modules. It further appears that the `virtio_net` module is not loaded automatically on boot when running as a firecracker VM.

Could you please investigate whether it's possible to set up Flatcar with firecracker so that `virtio_net` is loaded upon each boot (e.g. by injecting a respective systemd unit)?

**Comment by bzub** [comment]
Hey @t-lo 

Even when I loaded the `virtio_net` module manually the network interface still didn't exist with the flatcar kernel + firecracker. Something else is enabled in their kernel config that must be causing this, but I don't know what yet.

**Comment by pothos** [comment]
This is fixed now.

```
dd if=flatcar_production_image.vmlinuz skip=`grep -a -b -o -m 1 -P '\x1f\x8b\x08\x00' flatcar_production_image.vmlinuz | cut -d: -f 1` bs=1 | zcat > vmlinux
```

```
{
  "boot-source": {
    "kernel_image_path": "vmlinux",
    "boot_args": "rootflags=rw mount.usrflags=ro BOOT_IMAGE=/flatcar/vmlinuz-a mount.usr=/dev/mapper/usr verity.usr=PARTUUID=7130c94a-213a-4e5a-8e26-6cce9662f132 consoleblank=0 root=LABEL=ROOT console=ttyS0,115200n8 console=tty0 flatcar.autologin verity.usrhash=aba44af6a6660331cb8d6be8beeb383326cf487eff1983423aa1a0308aa543fb rd.driver.pre=virtio_mmio console=ttyS0 reboot=k panic=1 i8042.noaux i8042.nomux i8042.nopnp i8042.dumbkbd"
  },
  "drives": [
    {
      "drive_id": "rootfs",
      "path_on_host": "flatcar_production_image.bin",
      "is_root_device": false,
      "is_read_only": false
    }
  ],
  "machine-config": {
    "vcpu_count": 1,
    "mem_size_mib": 1048,
    "ht_enabled": false
  }
}
```

where the `usrhash` comes from the `/proc/cmdline` of a booted QEMU VM instance, for example. Note that updates won't work because the kernel is kept outside of the image, so I recommend to disable update engine.
On first boot to run Ignition you have to add `flatcar.first_boot=1`.
