### ISSUE TITLE
Update Iptables from 1.6.2 to 1.8.x in flatcar OS version 2605.8.0

### ISSUE THREAD

**Issue by amitsingla** [flatcar/Flatcar#394]
## Current situation

Currently, we are running Kubernetes clusters on flatcar OS in production. 
Kubernetes 1.16.x onwards updated their internal iptables version within the hyperkube images to 1.8.3(nft) . However the iptables version on flatcar OS remains 1.6.2.

Kube-proxy which is a component of kubernetes utilizes iptables internally for all pod routing and the version of iptables they are using 1.8.3( using --random-fully as a mandatory flag)  which is incompatible with the host OS(flatcar). This is causing the iptables rules to break on the host. 

## Impact

We are unable to upgrade kubernetes running on flatcar OS because of iptables incompatible version with Kubernetes hyperkube image 1.16.x onwards. 

## Ideal future situation

Update iptables to 1.8.3 on flatcar OS.

**Comment by jepio** [comment]
This shipped in stable 3033.2.0 (https://www.flatcar.org/releases/#release-3033.2.0), please try that version.

**Comment by amitsingla** [comment]
Thanks @jepio.  I will test this flatcar version in coming weeks and get back to you if I have any further questions/issues.
