### ISSUE TITLE
[RFE] Update OpenSSH to at least 8.2 for FIDO support

### ISSUE THREAD

**Issue by invidian** [flatcar/Flatcar#395]
## Current situation

Currently Flatcar use OpenSSH 8.1p1

## Impact

OpenSSH 8.2 supports FIDO/U2F authentication (https://www.openssh.com/releasenotes.html#8.2), it would be great to be able to utilize it on Flatcar as well.

## Ideal future situation

OpenSSH is updated to latest available version.

**Comment by dongsupark** [comment]
Filed PR https://github.com/kinvolk/coreos-overlay/pull/1023
