### ISSUE TITLE
DHCPv6 broken since 2765.2.0/Systemd 247

### ISSUE THREAD

**Issue by x4e-jonas** [flatcar/Flatcar#397]
## Description

DHCPv6 is broken since 2765.2.0/Systemd 247.

## Impact

With the configuration below, Flatcar Container Linux 2605.12.0 with Systemd 246 gets a (static) DHCPv6 lease assigned as expected. Since 2765.2.0/Systemd 247 no IPv6 is assigned anymore.

## Environment and steps to reproduce

Container Linux Config:
```yml
networkd:
  units:
    - name: 20-dhcp.network
      contents: |
        [Match]
        Name=eth0

        [Network]
        DHCP=yes

        [DHCP]
        DUIDRawData=[redacted]
        DUIDType=vendor
        UseDomains=true
        UseMTU=true

        [DHCPv6]
        WithoutRA=solicit
```

1. **Set-up**: deploy a Flatcar installation with the above config
2. **Task**: boot the machine
3. **Action(s)**: connect to the machine over IPv4, console etc. and run `ip addr show eth0`
4. **Error**: IPv6 is not configured as expected by the DHCPv6 server

## Expected behavior

IPv6 lease is assigned using the DHCPv6 server as with 2765.2.0/Systemd 247

## Additional information

DHCPv4 works as expected. A rollback to 2605.12.0 fixes the DHCPv6 issue.

**Comment by jepio** [comment]
This is related to this: https://github.com/flatcar-linux/Flatcar/issues/384 and so will be fixed at the same time. Fixed in the next alpha release (after 3128.0.0). Please re-open if this isn't the case.
