### ISSUE TITLE
[RFE] Upgrade Config Transpiler so it would support new ETCD versions

### ISSUE THREAD

**Issue by opiumfor** [flatcar/Flatcar#398]
## Current situation

The Config Transpiler (ct) seem to be not upgraded since 2018, just forked
from CoreOS as is. The problem is that current version of Config Transpiler does not allow us
to upgrade etcd, because allowed versions are hardcoded into ct:
 
https://github.com/coreos/container-linux-config-transpiler/blob/master/config/types/etcd.go#L51

## Impact
We can't upgrade ETCD to fresh versions

## Ideal future situation
Fresh ETCD versions can be installed using configs made by Config Transpiler, so we could automatically provision VM's with Flatcar Linux in clouds, e.g. Openstack.

## **Implementation options
Allow to use fresh versions somewhere here, and test if it works as expected
https://github.com/coreos/container-linux-config-transpiler/blob/master/config/types/etcd.go#L51

## Additional information
The reason we need it is that fresh Kubernetes versions are using ETCD 3.4 and above by default.

**Comment by pothos** [comment]
Thanks for filing the issue. As workaround you can directly specify the resulting Ignition entries as regular Container Linux Config entries (for etcd this is mostly the systemd drop in unit).

Maybe we need to think whether it actually makes sense to have Flannel and Etcd as special cases baked into the specification of the Container Linux Config.

**Comment by jepio** [comment]
Manual labor required here: https://github.com/flatcar-linux/container-linux-config-transpiler/blob/flatcar-master/config/types/etcd.go.

**Comment by pothos** [comment]
We migrated the docs to use Butane now instead of CT.
