### ISSUE TITLE
Documentation bug: Migration from Container Linux to Flatcar

### ISSUE THREAD

**Issue by joerggollnick** [flatcar/Flatcar#4]
While migrating from Container Linux bare metal to Flatcar path to user_data changes from /var/lib/coreos-install/ to /var/lib/flatcar-install. 
Please add an optional step into migration documentation.

**Comment by iaguis** [comment]
We added a note about this, it will be online soon.

**Comment by iaguis** [comment]
This is online now: https://docs.flatcar-linux.org/os/update-from-container-linux/#modifying-the-configuration-files

Please reopen if that's not clear enough.

Thanks!
