### ISSUE TITLE
[RFE] Add instruction for reporting security issues to README.md and via GitHub security policy

### ISSUE THREAD

**Issue by invidian** [flatcar/Flatcar#402]
## Current situation

`README.md` currently only mentions that problems should be reported via issues. It would be good to better align with https://kinvolk.io/flatcar-container-linux/security/ and mention channels for reporting security issues.

## Impact

Security issues might get accidentally disclosed because of lack of clear secure communication channels for reporting security issues.

## Ideal future situation

It is clearly documented where to report possible security issues.

## **Implementation options

- add section with security email to README.md 
- add GitHub security policy

**Comment by dongsupark** [comment]
This has been done by creating [SECURITY.md](https://github.com/flatcar/Flatcar/blob/5c270131f1c54f14fb89a330cbc1238fcb923189/SECURITY.md) via https://github.com/flatcar/Flatcar/pull/1039.
If there is more to update the docs, feel free to open a new issue or create a PR.
