### ISSUE TITLE
Docker 19.03.7 released - Flatcar is two releases behind

### ISSUE THREAD

**Issue by sxiii** [flatcar/Flatcar#41]
The title says it's all. Would be nice to have an update at least for the testing branch. Thanks

**Comment by t-lo** [comment]
Thanks for the report! Please note that we are currently still following CoreOS with our Beta and Stable releases, to ease transition and minimise risk for users who want to migrate to Flatcar.

However, your call-out is absolutely relevant for our Alpha and Edge channels.

**Comment by sxiii** [comment]
Thanks for answering, @t-lo. I understand. But yeah; strange to have the same version in different channels. :)

**Comment by dongsupark** [comment]
FYI, we updated Docker to 19.03.8 for Alpha.
https://github.com/flatcar-linux/coreos-overlay/pull/227
It will be included in the next Alpha release.

**Comment by dongsupark** [comment]
Docker was updated to 19.03.8 for Alpha 2466.0.0 and Edge 2466.99.0.
