### ISSUE TITLE
Rename github org to flatcar-linux in each repo

### ISSUE THREAD

**Issue by dongsupark** [flatcar/Flatcar#410]
The following Github repos still rely on Github org name `coreos`.

* https://github.com/kinvolk/afterburn
* https://github.com/kinvolk/coreos-cloudinit
* ~https://github.com/kinvolk/ignition~
* ~https://github.com/kinvolk/mantle~
* https://github.com/kinvolk/sdnotify-proxy
* https://github.com/kinvolk/update-ssh-keys

We should update the repos above, so they could have the correct Github org name `flatcar-linux`.

See also https://github.com/kinvolk/coreos-overlay/pull/1041#pullrequestreview-673255797 .

**Comment by tormath1** [comment]
it would maybe not be required to move the `flatcar-linux` go projects. See https://github.com/kinvolk/Flatcar/issues/452

**Comment by dongsupark** [comment]
Updated the title and the description.

**Comment by vbatts** [comment]
worth mentioning, we have github.com/flatcar that we've discussed whether and how to migrate to

**Comment by dongsupark** [comment]
Dup of https://github.com/flatcar/Flatcar/issues/543.
