### ISSUE TITLE
Doesn't explain how to add more than one static route

### ISSUE THREAD

**Issue by ronnessim** [flatcar/Flatcar#412]
The documentation doesn't explain how to add multiple static routes. 

https://kinvolk.io/docs/flatcar-container-linux/latest/setup/customization/network-config-with-networkd/

Should the [route] section be repeated?

**Comment by tormath1** [comment]
Hi @ronnessim , thanks for raising this issue ! 

Actually, this question is more on the side of `systemd.network`. Please find the associated documentation: 
> [...] Specify several [Route] sections to configure several routes.

[[doc](https://www.freedesktop.org/software/systemd/man/systemd.network.html#%5BRoute%5D%20Section%20Options)]
