### ISSUE TITLE
migrate to 17.1 profiles

### ISSUE THREAD

**Issue by jepio** [flatcar/Flatcar#428]
## Current situation

On every emerge operation the following message is printed:
```
!!! Your current profile is deprecated and not supported anymore.
!!! Use eselect profile to update your profile.
!!! Please upgrade to the following profile if possible:

        default/linux/amd64/17.1/no-multilib/hardened

To upgrade do the following steps:

The amd64 17.1 profiles switch to a more standard 'no SYMLINK_LIB'
multilib layout, and require an explicit migration.
The migration is performed using the app-portage/unsymlink-lib tool.
The following steps can be used to upgrade your system:
```

## Impact

Annoying and unsupported upstream.

## Ideal future situation

flatcar profile upgraded to 17.1.

## Additional information

The only real difference between 17.0 and 17.1 profiles is defaulting to "SYMLINK_LIB=no" (instead of "yes"), which affects whether lib is a symlink to lib64 or a proper directory. The arm64 profiles already use SYMLINK_LIB=no. There might be a couple spots in ebuilds and SDK thataccidentally rely on the symlink, but we can weed them out.

**Comment by jepio** [comment]
Problematic with stage1/stage2 bootstrap. If stage1 uses old ebuilds, then its built with old profile, and stage2 switches profile (fail); if stage1 uses new ebuilds it fails because old seed.

Also requires updating a bunch of docs that reference /usr/lib64 paths that might not be correct after profile update (/usr/lib/systemd as an example).

**Comment by sayanchowdhury** [comment]
@krnowak can we close this, as we have migrated to 17.1? 
ref: https://github.com/flatcar/coreos-overlay/pull/2502

**Comment by krnowak** [comment]
Yes, it's done. I forgot that we had an issue about it filed.
