### ISSUE TITLE
ARM 32-bit builds on the download page

### ISSUE THREAD

**Issue by larstobi** [flatcar/Flatcar#43]
It is great that there are ARM64 builds on the download page. However, I also have ARM 32-bit processors that I'd like to run Flatcar Linux on.

Can we have ARM 32-bit builds as well?

**Comment by jepio** [comment]
Thanks for the issue - it would be cool but:
- introducing and maintaining a platform is a lot of work
- 32-bit platforms are slowly disappearing
- most ARM systems require custom bootloaders/kernels
 
We are going to be working on #502, though. So I'm going to have to close this issue.
