### ISSUE TITLE
System clock not synchronized

### ISSUE THREAD

**Issue by DeltaFox0018** [flatcar/Flatcar#435]
## Description

Hello, in the prod environment all flatcar cars do not have the clock synchronized via NTP server, instead in staging machines with flatcar have active synchronization with NTP servers
Machines re-emerge on Azure on two different resource groups but configured in the same way, the only thing that changes is the amount of machines.
In prod not having the timing synchronized I cause problems with JWT tokens since I’m ahead even a few minutes sometimes

Prod not sync clock
![Not Sync Prod](https://user-images.githubusercontent.com/35847603/126680867-8499563a-474e-4bff-9ce1-ddfc36117f39.png)

Staging sync clock
![Sync Staging](https://user-images.githubusercontent.com/35847603/126681399-fa769382-0fb3-461a-a611-c8837266632c.png)

**Comment by jepio** [comment]
Hi, can you compare and paste the output of `sudo timedatectl show-timesync --all` and `sudo systemctl status systemd-timesyncd` on both machines. Is networking configured in the same way for both environments? Are you sure both VMs can access the NTP servers?

**Comment by jepio** [comment]
and also `sudo timedatectl timesync-status`.

**Comment by DeltaFox0018** [comment]
Hello,
the network configuration is configured in the same way on both Azure resource groups but on the prod environment when trying to contact an NTP server goes in timeout

here the screen of the 3 commands indicated

Prod screen
![image](https://user-images.githubusercontent.com/35847603/126776546-10609d28-251e-495b-ad92-a057e046d537.png)

Staging screen
![image](https://user-images.githubusercontent.com/35847603/126776684-61289120-4748-4548-98ea-d700f42a5fcb.png)

**Comment by jepio** [comment]
That's weird - can you try pinging that ntp server (`94.198.159.11`) from prod to see if its a connectivity issue?

You can try a different ntp config for the prod env. Replace the contents of `/etc/systemd/timesyncd.conf` with:
```
[Time]
NTP=pool.ntp.org
```
and then reboot or `systemctl restart systemd-timesync`

**Comment by DeltaFox0018** [comment]
Hello,

ping in both prod and staging environments does not work even if it is all configured correctly
Also even after editing the file and restarting systemd-timesyncd continues to timeout

**Comment by DeltaFox0018** [comment]
Should I try to contact Microsoft for information about the network configuration?

**Comment by jepio** [comment]
Yes please - that would probably be the best course of action.

**Comment by jepio** [comment]
I'll close this, since it seems like an Azure networking issue.
