### ISSUE TITLE
How can I install python on Flatcar

### ISSUE THREAD

**Issue by alpana17** [flatcar/Flatcar#439]

**Comment by pothos** [comment]
Hi,

you can use https://www.pypy.org/download.html which is easier to install than cpython if you need a python interpreter. Other options are compilation to a binary with https://github.com/Nuitka/Nuitka (edit: called out numba first by mistake)

**Comment by pothos** [comment]
In case you use Ansible there is this: https://github.com/vmware/ansible-coreos-bootstrap
