### ISSUE TITLE
air-gapped install / updates?

### ISSUE THREAD

**Issue by austinnichols101** [flatcar/Flatcar#44]
Is there a manual installation procedure for flatcat installation that do not have internet access?

Is there a manual update procedure for flatcar installations that do not have internet access?

**Comment by pothos** [comment]
For the installation you can download the image in advance and provide it to `flatcar-install` via `-f filename`. To server updates you would need an internal [Nebraska](https://github.com/kinvolk/nebraska/) running but of course it needs to sync from our public instance through the Internet if you do not internally push the update payloads to it yourself.
