### ISSUE TITLE
Ignition configuration with VMware not aligned with stable image 2345.3.0

### ISSUE THREAD

**Issue by DiCanio** [flatcar/Flatcar#45]
We are currently in the process of transitioning from Core OS on VMWare as its EOL has been announced.
There is a section in the documentation about migrating from Core OS with regards to [VMWare ](https://docs.flatcar-linux.org/os/migrate-from-container-linux/#ignition-configuration-with-vmware).

It states the following:
> Optional: Instead of `coreos.config.data` and `coreos.config.data.encoding` for the VMware `guestinfo.VARIABLE` command line options you need to use `ignition.config.data` and `ignition.config.data.encoding`. As for the kernel parameter this change was done upstream by the Ignition project.

When following this information the virtual machine cannot be started. Instead an error is produced stating that these vApp properties do not exist.

Having a look into the current stable (2345.3.0) image the following entries surface:

```
<Property ovf:userConfigurable="true" ovf:type="string" ovf:key="guestinfo.coreos.config.data" ovf:value="">
  <Label>CoreOS config data</Label>
  <Description>Inline cloud-config data</Description>
</Property>
<Property ovf:userConfigurable="true" ovf:type="string" ovf:key="guestinfo.coreos.config.url" ovf:value="">
  <Label>CoreOS config url</Label>
  <Description>URL to cloud-config data</Description>
</Property>
<Property ovf:userConfigurable="true" ovf:type="string" ovf:key="guestinfo.coreos.config.data.encoding" ovf:value="">
  <Label>CoreOS config data encoding</Label>
  <Description>Encoding for cloud-config data</Description>
</Property>
```

So the current `stable` image does not align with what is stated in the documentation (not sure if the documentation is ahead of the stable image). Usage of former variables `guestinfo.coreos.config.data` and `guestinfo.coreos.config.data.encoding` is still required.

Affected version: `2345.3.0`
Platform: `VMWare`

**Comment by pothos** [comment]
Yes, correct, we got a report already and fixed it for the next release (not yet published) by adding the new generic variables to the OVF XML template. We have to fix it in the docs until the release is done.

**Comment by DiCanio** [comment]
Thanks for reaching out.
Let me know if contribution is wanted.

**Comment by pothos** [comment]
I've tried to make this temporary situation clearer here: https://github.com/flatcar-linux/docs/pull/59

Pointing out bugs is already very helpful, also in the docs (PRs are welcome). Thanks for reporting!

**Comment by t-lo** [comment]
Reopening as we've received information on this issue still affecting some users after the 2345.3.1 release.

**Comment by pothos** [comment]
https://github.com/flatcar-linux/ignition/pull/11 fixes support for both guest variables. In https://github.com/flatcar-linux/scripts/pull/56 the old variables are removed from the OVF metadata but will continue to work when specified via `ovftool --X:guest:coreos.config.…`.

**Comment by pothos** [comment]
Created a docs PR to change the default variable used: https://github.com/flatcar-linux/docs/pull/93
Closing this now as both are supported anyway in all current releases.
