### ISSUE TITLE
Cilium breaks on stable-2905.2.0

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#455]
## Description

Cilium containers appear to be unable to start on the new Stable-2905.2.0 release. After updating a node, the cilium containers are not running. Verified with cilium 1.9.4 and 1.9.8.

## Impact

Cluster loses networking and becomes inaccessible.

## Environment and steps to reproduce

1. **Set-up**: Kubernetes Cluster with cilium 1.9.x, Flatcar 2765.2.6 or earlier.
2. **Task**: Update via Flatcar's update mechanism.
3. **Action(s)**:
  a. Update downloads and installs automatically
  b. Node reboots
4. **Error**: Cilium containers fail to start

## Expected behavior

Cilium containers launch as expected, cluster remains accessible via network.

## Additional information

PR for adding container networking tests to CI / release tests to prevent these issues in the future: https://github.com/kinvolk/mantle/pull/182

The PR can also be used to repro this issue.

**Comment by pothos** [comment]
The workaround I try to verify now is:
```
printf '[Match]\nName=cilium_vxlan\n[Link]\nUnmanaged=yes\n' | sudo tee /etc/systemd/network/20-cilium_vxlan.network
sudo networkctl reload
```

**Comment by pothos** [comment]
The newly added kubeadm.cilium.base kola test passed with the workaround for kola.

```
diff --git a/kola/tests/kubeadm/kubeadm.go b/kola/tests/kubeadm/kubeadm.go
index 44b47387..d70ac9d6 100644
--- a/kola/tests/kubeadm/kubeadm.go
+++ b/kola/tests/kubeadm/kubeadm.go
@@ -71,6 +71,17 @@ systemd:
   units:
     - name: etcd-member.service
       enabled: true
+storage:
+  files:
+    - path: /etc/systemd/network/20-cilium_vxlan.network
+      filesystem: root
+      mode: 0644
+      contents:
+        inline: |
+          [Match]
+          Name=cilium_vxlan
+          [Link]
+          Unmanaged=yes
 `)
 )
 
diff --git a/kola/tests/kubeadm/templates.go b/kola/tests/kubeadm/templates.go
index 6943a6f0..7b064d1f 100644
--- a/kola/tests/kubeadm/templates.go
+++ b/kola/tests/kubeadm/templates.go
@@ -51,6 +51,15 @@ var (
         WantedBy=multi-user.target
 storage:
   files:
+    - path: /etc/systemd/network/20-cilium_vxlan.network
+      filesystem: root
+      mode: 0644
+      contents:
+        inline: |
+          [Match]
+          Name=cilium_vxlan
+          [Link]
+          Unmanaged=yes
     - path: /opt/cni-plugins-linux-{{ .Arch }}-{{ .CNIVersion }}.tgz
       filesystem: root
       mode: 0644
@@ -135,6 +144,15 @@ storage:
         WantedBy=multi-user.target
 storage:
   files:
+    - path: /etc/systemd/network/20-cilium_vxlan.network
+      filesystem: root
+      mode: 0644
+      contents:
+        inline: |
+          [Match]
+          Name=cilium_vxlan
+          [Link]
+          Unmanaged=yes
     - path: /opt/cni-plugins-linux-{{ .Arch }}-{{ .CNIVersion }}.tgz
       filesystem: root
       mode: 0644
```

**Comment by pothos** [comment]
The workaround for existing nodes is:

```
printf '[Match]\nName=cilium_vxlan\n[Link]\nUnmanaged=yes\n' | sudo tee /etc/systemd/network/20-cilium_vxlan.network
sudo networkctl reload
```

And when deploying new nodes you can create the file via Ignition:

Container Linux Config YAML (to be transpiled)
```
storage:
  files:
    - path: /etc/systemd/network/20-cilium_vxlan.network
      filesystem: root
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=cilium_vxlan
          [Link]
          Unmanaged=yes
```

Please tell if this resolves your issue or now. We plan to include this file under /usr/lib/systemd/network/ for a bugfix release.

**Comment by sdlarsen** [comment]
Hi,

Thank you for swiftly dealing with this. The work-around works for me using the following terraform snippet should anyone need it:
```
data "ignition_file" "cilium_fix" {
  filesystem = "root"
  path       = "/etc/systemd/network/20-cilium_vxlan.network"
  mode       = 420

  content {
    content = <<EOF
[Match]
Name=cilium_vxlan
[Link]
Unmanaged=yes
EOF
  }
}
```

FYI: I'm on cilium-10.3.0 and k8s 1.21.3

**Comment by abyth** [comment]
Hi,

can confirm the same for cilium `v1.8.9`. Issue occured during the update operator induced update to flatcar stable 2905.2.0 and could be resolved with the mentioned workaround. Thanks to all participants for the quick fix

**Comment by martin31821** [comment]
Same problem here, fix works for a v1.9.9 and v1.10.2 too.
Last known-working version for me is 2801.1.0.

**Comment by shosti** [comment]
I'm getting similar behavior when using https://github.com/k8snetworkplumbingwg/sriov-network-operator for SR-IOV capabilities. As soon as the VFs are created, systemd seems to try to give them IP addresses through DHCP and the entire node becomes inaccessible.

**Comment by pothos** [comment]
@shosti Before/when creating you need to also have `.network` units which specify the right IP address assingment or mark the interface as `Unmanaged`. That's expected.

**Comment by pothos** [comment]
The fix for the Cilium issue got included in the latest Stable release:
https://kinvolk.io/flatcar-container-linux/releases/#release-2905.2.1

**Comment by Joseph-Irving** [comment]
We're currently seeing strange behaviour with Cilium on any flatcar version greater than 2905.2.1. Most of the time (but weirdly not always) shortly after cilium starts up on the node all network connectivity is lost, i.e the node cannot communicate at all, no ssh no outbound etc.  Nothing else about our setup changed apart from upgrading our flatcar version. 
Are there any obvious suspects to investigate on what might be causing this kind of behaviour?

**Comment by pothos** [comment]
@Joseph-Irving Please try to get some info through the serial console, e.g. `networkctl status` output and `journalctl` output shortly after it happened (best is to use the latest Stable release when reproducing), then open a new issue

**Comment by christianhuening** [comment]
I think you probably have another problem. I am running 2905.2.6 just fine with cilium. also if your entire node is disconnected that's a different level imho than what cilium would affect.

**Comment by Joseph-Irving** [comment]
I've tried running our nodes without cilium and it seems to works just fine @christianhuening, it's only when cilium starts up the problems occur. I'm gonna try and get onto the nodes via the ec2 console @pothos to see what I can find, it's currently awkward to debug as I lose network access to the nodes when this happens

**Comment by schmitch** [comment]
btw. I'm on `stable` thus on `3033.2.0` and it works just fine on k8s cilium and we've run that since way before 2905

**Comment by martin31821** [comment]
@Joseph-Irving which cilium version are you running? There used to be a bug with reboots until 1.9.7

xref: https://github.com/cilium/cilium/issues/16279

**Comment by Joseph-Irving** [comment]
@martin31821 1.9.11, although I've also tried 1.10.6 and the same thing occurred. Also we're not rebooting the nodes to apply the patch, these are fresh new nodes. I've tried stable flatcar versions from 2905.2.1 to the most recent and all exhibited the same behaviour.

**Comment by martin31821** [comment]
I'm running 1.9.11 with several different flatcar versions but all newer than 2905.2.1 up to 3033.2.0 and it works fine.

**Comment by pothos** [comment]
@Joseph-Irving Would be nice to have a new issue for your problem, comments here somehow go under the radar, sorry
