### ISSUE TITLE
Broken link to cloud config migration guide

### ISSUE THREAD

**Issue by vpnachev** [flatcar/Flatcar#458]
In the page https://kinvolk.io/docs/flatcar-container-linux/latest/provisioning/cl-config/ there is a link to a migration guide which is not available. The broken link is https://kinvolk.io/docs/flatcar-container-linux/latest/provisioning/cl-config/migrating-to-clcs. this pages returns 404.

> For help migrating from these legacy cloud-configs to Container Linux Configs, refer to the [migration guide](https://kinvolk.io/docs/flatcar-container-linux/latest/provisioning/cl-config/migrating-to-clcs) .

**Comment by jepio** [comment]
Thanks, the link on the page should work now, and I also added an alias for the old link.

**Comment by vpnachev** [comment]
Thanks for the quick fix! Appreciate it.
