### ISSUE TITLE
flatcar-linux.net is gone

### ISSUE THREAD

**Issue by george-angel** [flatcar/Flatcar#463]
Hello, we have several applications that are using that domain, we have an application to upload GCP images:

https://github.com/utilitywarehouse/flatcar-google-image-uploader/blob/master/flatcar-google-image-uploader#L19 - it uses flatcar-linux.net to find the latest version and download the image: https://github.com/utilitywarehouse/flatcar-google-image-uploader/blob/master/flatcar-google-image-uploader#L38

Also Nebraska is using this domain by default: https://github.com/kinvolk/nebraska/blob/main/backend/cmd/nebraska/nebraska.go#L72

"Releases" page on kinvolk.io also has broken links: https://kinvolk.io/flatcar-container-linux/releases/ (https://stable.release.flatcar-linux.net/amd64-usr/current/) - if you hover over arch link (amd64|arm64).

1. If this change is intended - what domain should we be using now?
2. Was there announcement about `flatcar-linux.net` being removed? What is the best channel to watch for these kind of changes?

Thank you very much.

**Comment by ahrkrak** [comment]
Thanks, this change was not intentional. We have identified this is an issue with a third party cloud provider. We are working to resolve it.

**Comment by george-angel** [comment]
Thank you, looks like its back.
