### ISSUE TITLE
AMI images have changed for 2605.12.0

### ISSUE THREAD

**Issue by remusb** [flatcar/Flatcar#464]
## Description

We're using Flatcar-stable-2605.12.0-hvm in AWS in 4 regions and suddenly, all AMIs for Flatcar went private and are no longer available in the public market.

Previous AMI (went private):
```
us-east-1: ami-0bb4587614fc28248
eu-west-1: ami-06a2a39aecdc787d9
us-west-2: ami-0e844b4a872122e30
ap-northeast-1: ami-06471d461a6d5985b
```

New AMI (public):
```
us-east-1: ami-08c14ca1e0b80d0cf
us-west-2: ami-0f30271f51af1dfd8
eu-west-1: ami-0b50f5c72c2114ee0
ap-northeast-1: ami-008a6dfa49d3814c4
```

Unfortunately, we're also using P3 instances and these are not available with the currently available AMI.

1. We're not sure why the previous AMI disappeared. This has an autoscaling impact on our infrastructure
2. The P3 instances are currently blocked and we can't provision anything with this instance type

## Impact

Multiple autoscaling issues and not able to use AWS P3 instances.

## Environment and steps to reproduce
AWS Marketplace availability

## Expected behavior

AMI should still be available. P3 images should still be supported

Any guidance is appreciated

**Comment by mindw** [comment]
related https://github.com/kinvolk/Flatcar/issues/456#issuecomment-890524322 👎🏻

**Comment by ahrkrak** [comment]
This situation is resolved. We are working on a post mortem.
