### ISSUE TITLE
oem-gce breaks after upgrading flatcar from a version with rkt to systemd-nspawn

### ISSUE THREAD

**Issue by keymon** [flatcar/Flatcar#467]
## Description

We were starting our VMs with an old version of flatcar that uses `rkt`. Then  we noticed the `oem-gce` was failing, as instances started to fail to register in the loadbalancer. 

## Impact

We observed a similar issue to https://github.com/kinvolk/Flatcar/issues/459, the instances failing to listen the TCP loadbalancer IP and not serving traffic. Google support suggested to run the agent, we did run it directly and it fixed the issue.

[ 1 sentence detailing the impact this bug is creating for you ]

## Environment and steps to reproduce

1. Run a old version with rkt on GKE. 
2. Let it upgrade
3. check that gce-oem stops working

The logs of gce-oem:
```
-- Journal begins at Mon 2021-08-02 11:46:06 UTC, ends at Mon 2021-08-02 12:36:23 UTC. --
Aug 02 11:46:25 localhost systemd[1]: Starting GCE Linux Agent...
Aug 02 11:46:53 jumpbox-europe-west1-prod-default-rx82 rkt[850]: + '[' -e /etc/default/instance_configs.cfg.template ']'
Aug 02 11:46:53 jumpbox-europe-west1-prod-default-rx82 rkt[850]: + echo -e '[InstanceSetup]\nset_host_keys = false'
Aug 02 11:46:53 jumpbox-europe-west1-prod-default-rx82 rkt[850]: + /usr/bin/google_instance_setup
...

Aug 02 11:56:57 jumpbox-europe-west1-prod-default-rx82 rkt[850]: ++ stopping=1
....
-- Boot 23bebd36e91a472885b0fd88bfbb9121 --
Aug 02 11:57:24 localhost systemd[1]: Starting GCE Linux Agent...
Aug 02 11:57:25 localhost systemd[1]: oem-gce.service: Main process exited, code=exited, status=203/EXEC
Aug 02 11:57:25 localhost systemd[1]: oem-gce.service: Control process exited, code=exited, status=203/EXEC
Aug 02 11:57:25 localhost systemd[1]: oem-gce.service: Failed with result 'exit-code'.
Aug 02 11:57:25 localhost systemd[1]: Failed to start GCE Linux Agent.
Aug 02 11:57:30 jumpbox-europe-west1-prod-default-rx82 systemd[1]: oem-gce.service: Scheduled restart job, restart counter is at 1.
Aug 02 11:57:30 jumpbox-europe-west1-prod-default-rx82 systemd[1]: Stopped GCE Linux Agent.
Aug 02 11:57:30 jumpbox-europe-west1-prod-default-rx82 systemd[1]: Starting GCE Linux Agent...
Aug 02 11:57:30 jumpbox-europe-west1-prod-default-rx82 systemd[1]: oem-gce.service: Main process exited, code=exited, status=203/EXEC
Aug 02 11:57:30 jumpbox-europe-west1-prod-default-rx82 systemd[1]: oem-gce.service: Control process exited, code=exited, status=203/EXEC
Aug 02 11:57:30 jumpbox-europe-west1-prod-default-rx82 systemd[1]: oem-gce.service: Failed with result 'exit-code'.
Aug 02 11:57:30 jumpbox-europe-west1-prod-default-rx82 systemd[1]: Failed to start GCE Linux Agent.
```

The service definition after upgrade still uses rkt
```
$ cat /etc/systemd/system/oem-gce.service 
[Unit]
Description=GCE Linux Agent
After=local-fs.target network-online.target

[Service]
Type=notify
Restart=always
RestartSec=5

# There is a custom main process that kills all of the contained services.
KillMode=process
KillSignal=SIGTERM

ExecStart=/usr/bin/rkt run \
    --inherit-env=true \
    --insecure-options=image \
    --net=host \
    --stage1-path=/usr/lib/rkt/stage1-images/stage1-fly.aci \
    --volume=etc,kind=host,source=/etc,readOnly=false \
    --volume=home,kind=host,source=/home,readOnly=false \
    --volume=runsystemd,kind=host,source=/run/systemd,readOnly=false \
    --volume=nsswitch,kind=host,source=/usr/share/google-oslogin/nsswitch.conf,readOnly=true \
    --mount=volume=nsswitch,target=/usr/share/google-oslogin/nsswitch.conf \
    /usr/share/oem/flatcar-oem-gce.aci

ExecStopPost=/usr/bin/rkt gc --mark-only

[Install]
WantedBy=multi-user.target

```

## Expected behavior

The service should keep working

**Comment by keymon** [comment]
The workaround will use a image including the patches from https://github.com/kinvolk/Flatcar/issues/459

**Comment by pothos** [comment]
Hello,
the OEM partition content is not updated, there are instructions how to do it manually in the release notes:
https://kinvolk.io/flatcar-container-linux/releases/#release-2905.2.0

GCE: The oem-gce.service was ported to use systemd-nspawn instead of rkt. A one-time action is required to fetch the new service file because the OEM partition is not updated: `sudo curl -s -S -f -L -o /etc/systemd/system/oem-gce.service https://raw.githubusercontent.com/kinvolk/coreos-overlay/fe7b0047ef5b634ebe04c9627bbf1ce3008ee5fa/coreos-base/oem-gce/files/units/oem-gce.service && sudo systemctl daemon-reload && sudo systemctl restart oem-gce.service`

but you can also download https://raw.githubusercontent.com/kinvolk/coreos-overlay/main/coreos-base/oem-gce/files/units/oem-gce.service which has the unreleased fix for the routing entries:

`sudo curl -s -S -f -L -o /etc/systemd/system/oem-gce.service https://raw.githubusercontent.com/kinvolk/coreos-overlay/main/coreos-base/oem-gce/files/units/oem-gce.service && sudo systemctl daemon-reload && sudo systemctl restart oem-gce.service`

**Comment by keymon** [comment]
Oh, ok. I would have expected a way to automatically update these between versions of the stable channel.

Is there any way to recreate these files from the oem partition on boot?

**Comment by pothos** [comment]
Not a generic one but for VMware someone wrote a service that does this, you could roll your own for GCE as follows:

```
source /usr/lib/os-release
MAJOR="${VERSION_ID%%.*}"
curl -s -S -f -L -o /etc/systemd/system/oem-gce.service https://raw.githubusercontent.com/kinvolk/coreos-overlay/flatcar-${MAJOR}/coreos-base/oem-gce/files/units/oem-gce.service
systemctl daemon-reload
systemctl restart oem-gce.service
```
