### ISSUE TITLE
[RFE] Include MOSH as part of flatcar

### ISSUE THREAD

**Issue by mleklund** [flatcar/Flatcar#469]
## Current situation

Mosh is a mobile shell, described as:

Remote terminal application that allows roaming, supports intermittent connectivity, and provides intelligent local echo and line editing of user keystrokes.

Mosh is a replacement for interactive SSH terminals. It's more robust and responsive, especially over Wi-Fi, cellular, and long-distance links.

## Impact

While I can use SSH, sometimes lack of TMUX or MOSH hampers me when I am problem solving on the go.  In my mind mosh is more useful, though may not be as widely used as TMUX.

## Ideal future situation

inclusion of `net-misc/mosh` in the overlay.

## **Implementation options

inclusion of `net-misc/mosh` in the overlay.

**Comment by pothos** [comment]
FYI, there is a workaround for tmux inside the toolbox: https://kinvolk.io/docs/flatcar-container-linux/latest/setup/debug/install-debugging-tools/#spawn-a-toolbox-with-tmux-in-the-background (and from there you can nsenter back to the host in a tmux window)

**Comment by dharmab** [comment]
One way to leverage Mosh could be to run an SSH bastion host running Mosh, and then SSH from the bastion to Flatcar.

**Comment by pothos** [comment]
fyi one could also provision a static binary through Ignition: https://github.com/mobile-shell/mosh/issues/1006#issuecomment-909227128
