### ISSUE TITLE
Review and link missing platforms in docs

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#47]
The docs on about [rackspace](https://github.com/flatcar-linux/docs/blob/1d9c18ac38cf054b8280e46fd70d9f06d99ec26b/os/booting-on-rackspace.md), [vultr](https://github.com/flatcar-linux/docs/blob/1d9c18ac38cf054b8280e46fd70d9f06d99ec26b/os/booting-on-vultr.md), [exoscale](https://github.com/flatcar-linux/docs/blob/1d9c18ac38cf054b8280e46fd70d9f06d99ec26b/os/booting-on-exoscale.md) and others are currently hidden.
Review which ones are accurate and can be added to the menu.

**Comment by margamanterola** [comment]
With the migration to the new docs, these files became visible through the side bar navigation. They are now grouped together under "Community Platforms" and the Overview page explicitly says that they are not officially supported:

https://kinvolk.io/docs/flatcar-container-linux/latest/installing/community-platforms/

We haven't reviewed them, but I don't think we will get to that any time soon, so closing this now.
