### ISSUE TITLE
Rkt does not exist and kubelet.service still use it

### ISSUE THREAD

**Issue by torrescd** [flatcar/Flatcar#472]
## Description

Rkt does not exist and kubelet.service still use it
## Impact

kubelet is not starting

## Environment and steps to reproduce

Update to stable 2905.2.0

## Expected behavior

kubelet works

## Additional information

* Closing as it has nothing to do with flatcar, but typhoon management

**Comment by torrescd** [comment]
* Closing as it has nothing to do with flatcar, but typhoon management

**Comment by dghubble** [comment]
@torrescd for clarity, Typhoon stopped using rkt in [v1.19.4](https://github.com/poseidon/typhoon/releases/tag/v1.19.4) so have a look at newer releases.

**Comment by pothos** [comment]
Thanks, I guess it's also good to put this link here: https://typhoon.psdn.io/topics/maintenance.html#upgrades
