### ISSUE TITLE
Cork: New Package not showing up in built image.

### ISSUE THREAD

**Issue by ajrpayne** [flatcar/Flatcar#473]
I am attempting to add the net-wireless/iwd package to a image.

First I built a base image and tested that it works with qemu.

    1  ./setup_board --default --board=amd64-usr
    2  ./build_packages
    3  ./build_image
    4  ./image_to_vm.sh --from=../build/images/amd64-usr/developer-latest --board=amd64-usr

Then I emerged the new package with all it dependencies.

emerge-amd64-usr --newuse net-wireless/iwd

I added the package to

../third_party/coreos-overlay/coreos-base/coreos/coreos-0.0.1.ebuild

rebuilt the image

   1  ./build_image
   2  ./image_to_vm.sh --from=../build/images/amd64-usr/developer-latest --board=amd64-usr

But it doesn't look like the new image is including the new package.

Is there a step I am missing to get the image build script to grab the newly built package?

**Comment by jepio** [comment]
When you added the package to coreos-base/coreos, did you rebuild it? Its a good idea to bump the revision of the ebuild (`mv coreos-0.0.1-rXXX.ebuild coreos-0.0.1-rXXY.ebuild`) when you modify the deps so that portage knows something has changed and considers binary packages out of date. `./build_image` uses binpkgs, so that would not care, but at least `./build_packages` would notice.

So to make it work you would need:
```
emerge-amd64-usr coreos-base/coreos
./build_image
./image_to_vm.sh --board=amd64-usr
```

**Comment by pothos** [comment]
It's also good to run `./build_packages` before `./build_image` to make sure that all missing binary packages are generated.

And in case you work on the `main` branch or `flatcar-MAJOR` branch I recommend you to set up the nightly binary package cache to save some hours:
https://kinvolk.io/docs/flatcar-container-linux/latest/reference/developer-guides/sdk-tips-and-tricks/#use-the-nightly-build-sdk--flatcar-packages-for-the-development-branches

**Comment by jepio** [comment]
I hope the above comments helped you add your package to the image. You can also get help in our  matrix room: https://app.element.io/#/room/#flatcar:matrix.org.
