### ISSUE TITLE
How to manualy set DNS during baremetal install (No DHCP)

### ISSUE THREAD

**Issue by Keithsc** [flatcar/Flatcar#477]
I am trying to install Flatcar onto a server in a data canter the problem is that the network that I am using does not have a dhcp server so I need to manual set a IP/Mask and DNS (Oh and probably a gateway). I can set an IP address and can ping other devices but I am unsure how to set the DNS. The online tutorials I have looked at for setting dns using systemd are all slightly different and none have worked so far.

If anyone can help that would be great.

**Comment by pothos** [comment]
Hi,
you can have a look at these two examples here:
https://github.com/kinvolk/mantle/blob/flatcar-master/platform/machine/esx/cluster.go#L54
https://github.com/kinvolk/racker/blob/main/bootstrap/network.yaml.template
For the details see docs here: https://www.freedesktop.org/software/systemd/man/systemd.network.html

Can you share your configuration which doesn't work?

Do you also need to set up a static IP address for the initramfs? That's done via kernel command line parameters: https://kinvolk.io/docs/flatcar-container-linux/latest/provisioning/ignition/network-configuration/#using-static-ip-addresses-with-ignition

**Comment by Keithsc** [comment]
Thanks for replying @pothos, Apologies for not being clearer, I have downloaded the flatcar install .ISO file and have booted from it and plan to run "./flatcar-install -d ......" so I just need to manual set an IP on the machine, this i can do but I am stuck trying to figure out how to set the dns, I have tried setting it in /etc/resolv and also somwhere in /run/???/resolv.conf and have attempted to reload & restart systemd but without any luck.

**Comment by pothos** [comment]
Did you try to add the DNS in the networkd unit as done in https://github.com/kinvolk/mantle/blob/flatcar-master/platform/machine/esx/cluster.go#L54?

**Comment by jepio** [comment]
@Keithsc you need to configure networking through systemd network units. This would involve preparing an ignition file and passing it to `flatcar-install -i ignition.json`. Kai has linked examples, and there are more in our documentation. Closing.
