### ISSUE TITLE
network-cleanup.service vanished on the latest stable release (2905.2.1)

### ISSUE THREAD

**Issue by yokaze** [flatcar/Flatcar#478]
## Description

We run the stable Flatcar OS (2905.2.1) using HTTP boot on a bare-metal server and got the following error.

```
Aug 11 19:11:27 rack0-cs21 systemd[1]: network-cleanup.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Aug 11 19:11:27 rack0-cs21 systemd[1]: network-cleanup.service: Control process exited, code=killed, status=15/TERM
Aug 11 19:11:27 rack0-cs21 systemd[1]: network-cleanup.service: Failed with result 'signal'.
Aug 11 19:11:27 rack0-cs21 systemd[1]: Stopped network-cleanup.service.
```

## Impact

We use the list of failed systemd units for the sanity check, therefore the OS is marked erroneous on our datacenter.

## Environment and steps to reproduce

1. Run Flatcar 2905.2.1 using HTTP boot.

## Expected behavior

network-cleanup.service does not appear as a failed systemd unit.

## Additional information

- It did not occur with the previous stable release: 2765.2.6. 
- We did not observe the problem on a nested QEMU VM on GCP.
- The problem looks similar to the one: https://github.com/kinvolk/bootengine/pull/27
- The latest alpha release (2955.0.0) says "Fixed the network-cleanup service race in the initramfs which resulted in a failure being reported". https://groups.google.com/g/flatcar-linux-user/c/t9iDuYcMMjc

**Comment by pothos** [comment]
Hello,

yes, the bug fix is not yet in Stable or Beta.

I created a backport PR: https://github.com/kinvolk/coreos-overlay/pull/1182

**Comment by yokaze** [comment]
Thanks for the quick fix!
