### ISSUE TITLE
Developmental Containers for building kernel modules

### ISSUE THREAD

**Issue by kshitizbakshi** [flatcar/Flatcar#48]
Hi,

We're evaluating moving to Flatcar from CoreOS due to the CoreOS EOL happening.

One maybe-peculiar thing we do is use the CoreOS developmental containers that they release to enable development/build of things like kernel module, etc. which are hard to do on the released builds due to lack of build toolchains. Example: https://stable.release.core-os.net/amd64-usr/2345.3.0/coreos_developer_container.bin.bz2

We consume kernel sources inside the development container like this:
```
emerge-gitclone
emerge -gKq coreos-sources
```

one very critical use case for us is NVIDIA drivers - we run clusters which use NVIDIA GPUs. Two things needed to build the driver modules are kernel sources and the developmental containers.

Could you guide us if these things are already available for Flatcar? And if yes, where? I could not find documentation on developmental containers on the Flatcar website, but if I missed something obvious, my apologies.

**Comment by chrskhl** [comment]
I think you can find the image you're looking for here: https://stable.release.flatcar-linux.net/amd64-usr/2345.3.0/flatcar_developer_container.bin.bz2
The steps should be exactly like those for CoreOS Container Linux.
The development guides are here: https://docs.flatcar-linux.org/os/developer-guides/

Please let us know if there's more info you may need.

**Comment by kshitizbakshi** [comment]
Awesome, thank you @blixtra! this should work perfectly - sounds like a perfect drop-in.

**Comment by t-lo** [comment]
I'll close this issue as we appear to have addressed the problem. @kshitizbakshi please feel free to re-open if your issue persists.
