### ISSUE TITLE
fstrim.service as shipped creates dependency on /etc/fstab which doesn't exist

### ISSUE THREAD

**Issue by ericb-summit** [flatcar/Flatcar#480]
## Description

Stock `fstrim.service`, calls `/sbin/fstrim -Av`, which fails because `/etc/fstab` as we all know doesn't exist.

## Environment and steps to reproduce

Install flatcar in an environment whose controller and drives support the fstrim command.

1. `sudo systemctl start fstrim.service`
2. weep softly

## Additional information

If copy the unit from /usr/lib to /etc and modify it to call `/sbin/fstrim -av` not `/sbin/fstrim -Av`, it works fine.  `-A` means `trim all supported mounted filesystems from /etc/fstab`, while `-a` means `trim all supported mounted filesystems`, without looking at `/etc/fstab`.

**Comment by jepio** [comment]
Thanks for reporting this. This appears to come from util-linux, we'll need to fixup the service file.

**Comment by george-angel** [comment]
+1

We created the following drop-in to do just that: https://github.com/utilitywarehouse/tf_kube_ignition/blob/master/resources/fstrim.conf

**Comment by t-lo** [comment]
It appears our todo is to add the [proposed fstrim conf](https://github.com/flatcar-linux/Flatcar/issues/480#issuecomment-956203209) to [util-linux](https://github.com/flatcar-linux/portage-stable/tree/main/sys-apps/util-linux) and [install it in pkg_postinst](https://github.com/flatcar-linux/portage-stable/blob/main/sys-apps/util-linux/util-linux-2.37.2-r1.ebuild#L327), overwriting the default shipped with upstream.

Looks like a good first issue.

**Comment by krishjainx** [comment]
@t-lo It appears that this was fixed in this commit https://github.com/flatcar/scripts/commit/faf115acdec955cc31d528ada266d9053c13bc71 and in flatcar release stable-3510.2.2.

**Comment by pothos** [comment]
Yes, thanks for noticing!
