### ISSUE TITLE
[RFE] Support of Intel E810-XXV

### ISSUE THREAD

**Issue by umezawatakeshi** [flatcar/Flatcar#482]
## Current situation

I want support of Intel E810-XXV ethernet adapter (PCI vendor:device = 8086:159B). It seems supported by kernel 5.10.55, the version used by latest Flatcar stable.

## Impact

[ Please describe the impact the lack of the feature requested is creating ]

## Ideal future situation

[ Please describe the future situation after the improvement was implemented ]

## **Implementation options

[ Optional: please provide one or more options for implementing the feature requested ]

## Additional information

[ Please Add any information that does not fit into any of the above sections here ]

**Comment by t-lo** [comment]
Looks like we want to [enable `CONFIG_ICE=m`](https://cateee.net/lkddb/web-lkddb/ICE.html) in the [common kernel config](https://github.com/kinvolk/coreos-overlay/blob/main/sys-kernel/coreos-modules/files/commonconfig-5.10).

Instructions on how to add kernel modules are in the [custom OS images guide](https://kinvolk.io/docs/flatcar-container-linux/latest/reference/developer-guides/sdk-modifying-flatcar/). Seems like a low-hanging fruit, adding "good first issue" label.

**Comment by umezawatakeshi** [comment]
Thanks. I will try it.

**Comment by umezawatakeshi** [comment]
@t-lo 
I just confirmed that the custom kernel + driver module works fine on my hardware. May I send PR to https://github.com/kinvolk/coreos-overlay repo ?

**Comment by t-lo** [comment]
Yes, please do! Sorry for the long wait.
