### ISSUE TITLE
[cork] Failed to run create with UTF-8 user.name in git config

### ISSUE THREAD

**Issue by akunszt** [flatcar/Flatcar#506]
If you have an UTF-8 user.name value in git config then `cork create` command fails with this:
```
Traceback (most recent call last):
  File "/mnt/host/source/.repo/repo/main.py", line 541, in <module>
    _Main(sys.argv[1:])
  File "/mnt/host/source/.repo/repo/main.py", line 516, in _Main
    result = run()
  File "/mnt/host/source/.repo/repo/main.py", line 509, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/mnt/host/source/.repo/repo/main.py", line 212, in _Run
    result = cmd.Execute(copts, cargs)
  File "/mnt/host/source/.repo/repo/subcmds/init.py", line 460, in Execute
    if opt.config_name or self._ShouldConfigureUser():
  File "/mnt/host/source/.repo/repo/subcmds/init.py", line 343, in _ShouldConfigureUser
    mp.config.GetString('user.email')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc1' in position 18: ordinal not in range(128)
2021-09-13T09:56:26Z cork: repo init failed: exit status
```
After changing the value to an ASCII-only then it will work as expected.

Please not that the stacktrace mentions only `user.email` but the whole line looks like this:
```python
    print('Your identity is: %s <%s>' % (mp.config.GetString('user.name'),
                                         mp.config.GetString('user.email')))
```

This is not working:
```arpad@trantor ~ $ git config --global --list
user.name=Árpád Kunszt
```
This is working:
```arpad@trantor ~ $ git config --global --list
user.name=Arpad Kunszt
```
I think this is a bug in [gerrit/git-repo](https://gerrit.googlesource.com/git-repo) but I'm not familiar with `mantle`/`cork` enough to open a ticket there. Until that it worth to mention this limitation in the documentation. If it's already there and I didn't find then then please excuse me about the noise.

**Comment by t-lo** [comment]
Should be resolved with the new [containerised SDK](https://www.flatcar.org/docs/latest/reference/developer-guides/sdk-modifying-flatcar/) which does not use `cork` or `repo`.
I did some cursory testing by pasting the UTF8 name provided in the issue report into my local `.git/config` and the container starts as expected.
@akunszt I'll close this issue, please feel free to re-open if you encounter similar issues with the new containerised SDK.
