### ISSUE TITLE
Error creating libvirt domain  Failed to lock byte 100

### ISSUE THREAD

**Issue by ghost** [flatcar/Flatcar#512]
## Description

[ 1 paragraph concisely describing the bug ]

I am trying to create a VM by following this:
https://kinvolk.io/docs/flatcar-container-linux/latest/installing/vms/libvirt/#terraform

terraform apply  returns an error saying that it failed to create the libvirt domain.

## Impact

[ 1 sentence detailing the impact this bug is creating for you ]

I can't use terraform to create VMs.

## Environment and steps to reproduce

1. **Set-up**: [ describe the environment Flatcar/Lokomotive/Nebraska etc was running in when encountering the bug; Platform etc. ]

Ubuntu server 20.04

terraform -v
Terraform v1.0.7
on linux_amd64
+ provider registry.terraform.io/dmacvicar/libvirt v0.6.11
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/poseidon/ct v0.7.1

2. **Task**: [ describe the task performing when encountering the bug ]

terraform apply
...
libvirt_domain.machine["mynode"]: Creating...

3. **Action(s)**: [ sequence of actions that triggered the bug, see example below ]
  a. [ requested the start of a new pod or container ]
  b. [ container image downloaded ]

4. **Error**: [describe the error that was triggered]

│ Error: Error creating libvirt domain: internal error: qemu unexpectedly closed the monitor: 2021-09-17T18:10:41.352767Z qemu-system-x86_64: -blockdev {"node-name":"libvirt-2-format","read-only":true,"driver":"qcow2","file":"libvirt-2-storage","backing":null}: Failed to lock byte 100

## Expected behavior

[ describe what you expected to happen at 4. above but instead got an error ]

I expect a Flatcar VM to be created and started.

## Additional information

Please add any information here that does not fit the above format.

karl@k8s:~$ virsh list --all
 Id   Name               State
-----------------------------------
 -    mycluster-mynode   shut off

karl@k8s:~$ virsh pool-list
 Name             State    Autostart
--------------------------------------
 mycluster-pool   active   yes

virtlockd is active

karl@k8s:~$ tail -n 5 /etc/apparmor.d/abstractions/libvirt-qemu
  # Site-specific additions and overrides. See local/README for details.
  #include <local/abstractions/libvirt-qemu>
  # For ignition files
  /var/lib/libvirt/flatcar-linux/** r,
  /var/tmp/mycluster-pool/** r,

Thanks in advance for any help.

EDIT:
Just to make the link, an issue has been opened into https://github.com/dmacvicar/terraform-provider-libvirt/issues/882 too.

**Comment by pothos** [comment]
Hello,
does it work with apparmor disabled?

**Comment by jepio** [comment]
@KarlNord check dmesg or the log for apparmor audit failures, and please paste those, that should contain a hint. File locking requires the 'k' permission. Who created the apparmor override files that you pasted into the issue?

**Comment by jepio** [comment]
@KarlNord I'm fairly sure that it's an apparmor issue and you need to add the 'locking' permission to the apparmor overrides. In that case i'll close this issue. You can re-open if you think there's more to it.

**Comment by ghost** [comment]
I found this on https://kinvolk.io/docs/flatcar-container-linux/latest/installing/vms/libvirt/

https://kinvolk.io/docs/flatcar-container-linux/latest/installing/vms/libvirt/#create-the-ignition-config

If the host uses AppArmor, allow qemu to access the config files:

echo "  # For ignition files" >> /etc/apparmor.d/abstractions/libvirt-qemu
echo "  /var/lib/libvirt/flatcar-linux/** r," >> /etc/apparmor.d/abstractions/libvirt-qemu

This wasn't on the website. I added it on my own.

echo "  /var/tmp/mycluster-pool/** r," >> /etc/apparmor.d/abstractions/libvirt-qemu

After modifiy it to 

  # For ignition files
  /var/lib/libvirt/flatcar-linux/** rk,
  # for storage pool
  /var/tmp/mycluster-pool/** rwk,

I was able to get the VM created.

Thanks
