### ISSUE TITLE
tests: `cl.ignition.oem.wipe` fails on `esx`

### ISSUE THREAD

**Issue by tormath1** [flatcar/Flatcar#514]
## Description

In this PR: https://github.com/flatcar-linux/mantle/pull/235, we added testing for `OEM` especially for playing around the FS format since we introduced this patch: https://github.com/flatcar-linux/ignition/pull/22 - but the associated test is failing on `esx` platform:
```
harness.go:535: Cluster failed starting machines: getting machine info: waiting for net ip: Post "https://1.2.3.4/sdk": context deadline exceeded
```

## Impact

We can't test correctly the OEM patch.

## Environment and steps to reproduce

1. Get access to ESX
2. Run `cl.ignition.oem.wipe` test (`esx` needs to be removed from `ExcludedPlatforms`)
3. See the failing test

## Additional information

It might be related to some required components erased with the wiping of the FS.

**Comment by jepio** [comment]
Wiping the OEM partition will also not work for Azure, because the waagent is responsible for reporting successful boot - without it the VM creation is considered a failure.

**Comment by pothos** [comment]
We can close this, right?
