### ISSUE TITLE
Not able to ssh into cluster nodes using public key in Flatcar 2905.2.3

### ISSUE THREAD

**Issue by jyotishsre36** [flatcar/Flatcar#517]
## Description
We are facing login failures into kubernetes nodes using ssh core public key since migrating to 2905.2.3 version.
We are currently running version Flatcat 2765.2.3 in our production environment and ssh works perfectly fine
## Impact

We are not able to login and troubleshoot any issues into kubernetes cluster nodes
## Environment and steps to reproduce
Below is the error we get when we try to login

bash-5.1$  ssh -i /tmp/key core@x.x.x.x -vvv
OpenSSH_8.4p1, OpenSSL 1.1.1k  25 Mar 2021
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolve_canonicalize: hostname x.x.x.x is address
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/go/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/go/.ssh/known_hosts2'
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug2: ssh_connect_direct
debug1: Connecting to x.x.x.x [x.x.x.x] port 22.
debug1: Connection established.
debug1: identity file /tmp/key type 0
debug1: identity file /tmp/key-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.4

## Expected behavior

ssh works and login is successfull with Flatcar 2765.2.3 version

## Additional information

In the release notes of 2905.2.3 ,we could see some OpenSSL changes ,is there some change which may be affecting the logins through ssh

**Comment by jepio** [comment]
None of the OpenSSL changes should affect ssh login.
Do I understand correctly that the login just hangs and no prompt comes up on screen?

Can you describe the scenario in a bit more detail:
* do you see the issue after a node upgrades from 2765.2.3 -> 2905.2.3?
* do you see the issue on new 2905.2.3 nodes after installing kubernetes?
* can you login to fresh 2905.2.3 nodes before installing kubernetes?
* what CNI are you using?
* can you share the bootstrap script you use to setup kubernetes (or: what method of deploying kubernetes do you use)?

**Comment by jyotishsre36** [comment]
> None of the OpenSSL changes should affect ssh login.
> Do I understand correctly that the login just hangs and no prompt comes up on screen? Yes ,it is able to connect to the VM on port 22 BUT ssh hangs and no error is thrown.
> 
> Can you describe the scenario in a bit more detail:
> 
> * do you see the issue after a node upgrades from 2765.2.3 -> 2905.2.3? Yes
> * do you see the issue on new 2905.2.3 nodes after installing kubernetes? No ,its before installation of Kubernetes
> * can you login to fresh 2905.2.3 nodes before installing kubernetes? No
> * what CNI are you using?( canal ,  cniVersion: v0.12.0-amd64)
> * can you share the bootstrap script you use to setup kubernetes (or: what method of deploying kubernetes do you use)?We are using the kubeadm and shell scripts to to setup kubernetes, but we are getting ssh during the initial base template creations without any kubernetes installed.

**Comment by jepio** [comment]
What environment is this? (cloud provider, etc.)

Can you paste your ignition config (or do you use a different means to configure ssh key)?

Do you have access to a out-of-band method to verify that the nodes boot correctly (serial log)?

**Comment by Chandrapal-Panwar** [comment]
What environment is this? (cloud provider, etc.)
We are not using any cloud provider but performing it in on-prem with  downloads the ova from Flatcar.
Can you paste your ignition config (or do you use a different means to configure ssh key)?
We use script to put ssh key on vm template for bringing it up.
Do you have access to a out-of-band method to verify that the nodes boot correctly (serial log)?
We push template to vpshere and from there it is coming with out any issue.

**Comment by jepio** [comment]
Hi @Chandrapal-Panwar,

So you're running on vsphere and have access to the console - that's good. This look like a connectivity issue and not anything ssh specific.

Can you paste the outputs of the following commands on a 2905.2.3 node:
* `networkctl`
* `ip addr`
* `ip route`
* `iptables -vnL`

**Comment by Chandrapal-Panwar** [comment]
Hello Jepio,
Please find the output of commands from console in [attachment.](url) 
![screenshot1](https://user-images.githubusercontent.com/69238204/135043212-8394f299-f21c-4740-b604-eb7053a3a3b2.JPG)
![Uploading screenshot2.JPG…]()

**Comment by jepio** [comment]
I can't see the second screenshot.

Can you run a `tcpdump -i ens192 -p -n -e` on the console, while attempting  to ssh and verify that packets are being accepted?
And check if `journalctl -g ssh` on the node shows some more hints.

**Comment by Chandrapal-Panwar** [comment]
Please find all details attached.
![screenshot1](https://user-images.githubusercontent.com/69238204/135068923-f7fe5163-9d64-422a-8bbb-1fb6f4cf5e64.JPG)
![screenshot2](https://user-images.githubusercontent.com/69238204/135068926-7ded53b8-ccb9-428c-913e-f0c088231d49.JPG)

**Comment by Chandrapal-Panwar** [comment]
One more
![screenshot2](https://user-images.githubusercontent.com/69238204/135069101-38066087-d42f-4398-ba04-1e1baca9c5d1.JPG)

**Comment by Chandrapal-Panwar** [comment]
One more
![Screenshot4](https://user-images.githubusercontent.com/69238204/135069680-f3b6b7eb-7c9f-4131-b1fa-09849c46a39c.jpg)

**Comment by jepio** [comment]
Im starting to run out of ideas, but here's two more questions:
* what kind of customizations do you do to `/etc` in your image build?
* can you paste the output of `ssh -i /tmp/key core@x.x.x.x -vvv` when connecting to a 2765 node?
* check journalctl if there are any error messages on the 2905 node

**Comment by Chandrapal-Panwar** [comment]
@jepio : Issue got resolve with adding CASignatureAlgorithms ^ssh-rsa in sshd_config file.
Please close the bug.

**Comment by jepio** [comment]
Awesome! Thanks for following up with your findings.

In that case it seems that you were affected by these changes that came around the 2801 release: https://github.com/flatcar-linux/Flatcar/issues/62.

Closing.
