### ISSUE TITLE
Use mirror server instead of GCS bucket for SDK tar balls and binary packages

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#523]
## Description

Both `cork`'s way of downloading the SDK tar ball and the portage binary package URLs in the SDK and the developer container make use of the GCS bucket. However, we will immediately move this content to the regular release server that hosts the other release assets.

## Impact

Users can't set up the SDK or use binary packages in the developer container to compile kernel modules or similar, until we have published the content at the new location and changed the portage URLs for new releases and document how to set them for old releases, and published a new `cork` release that uses the new location.

**Comment by jonasclaes** [comment]
What's the current status? How long do you estimate the move? I would love to develop something for Hacktober, but I can't because of this issue at the moment.

**Comment by pothos** [comment]
You can find the SDKs now on https://mirror.release.flatcar-linux.net/sdk/ (tar balls and binary packages for `/etc/portage/make.conf`), and the board packages on https://mirror.release.flatcar-linux.net/boards/ for `/build/BOARD/etc/portage/make.conf` in the SDK board or for `/etc/portage/make.conf` in the developer container.
The SDK download via `cork` needs a source code change and is not yet done.

**Comment by miao0miao** [comment]
@jonasclaes we are currently working on a new release to all channels that will fix this issue, it should be ready by the end of this week.

**Comment by tormath1** [comment]
Linking related PRs:
* https://github.com/flatcar-linux/mantle/pull/239: provide a `--json-key` argument to pull artifacts from private GCS buckets
* https://github.com/flatcar-linux/mantle/pull/238 (https://github.com/flatcar-linux/mantle/pull/240) provide a `--sdk-url` to modify the SDK location (default to `mirror.release...`) 
* https://github.com/flatcar-linux/scripts/pull/158: include the `--json-key` changes to the CI scripts
* https://github.com/flatcar-linux/scripts/pull/159

**Comment by pothos** [comment]
Downloading the SDK works again with the latest `cork`: https://github.com/flatcar-linux/mantle/releases/tag/v0.17.0

**Comment by tbbharaj** [comment]
Hello, I tried with latest cork and getting the same download failure error with `https://github.com/flatcar-linux/mantle/releases/tag/v0.17.0`

```
2021-10-06T21:42:28Z cli: Started logging at level INFO
2021-10-06T21:42:28Z cork: Detecting SDK version
2021-10-06T21:42:29Z cork: Found SDK version 2801.0.0 from remote repo
2021-10-06T21:42:29Z cork: Downloading SDK version 2801.0.0
2021-10-06T21:42:29Z sdk: Downloading https://mirror.release.flatcar-linux.net/sdk/amd64/2801.0.0/flatcar-sdk-amd64-2801.0.0.tar.bz2 to /home/ubuntu/flatcar-sdk/.cache/sdks/flatcar-sdk-amd64-2801.0.0.tar.bz2
2021-10-06T21:42:34Z cork: Download failed: 404 Not Found: https://mirror.release.flatcar-linux.net/sdk/amd64/2801.0.0/flatcar-sdk-amd64-2801.0.0.tar.bz2
```

**Comment by jepio** [comment]
Hi @tbbharaj, we prioritized copying current releases over (check https://mirror.release.flatcar-linux.net/sdk/amd64/). Are you able to update to a newer version?

**Comment by tbbharaj** [comment]
@jepio Thanks I was able to pull latest version. I am trying to build image from source following steps here: https://kinvolk.io/docs/flatcar-container-linux/latest/reference/developer-guides/sdk-modifying-flatcar/
1. Using latest cork `0.17.0`
2. Downloaded latest version `3005.0.0`

But still when I do `./setup_board --board=amd64-usr` I am getting following error:

```
!!! Error fetching binhost package info from 'https://storage.googleapis.com/flatcar-jenkins/boards/amd64-usr/2905.0.0/pkgs'
!!! HTTP Error 403: Forbidden

!!! Error fetching binhost package info from 'https://storage.googleapis.com/flatcar-jenkins/boards/amd64-usr/2905.0.0/toolchain'
!!! HTTP Error 403: Forbidden

!!! Error fetching binhost package info from 'https://storage.googleapis.com/flatcar-jenkins/sdk/amd64/2905.0.0/toolchain'
!!! HTTP Error 403: Forbidden

!!! Error fetching binhost package info from 'https://storage.googleapis.com/flatcar-jenkins/sdk/amd64/2905.0.0/pkgs'
!!! HTTP Error 403: Forbidden

emerge: there are no binary packages to satisfy "sys-devel/binutils" for /build/amd64-usr/.

emerge: searching for similar names... nothing similar found.
ERROR   setup_board: script called: setup_board '--board=amd64-usr'
ERROR   setup_board: Backtrace:  (most recent call is last)
ERROR   setup_board:   file setup_board, line 330, called: die_err_trap '"${EMERGE_WRAPPER}" --usepkgonly --getbinpkg --rebuilt-binaries n ${EMERGE_TOOLCHAIN_FLAGS} "${TOOLCHAIN_PKGS[@]}"' '1'
ERROR   setup_board: 
ERROR   setup_board: Command failed:
ERROR   setup_board:   Command '"${EMERGE_WRAPPER}" --usepkgonly --getbinpkg --rebuilt-binaries n ${EMERGE_TOOLCHAIN_FLAGS} "${TOOLCHAIN_PKGS[@]}"' exited with nonzero code: 1
ERROR   setup_board:   (Note bash sometimes misreports "command not found" as exit code 1 instead of 127)
```

**Comment by jepio** [comment]
We are working on making this work again, but as of right now binary packages are still missing. I apologize for this.

**Comment by tbbharaj** [comment]
> We are working on making this work again, but as of right now binary packages are still missing. I apologize for this.

No issues...Thanks for the update!

**Comment by SuhasreddyN** [comment]
Any update?

**Comment by jepio** [comment]
Still working on it.

**Comment by SuhasreddyN** [comment]
update?

**Comment by t-lo** [comment]
We'll provide a brief update in today's community meeting. TL;DR:
* Future releases will use https://mirror.release.flatcar-linux.net/ by default for SDK tarballs and for binary packages. This is the preferred source for building Flatcar. We're in the process of wrapping up releases to all channels - and to Mantle - which use that mirror by default; we expect to release later this week.
* For nightlies / CI builds, we introduce cached public access to the GCS bucket via https://bucket.release.flatcar-linux.net/ .

**Comment by pothos** [comment]
If you develop on the `main` branch in your cork SDK, run this here to get access to the nightly packages:

```
./set_version --binhost https://bucket.release.flatcar-linux.net/flatcar-jenkins --dev-board --board-version amd64-usr/main-nightly --dev-sdk --sdk-version sdk-main-nightly
```

**Comment by juliantaylor** [comment]
Is here any way to build kernel modules?
As documented here:
https://kinvolk.io/docs/flatcar-container-linux/latest/reference/developer-guides/kernel-modules/
still returns 403 for all stable versions

     !!! Error fetching binhost package info from 'https://storage.googleapis.com/flatcar-jenkins/boards/amd64-usr/2905.2.4/pkgs'
     !!! HTTP Error 403: Forbidden

**Comment by t-lo** [comment]
Because of a change in our build infrastructure the URL of our binhost has changed from
```
https://storage.googleapis.com/flatcar-jenkins/boards/amd64-usr/<version>/pkgs
```
to 
```
https://mirror.release.flatcar-linux.net/boards/amd64-usr/<version>/pkgs
```
We are in the process of issuing an update to all channels to reflect the change.

**Comment by ManojMondal02062019** [comment]
> We'll provide a brief update in today's community meeting. TL;DR:
> 
> * Future releases will use https://mirror.release.flatcar-linux.net/ by default for SDK tarballs and for binary packages. This is the preferred source for building Flatcar. We're in the process of wrapping up releases to all channels - and to Mantle - which use that mirror by default; we expect to release later this week.
> * For nightlies / CI builds, we introduce cached public access to the GCS bucket via https://bucket.release.flatcar-linux.net/ .

What will be steps to build the Flatcar.. Meant to say that if I download the flatcar sdk from this link -> https://mirror.release.flatcar-linux.net/sdk/amd64/3005.0.0/flatcar-sdk-amd64-3005.0.0.tar.bz2 then how to proceed further with it. I extracted the file under the folder chroot and running "cork enter" - doesn't works. 
@t-lo : Please suggest. Thanks

**Comment by pothos** [comment]
From yesterday on `cork create` will default to downloading the 3033.0.0 Alpha SDK which already has the new URLs set up for binary packages (but you need to check out the right `flatcar-3033` Alpha release branches in the repos). The latest Stable, Beta, and LTS releases also have a new SDK with the right URLs (e.g., `cork create --manifest-branch flatcar-stable-2905.2.6`), and specifying the manifest branch will additionally check out the right release branches. Make sure to run the latest cork compiled from https://github.com/flatcar-linux/mantle

For developing on `main` branches after `cork create`, see https://github.com/flatcar-linux/Flatcar/issues/523#issuecomment-946851091
