### ISSUE TITLE
[RFE] Use shorter TLS certificate chain for iPXE hosting

### ISSUE THREAD

**Issue by jepio** [flatcar/Flatcar#527]
## Current situation

Booting with iPXE from https:// urls on Equinix Metal fails in most cases.

## Impact

Users are confused, need to guess the solution and fall back to http.

## Ideal future situation

https works on Equinix Metal by default.

## Implementation options

User Arian on matrix suggested:
> Friend of mine did some debugging. The issue isn't ciphr suites here (Your server seems to support all IPXE ciphers) the problem is that the letsencrypt certificate chain is too large for IPXE to support. And a workaround would be to issue a certificate from the ISRG Root X1 chain instead of the default letsencrypt chain. that one is "short" enough to not get IPXE confused... If that's something you want to consider that'd be awesome.

**Comment by pothos** [comment]
I remember it used to work from the NGINX caching server but not from Caddy. There could be more problems involved with the TLS implementation in iPXE.

**Comment by nshalman** [comment]
Related:
 - https://community.letsencrypt.org/t/production-chain-changes/150739
 - tinkerbell/ipxedust#53
 - ipxe/ipxe#116
 - If you use cert-manager, https://cert-manager.io/docs/configuration/acme/#use-an-alternative-certificate-chain may be of interest.

**Comment by pothos** [comment]
Ok, the goal would be to get the NGINX servers get accepted by iPXE again and for that it would be a way forward to set this as long as nothing changes on the iPXE side…

**Comment by jepio** [comment]
We switched to ISRG Root X1 preferred chain, the handshake data is now short enough that iPXE can digest it. I have validated that this works on several Equinix instances sizes and all is good.

Follow up: use https for PXE boot in mantle again.
