### ISSUE TITLE
Update Azure WAAgent to latest release

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#53]
We currently ship WAAgent `2.2.32` which will be deprecated starting May 2020 (https://support.microsoft.com/en-us/help/4049215/extensions-and-virtual-machine-agent-minimum-version-support). Update WAAgent to the latest upstream release (`2.2.46` at the time of writing: https://github.com/Azure/WALinuxAgent/releases ) for the Azure platform.

**Comment by pothos** [comment]
Since OEM partitions are not updated (see https://github.com/flatcar-linux/Flatcar/issues/21) it would be good to not just bump the version because it does not solve our problem and just delays it.

We should containerize the service with a unit on `/usr` that is started under the condition that the Azure OEM ID is in the kernel command line.

**Comment by t-lo** [comment]
Eventually yes, but the version bump is on a schedule (Microsoft will deprecate the version currently shipped in May). I would like to prevent for the containerisation to be on a schedule.

**Comment by pothos** [comment]
First try in https://github.com/flatcar-linux/coreos-overlay/pull/245

**Comment by dongsupark** [comment]
Stable 2345.3.1 and Beta 2411.1.1 were just released, so this issue should be fixed.
Alpha and Edge are still with the older version of WAAgent.

**Comment by pothos** [comment]
No, that was not part of the Stable and Beta releases because it landed later. It will be in all new releases, however.

**Comment by t-lo** [comment]
@dongsupark @pothos  Alpha and Edge should ship the updated version so we can stabilise this (move to Beta and then Stable in successive releases) before Microsoft deprecates the version currently used in Stable on May 1st.

**Comment by t-lo** [comment]
Implemented in https://github.com/flatcar-linux/coreos-overlay/pull/245, will be included in the next Alpha and Stable. Thank you!

**Comment by dongsupark** [comment]
wa-linux-agent was updated to 2.2.46 for for Alpha 2466.0.0 and Edge 2466.99.0.
Will leave the issue open, as Stable and Beta are not updated yet.

**Comment by dongsupark** [comment]
Stable 2512.2.0 or newer already has wa-linux-agent 2.2.46.
