### ISSUE TITLE
getting error E1014 while update core os to flatcar and on another E1008

### ISSUE THREAD

**Issue by marc5feb** [flatcar/Flatcar#531]
## Description

While using update-to-flatcar.sh i'm getting error E1014 on 1 machine and E1008 on another.

## Impact

upgrade to flatcar is failing.

## Environment and steps to reproduce

machine 1
./update-to-flatcar.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   451  100   451    0     0   1919      0 --:--:-- --:--:-- --:--:--  1919
SERVER=https://public.update.flatcar-linux.net/v1/update/
I1014 21:59:36.143656  2470 update_engine_client.cc:247] Initiating update check and install.
I1014 21:59:36.146760  2470 update_engine_client.cc:252] Waiting for update to complete.
LAST_CHECKED_TIME=1634248777
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_UPDATE_AVAILABLE
NEW_VERSION=2905.2.5
NEW_SIZE=403144993
LAST_CHECKED_TIME=1634248777
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_UPDATE_AVAILABLE
NEW_VERSION=2905.2.5
NEW_SIZE=403144993
LAST_CHECKED_TIME=1634248777
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_IDLE
NEW_VERSION=0.0.0
NEW_SIZE=0
E1014 21:59:51.177453  2470 update_engine_client.cc:190] Update failed.

and machine 2

 $ ./update-to-flatcar.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   451  100   451    0     0   1459      0 --:--:-- --:--:-- --:--:--  1459
umount: /usr/share/update_engine/update-payload-key.pub.pem: not mounted.
SERVER=https://public.update.flatcar-linux.net/v1/update/
umount: /usr/share/coreos/release: not mounted.
I1008 14:31:37.531222   838 update_engine_client.cc:247] Initiating update check and install.
I1008 14:31:37.535339   838 update_engine_client.cc:252] Waiting for update to complete.
LAST_CHECKED_TIME=1633703498
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_UPDATE_AVAILABLE
NEW_VERSION=2905.2.5
NEW_SIZE=403144993
LAST_CHECKED_TIME=1633703498
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_UPDATE_AVAILABLE
NEW_VERSION=2905.2.5
NEW_SIZE=403144993
LAST_CHECKED_TIME=1633703498
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_IDLE
NEW_VERSION=0.0.0
NEW_SIZE=0
E1008 14:31:54.767844   838 update_engine_client.cc:190] Update failed.

both machines are running coreos.
machine 1 version coreos stable 2135.6.0
machine 2 version coreos stable 2135.6.0

## Expected behavior

My intention is to upgrade these machines to flatcar. The same way i have upgraded multiple machine before these 2.

## Additional information

Please add any information here that does not fit the above format.

**Comment by jepio** [comment]
That part is just the date: `E1014`: October 14th, `E1008`: October 8th. Can you check `journalctl` for the specifics of the error?

If it's about the expired DST root certificate, then the following will help the nodes update:
```
# check that connection fails
curl -sS  https://stable.release.flatcar-linux.net/  >/dev/null
sudo rm /etc/ssl/certs/DST_Root_CA_X3.pem
sudo update-ca-certificates
# no error
curl -sS  https://stable.release.flatcar-linux.net/  >/dev/null
```
but I was only able to test on Flatcar 2135.6.0, not CoreOS as I can't find images anywhere, so I'm not sure if the cert path is correct for you.

**Comment by marc5feb** [comment]
thanks for your reply. i will check when i can and get back to you.

**Comment by marc5feb** [comment]
I would like to thank you for your assistance. The problem has been solved. The fault was the expired root certificate.
thanks!
