### ISSUE TITLE
[RFE] GitHub Action to update the ca-certificates package

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#533]
## Current situation

We have a GitHub Action for the kernel package that helps to keep maintenance branches up-to-date. However, if the ca-certificate package gets outdated and is not able to accept new certificates, OS updates are not possible.

## Impact

When ca-certificates is outdated, some HTTPS connections fail, which could also be the one used for updating the OS itself. This is a danger for long-term maintenance releases.

## Ideal future situation

A GitHub action files PRs for all branches when new ca-certs updates are available.

## **Implementation options

It can be a simple symlink bump like done for the kernel and then run the `ebuild … manifest` command to update the checksum.
 
## Additional information

We can do a manual update first and prepare the package for easier automation. ← Done

**Comment by dongsupark** [comment]
Recently nss 3.72 was released.
It looks like we really need the Github Actions to keep that up-to-date.

The default [hg repo](https://hg.mozilla.org/releases/) of nss does not look easy to deal with.
I would fetch its [Github mirror](https://github.com/nss-dev/nss/tags) to parse the latest tag with `_RTM` suffix.
Then it will get easier to write the new Github Action for ca-certificates.

**Comment by pothos** [comment]
Good idea, I had only thought about extracting the release tar balls from the HTML folder listing, and sorting them to find the highest version.

**Comment by dongsupark** [comment]
I will soon write the Github Actions.
