### ISSUE TITLE
[RFE] include Flatcar CPE in `/etc/os-release`

### ISSUE THREAD

**Issue by vbatts** [flatcar/Flatcar#536]
[Flatcar is in the NIST CPE dictionary](https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.2&keyword=flatcar).

For scanners to more easily detect the definition of the host they're inspecting, let's get `CPE_NAME=` defined in our `/etc/os-release` file like a number of other distros do.

**Comment by tormath1** [comment]
@vbatts , I see two versions:
* 2.2: `cpe:/o:flatcar-linux:flatcar_linux:3005.0.1`
* 2.3: `cpe:2.3:o:flatcar-linux:flatcar_linux:3005.0.1:*:*:*:*:*:*:*`

which one should be implemented ? I'd say `2.3` to use the latest "standard".

**Comment by vbatts** [comment]
fair, but the distros that include `CPE_NAME`, it is the v2.2 format

**Comment by vbatts** [comment]
https://www.linux.org/docs/man5/os-release.html ambiguously says that the field follows the format proposed by the MITRE corporation, with link to the now-archived https://cpe.mitre.org/specification/ which describes the v2.3 format. 🤷

**Comment by tormath1** [comment]
@vbatts on my manual page I have:
```
       CPE_NAME=
           A CPE name for the operating system, in URI binding syntax, following the Common Platform Enumeration
           Specification[^2] as proposed by the NIST. This field is optional. Example:
           "CPE_NAME="cpe:/o:fedoraproject:fedora:17""
...
[^2]: Common Platform Enumeration Specification
           http://scap.nist.gov/specifications/cpe/
```

Which leads to: 
> The current version of CPE is 2.3.

I'd be :+1: to use `2.3` version.

**Comment by vbatts** [comment]
yep. Let's go with that. No need to follow other's precedent for no reason!

**Comment by tormath1** [comment]
Just as a note, `CPE_NAME` needs to be added in there: https://github.com/flatcar-linux/scripts/blob/e86eadcdeb209ee199f282407b3ed2206ffc2db3/build_library/set_lsb_release#L46-L60
