### ISSUE TITLE
Unable to update from old version due to SSL certificate problem

### ISSUE THREAD

**Issue by pathshaper** [flatcar/Flatcar#538]
## Description

A server running Flatcar Container Linux 2512.2.1 cannot fetch new version of Flatcar. The update-engine log contain the error "Unable to get http response code: SSL certificate problem: certificate has expired".

## Impact

I can no longer automatically update Flatcar Container Linux. I have googled for a manual workaround but was not able to find one.

## Environment and steps to reproduce

1. **Set-up**: Flatcar Container Linux 2512.2.1
2. **Task**: Rebooted in hope of having the server updated to a newer version.
3. **Action(s)**: No action required.
4. **Error**: From "journalctl -u update-engine": "Oct 31 10:08:49 server update_engine[911]: E1031 10:08:49.817859   911 libcurl_http_fetcher.cc:243] Unable to get http response code: SSL certificate problem: certificate has expired"

## Expected behavior

That the server will download a new version of Flatcar Container Linux to the passive partition, and make it active at the next reboot.

## Additional information

I think the problem may be related to this:
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

Perhaps the problem can be fixed by using an SSL certificate on update.release.flatcar-linux.net which is not from LetsEncrypt. Earlier in the update process update-engine contacts https://public.update.flatcar-linux.net without any problem - and that domain uses an SSL certificate from a different provider.

**Comment by jepio** [comment]
See the solution in this comment: https://github.com/flatcar-linux/Flatcar/issues/531#issuecomment-944113528

**Comment by pothos** [comment]
We have docs for how to update in case of SSL errors:
https://www.flatcar.org/docs/latest/migrating-from-coreos/update-from-container-linux/#the-migration-script
