### ISSUE TITLE
New release including 2345.3.1 (all channels)

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#54]
**Alpha 2466.0.0**
* ship `tracepath` alongside `traceroute6` (#50 )
* Update docker to 19.03.08 (#41 )
* Update `open-vm-tools` to `11.0.5` (#52 ) for VMWare ESX platform
* Update `WAAgent` to latest `2.2.46` for Azure platform (#53 )
* Bug fix for #36: Uses newest network interface naming scheme, possible breaking change for some persistent network interface names
* Fix coreos-cloudinit variable names (https://github.com/flatcar-linux/coreos-overlay/pull/206)
* Bug fix: prefer /boot/coreos to write the update if it exists (https://github.com/flatcar-linux/update_engine/pull/2)
* Bug fix: build a download URL in a safer way (https://github.com/flatcar-linux/update_engine/issues/3)
* Bug fix: remove /boot/coreos/first_boot after a Ignition rerun was triggered on migrated machines (https://github.com/flatcar-linux/bootengine/pull/10)
* Bug fix: make flannel cross-node traffic work with systemd > 242 (https://github.com/coreos/flannel/issues/1155, https://github.com/flatcar-linux/coreos-overlay/pull/279)
* Support coreos.config.url as kernel command line parameter for Ignition (https://github.com/flatcar-linux/ignition/pull/10)
* Extend logging capabilities of mayday (#61)

**Edge 2466.99.0**
* base new Edge on Alpha (see above)
* Upgrade to kernel 5.6.2 (#64)
* Update `open-vm-tools` to `11.0.5` (#52 ) for VMWare ESX platform
* Update `WAAgent` to latest `2.2.46` for Azure platform (#53 )
* ship `tracepath` alongside `traceroute6` (#50 )
* Bug fix for #36: Uses newest network interface naming scheme, possible breaking change for some persistent network interface names
* Fix coreos-cloudinit variable names (https://github.com/flatcar-linux/coreos-overlay/pull/206)
* Bug fix: prefer /boot/coreos to write the update if it exists (https://github.com/flatcar-linux/update_engine/pull/2)
* Bug fix: build a download URL in a safer way (https://github.com/flatcar-linux/update_engine/issues/3)
* Bug fix: remove /boot/coreos/first_boot after a Ignition rerun was triggered on migrated machines (https://github.com/flatcar-linux/bootengine/pull/10)
* Bug fix: make flannel cross-node traffic work with systemd > 242 (https://github.com/coreos/flannel/issues/1155, https://github.com/flatcar-linux/coreos-overlay/pull/279)
* Support coreos.config.url as kernel command line parameter for Ignition (https://github.com/flatcar-linux/ignition/pull/10)

**Beta 2411.1.1**
* Point release containing bug fixes, *no* update to previous Alpha (`2430.0.0`)
* ship `tracepath` alongside `traceroute6` (#50 )
* Bug fix for #36: Uses newest network interface naming scheme, possible breaking change for some persistent network interface names
* Fix a bug in emerge-gitclone for https://github.com/flatcar-linux/coreos-overlay/issues/223
* Add QEDE kernel config https://github.com/flatcar-linux/coreos-overlay/pull/198
* Fix coreos-cloudinit variable names https://github.com/flatcar-linux/coreos-overlay/pull/206
* Kernel 4.19.112
* Bug fix: Prefer /boot/coreos to write the update if it exists
* Bug fix: remove /boot/coreos/first_boot after a Ignition rerun was triggered on migrated machines
* Support coreos.config.url as kernel command line parameter for Ignition 

**Stable 2345.3.1**
* Point release containing bug fixes, *no* update to previous Beta (`2411.1.0`)
* ship `tracepath` alongside `traceroute6` (#50 )
* Bug fix for #36: Uses newest network interface naming scheme, possible breaking change for some persistent network interface names
* Fix a bug in emerge-gitclone for https://github.com/flatcar-linux/coreos-overlay/issues/223
* Add QEDE kernel config https://github.com/flatcar-linux/coreos-overlay/pull/198
* Fix coreos-cloudinit variable names https://github.com/flatcar-linux/coreos-overlay/pull/206
* Kernel 4.19.107
* Bug fix: Prefer /boot/coreos to write the update if it exists
* Bug fix: remove /boot/coreos/first_boot after a Ignition rerun was triggered on migrated machines
* Support coreos.config.url as kernel command line parameter for Ignition

**Comment by dongsupark** [comment]
Stable 2345.3.1 and Beta 2411.1.1 were released.
Alpha and Edge are to be done.

**Comment by dongsupark** [comment]
Alpha 2466.0.0 and Edge 2466.99.0 were released.
