### ISSUE TITLE
[RFE] Add symlink from ncat to nc

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#545]
## Current situation

There is no `nc` on Flatcar but `ncat`.

## Impact

Scripts calling `nc` don't work

## Ideal future situation

Since `ncat` is a drop-in for `nc` there should be a symlink to it

## **Implementation options

Maybe do it as part of the ncat ebuild file, with a useflag for upstream Gentoo

## Additional information

I found one missing option in ncat: https://github.com/nmap/nmap/issues/2422

**Comment by tormath1** [comment]
Sent a PR upstream: https://github.com/gentoo/gentoo/pull/26287
