### ISSUE TITLE
Ping can't work after customizing Flatcar with Ignition

### ISSUE THREAD

**Issue by Winnie81** [flatcar/Flatcar#55]
**Description**

Ping can't work after customizing Flatcar with Ignition

**Environment and steps to reproduce**

1. **Set-up**: ESXi 6.7GA, Flatcar 2345.3.0 vm
2. Steps to reproduce:
     1)Create a Flatcar vm. 
     2)Before the first power on, edit its vmx file as this:
   adding:
      guestinfo.coreos.config.data.encoding = "base64"
      guestinfo.coreos.config.data= "ewogICJpZ25pdGlvbiI6IHsgInZlcnNpb24iOiAiMi4wLjAiIH0sCiAgICJuZXR3b3JrZCI6IHsKICAgICJ1bml0cyI6IFt7CiAgICAgICJuYW1lIjogIjAwLWVuczE5Mi5uZXR3b3JrIiwKICAgICAgImNvbnRlbnRzIjogIltNYXRjaF1cbk5hbWU9ZW5zMTkyXG5cbltOZXR3b3JrXVxuQWRkcmVzcz0xMC4xMTcuMTYuOThcbkdhdGV3YXk9MTAuMTE3LjE3LjI1M1xuRE5TPTEwLjExNy4wLjFcbk5ldG1hc2s9MjU1LjI1NS4yNTQuMCIKICAgIH1dCiAgfQp9Cg=="
     3)Power on the vm.

     Note: above data for guestinfo.coreos.config.data is the base64 encoding for:
      {
  "ignition": { "version": "2.2.0" },
   "networkd": {
    "units": [{
      "name": "00-ens192.network",
      "contents": "[Match]\nName=ens192\n\n[Network]\nAddress=10.117.16.98\nGateway=10.117.17.253\nDNS=10.117.0.1\nNetmask=255.255.254.0"
    }]
  }
}

**Expected behavior**
Customized IP takes effect and network can work normally.

In fact, customized IP takes effect but network is not available.

**Comment by t-lo** [comment]
Thank you for your report. We are aware of this issue and fixed it recently: https://github.com/flatcar-linux/scripts/pull/53

The fix has not been released yet; it will be part of the upcoming release. The next release is tracked in https://github.com/flatcar-linux/Flatcar/issues/54 .

**Comment by Winnie81** [comment]
Update ignition version as 2.2.0, and it still failed.

**Comment by pothos** [comment]
Sorry that we didn't have a look at this issue earlier. Recently we updated the docs to include an example with static IP addresses and other related information: https://docs.flatcar-linux.org/os/booting-on-vmware/#container-linux-configs

I'm not sure if your networkd config is correct. Do you still have the issue? What output does `ip route` and `networkctl` give you when you log in on the VGA console?

Can you try to use a networkd unit content similar to the example in the docs (i.e., separate `[Address]` section and a `/subnet` size in the `Address` and a `[Route]` section with a `Destination`)?

**Comment by pothos** [comment]
Closing this as stale, please reopen if needed.
As written in the docs, this is what should work (here both private and public IP addresses are used, only one would also work):
```
[Match]
Name=ens192
[Network]
DHCP=no
DNS=1.1.1.1
DNS=1.0.0.1
[Address]
Address=123.45.67.2/29
[Address]
Address=10.0.0.2/29
[Route]
Destination=0.0.0.0/0
Gateway=123.45.67.1
[Route]
Destination=10.0.0.0/8
Gateway=10.0.0.1
```

**Comment by Winnie81** [comment]
> Closing this as stale, please reopen if needed.
> As written in the docs, this is what should work (here both private and public IP addresses are used, only one would also work):
> 
> ```
> [Match]
> Name=ens192
> [Network]
> DHCP=no
> DNS=1.1.1.1
> DNS=1.0.0.1
> [Address]
> Address=123.45.67.2/29
> [Address]
> Address=10.0.0.2/29
> [Route]
> Destination=0.0.0.0/0
> Gateway=123.45.67.1
> [Route]
> Destination=10.0.0.0/8
> Gateway=10.0.0.1
> ```

It doesn't work, please reopen this issue. Thanks a lot.

**Comment by Winnie81** [comment]
BTW, I tested it with 2765.2.0.

**Comment by margamanterola** [comment]
So, could you please tell us what output does `ip route` and `networkctl` give you when you log in on the VGA console?

Also, could you please show the config that you used in your last test?

Thanks.

**Comment by Winnie81** [comment]
My configurations are as below:

[Match]
Name=ens192
[Network]
DNS=10.117.0.1
[Address]
Address=10.117.16.226
Netmask=255.255.254.0
[Route]
Gateway=10.117.17.253

After customization, I got:
![Uploading Screen Shot 2021-04-02 at 10.22.34 AM.png…]()

**Comment by Winnie81** [comment]
<img width="581" alt="Screen Shot 2021-04-02 at 10 22 34 AM" src="https://user-images.githubusercontent.com/27849915/113375617-609fc300-93a2-11eb-922b-b6a005bcbb9b.png">

Repost.

**Comment by pothos** [comment]
Can you please try if adding `DHCP=no` under `[Network]` and adding the right `Destination=…` under `[Route]` makes a difference?

**Comment by Winnie81** [comment]
> Can you please try if adding `DHCP=no` under `[Network]` and adding the right `Destination=…` under `[Route]` makes a difference?

Sorry for the late response.

For below configuration,
{
  "ignition": { "version": "2.0.0" },
   "networkd": {
    "units": [{
      "name": "00-ens192.network",
      "contents": "[Match]\nName=ens192\n\n[Network]\nAddress=10.117.16.226\nGateway=10.117.17.253\nDNS=10.117.0.1\nNetmask=255.255.255.0\nDestination=10.117.16.0\nDHCP=no"
    }]
  }
}
it didn't work. ip route and networkctl got the same results.

**Comment by pothos** [comment]
In the example I posted I used a different notation, please try to follow (e.g., besides separate sections I also used `/0` as suffix in the destination): https://github.com/flatcar-linux/Flatcar/issues/55#issuecomment-727736449

**Comment by Winnie81** [comment]
Verified it with 3139.2.0, it works. Thanks a lot.

> > Closing this as stale, please reopen if needed.
> > As written in the docs, this is what should work (here both private and public IP addresses are used, only one would also work):
> > ```
> > [Match]
> > Name=ens192
> > [Network]
> > DHCP=no
> > DNS=1.1.1.1
> > DNS=1.0.0.1
> > [Address]
> > Address=123.45.67.2/29
> > [Address]
> > Address=10.0.0.2/29
> > [Route]
> > Destination=0.0.0.0/0
> > Gateway=123.45.67.1
> > [Route]
> > Destination=10.0.0.0/8
> > Gateway=10.0.0.1
> > ```
> 
> It doesn't work, please reopen this issue. Thanks a lot.
