### ISSUE TITLE
[RFE] Re-use servers on Equinix Metal during tests to ease pressure on server recycle back-end

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#551]
## Current situation

For each test, we create one or more servers using the EM API and discard these after a test concluded.

## Impact

We burn through ~300 server creations per release (all channels).

## Ideal future situation

We acquire a set of 3 servers once and re-use these through all tests (re-install Flatcar to start with a clean slate).

**Comment by pothos** [comment]
The ESX platform has a similar mechanism to allocate the fixed set of static IP addresses: https://github.com/flatcar-linux/mantle/blob/flatcar-master/platform/machine/esx/cluster.go#L51 and https://github.com/flatcar-linux/mantle/blob/flatcar-master/platform/machine/esx/flight.go#L84 which could be done to allocate the packngo machines. The steps to "reset" a machine would be configuring boot from iPXE and setting the new userdata. A problem can be that when the machines keep the same name it could cause filename clashes in the kola log directory.
