### ISSUE TITLE
[RFE] Native SDK for ARM64

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#552]
## Current situation

We only ship the SDK for AMD64 platforms.

## Impact

There is no native way on ARM64 to work with the Flatcar SDK. Instead, AMD64 emulations needs to be used.

## Ideal future situation

The SDK ships for both ARM64 and AMD64, including toolchains for both architecture's OS images so each SDK can support each OS image arch.

## Implementation options

Evaluate the SDK container changes / simplifications to be used for adding ARM64 support.

**Comment by dongsupark** [comment]
Do you mean this issue? https://github.com/flatcar-linux/Flatcar/issues/319
I am already using the arm64-native SDK.

**Comment by t-lo** [comment]
Good catch @dongsupark , closing this in favour of #319  .
