### ISSUE TITLE
Torcx not running after update to latest stable (2983.2.0)

### ISSUE THREAD

**Issue by JensVD** [flatcar/Flatcar#555]
## Description
When updating our FlatCar VM's to the latest stable version (2983.2.0) docker is no longer available. The issue seems to be related to torcx that is not running.
`core@docker09 ~ $ docker ps`
`The program docker is managed by torcx, which did not run.`

`core@docker09 ~ $ systemctl status torcx.target`
`○ torcx.target - Verify torcx succeeded`
`     Loaded: loaded (8;;file://docker09.qa.careconnect.be/usr/lib/systemd/system/torcx.target^G/usr/lib/systemd/system/torcx.target8;;^G; disabled; vendor preset: disabled)`
`     Active: inactive (dead)`
`core@docker09 ~ $ sudo systemctl start torcx.target`
`Assertion failed on job for torcx.target.`
`core@docker09 ~ $ systemctl status torcx.target`
`○ torcx.target - Verify torcx succeeded`
`     Loaded: loaded (8;;file://docker09.qa.careconnect.be/usr/lib/systemd/system/torcx.target^G/usr/lib/systemd/system/torcx.target8;;^G; disabled; vendor preset: disabled)`
`     Active: inactive (dead)`
`Nov 22 13:41:48 docker09.qa.careconnect.be systemd[1]: torcx.target: Starting requested but asserts failed.`
`Nov 22 13:41:48 docker09.qa.careconnect.be systemd[1]: Assertion failed for Verify torcx succeeded.`

## Impact
The impact for us is that we've disabled reboots on all our Docker servers and are now on the previous stable version (2905.2.6). When trying to set up a new FlatCar VM the same issue surfaces, it seems that as of now we are unable to update our FlatCar servers and unable to provision new FlatCar servers.

## Environment and steps to reproduce
1. We are running FlatCar on VMWare. To set up our VM's we use a Fedora Workstation ISO where we set up the keyboard and the main network interface. After this we retrieve an ignition file from our ignition webserver and perform a flatcar install.
2. We encountered the bugs when our VM's were rebooting last week, the update was already downloaded but we control when the VM's are rebooted.
3. Steps:
- Configure a FlatCar VM running the stable version 2905.2.6
- Run the update engine
`sudo update_engine_client -update`
- Wait for the update to be installed and reboot the server as request by the update engine
`sudo reboot -h now`
4. The server is reboot but when running the docker command the following error is shown
`core@docker09 ~ $ docker ps`
`The program docker is managed by torcx, which did not run.`

## Expected behavior
Server should reboot using the new version and docker should be running without any issues.

## Additional information
We are aware that this new stable version contains the update to CGroupsV2 and the issue is probably related to this but we're not sure on how we can fix this issue.

If any more information is required, we can provide it.

**Comment by tormath1** [comment]
Hi @JensVD, 

Thanks for raising a complete bug description. We recently updated SELinux libraries and policies with the latest `stable`. Torcx issue seems to occur only when `enforcing` mode is set at boot time or via the `/etc/selinux/config` file (see this comment: https://github.com/flatcar-linux/Flatcar/issues/544#issuecomment-968726197).

A patch has been submitted in: https://github.com/flatcar-linux/coreos-overlay/pull/1426 and should be soon released in a following `stable` maintenance release.

Can you please confirm you're running with `enforced` SELinux ? (`$ sestatus`)

**Comment by crinjes** [comment]
Do you have a `/etc/flatcar/docker-1.12` file?
Mine contained "no" and removing that file resolved the issue of missing docker and failed torcx for us.

Logs:
```
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="common configuration parsed" base_dir=/var/lib/torcx/ conf_dir=/etc/torcx/ run_dir=/run/torcx/ store_paths="[/usr/share/torcx/store /usr/share/oem/torcx/store/2983.2.0 /usr/share/oem/torcx/store /var/lib/torcx/store/2983.2.0 /var/lib/torcx/store]"
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="profile found" name=docker-1.12-no path=/usr/share/torcx/profiles/docker-1.12-no.json
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="profile found" name=vendor path=/usr/share/torcx/profiles/vendor.json
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=info msg="selecting vendor profile \"docker-1.12-no\" from /etc/flatcar/docker-1.12"
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="skipped missing lower profile" missing profile=oem
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=warning msg="no next profile: unable to read profile file: open /etc/torcx/next-profile: no such file or directory"
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="apply configuration parsed" lower profiles (vendor/oem)="[docker-1.12-no]" upper profile (user)=
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="mounted tmpfs" target=/run/torcx/unpack
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="profile found" name=docker-1.12-no path=/usr/share/torcx/profiles/docker-1.12-no.json
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="profile found" name=vendor path=/usr/share/torcx/profiles/vendor.json
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="new archive/reference added to cache" format=tgz name=docker path="/usr/share/torcx/store/docker:20.10.torcx.tgz" reference=20.10
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="new archive/reference added to cache" format=tgz name=docker path="/usr/share/torcx/store/docker:com.coreos.cl.torcx.tgz" reference=com.coreos.cl
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=info msg="store skipped" err="open /usr/share/oem/torcx/store/2983.2.0: no such file or directory" path=/usr/share/oem/torcx/store/2983.2.0
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=info msg="store skipped" err="open /usr/share/oem/torcx/store: no such file or directory" path=/usr/share/oem/torcx/store
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=info msg="store skipped" err="open /var/lib/torcx/store/2983.2.0: no such file or directory" path=/var/lib/torcx/store/2983.2.0
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=info msg="store skipped" err="open /var/lib/torcx/store: no such file or directory" path=/var/lib/torcx/store
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=error msg="image docker:19.03 not found" image=docker reference=19.03
/usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=error msg="apply failed: failed to install 1 images"
```

**Comment by jepio** [comment]
@crinjes did you update from a very old version of Flatcar or create that file yourself?

**Comment by crinjes** [comment]
> @crinjes did you update from a very old version of Flatcar or create that file yourself?

A very old version of CoreOS, then Container Linux, then Flatcar. We did create that file ourselves as a workaround for something I believe, and it's stuck around since then (and made it into new configs as well) and forgotten.

I just mentioned it because the existence of this file produces the exact same symptoms starting with this version.

**Comment by jepio** [comment]
Thanks, that helps - i was completely unaware of that file and with the update to Docker 20.10 it now references a version we no longer ship. We'll need to think about what to do with that.

**Comment by JensVD** [comment]
Hello @tormath1 

Sorry for the late reply but there were some other things I had to take care off.
I just tested it again but it still fails, even with the new available release:
- Upgraded with SELinux in enforcing mode
- Upgraded with SELinux in permissive mode

The same issue occurs, torcx isn't running and starting it is not an option with the same error message.

Is there another setting that can be preventing us from upgrading our CoreOS servers?

Kind regards
Jens VD

**Comment by pothos** [comment]
@JensVD Yes, right, the issue is still there in enforcing mode, but interesting that it also hits the permissive mode in your case… Is disabling SELinux an option for you until this is fixed?

**Comment by JensVD** [comment]
Hello @pothos 

Even when disabling SELinux we get the same issue, torcx.target isn't running and starting it fails.
Could it be that something other than SELinux causes torcx to fail when updating to the latest version?

Kind regards
Jens VD

**Comment by zzvara** [comment]
> Do you have a `/etc/flatcar/docker-1.12` file? Mine contained "no" and removing that file resolved the issue of missing docker and failed torcx for us.
> 
> Logs:
> 
> ```
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="common configuration parsed" base_dir=/var/lib/torcx/ conf_dir=/etc/torcx/ run_dir=/run/torcx/ store_paths="[/usr/share/torcx/store /usr/share/oem/torcx/store/2983.2.0 /usr/share/oem/torcx/store /var/lib/torcx/store/2983.2.0 /var/lib/torcx/store]"
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="profile found" name=docker-1.12-no path=/usr/share/torcx/profiles/docker-1.12-no.json
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="profile found" name=vendor path=/usr/share/torcx/profiles/vendor.json
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=info msg="selecting vendor profile \"docker-1.12-no\" from /etc/flatcar/docker-1.12"
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="skipped missing lower profile" missing profile=oem
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=warning msg="no next profile: unable to read profile file: open /etc/torcx/next-profile: no such file or directory"
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="apply configuration parsed" lower profiles (vendor/oem)="[docker-1.12-no]" upper profile (user)=
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="mounted tmpfs" target=/run/torcx/unpack
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="profile found" name=docker-1.12-no path=/usr/share/torcx/profiles/docker-1.12-no.json
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="profile found" name=vendor path=/usr/share/torcx/profiles/vendor.json
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="new archive/reference added to cache" format=tgz name=docker path="/usr/share/torcx/store/docker:20.10.torcx.tgz" reference=20.10
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=debug msg="new archive/reference added to cache" format=tgz name=docker path="/usr/share/torcx/store/docker:com.coreos.cl.torcx.tgz" reference=com.coreos.cl
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=info msg="store skipped" err="open /usr/share/oem/torcx/store/2983.2.0: no such file or directory" path=/usr/share/oem/torcx/store/2983.2.0
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=info msg="store skipped" err="open /usr/share/oem/torcx/store: no such file or directory" path=/usr/share/oem/torcx/store
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=info msg="store skipped" err="open /var/lib/torcx/store/2983.2.0: no such file or directory" path=/var/lib/torcx/store/2983.2.0
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=info msg="store skipped" err="open /var/lib/torcx/store: no such file or directory" path=/var/lib/torcx/store
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=error msg="image docker:19.03 not found" image=docker reference=19.03
> /usr/lib64/systemd/system-generators/torcx-generator[662]: time="2021-11-24T15:45:49Z" level=error msg="apply failed: failed to install 1 images"
> ```

Same issue here. Upgraded from CoreOS to Flatcar initially.

**Comment by pothos** [comment]
@JensVD I don't know yet what your issue (edit: please post logs) is but the one @zzvara ran into has a fix in the coming release: https://github.com/flatcar-linux/coreos-overlay/pull/1456
I recommend you to try this workaround in the mean time by deleting `/etc/flatcar/docker-1.12` or `/etc/torcx/next-profile` to go back to the vendor profile.

**Comment by JensVD** [comment]
Hello @zzvara  and @pothos 

Appaerently we were indeed hitting the docker-1.12 issue.
It looks like it wasn't configured on one server causing that one to be successfully updated but all others failed. When removing that an update works.

Thank you for your help!
