### ISSUE TITLE
`mantle`: rename `packet` to `equinix-metal`

### ISSUE THREAD

**Issue by tormath1** [flatcar/Flatcar#561]
## Current situation

Mantle still refers to `Packet` instead of `Equinix Metal`

## **Implementation options

Something like:
```
git mv platform/api/packet/ platform/api/em
git mv platform/machine/packet/ platform/machine/em
sed -i "s,package packet,package em,"
sed -i "s,platform/api/packet,platform/api/em,"
sed -i "s,platform/machine/packet,platform/machine/em,"
```

`em` looks relevant as package name in front of other Mantle package name (`do`, `esx` and so on.) 

## Additional information

Need to be careful with automation that still relies on Packet [like](https://github.com/flatcar-linux/scripts/blob/7a0c0028b56c652f846f64d755ccfa28b267d83b/jenkins/kola/packet.sh#L60-L67): 
```shell
    --packet-api-key="${PACKET_API_KEY}" \
    --packet-facility="${PACKET_REGION}" \
    --packet-image-url="${IMAGE_URL}" \
    --packet-installer-image-kernel-url="${KERNEL_URL}" \
    --packet-installer-image-cpio-url="${CPIO_URL}" \
    --packet-project="${PACKET_PROJECT}" \
    --packet-storage-url="${UPLOAD_ROOT}/mantle/packet" \
    --packet-plan="${INSTANCE}" \
```

It can be considered as a good first issue from a technical PoV: massive sed + testing - but we should be able to run custom `mantle` into the CI in order to test it in a full CI before merging the contribution (see also: https://github.com/flatcar-linux/Flatcar/issues/562).

**Comment by jepio** [comment]
We could make mantle cli arg handling process `--packet-xxx` the same as `--em-xxx` for a release or two, which would make it possible to deploy mantle into CI first, and later sed all the CI scripts and test properly.

**Comment by tormath1** [comment]
@jepio totally, we can try to bind two flags to the same value and mark `--packet-xxx` as [deprecated](https://pkg.go.dev/github.com/spf13/pflag#FlagSet.MarkDeprecated).
