### ISSUE TITLE
Spliting Container Linux Configuration in multiple files

### ISSUE THREAD

**Issue by Beetix** [flatcar/Flatcar#564]
Hi,

Is it possible to split the Container Linux Configuration in multiple files? Is there an include mechanism?

Thanks

**Comment by jepio** [comment]
There is a runtime include mechanism, so you can have a single config that references multiple others that get appended.  Check out `ignition.config.append` here https://www.flatcar-linux.org/docs/latest/provisioning/config-transpiler/configuration/. Is that what you're after?

**Comment by Beetix** [comment]
> There is a runtime include mechanism, so you can have a single config that references multiple others that get appended. Check out `ignition.config.append` here https://www.flatcar-linux.org/docs/latest/provisioning/config-transpiler/configuration/. Is that what you're after?

I've just tried it like so:
```
ignition:
  config:
    append:
      - source: "../services/service.yaml"
```
I am getting an `invalid url scheme` error. My understanding is that it doesn't support inclusion of files from the local filesystem, right?

I saw in `ct`'s usage a `files-dir` option. Is this used for the configuration yaml files?

Thank you for your help

**Comment by jepio** [comment]
ct's `files-dir` is applicable to `storage.files.contents.local`. `ignition.config.append` needs to be:
> the URL of the config. Supported schemes are http, https, s3, tftp, and data

The only way to make this work right now, would be to format the configuration in the `source` field manually:
```
printf "data:;base64,%s\n" "$(ct <service.yaml | base64 -w 0)"
```
This value needs to go into the `source` field.

**Comment by Beetix** [comment]
I see. Not very convenient :grimacing:

Thanks

**Comment by jepio** [comment]
This will be possible when we upgrade to ignition v3.
#387
