### ISSUE TITLE
VRF (Virtual Routing and Forwarding) not working

### ISSUE THREAD

**Issue by defo89** [flatcar/Flatcar#568]
## Description

Not possible to create VRFs. [Reference](https://www.kernel.org/doc/html/latest/networking/vrf.html)

## Environment and steps to reproduce

1. **Set-up**: Flatcar 3033.1.1, 5.10.80-flatcar (current Beta). Also tested on Stable.
2. **Task**: Trying to set up VRF
3. **Action(s)**:
```
# ip link add VRF-A type vrf table 10
Error: Unknown device type.
```
4. **Error**:
```
# lsmod | grep vrf
# modprobe vrf
modprobe: FATAL: Module vrf not found in directory /lib/modules/5.10.80-flatcar
```

To compare with Ubuntu 20.04.3 LTS, 5.4.0-90-generic.
```
# ip link add VRF-A type vrf table 10
# ip link show VRF-A
22: VRF-A: <NOARP,MASTER> mtu 65575 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 42:bb:1e:c0:22:8b brd ff:ff:ff:ff:ff:ff
# modprobe vrf
# lsmod | grep vrf
vrf                    28672  0
```

**Comment by pothos** [comment]
Hi,
right, `CONFIG_NET_VRF` is not set (I think it's rather a feature request and not a real bug?). We would need to add it to this file: https://github.com/flatcar-linux/coreos-overlay/blob/main/sys-kernel/coreos-modules/files/commonconfig-5.15

**Comment by krnowak** [comment]
There is a PR doing it, among other things: https://github.com/flatcar-linux/coreos-overlay/pull/1524

**Comment by jepio** [comment]
I'll resolve this since it will be a part of the next alpha release.

**Comment by krnowak** [comment]
I'd swear that I added a closing clause to the PR, but apparently I didn't. Thanks for closing it.
