### ISSUE TITLE
Update Docker to major release 19

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#57]
**Description**
Flatcar ships Docker 18.x.. This issue tracks the upgrade to Docker major release 19.x.

**Comment by dmazhar-cogniance** [comment]
Hi @t-lo 
Could you please suggest when this will be propagated into the stable channel? It looks like we found a little-bit incompatibility in our set-up between 18.x and 19.x, so we trying to schedule fix before this will go to stable.

**Comment by t-lo** [comment]
Hello @dmazhar-cogniance,
It's on the roadmap but we don't have a fixed ETA yet; I'll keep you posted.

To mitigate your risk you might want to investigate supplying a custom [torcx](https://docs.flatcar-linux.org/os/torcx-overview/#what-is-torcx) profile which you could use to install a custom docker version. Not suggesting anything, just making sure you're aware of alternatives.

**Comment by dmazhar-cogniance** [comment]
Thanks for the suggestion :)
We have identified an issue and prepared a fix, so we'll be ready to migrate to docker 19.x. Just a little bit afraid that will not be able to propagate it through all the environments before this will get to stable channel. Is it something that will happen this/next week or later?

**Comment by mikekuzak** [comment]
Hi

Back on CoreOS I froze the Docker version 18.06 via this script: 
https://support.coreos.com/hc/en-us/articles/360005202674-Update-Docker-on-CoreOS-using-torcx

I have migrated CoreOS to Flatcar and now running Beta 2513.2.0 with Docker 19. 
How do I unfreeze the docker version to use the one which comes with Flatcar in this case docker 19 ? 

Thanks

**Comment by pothos** [comment]
Hi,

writing `vendor` to `/etc/torcx/next-profile` and rebooting should bring you back to the default version.

**Comment by dongsupark** [comment]
Now all channels have Docker 19.
Can we close?
