### ISSUE TITLE
custom kernel module build broken with stable channel release 2983.2.1

### ISSUE THREAD

**Issue by kthommandra** [flatcar/Flatcar#574]
The packages needed to build dev container are missing from latest release on stable channel.

The latest release on stable channel as of now is https://www.flatcar-linux.org/releases/#release-2983.2.1

However the packages corresponding to this release are NOT available yet here

https://mirror.release.flatcar-linux.net/boards/amd64-usr/

The latest release on the above URL is 2983.2.0

Given that custom kernel modules need the packages and dev container to build against the kernel release, need the appropriate packages to be updated on the mirror.release URL as soon as a release is published on the stable channel.

Is this lag between the publication of a release on the "stable" channel and corresponding "dev container" available AFTER few days the norm? or is this a one-time miss?

**Comment by dongsupark** [comment]
Thanks for the bug report.
Yeah, indeed https://mirror.release.flatcar-linux.net/boards/amd64-usr/2983.2.1 does not exist.
Mirrors were not synced last time when we did the releases.
Will soon update the mirror.

**Comment by dongsupark** [comment]
Fixed.
Mirrors are synced now for Stable 2983.2.1 as well as Beta 3033.1.1.
If there is any remaining issue, feel free to reopen.

**Comment by kthommandra** [comment]
Thank you very much. Appreciate the quick response and fix.

FlatCar experience, including the smooth upgrade from CoreOS has been very smooth for us.
Thank you for all the work.
