### ISSUE TITLE
[RFE] Provide OpenStack images using gzip compression to allow import via web_download to Glance

### ISSUE THREAD

**Issue by frittentheke** [flatcar/Flatcar#575]
## Current situation

Flatcar images for OpenStack (https://www.flatcar-linux.org/docs/latest/installing/community-platforms/openstack/) currently are provided bzip2 compressed (https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_openstack_image.img.bz2 is the only version).

## Impact

While it's no issue to download the image, decompress it and then import into OpenStack Glance bzip2-compressed images cannot be imported using the web_download of the interoperable image import (https://docs.openstack.org/glance/latest/admin/interoperable-image-import.html#image-import-methods) instructing Glance to download the image directly with no requirement for the image to be downloaded by the user and then to be decompressed and uploaded by the user (and his potentially poor internet upstream capacity).

Glance very much can download and decompress images, just not in bzip2 format, see https://docs.openstack.org/glance/latest/admin/interoperable-image-import.html#the-image-decompression or https://opendev.org/openstack/glance/src/branch/master/glance/async_/flows/plugins/image_decompression.py

## Ideal future situation

Please kindly provide a gzip compress version (and phase out the bzip2 if you don't want to waste the space for two compression formats).

I compared the sizes and there is not a huge difference:

`flatcar_production_openstack_image.img.bz2`: 345M 
`flatcar_production_openstack_image.img.gz`: 362M 

## **Implementation options

While it certainly possible to add more algorithms like bzip2 or xz to Glance, this will take quite a while to be found in actual production setups.

## Additional information

none

**Comment by t-lo** [comment]
* Compression happens in the [upload step of image_to_vm.sh](https://github.com/flatcar-linux/scripts/blob/main/image_to_vm.sh#L132)
* via `upload_image` in [vm_image_util.sh](https://github.com/flatcar-linux/scripts/blob/main/build_library/vm_image_util.sh#L1197)
* which is implemented in [release_util.sh](https://github.com/flatcar-linux/scripts/blob/main/build_library/release_util.sh#L194)
* the relevant line being https://github.com/flatcar-linux/scripts/blob/main/build_library/release_util.sh#L194

I guess this could be extended to detect `openstack` image types (`openstack` and `openstack_mini`) and to use gzip in that case. Looks like a good first issue!

**Comment by gabriel-samfira** [comment]
Heya! I'd like to tackle this one if no one else is interested.

**Comment by jepio** [comment]
Go ahead @gabriel-samfira

**Comment by gabriel-samfira** [comment]
Addressed by: https://github.com/flatcar-linux/scripts/pull/233
