### ISSUE TITLE
Update to kernel version 5.6 or newer

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#58]
**Description**
Currently, Flatcar Container Linux Alpha, Beta, and Stable use the LTS kernel series 4.19.x. This issue tracks the update to 5.6 (or newer).

**Impact**
Kernel release 5.6 ships many desirable features not present in 4.19, e.g. upstream wireguard support. Not providing recent features restricts the use cases covered by Flatcar, limiting our users.

**Comment by dongsupark** [comment]
When Kernel 5.6 is released, we should immediately update Edge to Kernel 5.6.
Though for Stable, Beta, Alpha, we should first update to Kernel 5.4, as 5.4 would be LTS for the next years.
After that, when Stable is well-known to work with 5.4, we can update to newer versions like 5.6 for Alpha, Beta, etc.

**Comment by dongsupark** [comment]
5.6 for Edge: https://github.com/flatcar-linux/Flatcar/issues/64

**Comment by dongsupark** [comment]
5.4 for Alpha: https://github.com/flatcar-linux/Flatcar/issues/73

**Comment by t-lo** [comment]
While we should move to 5.6 in Alpha (then Beta, Stable) at some point, ingesting 5.4 makes sense for now. This will allow us to stabilise 5.6 as long as needed while having a modern kernel (5.4) available soon.

**Comment by t-lo** [comment]
Closing this as 5.6 is shipped with current Edge and we'll go with 5.4 in the upcoming Alpha.
