### ISSUE TITLE
Question: How to find the OS version upon next boot 

### ISSUE THREAD

**Issue by kthommandra** [flatcar/Flatcar#580]
Assuming the update-engine has updated the alternate partition with a new FlatCar version.

Post install and prior to reboot, how can I find out the exact version into which the system will boot into upon next reboot ?

update-engine logs seems to indicate current version but not the version that was last updated.

**Comment by kthommandra** [comment]
update-engine upon restart did print the URL version it is trying to fetch

Url0 = https://update.release.flatcar-linux.net/amd64-usr/3033.2.0/flatcar_production_update.gz

I was trying to find out if we can know the OS version present in the USR-A and USR-B partition.

**Comment by pothos** [comment]
Hello,
`update_engine_client -status` prints out the new version that got downloaded. When you booted into the new version, you find the old version in `/var/lib/update_engine/prefs/previous-version`.

The version you currently run is in `/usr/share/flatcar/release`. You can mount the inactive `/usr` partition and read the file there as well: `sudo mkdir -p /mnt/inactive-usr ; sudo mount -r "$(sudo cgpt find -t flatcar-usr | grep --invert-match "$(rootdev -s /usr)")" /mnt/inactive-usr/ ; cat /mnt/inactive-usr/share/flatcar/release ; sudo umount /mnt/inactive-usr`

(Took the command to find the inactive partition from https://www.flatcar-linux.org/docs/latest/setup/debug/manual-rollbacks/#performing-a-manual-rollback)
