### ISSUE TITLE
[RFE] Upgrade all releases to iproute2 v5.8.0+ 

### ISSUE THREAD

**Issue by andy-v-h** [flatcar/Flatcar#584]
## Current situation

While attempting to take advantage of XDP with cilium and have found we’re hitting an issue similar to #172. and looking it seems like this libelf and iproute2 issue was resolved and merged in a few LTS branches, but it’s not currently in the stable branches. I am wondering if there is a reason I’m not finding or if it would be possible to cherry-pick the change into stable branches going forward. https://github.com/flatcar-linux/portage-stable/pull/100

## Impact

Would provide a newer iproute2 binary that is also linked against libelf.

## Ideal future situation

n/a

## **Implementation options

n/a
## Additional information

n/a

**Comment by tormath1** [comment]
Hi @andy-v-h, 

Thanks for raising this issue. It seems we are hitting a regression, let's compare two `iproute2` from current (`3033.2.0`) stable and an old stable (`2765.2.6`):

3033.2.0:
```
$ ldd $(which ip)
	linux-vdso.so.1 (0x00007ffda0301000)
	libbsd.so.0 => /lib64/libbsd.so.0 (0x00007f1aa9622000)
	libmnl.so.0 => /lib64/libmnl.so.0 (0x00007f1aa961a000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f1aa9615000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f1aa944e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1aa9720000)
```
2765.2.6:
```
$ ldd $(which ip)
	linux-vdso.so.1 (0x00007ffd145ea000)
	libbsd.so.0 => /lib64/libbsd.so.0 (0x00007fc18620f000)
	libelf.so.1 => /lib64/libelf.so.1 (0x00007fc1861f5000)
	libmnl.so.0 => /lib64/libmnl.so.0 (0x00007fc1861ed000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc1861e8000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc186024000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fc18600a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc186317000)
```

As you pointed, `libelf` linking is missing - it seems to appear in this commit: https://github.com/flatcar-linux/portage-stable/commit/406576c5e554e10950c82fa7f3692d62743958b2:

```
$ git show 406576c5e554e10950c82fa7f3692d62743958b2 -- profiles/base/package.use | grep iproute
-sys-apps/iproute2 elf
```

**Comment by tormath1** [comment]
Hi @andy-v-h, 

Thanks again for this bug report. `iproute2` should be now linked against `libelf` in the following set of releases.
