### ISSUE TITLE
Use CGroups v2 by default

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#59]
**Description**
Currently, Alpha, Beta and Stable channels ship CGroups v1. The kernel community has moved on, to CGroups v2.

**Impact**
CGroups v2 supports cgroup hierarchies and includes highly desired features used e.g. by [inspektor gadget](https://github.com/kinvolk/inspektor-gadget).

**Comment by pothos** [comment]
Two thoughts:
- We should consider using the `unified` mode directly instead of transitioning to `hybrid` and later transitioning again to `unified`.
- In Edge the mode is set via the kernel command line. We should just set it in the systemd ebuild where we currently set `-Ddefault-hierarchy=legacy`.

**Comment by goochjj** [comment]
`unified` will likely break Docker, until Docker 20 is released. `hybrid` will not

**Comment by dongsupark** [comment]
FYI, cluster-api and kubeadm [decided](https://github.com/kubernetes/kubeadm/issues/2376#issuecomment-764566612) to together move on to systemd cgroup.
Effective starting from Kubernetes 1.21, which will be probably released in March or April 2021.
It is not a breaking change per-se on the Flatcar side.
However, we should really think about the transition.

**Comment by mleklund** [comment]
what is the general timeline of a feature like this making it to stable?

I saw it has been released in alpha.

**Comment by jepio** [comment]
In general alpha->stable transitions take between 2 and 4 months, but there is no hard rule. In this case I expect this feature to land on stable next month (October).

Are you asking because you're looking forward to it?

**Comment by mleklund** [comment]
Yes, I looking to move k8s to 1.20+, I use kubeadm which wants systemd-cgroups, and we are trying to get away from root containers.

**Comment by till** [comment]
@t-lo Is there a doc with implications and how to continue on `v1` for a bit? I struggle to find something.

**Comment by pothos** [comment]
@till Docs are here: https://www.flatcar-linux.org/docs/latest/container-runtimes/switching-to-unified-cgroups/
You can deploy new nodes in a way that they get the same settings as the existing nodes get during an update to make them stay on v1.
