### ISSUE TITLE
Leaked selinux policy store files to the image root directory

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#596]
## Description

These files/directories got added to the images compared to the 3066 Alpha:

```
+/final
+/mcs
+/mcs/active
+/mcs/active/modules
+/mcs/semanage.read.LOCK
+/mcs/semanage.trans.LOCK
+/mls
+/mls/active
+/mls/active/modules
+/mls/semanage.read.LOCK
+/mls/semanage.trans.LOCK
+/targeted
+/targeted/active
+/targeted/active/modules
+/targeted/semanage.read.LOCK
+/targeted/semanage.trans.LOCK
```

## Impact

Possibly people are confused/concerned

## Environment and steps to reproduce

```
FILE=flatcar_production_image_contents.txt FILESONLY=1 CUTKERNEL=1 CHANNEL_A=alpha CHANNEL_B=alpha ./package-diff 3066.0.0 3115.0.0
```

## Expected behavior

These files should not leak to the rootfs

## Additional information

Probably related to the recent selinux policy store fix

**Comment by tormath1** [comment]
Issue is fixed in this upstream commit: https://github.com/gentoo/gentoo/commit/54a8322d1885f7f1bfe2718fb731d6e195f86466

**Comment by pothos** [comment]
Also newest Stable and Beta got affected but the fix is merged already and will be part of the following releases
