### ISSUE TITLE
Bug smashing Friday - 2022-01-28

### ISSUE THREAD

**Issue by tormath1** [flatcar/Flatcar#603]
The goal of this event is to go trough the Flatcar [issues](https://github.com/flatcar-linux/Flatcar/issues) and try to:
* check if they are still relevant
* add steps to reproduce the issue
* add the correct labels
* ask for more information
* ...

<details>
  <summary>Click for Zoom information</summary>
  
* Link: https://us06web.zoom.us/j/89332204295?pwd=WXBMTndKNjh6SE1GR1Q3dGp2MzdMUT09
* Meeting ID: 893 3220 4295
* Passcode: 99999
</details>

Let's kick-off the first bug smashing of the year. 
- [x] tweet announcement @miao0miao 
- [x] add event to the Flatcar Community [Calendar](https://calendar.google.com/calendar/ical/c_ii991mqrpta9en8o7ofd4v19g4%40group.calendar.google.com/public/basic.ics) @t-lo
- [x] create a document to track the on-going discussions during the event: https://hackmd.io/qnV1OSSbRKqB7v161nEfyQ
- [x] 1h before meeting: announce in matrix (w/ Zoom link) @miao0miao
- [x] add the YouTube link to the event
- [x] conduct the event @flatcar-linux/flatcar-maintainers

**Comment by t-lo** [comment]
Zoom link: https://us06web.zoom.us/j/89332204295?pwd=WXBMTndKNjh6SE1GR1Q3dGp2MzdMUT09
Meeting ID: 893 3220 4295
Passcode: 99999

**Comment by miao0miao** [comment]
should we aim for some specific time for the streaming? (I want to add that info in a tweet)

**Comment by t-lo** [comment]
The [calendar slot on Friday is from 9am to 6pm CET](https://calendar.google.com/calendar/u/0/embed?src=c_ii991mqrpta9en8o7ofd4v19g4@group.calendar.google.com), happy to adjust if that's not right.

**Comment by miao0miao** [comment]
I created a link tree: 
https://flow.page/flatcarbugsmashingday

**Comment by tormath1** [comment]
We closed around 39 issues (40 with this one) and updated more than 55. Thanks everyone !
