### ISSUE TITLE
[RFE] support for toolbox  without `docker.service` running

### ISSUE THREAD

**Issue by andy-v-h** [flatcar/Flatcar#607]
## Current situation

The `toolbox` script is written to rely on `docker.socket` and `docker.service` being up and running. I run a Kubernetes environment with `containerd` as the `cri` directly. 

## Impact

In my environment, if enable `docker` to run `toolbox` it creates undesirable network configs for `docker0`, namely the default configuration creates a network in 172.16.0.0/12. This leads to issues for me. 

## Ideal future situation

`toolbox` functionality is available without `docker` as a dependency. Given many Kubernetes installations no longer use the `docker-shim`, moving away from dependencies on `docker` would be beneficial to many of those operators.

## Implementation options

`containerd` tooling would be used to create the `toolbox` container such as `crictl` or `nerdctl`.

## Additional information

While I acknowledge this issue is impacting my environment directly, I would imagine this is not an uncommon use-case/configuration for Flatcar to be running as the OS for a production Kubernetes environment.

**Comment by pothos** [comment]
It got implemented in https://github.com/flatcar/toolbox/pull/7 by using `ctr`, and will be available in a future Alpha release (you can also copy the script and invoke it as `./toolbox` to get it now already).
