### ISSUE TITLE
Include boot logs and pstore contents in mayday tarball

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#61]
**Current situation**
Debugging early boot issues and kernel crashes is hard as vital information is missing from the mayday tarball.

**Impact**
Automated retrieval of kernel crash logs and early boot logs is not possible. Users need to manually capture the respective information.

Impact is particularly high for large, automated fleets.

**Ideal future situation**
The output of `journalctl -b -1` and the contents of `/sys/fs/pstore/`, and possibly the contents of any directory specified in the mayday configuration, is delivered via the mayday tarball.

**Additional information**
* Mayday repo: https://github.com/flatcar-linux/mayday
* Mayday issues:
  * https://github.com/flatcar-linux/mayday/issues/2 _Include boot logs with mayday_
  * https://github.com/flatcar-linux/mayday/issues/3 _Add the contents of /sys/fs/pstore to mayday tarballs_
  * https://github.com/flatcar-linux/mayday/issues/1 _Add ability to include contents of a directory with mayday_

**Comment by pothos** [comment]
Support for the features was merged and is scheduled for inclusion in the next Alpha and Edge release, then the following Beta and Stable releases.
