### ISSUE TITLE
[RFE] bpftool on Flatcar

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#617]
## Current situation

While for debugging a node with, e.g., broken network, there is tcpdump already but nowadays there can be bpf programs loaded, too, that interact with the network system yet Flatcar has no way to easily see this layer. The normal tool for interaction with bpf is bpftool, which allows to list the loaded programs or the bpf features of the kernel.

## Impact

Bpf is effectively a black box except for looking for files under `/sys/fs/bpf/`, and without network access it's hard to fetch the tool from a container.
Also, bpftool should match the running kernel version.

## Ideal future situation

bpftool is shipped on `/usr`

**Comment by dongsupark** [comment]
Right, we should have bpftool.
In the past we had that only in [edge](https://github.com/flatcar-linux/coreos-overlay/pull/402), but never in other channels.
Meanwhile Gentoo started to natively provide [dev-util/bpftool](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-util/bpftool), so it should be even easier.

**Comment by dongsupark** [comment]
Filed PRs:
* https://github.com/flatcar-linux/portage-stable/pull/291
* https://github.com/flatcar-linux/coreos-overlay/pull/1658

**Comment by dongsupark** [comment]
Merged
