### ISSUE TITLE
Weak Key Exchange algorithm diffie-hellman-group14-sha1 is enabled by default

### ISSUE THREAD

**Issue by dharmab** [flatcar/Flatcar#62]
**Description**

The default SSHD configuration on Flatcar enables the `diffie-hellman-group14-sha1` Key Exchange algorithm. This algorithm is considered to be a weak algorithm by the CIS Distribution Independent Linux benchmark v2.0.0:

![Screen Shot 2020-03-26 at 19 49 39](https://user-images.githubusercontent.com/4450708/77713027-f5efc680-6f9a-11ea-9cfd-6c1820c875a0.png)

**Impact**

Organizations using Flatcar subject to CIS benchmarks must customize the SSH key exchange algorithms to remove weak algorithms.

**Environment and steps to reproduce**

Run `sudo sshd -T | grep kexalgorithms`

**Expected behavior**

Weak algorithms should not be present by default.

**Additional information**

This is super nitpicky, but I was running through the CIS benchmark for my org to make sure Flatcar met our compliance requirements and I noticed this. Thought I'd file an issue.

**Comment by vbatts** [comment]
Incoming fixes:
- https://github.com/kinvolk/init/pull/36
- https://github.com/kinvolk/coreos-overlay/pull/852

**Comment by dongsupark** [comment]
Alpha 2801.0.0 includes the fix https://github.com/kinvolk/init/pull/36 .

On its production image, you can see:
```
$ sudo sshd -T | grep kexalgorithms 
kexalgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
```
As it shows, the kexalgorithms do not include weak ones like `diffie-hellman-group14-sha1`.

The fix will be included in other channels as well in the future.
Thanks!
