### ISSUE TITLE
[RFE] ci: Migrate emerge-gitclone to use scripts repo tags and submodule refs

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#623]
## Current situation

emerge-gitclone used in the dev container relies on the manifest to check out the right scripts/coreos-overlay/scripts/portage-stable references: https://github.com/flatcar-linux/flatcar-dev-util/blob/flatcar-master/emerge-gitclone#L22
In the future we want to retire the manifest as we now have tags on the "scripts" repo for each build and two submodules for coreos-overlay and portage-stable that are alreay in sync.

## Impact

To avoid future breakage we should migrate early

## Ideal future situation

The emerge-gitclone tool checks out the scripts tag and initializes the submodules to checkout the right references

## Implementation options

Do it as the SDK container helper scripts which have all the git commands already

## Additional information

emerge-gitclone is supposed to be run in the dev container and find the right version at runtime. One thing to keep in mind is that our git tag have a name like "alpha-VERSION" but in the version.txt we don't store the channel and we need to read the channel from/usr/share/flatcar/update.conf
The tag should only be used for the scripts repo, but for coreos-overlay and portage-stable we should use the submodule refs from the scripts repo.

**Comment by pothos** [comment]
While testing that the dev container works, we should also check if it can use binary packages (e.g., in case it is https://mirror.release.flatcar-linux.net/boards/ we need to make sure we still upload the binary packages there).

**Comment by krnowak** [comment]
Taking it.

**Comment by pothos** [comment]
One way would be coreos-overlay/portage-stable symlinks to the scripts repo's submodules, another is to clone separately and check out the submodule ref by getting it like in https://github.com/flatcar-linux/flatcar-build-scripts/blob/master/show-changes#L55

**Comment by krnowak** [comment]
Reassigning to Sayan, since he has started working on it. I'll pick up something else.

**Comment by pothos** [comment]
Let's reopen until the [coreos-overlay update](https://github.com/flatcar-linux/flatcar-dev-util/pull/9#issuecomment-1239422100) is done

**Comment by pothos** [comment]
One PR for LTS-2021 is opened https://github.com/flatcar-linux/coreos-overlay/pull/2134 but we still need it for main and backports
