### ISSUE TITLE
Kola tests sometimes fail

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#629]
Tracking issue:

- [x] `cl.ignition.oem.regular` complains that it "got: btrfs\nbtrfs" instead of `btrfs` for the OEM filesystem check: https://github.com/flatcar-linux/mantle/pull/304
- [x] random tests fail due to etcd type errors: `panic: field etcdserverpb.Request.ID has invalid type: got uint64, want pointer` https://github.com/flatcar-linux/mantle/pull/293
- [ ] `cl.ignition.v1.once` fails to delete the created test file because it is not found
- [x] `cl.filesystem/{deadlinks,stickydirs,suid}` on GCE complains about files in `/var/lib/flatcar-oem-gce/`: the test is racing with GCE OEM services, and should not be looking under that directory: https://github.com/flatcar-linux/mantle/pull/310
- [ ] `cl.ignition.v2_1.swap` tries to reformat USR-B as swap, sometimes fails with: 	
`cluster.go:130: "sudo blkid -s UUID -o value /dev/disk/by-label/USR-B" failed: output , status Process exited with status 2`
- [ ] `bpf.execsnoop/filter_name_and_args` fails with "bpf.go:78: unable to get container ready: no logs, the service has not started yet properly"
- [ ] `cl.swap_activation` fails with Error: "filesystem.go:403: swap is not enabled while it should be" but in the console log I see the swap getting activated. Maybe the test does the check too early and should retry a bit.
- [ ] `cl.cloudinit.basic` seen failing because cloudinit didn't run, because some logic explicitly skipped enabling it.
- [x] `cl.update.grubnop` fails because it uses coreos-cloudinit to mask update-engine.service after it started. Systemd sees that the service file got invalidated and kills the service. Later kola finds a failed service and complains (harness.go:535: Cluster failed starting machines: machine \"90f1a678-1fe7-4563-9d74-82d638fd290c\" failed basic checks: some systemd units failed:\n● update-engine.service masked failed failed update-engine.service\nstatus: \njournal:-- No entries --): https://github.com/flatcar-linux/mantle/pull/309
- [ ] `cl.ignition.kargs` timeouts on Equinix Metal (because SSH client for journal expect a quick reboot (like 10minutes)) https://github.com/flatcar-linux/mantle/pull/320

**Comment by pothos** [comment]
- [ ] `cl.swap_activation` fails with   `Error: "filesystem.go:403: swap is not enabled while it should be"` but in the console log I see the swap getting activated. Maybe the test does the check too early and should retry a bit.

**Comment by pothos** [comment]
I found the strange case that `cl.ignition.v2.ext4root/1463f2c2-440a-4201-9884-006be3451899/journal.txt` and `console.txt` totally differ. The console.txt has the output matching the userdata but `journal.txt` seems to be the output of `coreos.ignition(v1).groups`

**Comment by pothos** [comment]
- [ ] `cl.update.grubnop` fails because it uses `coreos-cloudinit` to mask `update-engine.service` after it started. Systemd sees that the service file got invalidated and kills the service. Later kola finds a failed service and complains (`harness.go:535: Cluster failed starting machines: machine \"90f1a678-1fe7-4563-9d74-82d638fd290c\" failed basic checks: some systemd units failed:\n● update-engine.service masked failed failed update-engine.service\nstatus: \njournal:-- No entries --`).

**Comment by jepio** [comment]
# cl.cloudinit.basic
Seen failing because cloudinit didn't run, because some logic explicitly skipped enabling it. Here are logs from a failing run and a passing (re)run.
[journal-fail.txt](https://github.com/flatcar-linux/Flatcar/files/8212690/journal-fail.txt)
[journal-pass.txt](https://github.com/flatcar-linux/Flatcar/files/8212689/journal-pass.txt)

**Comment by pothos** [comment]
- [ ] `bpf.execsnoop`: `cluster.go:117: Status: Downloaded newer image for quay.io/iovisor/bcc:latest` `bpf.go:78: unable to get container ready: no logs, the service has not started yet properly`

Edit: ah, that was already in the list…

**Comment by tormath1** [comment]
I think we can close this. With the retry loop on the new CI automation, it's been a while since we did not notify flaky tests.
