### ISSUE TITLE
How to update a custom Flatcar machine ?

### ISSUE THREAD

**Issue by carezkh** [flatcar/Flatcar#631]
I built a custom Flatcar image following the instructions in document https://www.flatcar.org/docs/latest/reference/developer-guides/sdk-modifying-flatcar/#making-changes

> board: amd64-user
version:  3033.2.2+2022-02-14-1145

I use `flatcar-install` to install Flatcar to disk with this image (in `__build__/images/images/amd64-usr/developer-3033.2.2+2022-02-14-1145-a1/flatcar_production_image.bin` , use bzip2 to compress it) . Reboot from the disk, and OS is running...

In the future I might add some packages and build another custom image using the same method. How can I use this new image to update the Flatcar machine ?

Thanks!

**Comment by pothos** [comment]
The end of this section shows how to use the `flatcar-update` script for that:
https://www.flatcar.org/docs/latest/migrating-from-coreos/update-from-container-linux/#the-migration-script
In your case you would use `--force-dev-key` instead of `--force-flatcar-key`.

**Comment by pothos** [comment]
(If you want your machine to follow the regular Flatcar updates you would need to use an other way of customization: https://www.flatcar.org/docs/latest/installing/customizing-the-image/customize-the-image/)

**Comment by carezkh** [comment]
Oh I see, thanks for your advice!

**Comment by pothos** [comment]
The flow is like for airgapped updates, I guess we should add a new docs section for that

**Comment by pothos** [comment]
Created a docs PR here: https://github.com/flatcar-linux/flatcar-docs/pull/211
