### ISSUE TITLE
Raspberry PI 3 support

### ISSUE THREAD

**Issue by maxromanovsky** [flatcar/Flatcar#634]
- I have followed steps depicted in https://github.com/flatcar-linux/Flatcar/issues/502 and in blog post mentioned on https://github.com/flatcar-linux/Flatcar/blob/main/community-meetings/2022-01-11-slides.pdf (BTW, the blog is offline, but the page is still available at https://github.com/littichokha/journalctl.dev/blob/main/content/posts/2021-12-25-flatcar-runs-on-raspberry-pi.md).
- I've used RPI3 UEFI firmware from https://github.com/pftf/RPi3 instead of RPI4 firmware

Raspberry PI goes through UEFI, the GRUB, however it reboots after the following lines displayed on connected monitor:
```
Booting "Flatcar default'
EFI stub: Booting Linux Kernel...
EFI stub: Using DIB from configuration table
EFI stub: Exiting boot services and installing virtual address map...
```

As I understand, RPI3 also uses `arm64` architecture, as it's compatible with Raspberry PI OS 64-bit.

Is it possible to add support for RPI v3, as there are still plenty of them around.

Thanks in advance!

**Comment by jepio** [comment]
I'm not super familiar with the state of UEFI and mainline kernels on rpi3, but the most likely culprit is the `acpi=force` flag passed to the kernel. Rpi3 might work in device tree mode. When in grub, try editing the menuentry and adding a line like this before `linux`:
```
set linux_cmdline="rootflags=rw mount.usrflags=ro consoleblank=0 $linux_root $linux_console $first_boot $randomize_disk_guid $oem $linux_append"
```
I removed `extra_options` from the default one, which contains the acpi=force arg.

**Comment by maxromanovsky** [comment]
@jepio it didn't help unfortunately. I've edited `Flatcar default` like this and pressed `F10` to boot. It reboots just as previously in ~5 sec after `EFI stub: Exiting boot services and installing virtual address map...`

![IMG_9256](https://user-images.githubusercontent.com/749775/154859913-0756d640-f23c-4414-9ae2-87dc89926fdc.jpg)

**Comment by pothos** [comment]
I guess the problem could be missing kernel config settings
