### ISSUE TITLE
[RFE] - NFS4 with Kerberos 

### ISSUE THREAD

**Issue by owenthomas17** [flatcar/Flatcar#636]
## Current situation

Currently not able to mount nfs4 shares with Kerberos on flatcar. 

## Impact

Unable to use flatcar against our new storage provider. The company I work for has traditionally been Windows and we're in the process of migrating all of the code to Linux. Our storage provider is able to expose the same share as CIFS/NFS/S3 and therefore gives us the cleanest migration path into Linux, first to CIFS then move CIFS mounts to NFS and finally can start to focus time on moving codebases to use S3. NFS gives us significant performance improvements over SMB/CIFS even when using multichannel.

## Ideal future situation

Unable to mount NFS4 shares with Kerberos.

## Implementation options

- Add use flags to nfs-utils so that we can use nfs4.1 and kerberos
- Add kernel module to support `rpc-gssd.service` 

## Additional information

N/A

**Comment by tormath1** [comment]
Support is enabled on the latest Alpha-3165.0.0 release: https://www.flatcar.org/releases/#release-3165.0.0. Thanks again for your contribution !
