### ISSUE TITLE
[RFE] Keep packages in portage-stable updated

### ISSUE THREAD

**Issue by krnowak** [flatcar/Flatcar#645]
Here is an ongoing effort to update the packages in portage-stable. The goal is to have all the packages that are either the same version as gentoo or of lower revision.

It's a part of #96.

First done by EAPI versions:

- [x] EAPI 0 - https://github.com/flatcar/portage-stable/pull/264
- [x] EAPI 1 - N/A
- [x] EAPI 2 - https://github.com/flatcar/portage-stable/pull/226
- [x] EAPI 3 - https://github.com/flatcar/portage-stable/pull/242
- [x] EAPI 4 - https://github.com/flatcar/portage-stable/pull/246

EAPI 5 and further had too many packages to update in one go, so switching to years:

- [x] 2011 - https://github.com/flatcar/portage-stable/pull/290
- [x] 2012 - https://github.com/flatcar/portage-stable/pull/293
- [x] 2013 - https://github.com/flatcar/portage-stable/pull/295
- [x] 2014 - https://github.com/flatcar/portage-stable/pull/287
- [x] 2015 - https://github.com/flatcar/portage-stable/pull/299
- [x] 2016 - https://github.com/flatcar/portage-stable/pull/300  
- [x] 2017 - https://github.com/flatcar/portage-stable/pull/301
- [x] 2018 - https://github.com/flatcar/portage-stable/pull/302
- [x] 2019 - https://github.com/flatcar/portage-stable/pull/305
- [x] 2020 - https://github.com/flatcar/portage-stable/pull/320
- [x] 2021 - https://github.com/flatcar/portage-stable/pull/352 https://github.com/flatcar/portage-stable/pull/323 https://github.com/flatcar/portage-stable/pull/329

Most of the packages are from 2022 or 2023, so next step is to put system packages under automation (system packages are packages maintained by `base-system@gentoo.org`):

- [x] app-arch - https://github.com/flatcar/portage-stable/pull/431
- [x] app-* - https://github.com/flatcar/scripts/pull/791
- [x] dev-* - https://github.com/flatcar/scripts/pull/811
- [x] net-* - https://github.com/flatcar/scripts/pull/812
- [x] sys-apps - https://github.com/flatcar/scripts/pull/822
- [x] rest - https://github.com/flatcar/scripts/pull/931

Most of the portage-stable packages are now relatively new and all the system packages are under automation. We can have a look at our reports repository to see how many packages are automated, currently (as of 2023-09-28) [we have automated 449 out of 551 items in portage-stable](https://github.com/flatcar/reports/blob/master/2023-09-21/txt#L44-L50), which is about 80%. Let's have percentage-based goals now.

- [x] 85% - https://github.com/flatcar/scripts/pull/1394
- [x] 90% - https://github.com/flatcar/scripts/pull/1446, https://github.com/flatcar/scripts/pull/1470
- [x] 95% - https://github.com/flatcar/scripts/pull/2192, https://github.com/flatcar/scripts/pull/2193
- [x] 99% - https://github.com/flatcar/scripts/pull/2214
- [ ] 100% - https://github.com/flatcar/scripts/pull/2373

Note: there is a `usr-ldscript` eclass that we have overridden, will be handled as a part of #646.

**Comment by dongsupark** [comment]
Checked 2020 & 2021.

**Comment by krnowak** [comment]
Updated the issue to reflect current state.
