### ISSUE TITLE
users cannot write system-shutdown scripts

### ISSUE THREAD

**Issue by mdaniel** [flatcar/Flatcar#65]
**Description**

Due to `/usr/lib` being mounted read-only, [and systemd only looking in that directory](https://github.com/systemd/systemd/blob/v241/src/core/shutdown.c#L266), it is not possible to author [system-shutdown script(s)](https://www.freedesktop.org/software/systemd/man/systemd-halt.service.html)

**Impact**

Similar to [other users](https://stackoverflow.com/questions/38234554/coreos-alternative-to-usr-lib-systemd-system-shutdown), it was not obvious how to write a script that would execute only for halt or poweroff.

**Environment and steps to reproduce**

1. **Set-up**: AWS ami-007776654941e2586 (Flatcar-stable-2345.3.0-hvm)
2. **Task**: attempting to unregister etcd members during AWS instance shutdown/termination
3. **Action(s)**:
  a. read the man page for systemd-halt.service
  b. attempt to author a shutdown script
4. **Error**: `/usr/lib/systemd/system-shutdown is read-only`

**Expected behavior**

```console
# echo "echo 'bye cruel world'" > /var/lib/systemd/system-shutdown/bye-bye.sh
```

**Additional information**

I'm actually not sure which repo has responsibility for this misalignment: Flatcar because it mounts `/usr` readonly and [seemingly has influence over the shutdown directory](https://github.com/systemd/systemd/blob/v241/meson.build#L133), or systemd for using a **list** of `char* dirs[]` that contains only one magic compile-time path, rather than offering customization via a flag or environment variable or such

**Comment by pothos** [comment]
Thanks for raising this here.
On a first look I think it is possible to define a custom service that is pulled by the halt/reboot target or service and other people have done it: see https://unix.stackexchange.com/a/41756 or https://unix.stackexchange.com/a/39250 or maybe the most promising https://unix.stackexchange.com/a/479048. It would be good to document the best workaround.

Using a shutdown script is possible with a bind mount to `/usr/lib/systemd/systemd-shutdown/` but I don't recommend it if using real service units works.

**Comment by t-lo** [comment]
Alternatively, you could create an override file for the `etcd-member.service` in `/lib/systemd/system/` and put it into `/etc/systemd/system/`. In that file, you could add an [ExecStopPost](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStopPost=) stanza to unregister etcd members after the etcd service stopped.

This would implement the **Task** in a service-centric way in contrast to the system-centric approach discussed previously.

**Comment by mdaniel** [comment]
Thank you for pointing out those stackexchange links; I tried that but it turns out that an EC2 Auto Scaling event appears to be the equivalent of yanking the power cord out of the machine, and as best I can tell the `etcdadm reset` either doesn't run or doesn't _finish_ running before the machine dies

So at your discretion: I can close this issue because it seems there are other systemd-y ways of doing things, or alternatively we can leave it open to track that Flatcar and systemd have a misalignment about who can write to where

Either way, I do appreciate your quick response, and I am very grateful for Flatcar!

**Comment by pothos** [comment]
With systemd 249 on Stable one can use a sysext image that makes the hook available under `/usr`.

**Comment by pothos** [comment]
Actually it's only recommended for use it starting from Flatcar 3227.1.0 Beta.
We have docs for sysext images here: https://www.flatcar.org/docs/latest/provisioning/sysext/
In this case it's just a single file besides the sysext metadata file, so you can also put them into a directory instead of using a squashfs.

Here a CLC yaml to be transpiled to Ignition:
```
storage:
  files:
    - path: /etc/extensions/shutdown-hook/usr/lib/extension-release.d/extension-release.shutdown-hook
      contents:
        inline: |
          ID=flatcar
          SYSEXT_LEVEL=1.0
    - path: /etc/extensions/shutdown-hook/usr/lib/systemd/system-shutdown/bye-bye.sh
      mode: 0755
      contents:
        inline: |
          echo 'bye cruel world'
```

**Comment by pothos** [comment]
Would be good to add this example to the docs.

**Comment by pothos** [comment]
Tried, does not work because the sysext seems to gets unloaded before the hook.

Back to one of these here then:

> On a first look I think it is possible to define a custom service that is pulled by the halt/reboot target or service and other people have done it: see https://unix.stackexchange.com/a/41756 or https://unix.stackexchange.com/a/39250 or maybe the most promising https://unix.stackexchange.com/a/479048. It would be good to document the best workaround.

**Comment by pothos** [comment]
Docs PR: https://github.com/flatcar/flatcar-docs/pull/283
