### ISSUE TITLE
trying to disable net.ipv4.ip_forward

### ISSUE THREAD

**Issue by Akshaybaisla** [flatcar/Flatcar#658]
I am trying to disable net.ipv4.ip_forward from file "/etc/sysctl.d/*" (nt.conf file) but when I write net.ipv4.ip_forward=0. I found out that it is not reading from that file. It is changing according to /proc/sys/net/ipv4/ip_forward. 

- provide some solution by which I can disable "net.ipv4.ip_forward"

**Comment by jepio** [comment]
Hi @Akshaybaisla, have you seen this issue https://github.com/flatcar-linux/Flatcar/issues/297? The sysctl.d files do work but there  are other ways through which ip_forwarding gets enabled: docker will enable it, systemd-networkd as well.

What you can do is set the iptables policy: `iptables -P FORWARD DROP`, which will stop ip_forwarding for anything not matching any other rules.

**Comment by tormath1** [comment]
Hello, I'll close this issue. Feel free to reopen that issue if you got a chance to try the resolution suggested. Thanks :)
