### ISSUE TITLE
Kola - add error messages of failing tests to tap file

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#66]
**Current situation**
While the result (pass / skip / fail) of a test run is recorded in the `.tap` file, the error message of failing tests is not recorded.

**Impact**
Understanding test failures requires manual digging through the test logs.

**Ideal future situation**
All test failures' error messages are recorded in the test run`.tap` file, so all failures of a test run can be viewed at a glance. The `.tap` file can be used to discuss both successes as well as to gauge the impact of failures.

**Comment by pothos** [comment]
According to https://testanything.org/tap-specification.html we can add a Diagnostics block after the line with the failure. The Diagnostics block should have `#` as prefix for its lines. Wikipedia mentions on https://en.wikipedia.org/wiki/Test_Anything_Protocol that it would use whitespace instead of a `#` – let's see what the Jenkins plugin handles.

**Comment by pothos** [comment]
I guess it wants the diagnostics as YAML: https://github.com/tupilabs/tap4j/blob/master/src/main/java/org/tap4j/parser/Tap13Parser.java#L448

**Comment by t-lo** [comment]
Example YAM-in-TAP (tested on Jenkins):
```YAML
1..3
ok - cl.ignition.misc.empty
not ok - cl.verity
  ---
  Error: "multi-line error message
with 
 some more error output
    at various indents
   which will end up in a single line"
  Something else: 'Maybe we want to record other stuff, too. In single quotes.'
  Third item: No need to use any quotes for single-line items.
  ...
ok - cl.basic
```

**Comment by pothos** [comment]
PR in https://github.com/flatcar-linux/mantle/pull/75

**Comment by t-lo** [comment]
Implemented via https://github.com/flatcar-linux/mantle/pull/75 which has been merged. Closing. Thank you Kai!
