### ISSUE TITLE
Compressing Ignition Files

### ISSUE THREAD

**Issue by strawgate** [flatcar/Flatcar#67]
Amazon AWS limits the size of User Data that can be attached (the Ignition File) to 16kb -- we have some pretty large ignition files that we are working on trimming but we'd love the ability to gzip the file (as it's mostly text) or perform some other compression to keep the size down.

**Comment by strawgate** [comment]
I think this might actually be already supported so im going to close this

**Comment by pothos** [comment]
Yes, but I think it is just base64 plus gzip, right? So me may want to revisit this topic if we have a good idea how to improve the situation.
I tried using compression a bit with but eventually realized that with a lot of cryptographic keys that are random data it is hard to gain much with compression. You can refer to file contents via URL in Ignition if that helps.
