### ISSUE TITLE
Recommendation to delete all the rules and enable the audit service to run

### ISSUE THREAD

**Issue by Akshaybaisla** [flatcar/Flatcar#681]
On applying Flatcar recommendations as mentioned in  https://www.flatcar.org/docs/latest/setup/security/selinux/ (https://www.flatcar.org/docs/latest/setup/security/selinux/%22) and running "auditctl -l" is returning "No Rules". And with "no rules" it means audit service will not work by default. Why we have this recommendation to delete all the rules and how we can enable the audit service to run ??

**Comment by jepio** [comment]
Hi @Akshaybaisla,
it is expected that you provide your own audit rules.

These instructions are the way they are because the default Flatcar audit rules in `99-default.rules` contain this entry:
```
# Ignore everything else.
-a exclude,always -F msgtype>0
```
which disables all other rules. So you definitely need to remove that one.
