### ISSUE TITLE
Systemd-networkd route setup leads to failed interface state (v249 but also in v250 now)

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#685]
## Description

We noticed that the DigitalOcean network setup is in a failed state since somewhere between 2512.5.0 (works, systemd v241) and 2605.7.0 (fails, systemd v245). This got visible now through a systemd 249.11 stable backport fix that changed the behavior of making failed network interfaces not pass the network-online check anymore as was the case before which hid this issue.
The failed state itself on DigitalOcean is not a huge problem because the network is operational already despite the errors (`Could not set route: Invalid prefix for given prefix length. Invalid argument`).

## Impact

We [reverted back to systemd 249.10](https://github.com/flatcar-linux/coreos-overlay/pull/1748) to continue to silence this issue and reach the network-online target successfully.

## Environment and steps to reproduce

TODO: come up with a QEMU reproducer instead of using the afterburn DigitalOcean networkd units

## Expected behavior

On v250 the `Could not set route: Invalid prefix for given prefix length. Invalid argument` are not present any longer and the interface is set up successfully (`configured` state). This is what we actually expect for 249, too.

## Additional information

We have not yet found the patch that fixed this issue in 250 to look whether we can propose a backport to 249 in the upstream systemd-stable repo, allowing us to update it in Stable.

**Comment by dongsupark** [comment]
Thanks for creating the issue.

> On v250 the "Could not set route: Invalid prefix for given prefix length. Invalid argument" are not present any longer 

Actually that error is not present only until v250.3.
In v250.4 or newer, it would fail like that just like v249.11, because v250.4 has also the following commits:
* https://github.com/systemd/systemd-stable/commit/397ede8dcd29f35350c015f1d945e50c88476a93
* https://github.com/systemd/systemd-stable/commit/056fcd4e318aa664bd36950bf6c2dae4647c96c7

**Comment by tormath1** [comment]
systemd 252 is now shipped and latest news regarding this issue: https://github.com/flatcar/coreos-overlay/pull/2343#issuecomment-1355448409
> All platforms green.

I guess we're safe to close this one.
