### ISSUE TITLE
arm64 image differences

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#689]
## Description

Some binaries and libraries are not present on the arm64 image.

## Impact

It may be confusing to users or block a migration to arm64 when suddenly something is missing that was present on amd64

## Environment and steps to reproduce

This will give the list:
```
BOARD_A=amd64-usr BOARD_B=arm64-usr CHANNEL_A=alpha CHANNEL_B=alpha FILE=flatcar_production_image_contents.txt FILESONLY=1 CUTKERNEL=1 flatcar-build-scripts/package-diff  3185.0.0   3185.0.0
```

## Expected behavior

Where it makes sense the arm64 image should be the same as the amd64 image

**Comment by pothos** [comment]
Here one concrete case: https://github.com/flatcar-linux/Flatcar/issues/690

**Comment by jepio** [comment]
sssd pulls in samba which pulls in liburing, which doesn't cross-compile. I've opened an upstream PR with a fix: https://github.com/gentoo/gentoo/pull/24733. Other than that there's a one keyword to be added.

**Comment by mtougeron** [comment]
Now that `liburing` has been updated in `3200.0.0` would it be possible to get `sambda` updated so `sssd` can be cross-compiled too so https://github.com/flatcar-linux/Flatcar/issues/690 can be fixed?

**Comment by krnowak** [comment]
I'm working on samba update among some other things here - https://github.com/flatcar-linux/coreos-overlay/pull/1819.

**Comment by jepio** [comment]
Perhaps you could contribute a PR to remove the amd64 condition from here: https://github.com/flatcar-linux/coreos-overlay/blob/main/coreos-base/coreos/coreos-0.0.1.ebuild#L76-L84 so that those sssd becomes part of arm64 images @mtougeron

**Comment by mtougeron** [comment]
Sure, I'd be happy to help. (I previously had no idea where to look)

**Comment by pothos** [comment]
I've checked with
```
BOARD_A=amd64-usr BOARD_B=arm64-usr CHANNEL_A=developer CHANNEL_B=developer MODE_A=/developer/ MODE_B=/developer/ FILE=flatcar_production_image_contents.txt FILESONLY=1 CUTKERNEL=1 ./package-diff  2022.06.13+dev-flatcar-master-5850 2022.06.13+dev-flatcar-master-5850
```
and when ignoring some harmless differences I see the following files missing:
```
[…]
-/usr/lib64/security/pam_oslogin_admin.so
-/usr/lib64/security/pam_oslogin_login.so
-/usr/libexec/google_authorized_keys
-/usr/libexec/google_oslogin_nss_cache
-/usr/share/google-oslogin/[…]
-/usr/lib/firmware/isci/isci_firmware.bin
-/usr/lib/firmware/mellanox/mlxsw_spectrum-13.2008.2406.mfa2
-/usr/lib/firmware/mellanox/mlxsw_spectrum2-29.2008.2406.mfa2
-/usr/lib/firmware/mellanox/mlxsw_spectrum3-30.2008.2406.mfa2
[…]
```
and of course the kernel configs are a bit different which results in different modules being available in `/usr/lib/modules/a.b.c-flatcar/kernel/drivers/`.

I think the oslogin parts are only relevant for GCE which doesn't have an arm64 image at the moment, so ok to ignore, but the firmware and kernel configs for the drivers like mlx* could be something to look into.
