### ISSUE TITLE
Missing AMIs

### ISSUE THREAD

**Issue by Rumbles** [flatcar/Flatcar#69]
**Description**

Sorry if this is the wrong place to report this issue. This is to do with releases and AMIs rather than the OS itself.

I just tried to pull the latest AMI from [here](http://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_ami_hvm_eu-west-1.txt) and it was not found in AWS

**Impact**

I have had to revert back to CoreOS

**Environment and steps to reproduce**

1. **Set-up**: We use a script to pull the latest AMI from:

```
url=`printf "http://%s.release.flatcar-linux.net/amd64-usr/current/flatcar_production_ami_%s_%s.txt" $COREOS_UPDATE_CHANNE $VM_TYPE $AWS_REGION` (stable, hvm and eu-west-1 in this case)
```

2. **Task**: N/A
3. **Action(s)**: N/A
4. **Error**: The AMI returned for eu-west-1 and us-east-1 are not visible in the AWS console.

**Expected behavior**
We should get a valid AMI returned

**Additional information**
We have used this method for a few months since moving to flatcar from CoreOS, for the time being I have had to use CoreOS instead but would prefer to go back to FlatCar

**Comment by t-lo** [comment]
Thank you for raising this issue. We are experiencing issues with our image synchronisation service for our ongoing new release and are prioritising effort to resolve this. We'll keep you up to date.

**Comment by t-lo** [comment]
We were able to address the synchronisation issues; affected AMI name text files have been updated. E.g. for `eu-west-one` it's `ami-002db020452770c0f` which is available in that region:
```
$ aws ec2 describe-images --filters="Name=image-id,Values=ami-002db020452770c0f" --region eu-west-1
{
    "Images": [
        {
            "Architecture": "x86_64",
            "CreationDate": "2020-03-27T09:40:39.000Z",
            "ImageId": "ami-002db020452770c0f",
            "ImageLocation": "075585003325/Flatcar-stable-2345.3.1-hvm",
            "ImageType": "machine",
            "Public": true,
            "OwnerId": "075585003325",
            "State": "available",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/xvda",
                    "Ebs": {
                        "DeleteOnTermination": true,
                        "SnapshotId": "snap-069f02e86b3d06cd6",
                        "VolumeSize": 8,
                        "VolumeType": "gp2",
                        "Encrypted": false
                    }
                },
                {
                    "DeviceName": "/dev/xvdb",
                    "VirtualName": "ephemeral0"
                }
            ],
            "Description": "Flatcar Container Linux stable 2345.3.1 (HVM)",
            "EnaSupport": true,
            "Hypervisor": "xen",
            "Name": "Flatcar-stable-2345.3.1-hvm",
            "RootDeviceName": "/dev/xvda",
            "RootDeviceType": "ebs",
            "SriovNetSupport": "simple",
            "VirtualizationType": "hvm"
        }
    ]
}
```

Thank you again for reporting this issue, and please pardon the inconvenience.

I'll resolve now - please feel free to re-open should your issue persist.

**Comment by Rumbles** [comment]
Thank you for the rapid response! LGTM!
