### ISSUE TITLE
[RFE] ci-automation: Provide a minimal Kola / qemu container for reproducably running tests

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#693]
## Current situation

In the classic build environment, tests are not reproducible since kola versions used for testing are not recorded. This leads to a divergence between community / 3rd party testing and our CI / release tests.

In the containerised build environment, the SDK's kola version is updated to the respective kola release corresponding to the OS version being tested (based on the git submodule pinning of coreos-overlay). However, the SDK is not available for ARM, impacting ARM64 virtualised tests (qemu_uefi).

## Impact

Release testing and CI tests are not reproducible (classic). Qemu_uefi tests cannot be run on ARM64 (containerised testing).

## Ideal future situation

Following the pattern already established in classic tests for ARM64 qemu_uefi, a versioned, reproducible kola test container exists that is pinned to any given commit of the scripts repo. Tests can be run in a versioned manner, making release tests reproducible for 3rd parties.

## Implementation options

1. Provide automation for building the kola test runner container in the scripts repository; hard-wire commit tags to the mantle repo in the automation. Alternatively, add mantle as a git submodule to scripts.
2. Build and publish the kola test runner container to ghcr.io when mantle is updated.
3. Update `ci-automation/test.sh` to use the kola container in the version pinned to the current git tree for running tests instead of the SDK container.

## Additional information

We could consider removing the mantle/kola ebuild from coreos-overlay if migration to the test runner container is completed.

**Comment by pothos** [comment]
Draft for the container in https://github.com/flatcar-linux/mantle/pull/323
It covers all mantle binaries because, e.g., for some platforms `ore` is needed to create a cloud image before kola runs.

**Comment by pothos** [comment]
Draft for the container in https://github.com/flatcar-linux/mantle/pull/323
It covers all mantle binaries because, e.g., for some platforms `ore` is needed to create a cloud image before kola runs.

**Comment by pothos** [comment]
Scripts PR in https://github.com/flatcar-linux/scripts/pull/275

**Comment by pothos** [comment]
ebuild removal PR: https://github.com/flatcar-linux/coreos-overlay/pull/1827
