### ISSUE TITLE
[RFE] ci-automation: Build nightlies only on changes, push nightly build tags to branches

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#694]
## Current situation
1. Nightlies are build unconditionally - even when there was no change to the previous nightly.
2. Nightly builds generate a build tag and push it to the repo. While "main" branch build tags are pushed to the "main" branch, release branch tags are not pushed to any branch. 
3. Thirdly, the "main" branch is always built from scratch - SDK and OS image - but currently generates two tags: one for the SDK ("sdk-[vernum]" in the SDK bootstrap job) and one for the OS image ("main-[vernum]" in the packages job). 

## Impact
1. Build resources are wasted and build tags pile up without tangible benefit.
2. Release branch nightly build tags are not visible in the release branch, and binary package hosts to use packages from nightly builds need to be set up manually.
3. Each nightly build of the main branch creates two tags that point to the same commit.

## Ideal future situation
1. Nightly builds only build branches that have changes compared to the previous nightly build tag.
2. With the conditional (on-change) build condition above, we should start pushing these tags to the release branches, too.
3. "packages" should not push a tag in this case, and the SDK bootstrap should use the "main-[vernum]" tag.
4. Release tags can be added retrospectively and are not required to start a release build

## Implementation options
This is an opportunity to simplify ci-automation tagging logic and remove complexity from the scripts.

**Comment by pothos** [comment]
First PR here: https://github.com/flatcar-linux/scripts/pull/266

A follow-up PR will address the point 4 of using a release version in version.txt for the OS in the nightly release branch builds, while still using the nightly build tag. This requires to rework the logic that currently assumes that the tag corresponds to the OS version.

**Comment by pothos** [comment]
Split out point 4 in a separate [issue](https://github.com/flatcar-linux/Flatcar/issues/701) (it wasn't part of the original issue here anyway)
