### ISSUE TITLE
Nodes not rejoining Docker Swarm after reboot

### ISSUE THREAD

**Issue by cpswan** [flatcar/Flatcar#705]
## Description

When a Flatcar Linux based worker node is rebooted it shows as `DOWN` in the list returned by `docker swarm node ls`.

## Impact

The docker service needs to be restarted on the worker node with `sudo systemctl restart docker`

## Environment and steps to reproduce

1. **Set-up**: Flatcar 3033.2.4 (and 3033.2.2 previously)
2. **Task**: Rebooting a node
3. **Action(s)**:
  a. drain node from swarm
  b. reboot node
  c. node should be READY to be returned to ACTIVE, but it isn't 
4. **Error**: node shows as NOT READY

## Expected behavior

Node reboots and informs swarm manager that it's READY

**Comment by jepio** [comment]
Hi @cpswan

The default docker service is socket activated, have you executed `systemctl enable docker.service` to make sure the docker service is brought up after a reboot?

**Comment by till** [comment]
I can confirm, we use a workaround via systemd to poke the service and force start-up. Then node reboots work.

**Comment by jepio** [comment]
For reference, here's the section of the documentation that provides a config snippet to achieve this:
https://www.flatcar.org/docs/latest/container-runtimes/getting-started-with-docker/#permanently-running-a-container

**Comment by cpswan** [comment]
Thanks all. I haven't had the chance to test yet, but looks like this is a well paved path, so closing.
