### ISSUE TITLE
How long to wait between update_engine_client -reset_status and -check_for_update ?

### ISSUE THREAD

**Issue by cpswan** [flatcar/Flatcar#706]
## Description

When we find a node that doesn't have the latest version ready for upgrade we run `update_engine_client -reset_status` then `update_engine_client -check_for_update` according to the [Double update workaround](https://www.flatcar.org/docs/latest/setup/releases/update-strategies/#double-update-workaround) but we've found that it's not simply a case of running those two commands back to back. It only works properly with some delay (and repetition).

## Impact

At present my ripple restart script is having to `sleep 120` after `sudo update_engine_client -reset_status` then `sudo update_engine_client -check_for_update && sleep 120` and finally another `sudo update_engine_client -check_for_update`

## Environment and steps to reproduce

1. **Set-up**: Flatcar 3033.2.2
2. **Task**: Double update workaround
3. **Action(s)**: 
  a. `sudo update_engine_client -reset_status`
  b. `sudo update_engine_client -check_for_update`
4. **Error**: `sudo update_engine_client -status` does not move on
 
## Expected behavior

A single `sudo update_engine_client -check_for_update` should trigger an update in a deterministic timeframe.

**Comment by pothos** [comment]
Thanks for the report. Does `systemctl restart update-engine` have a similar effect as the sleep time?

**Comment by cpswan** [comment]
@pothos I'm struggling to come up with a practical way to test whether restarting the update-engine service will substitute for sleep, as I no longer have running instances that are >1 updates behind, and fresh installs of older images just grab the latest update rather than getting stuck on the next point release.

**Comment by cpswan** [comment]
I figured it out with `flatcar-update`, and indeed it seems that a `systemctl restart update-engine` does the trick between `-reset_status` and `-check_for_update`. But then whether I need to bother with all that now that `flatcar-update` exists is a different question.

**Comment by pothos** [comment]
Makes sense to change your approach and either use your own Nebraska update server to control the rollout or use [`flatcar-update --disable-afterwards`](https://www.flatcar.org/docs/latest/setup/releases/update-strategies/#disable-automatic-updates). Having updates downloaded without any reboot configured not only needs the workarounds above but also means that you would get unscheduled updates from a regular reboot and don't really know which version it will get.
