### ISSUE TITLE
[RFE] Get `flatcar_production_image_packages.txt` into the OS

### ISSUE THREAD

**Issue by tormath1** [flatcar/Flatcar#712]
Many enterprise companies (I can only speak for germans here) have a requirement to gather the software inventory from each running VM. Currently, I'm able to write a script which curls the packages.txt to the running VM. This is okay. But everybody has to do this.

In case, Flatcar would deliver this file inside the /usr as part of the distribution itself in a standardised way, tools like https://github.com/aquasecurity/trivy, https://github.com/aws/amazon-ssm-agent, e.g can be adjusted upstream to read the file and populate the software inventory of such files. 

The next step would be a vulnerability reporting based on installed packages inside Flatcar. I'm not expect that Flatcar is starting the setup a own vulnerability database, but Flatcar can be handled as Gentoo-like and could benefit from https://security.gentoo.org/.

_Originally posted by @jkroepke in https://github.com/flatcar-linux/Flatcar/discussions/709#discussioncomment-2529551_

**Comment by tormath1** [comment]
Implementation idea could be to have two files:
* `flatcar_production_image_packages.txt` as the one currently generated
* `flatcar_production_oem_packages.txt` for OEM packages

**Comment by pothos** [comment]
We have this information already in `/usr/share/licenses/licenses.json.bz2`, e.g., read it with `less /usr/share/licenses/licenses.json.bz2` or the command mentioned in `/usr/share/licenses/INFO`. We can also add a command that prints only the package version and skips other info.

**Comment by tormath1** [comment]
Since the file already exists, we can safely close that issue.
