### ISSUE TITLE
[RFE] Arm64 Support for Azure Kubernetes Service (AKS)

### ISSUE THREAD

**Issue by sfotony** [flatcar/Flatcar#716]
## Current situation

Azure recently announced [Azure Virtual Machines with Ampere Altra Arm-based processors](https://azure.microsoft.com/en-us/blog/now-in-preview-azure-virtual-machines-with-ampere-altra-armbased-processors/) is now in preview.  Flatcar was named as an OS whose support is "on the way".  I'd like to be able to use Flatcar on arm64 as the base for worker nodes on AKS.

## Impact

arm64 VMs bring costs savings and efficiency to certain workloads.  It would be a win for organizations to be able to have this as an option.

## Ideal future situation

I am able to use Flatcar arm64 images on AKS as soon as support for it is available on Azure VMs.

## Implementation options

[ Optional: please provide one or more options for implementing the feature requested ]

## Additional information

[ Please Add any information that does not fit into any of the above sections here ]

**Comment by ahrkrak** [comment]
Flatcar support for Arm64 virtual machines in Azure is now supported.
Enabling a different operating system for AKS worker nodes is an AKS product feature, and should be directed to the AKS team here: https://github.com/Azure/AKS
