### ISSUE TITLE
[RFE] Add afterburn-network-kargs service to initramfs for VMware static IP address configuration

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#717]
## Current situation

For VMware only DHCP works to set up networking in the initramfs, static IP addresses or special settings can't be used because they require to be passed via kernel command line

## Impact

VMware with static IP addresses means no remote content can be fetched with Ignition, this also impacts our CI coverage

## Ideal future situation

The initramfs network can be configured through guestinfo settings

## Implementation options

Put the new `afterburn-network-kargs.service` from https://github.com/coreos/afterburn/blob/main/dracut/30afterburn/afterburn-network-kargs.service in our bootengine dracut setup

**Comment by tormath1** [comment]
PR has been merged - this feature should be available in the next major alpha release.
