### ISSUE TITLE
ansible_os_family detection produces different results on different Flatcar versions

### ISSUE THREAD

**Issue by jepio** [flatcar/Flatcar#719]
## Description

Ansible determines ansible_os_family by looking at the existance of `/etc/flatcar/update.conf` or a fallback to parsing `/etc/os-release`. In the first case it determines the value "Flatcar" in the fallback case it's "Flatcar Container Linux by Kinvolk". This makes it difficult to write generic ansible code.

https://github.com/flatcar-linux/scripts/pull/212 removed /etc/flatcar/update.conf from default shipped images, which changed the ansible_os_family again.

## Impact

Difficult for users to handle Flatcar properly in Ansible.

## Environment and steps to reproduce

Run:
`ansible -i hosts.yaml hostname -m gather_facts | grep ansible_os_family`

## Expected behavior

One value of ansible_os_family (Flatcar) in all cases.

## Additional information

At this point /etc/flatcar/update.conf is API so we should restore it through a tmpfiles entry to either be empty or a symlink to /usr/share/flatcar/update.conf. Furthermore we should work with ansible to look at /usr/share/flatcar/update.conf instead of /etc.

**Comment by pothos** [comment]
> Furthermore we should work with ansible to look at /usr/share/flatcar/update.conf instead of /etc.

Why would Ansible need to read this file? I think it should just check `/etc/os-release` as with other distros.

**Comment by pothos** [comment]
> At this point /etc/flatcar/update.conf is API so we should restore it through a tmpfiles entry to either be empty or a symlink to /usr/share/flatcar/update.conf.

A symlink is not good because update-engine already has logic to check both locations and also it would require users to first delete the file and create it again before they can write their settings.

**Comment by pothos** [comment]
Ansible also tries to get the `distribtion_release` from the Nebraska group, which makes no sense: https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/system/distribution.py#L446

**Comment by pothos** [comment]
I suggest that Ansible implements the Flatcar detection similar how it's done for ClearLinux or Debian, to look at `/usr/lib/os-release` and ensure to always return `Flatcar` even if the name in os-release says `Flatcar Container Linux…`.

**Comment by jepio** [comment]
We contributed the code: https://github.com/ansible/ansible/commit/598e3392a9597f0214d68882da4f4ca07314ce41.

> A symlink is not good because update-engine already has logic to check both locations and also it would require users to first delete the file and create it again before they can write their settings.

As long as ignition handles overwriting a symlink we should be good?
Does update-engine parse both files? Then an empty file would work as well. Though ansible parses the GROUP= out of /etc/flatcar/update.conf.

Even if we fix ansible now, people pin ansible versions so they would still all be hurt by us removing the file.

**Comment by pothos** [comment]
Update-engine parses both files, the one under `/etc` is just for overwriting the defaults. I guess people don't rely on the GROUP information in ansible and an empty file should be fine, or?

**Comment by johananl** [comment]
FWIW I'm reporting the issue in Ansible upstream. We will obviously need workarounds wherever this bug is relevant but we might as well fix our Flatcar-related Ansible code. Will share a link soon.

**Comment by johananl** [comment]
Upstream issue: https://github.com/ansible/ansible/issues/77537

**Comment by till** [comment]
From a user perspective (mine): no big deal.

99% of the Ansible roles work with RedHat/Debian distributions, and will install software using a package manager. Not a very interesting use-case for Flatcar (or CoreOS, FCOS) anyway.

The gathering of instance data (IPs, disks, whatever) works very well though. :D

**Comment by pothos** [comment]
PR for creating an empty file if it doesn't exist: https://github.com/flatcar-linux/init/pull/71

**Comment by pothos** [comment]
The fix is merged and I'll close this now even though it will be out only in the next round of releases

**Comment by jepio** [comment]
Found the code: https://github.com/inspec/train/blob/main/lib/train/platforms/detect/specifications/os.rb#L201-L207

**Comment by invidian** [comment]
>The fix is merged and I'll close this now even though it will be out only in the next round of releases

Should there be a follow-up issue to remove this file after inspec, Ansible and others are fixed?

**Comment by pothos** [comment]
The file is empty and does not harm, we can leave it around I would say
