### ISSUE TITLE
cgroupv1-revert solution breaks procfs mounts within user namespaces

### ISSUE THREAD

**Issue by rodnymolina** [flatcar/Flatcar#722]
## Description

The solution introduced in `3033.2.4` to allow new nodes to revert to legacy [cgroup-v1](https://www.flatcar.org/docs/latest/container-runtimes/switching-to-unified-cgroups/#starting-new-nodes-with-legacy-cgroups) relies on the utilization of an artificial `/proc/cmdline`, which prevents the execution of unprivileged containers through the utilization of user namespaces.

## Impact

Upon activation of this feature (through the utilization of `/etc/flatcar-cgroupv1` file knob), procfs can't be mounted within user namespaces due to the presence of the `/proc/cmdline` bind-mount. In consequence, kernel's user-namespaces isolation feature is rendered unusable within flatcar nodes.

## Environment and steps to reproduce

1. Node running `3033.2.4` with `/etc/flatcar-cgroupv1` present. In my scenario (lokomotive) I do this through the utilization of a clc_snippet in my lokocfg file. These are the procfs related mountpoints in this scenario:

```
core@ip-10-0-4-128 ~ $ sudo cat /proc/self/mountinfo
19 128 0:18 / /proc rw,nosuid,nodev,noexec,relatime shared:14 - proc proc rw
...
26 19 259:7 /tmp/cmdline//deleted /proc/cmdline ro,relatime shared:15 - ext4 /dev/nvme0n1p9 rw,seclabel
...
45 19 0:39 / /proc/sys/fs/binfmt_misc rw,relatime shared:28 - autofs systemd-1 rw,fd=31,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=13625
```

2. Problem is reproduced by simply attempting to mount procfs within a user-namespace ...

```
core@ip-10-0-7-126 ~ $ sudo unshare -U -p -f --mount-proc -r /bin/bash
unshare: mount /proc failed: Operation not permitted

core@ip-10-0-7-126 ~ $ echo $?
1
```

## Potential Workaround

Problem can be workaround'd by doing a umount of the `/proc/cmdline` bind-mount, but I'm not sure about the implications that this may have for system applications that may be tempted to parse this (cmdline) file ...

```
core@ip-10-0-4-128 ~ $ sudo umount /proc/cmdline

core@ip-10-0-4-128 ~ $ sudo unshare -U -p -f --mount-proc -r /bin/bash
ip-10-0-4-128 /home/core #
```

## Expected behavior

I'm not sure why the kernel is returning EPERM upon detection of the `/proc/cmdline` bind-mount, but I did verify that this is not a Flatcar specific issue (other kernels do the same). My goal with this issue is to: 1) explore alternatives to the current `/proc/cmdline` approach for this nice (revert-cgroupv1) feature, and/or 2) validate/vet the workaround suggested above.

**Comment by pothos** [comment]
Thanks for the report. The `unmount` workaround should not have any negative effect.
That said, this should only affect your first boot because you are expected to set the kernel parameters in the `grub.cfg` config as well, maybe we should update the example in the [docs](https://www.flatcar.org/docs/latest/container-runtimes/switching-to-unified-cgroups/#starting-new-nodes-with-legacy-cgroups) to repeat the entries from the first example.

**Comment by pothos** [comment]
I filed a docs PR to improve the situation: https://github.com/flatcar-linux/flatcar-docs/pull/242

**Comment by rodnymolina** [comment]
Thanks for looking into this @pothos, it makes sense.

**Comment by rodnymolina** [comment]
The above workaround proved to be valid in the field. Also, thanks to @pothos doc [PR](https://github.com/flatcar-linux/flatcar-docs/pull/242), it's more clear now that this `/proc/cmdline` bind-mount should be only utilized during the first boot -- `grub.conf` should be updated from this moment on.

Closing issue now.

**Comment by jepio** [comment]
It would also be possible to move to setting `SYSTEMD_PROC_CMDLINE` (https://systemd.io/ENVIRONMENT/) instead of the bind mount, but that is extremely opaque to the user. Just a thought should there be more issues.
