### ISSUE TITLE
[RFE] ci-automation: Push nightly build references at job start

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#723]
## Current situation

When during the packages or SDK build a push to a development/release maintenance branch is done, the job fails to push it's build reference (version.txt, submodules update, and git tag).

## Impact

The nightly needs to be restarted or one needs to be aware of not pushing something during this 3 hour window.

## Ideal future situation

A rebase is not ideal because it would suggest that the nightly was build with this new change but in fact it was build before.
We can rather move the pushing to the front and try to monitor failures more closely to prevent having a reference to a broken build for too long.

## Implementation options

Currently the version.txt gets populated by `run_sdk_container` and we would need to invoke this logic a bit earlier already.

## Additional information

A related task: https://github.com/flatcar-linux/Flatcar/issues/701

**Comment by pothos** [comment]
The `run_sdk_container` invocation should in this case also not write the file again but use it as is (currently it prints `Writing versionfile…` each time)

**Comment by pothos** [comment]
One more consideration: The drawback of moving the push earlier is that there is a time where no binary packages nor images would be found for the nightly reference. This impacts mainly the case of starting a leave job in the CI directly, like the "test" job to run a simple kola test from a branch that was freshly branched away from `main` after the start of the nightly and gets used before the images are ready.

**Comment by t-lo** [comment]
+1 for pushing the tag at the start of the build. I think it's OK for leaf jobs to fail when the build did not finish yet. Also +1 for preventing `run_sdk_container` from writing a new versionfile.

**Comment by pothos** [comment]
> +1 for pushing the tag at the start of the build. I think it's OK for leaf jobs to fail when the build did not finish yet. Also +1 for preventing `run_sdk_container` from writing a new versionfile.

Good, maybe we can tweak the nightly build time a bit to prevent the case that we have to wait for it to finish.
