### ISSUE TITLE
[RFE] Support image signing in new CI pipeline

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#728]
## Current situation

The new CI pipeline in `scripts:ci-automation/` doesn't yet make use of the `--sign(_digest)` parameter as the original CI pipeline under `scripts:jenkins/` does.

## Impact

Currently we can only use the new CI pipeline for dev builds.

## Ideal future situation

Release builds can get signed with the new CI pipeline.

## Implementation options

It could be an optional job parameter or autodetection based on the git tag.

## Additional information

A possible reorganization of how we sign is out of scope, the aim here is feature parity with the original pipeline.

**Comment by krnowak** [comment]
If the plan is that at some point we can take a nightly build, run additional tests and make it a release, then nightly builds would also need to be signed. Or does this fall under the case of "a possible reorganization of how we sign is out of scope"?

**Comment by pothos** [comment]
Yeah, let's not get distracted by future possibilities^^ It's perfectly fine to reimplement what the original pipeline does but make it optional instead of on-by-default.

**Comment by pothos** [comment]
Since you already found out that it won't be straight port due to things not getting uploaded, you could also decouple the signing a bit more and do it at the end of the job instead of through the scripts parameters. Duplication of logic is not too bad then if the code gets more accessible than the magic hidden inside the current `sign_and_upload_files` function.

**Comment by pothos** [comment]
The signing works but I see only the .sig files and not the .asc files and the digest files are also missing (e.g., we expect to get something uploaded like `flatcar_production_azure.DIGESTS ….DIGEST.sig and ….DIGEST.asc`).
Other files we don't expect but land in the upload are the folders `oem-gce-aci pcrs rootfs torcx` (edit: now tracked in https://github.com/flatcar-linux/Flatcar/issues/801).

**Comment by krnowak** [comment]
Signing works, digests are generated, is there anything else to do?

**Comment by pothos** [comment]
I think we are good in terms of feature parity with the original pipeline :)
