### ISSUE TITLE
New Package Request: [acpid]

### ISSUE THREAD

**Issue by Patricol** [flatcar/Flatcar#738]
Hello!

I'm improvising a format as per #736.

When running Flatcar as a guest/vm in Proxmox, there is no proper way to poweroff or restart Flatcar instances. The two usual options are `qemu-guest-agent` (#737) and `acpid`, neither of which appear included in Flatcar. `acpid` is more universally useful as a backup option for hypervisors to use to power-cycle hosts, so I'd see it as a good solution.

This package will definitely improve the "Operate at scale / automation" core value, by adding a standard interface for power-cycling Flatcar VMs.

Gentoo repo: https://github.com/gentoo/gentoo/tree/master/sys-power/acpid

I'm not super familiar with the distinctions between `acpi` and `acpid`, and the `ACPI` protocol. It's clear to see that `ACPI` is involved in the Flatcar boot process based on tty output. The gentoo repo linked above also has `acpi`, `acpi_call`, and `acpitool` packages, but my understanding is that `acpid` is the only one necessary to get Flatcar VMs to handle ACPI events sent by the hypervisor.

The inclusion of `acpi`/`acpid` support would also help workaround a bug described in #737, which breaks ignition when configuring the hypervisor to not try to use `acpi`.

**Comment by tormath1** [comment]
Hi @Patricol, 

Thanks for opening this package request. `acpid` is now part of Flatcar and should be soon available in an Alpha release. :)

**Comment by Patricol** [comment]
Thank you so much!
