### ISSUE TITLE
[RFE] ci-automation: Rethink if we need the images container

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#740]
## Current situation

The image job of the new pipeline builds an image container that is multiple GBs big and takes >10 mins to be loaded in the vms job.
However, I think the vms job could also do its work by running from the packages container from the packages job when it fetchs the built image from bincache first (assuming the images job copies it there).

## Impact

Looking at the vms job makes one wonder if something is wrong because nothing happens for at least 10 minutes.

## Ideal future situation

We save the 10 minutes waiting time

## Implementation options

No images container is published anymore but the packages container is used in the vms job.

**Comment by till** [comment]
@pothos You are not referring to this right? https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar-container.tar.gz

Just in case, I am using that. 😅

**Comment by pothos** [comment]
Yes, not this^^ But interesting, what do you use it for and how?

**Comment by till** [comment]
> Yes, not this^^ But interesting, what do you use it for and how?

Building a (Docker) container for [footloose](https://github.com/weaveworks/footloose). To run a few tests for Ansible.

**Comment by amayausky** [comment]
@till That's pretty interesting. Do you mind sharing how you get the flatcar container running? I'm able to build an image and run it but it's missing a lot, including systemd. There's no real good docs on how to work with it. Hoping you might have something if you're using it to test Ansible.
