### ISSUE TITLE
networkd units not supported in ign-converter

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#741]
## Description

There was a bug report on Matrix that networkd units in a v2 config didn't get translated to v3 by ign-converter (i.e., when our Ignition sees a v2 config and lifts it to v3 internally).

## Impact

Either broken networking or the instance fails to boot? Didn't check

## Expected behavior

The v2 networkd unit (either a unit file or a drop-in) should be converted to a plain file entry in v3.

**Comment by tormath1** [comment]
as a follow-up action, we should update our doc to reflect this breaking change (like: https://www.flatcar.org/docs/latest/provisioning/ignition/network-configuration/)

**Comment by tormath1** [comment]
PR has been merged - and the fix should be available in the next beta / alpha release.
