### ISSUE TITLE
shutdown-script metadata in GCP not working. Was working in old coreos.

### ISSUE THREAD

**Issue by albertpx** [flatcar/Flatcar#743]
You can set a shutdown-script metadata in GCP, that will run upon instance shutdown:
https://cloud.google.com/compute/docs/shutdownscript

This used to work in CoreOS, but with Flatcar the script is not triggered.

Could be related to #737 and #738 - but I'm not sure if that is what's missing.

**Comment by tormath1** [comment]
hi @albertpx, 

Thanks for raising this. The issue has been identified and fixed there: https://github.com/flatcar-linux/coreos-overlay/pull/1912 and should be part of the next releases.

Feel free to re-open the issue if it does not work as expected :)
