### ISSUE TITLE
Ignition: networkd unit not applied (Link aggregation config not applied as a clc snippet)

### ISSUE THREAD

**Issue by mister2d** [flatcar/Flatcar#748]
### Discussed in https://github.com/flatcar-linux/Flatcar/discussions/746

<div type='discussions-op-text'>

<sup>Originally posted by **mister2d** May 19, 2022</sup>
Trying to bring up a DHCP `bond0` interface with no success. I based the config from this [example](https://www.flatcar.org/docs/latest/provisioning/ignition/network-configuration/#bonded-nics) in the Flatcar docs. Using this as a clc snippet doesn't appear to work. Udev has enumerated the two NICs as `eno12399` and `eno12409`.

```yaml
---
ignition:
  version: 2.0.0
networkd:
  units:
  - name: 00-eno.network
    contents: |-
      [Match]
      Name=eno12*

      [Network]
      Bond=bond0
  - name: 10-bond0.netdev
    contents: |-
      [NetDev]
      Name=bond0
      Kind=bond

      [Bond]
      Mode=802.3ad
      LACPTransmitRate=fast
      TransmitHashPolicy=layer2
      MIIMonitorSec=1s
  - name: 20-bond0.network
    contents: |-
      [Match]
      Name=bond0

      [Network]
      DHCP=true
```
</div>

**Comment by pothos** [comment]
PR for ign-converter in https://github.com/flatcar-linux/ign-converter/pull/6#event-6650669848

**Comment by pothos** [comment]
Previous issue: https://github.com/flatcar-linux/Flatcar/issues/741

**Comment by pothos** [comment]
I assume this happen with a Beta (3185) or Alpha release?

**Comment by tormath1** [comment]
Hi, yes Ignition translation fix should be available in the Beta (3227) / Alpha release :)

**Comment by mister2d** [comment]
I resolved with the following yaml. Had to change the unit name prefix to something higher than `10-`. I chose `60-` and it worked. Safe to close? Or is it a real bug?

```yaml
---
networkd:
  units:
  - name: 60-bond0.network
    contents: |-
      [Match]
      Name=eno12*

      [Network]
      Bond=bond0
  - name: 61-bond0.netdev
    contents: |-
      [NetDev]
      Name=bond0
      Kind=bond

      [Bond]
      Mode=802.3ad
      LACPTransmitRate=slow
      TransmitHashPolicy=layer2
      MIIMonitorSec=1s
       
  - name: 62-bond0.network
    contents: |-
      [Match]
      Name=bond0

      [Network]
      DHCP=true

      [DHCPv4]
      UseDomains=true
```

**Comment by pothos** [comment]
Ok, so this was on Stable, good.
Were there any other unit files under /etc/systemd/networkd/ or /run/systemd/networkd/ that had higher priority?

**Comment by tormath1** [comment]
Maybe this `afterburn` conflict (https://github.com/flatcar-linux/Flatcar/issues/731)  - what's your platform / provider @mister2d ?

**Comment by mister2d** [comment]
> Maybe this `afterburn` conflict (#731) - what's your platform / provider @mister2d ?

Bare metal.

**Comment by tormath1** [comment]
@mister2d hi, did you get a chance to check this:
> Were there any other unit files under /etc/systemd/networkd/ or /run/systemd/networkd/ that had higher priority?

Just to know if there are some generated files or remaining config that could conflict with your provided configuration.

**Comment by pothos** [comment]
Closing now, please tell if we should reopen.
