### ISSUE TITLE
GCP tests fail because /etc/pam.d doesn't exist when running the edge image

### ISSUE THREAD

**Issue by margamanterola** [flatcar/Flatcar#75]
**Description**

GCP tests are failing with errors related to /etc/pam.d not existing. From the journal.txt of the latest test:

```
Apr  6 22:07:09.265000 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:kernel_t:s0 msg='unit=systemd-update-utmp comm="systemd" exe="/usr/lib64/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr  6 22:07:09.305418 enable-oslogin[728]: ln: failed to create symbolic link '/etc/pam.d/sshd': No such file or directory
Apr  6 22:07:09.307306 systemd[1]: oem-gce-enable-oslogin.service: Main process exited, code=exited, status=1/FAILURE
Apr  6 22:07:09.307424 systemd[1]: oem-gce-enable-oslogin.service: Failed with result 'exit-code'.
Apr  6 22:07:09.307901 systemd[1]: Failed to start Enable GCE OS Login.
```
The same error was already present in tests that were run last weekend, so this isn't a fluke. The error shown above means that none of our tests can even run on the machines because it's not possible to login to them.

**What I've found so far**

I've downloaded the [stable image](https://console.cloud.google.com/storage/browser/_details/flatcar-jenkins/stable/boards/amd64-usr/2345.3.1/flatcar_production_qemu_image.img.bz2) and the [edge image](https://console.cloud.google.com/storage/browser/_details/flatcar-jenkins/edge/boards/amd64-usr/2466.99.0/flatcar_production_qemu_image.img.bz2) and compared them.

The stable image has **an empty /etc/pam.d**:
```
Flatcar Container Linux by Kinvolk stable (2345.3.1)
core@localhost ~ $ ls -l /etc/pam.d/
total 0
```

The edge image, has **no /etc/pam.d**:
```
Flatcar Container Linux by Kinvolk edge (2466.99.0)
core@localhost ~ $ ls -l /etc/pam.d/
ls: cannot access '/etc/pam.d/': No such file or directory
```

**Differences in packages shipped by each image**

I also checked the package versions (as published in the `flatcar_production_image_contents.txt` files for each track). These are the differences.

* Packages removed:
```
< virtual/shadow-0::portage-stable
```

* Packages added:
```
> acct-group/sshd-0::portage-stable
> acct-user/sshd-0::portage-stable
> app-crypt/gpgme-1.13.0::coreos
> virtual/libcrypt-1::portage-stable
> net-misc/cni-plugins-0.7.5::portage-stable
> net-vpn/wireguard-0.0.20191212::coreos
> sys-apps/bpftool-9999::coreos
> sys-apps/cgroupid-0.1.0::coreos
```

* New versions of packages:
```
< app-admin/kubelet-wrapper-0.0.4::coreos
> app-admin/kubelet-wrapper-0.0.4-r2::coreos
< app-admin/mayday-1.0.0-r1::coreos
> app-admin/mayday-1.0.0-r2::coreos
< app-admin/sudo-1.8.28::coreos
> app-admin/sudo-1.8.31::coreos
< app-admin/toolbox-0.0.0-r13::coreos
> app-admin/toolbox-0.0.0-r14::coreos
< app-emulation/docker-1.12.6-r8::coreos
< app-emulation/docker-18.06.3::coreos
> app-emulation/docker-19.03.8::coreos
< app-emulation/rkt-1.30.0-r2::coreos
> app-emulation/rkt-1.30.0-r1::coreos
> app-emulation/cri-o-1.15.2::coreos
> app-emulation/cri-tools-1.16.1::coreos
< coreos-base/afterburn-4.0.0-r4::coreos
> coreos-base/afterburn-4.0.1-r2::coreos
< coreos-base/update-ssh-keys-0.3.0-r4::coreos
> coreos-base/update-ssh-keys-0.4.2-r1::coreos
< dev-libs/libgcrypt-1.8.1::portage-stable
> dev-libs/libgcrypt-1.8.3::portage-stable
< dev-libs/libgpg-error-1.27-r1::coreos
> dev-libs/libgpg-error-1.29::coreos
< dev-vcs/git-2.21.0::portage-stable
> dev-vcs/git-2.24.1::portage-stable
< net-misc/openssh-7.9_p1-r4::coreos
> net-misc/openssh-8.1_p1-r3::coreos
< sys-apps/systemd-241-r7::coreos
> sys-apps/systemd-243::coreos
< sys-firmware/intel-microcode-20191115_p20190918-r1::coreos
> sys-firmware/intel-microcode-20191115_p20191110-r1::coreos
< sys-fs/mdadm-3.4::portage-stable
> sys-fs/mdadm-4.1-r1::coreos
< sys-kernel/coreos-firmware-20181001::coreos
> sys-kernel/coreos-firmware-20200122::coreos
< sys-kernel/coreos-kernel-4.19.107::coreos
> sys-kernel/coreos-kernel-5.6.0::coreos
< sys-kernel/coreos-modules-4.19.107::coreos
> sys-kernel/coreos-modules-5.6.0::coreos
```

Nothing here jumps clearly as the possible culprit. Interestingly, when looking at the `contents` file that we also publish, the empty `/etc/pam.d` is not listed.

**Manual image generation**

I've also run the manual image generation myself, following the instructions [here](https://docs.flatcar-linux.org/os/sdk-modifying-flatcar/), passing the edge version to the script. I could see that while installing the packages into the chroot, the `/etc/pam.d` directory was created by one of the PAM packages (either `pambase` or `pam`, I didn't catch which one). And then got populated with many different files as packages installed.

So, the files are there while the image is being created but then removed. After some digging, I've found this:

https://github.com/flatcar-linux/scripts/blob/flatcar-master/build_library/oem_aci_util.sh#L58
```
    # Move the PAM configuration into /usr
    sudo mkdir -p ${root_fs_dir}/usr/lib/pam.d
    sudo mv -n ${root_fs_dir}/etc/pam.d/* ${root_fs_dir}/usr/lib/pam.d/
    sudo rmdir ${root_fs_dir}/etc/pam.d
```

So, we're explicitly moving the files that get installed there to /usr and then deleting the directory. I'm not sure why the last line is there.  But it's been there for a long time, it's not a recent change. 

So, the directory isn't shipped with the image, but when booting up the stable image, it's there. Something was creating it (on first boot) and now isn't. It could be any of the packages that changed versions in between. I suspect it's systemd but I can't prove it (yet).

Maybe this commit? https://github.com/systemd/systemd/commit/9ba77b994926a2c1f671c9fbf112202a4e9d8e68
It seems related and the timing matches (present in 243-r1 onwards), but I'm not sure I understand what the code is doing to say that it's definitely it.

**Conclusion**

I think that the right thing to do is to not remove the directory, as it needs to actually exist for the system to work correctly. But I might be missing something, since I don't know how that code even came to be.

**Comment by pothos** [comment]
The code in `create_oem_aci_image` is not used for the production image, or?

It would be good to see if something in the openssh update caused this since the error message is about `/etc/pam.d/sshd`.

But your hint about systemd-tempfile is also very good because in some test logs I've seen this:

```
systemd-tmpfiles[719]: Failed to copy files to /etc/pam.d: No such file or directory
systemd-tmpfiles[719]: Failed to copy files to /etc/issue: No such file or directory
````

In Edge we have removed/disabled some systemd-tempfile units which is something to be aware of when comparing Stable and Edge – maybe an argument or a unit is missing to create the files.

**Comment by margamanterola** [comment]
I *think* the ssh error is a consequence of this rather than the cause. I'm not sure I understand the last part. Which units are removed from edge? In any case, I have a commit adding this to baselayout. I'll send it your way now.

**Comment by pothos** [comment]
The tempfile unit being different is only about the initramfs, I think.

But I actually found this: https://github.com/flatcar-linux/coreos-overlay/blob/flatcar-master-edge/sys-apps/systemd/systemd-9999.ebuild#L397

**Comment by pothos** [comment]
and that: https://github.com/flatcar-linux/coreos-overlay/blob/flatcar-master-edge/sys-apps/systemd/systemd-9999.ebuild#L279

**Comment by pothos** [comment]
Seems that the `sed` line won't work after https://github.com/systemd/systemd/commit/9ba77b994926a2c1f671c9fbf112202a4e9d8e68 because it's `C!` and not `C`? Just a guess. Adding it to baselayout makes sense if we aren't supposed to have a symlink to `/usr/share/pam.d`.

**Comment by margamanterola** [comment]
Yes, the file changed and the sed line doesn't match anymore:

```
core@localhost ~ $ cat /usr/lib/tmpfiles.d/etc.conf 
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

# See tmpfiles.d(5) for details

L /etc/os-release - - - - ../usr/lib/os-release
L+ /etc/mtab - - - - ../proc/self/mounts
L! /etc/resolv.conf - - - - ../run/systemd/resolve/resolv.conf
C! /etc/nsswitch.conf - - - -
C! /etc/pam.d - - - -
C! /etc/issue - - - -
```

At least in stable there's no symlink, it's an actual directory. Pam is configured to use the /usr directory instead, but some programs will still access the /etc/ directory instead (like ssh, apparently).

**Comment by margamanterola** [comment]
In contrast, in the stable installation the two lines are indeed removed:

```
Flatcar Container Linux by Kinvolk stable (2345.3.1)
core@localhost ~ $ cat /usr/lib/tmpfiles.d/etc.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

# See tmpfiles.d(5) for details

L /etc/os-release - - - - ../usr/lib/os-release
L /etc/localtime - - - - ../usr/share/zoneinfo/UTC
L+ /etc/mtab - - - - ../proc/self/mounts
L! /etc/resolv.conf - - - - ../run/systemd/resolve/resolv.conf
```

**Comment by margamanterola** [comment]
The meaning of the letter C:

```
       C
           Recursively copy a file or directory, if the destination files or directories do not exist
           yet or the destination directory is empty. Note that this command will not descend into
           subdirectories if the destination directory already exists and is not empty. Instead, the
           entire copy operation is skipped. If the argument is omitted, files from the source
           directory /usr/share/factory/ with the same name are copied. Does not follow symlinks.

```

**Comment by pothos** [comment]
But `/usr/lib/tmpfiles.d/pam.conf` has `d /etc/pam.d                    0755 root root  -       -` in Stable.

**Comment by margamanterola** [comment]
Yeah, that's also present in edge:
```
Flatcar Container Linux by Kinvolk edge (2466.99.0)
core@localhost ~ $ cat /usr/lib/tmpfiles.d/pam.conf
d /etc/pam.d			0755 root root	-	-
d /etc/security			0755 root root	-	-
d /etc/security/limits.d	0755 root root	-	-
d /etc/security/namespace.d	0755 root root	-	-
f /etc/environment		0755 root root	-	-	
L /etc/security/access.conf	-    -	  -	-	../../usr/lib/pam/access.conf
L /etc/security/group.conf	-    - 	  - 	-	../../usr/lib/pam/group.conf
L /etc/security/limits.conf	-    -	  -	-	../../usr/lib/pam/limits.conf
L /etc/security/namespace.conf	-    -	  -	-	../../usr/lib/pam/namespace.conf
L /etc/security/pam_env.conf	-    -	  -	-	../../usr/lib/pam/pam_env.conf
L /etc/security/time.conf	-    -	  -	-	../../usr/lib/pam/time.conf
```

**Comment by margamanterola** [comment]
On edge:
```
core@localhost ~ $ sudo systemd-tmpfiles --boot --create
[/usr/lib64/tmpfiles.d/etc.conf:13] Duplicate line for path "/etc/nsswitch.conf", ignoring.
[/usr/lib64/tmpfiles.d/issuegen.conf:1] Duplicate line for path "/etc/issue", ignoring.
[/usr/lib64/tmpfiles.d/pam.conf:1] Duplicate line for path "/etc/pam.d", ignoring.
Detected autofs mount point /boot during canonicalization of /boot.
Skipping /boot
Failed to copy files to /etc/pam.d: No such file or directory
Failed to copy files to /etc/issue: No such file or directory
```

**Comment by margamanterola** [comment]
So, I guess my change is not correct and what we need to do is fix that sed line.
