### ISSUE TITLE
.ssh/authorized_keys and .ssh/authorized_keys.d/flatcar-ignition

### ISSUE THREAD

**Issue by ahjohannessen** [flatcar/Flatcar#752]
## Description
On my Flatcar machines I noticed that `core` has both `.ssh/authorized_keys` and `.ssh/authorized_keys/flatcar-ignition` with the same content. If I remove `.ssh/authorized_keys` then sshd does not use `.ssh/authorized_keys/flatcar-ignition`.

On Fedora CoreOS the following is done wrt. authorized_keys.d:
```
cat /etc/ssh/sshd_config.d/40-ssh-key-dir.conf
# sshd_config drop-in for /etc/ssh/sshd_config.d

# Use ssh-key-dir to read all SSH keys from ~/.ssh/authorized_keys.d
AuthorizedKeysCommand /usr/libexec/ssh-key-dir %u

# ssh-key-dir needs to be able to seteuid to the target user
AuthorizedKeysCommandUser root
```

and this is in `/etc/ssh/sshd_config`:
```
# To modify the system-wide sshd configuration, create a  *.conf  file under
#  /etc/ssh/sshd_config.d/  which will be automatically included below
Include /etc/ssh/sshd_config.d/*.conf
```

## Environment
Flatcar Container Linux by Kinvolk stable 3139.2.1 for VMware

## Notes:

[This](https://github.com/flatcar-linux/init/pull/66) by @pothos might have relevance.

**Comment by pothos** [comment]
Sounds like it works as expected. Flatcar uses the update-ssh-keys tool to assemble the fragments under `.ssh/authorized_keys.d/` to a merged `.ssh/authorized_keys` file. The `AuthorizedKeysCommand` logic to read the drop-in files directly is not used (only by the GCE OEM tools).

**Comment by ahjohannessen** [comment]
Ok, I see. If I need to change the content of `.ssh/authorized_keys` do I need to update `.ssh/authorized_keys.d/flatcar-ignition` and then run `update-ssh-keys` manually afterwards?

[update-ssh-keys](https://github.com/coreos/update-ssh-keys) seems to be deprecated.

**Comment by pothos** [comment]
Yes, correct. Edit: or create a new file in the folder if you just want to add something

The fork lives on under https://github.com/flatcar-linux/update-ssh-keys - if a solution is found for multiple `AuthorizedKeysCommand`s we may want to revisit this and migrate to ssh-key-dir.

**Comment by ahjohannessen** [comment]
Ok, I'll figure it out. Thanks :)
