### ISSUE TITLE
CT - custom update group name

### ISSUE THREAD

**Issue by MattCrum1** [flatcar/Flatcar#756]
## Description

I'm setting up Nebraska to control updates on Flatcar instances and want to make use of Update Groups to control when updates are available to specific customers.

I have done a script to convert some host details into an Ignition YML file, which I feed into CT using Docker. It looks like CT does not support custom update group names? 

- Setting the group name to "testgroup" or the ID of one of the Nebraska groups results in an error: "unknown update group".
- Setting the group name to "stable" works fine.

## Impact

Cannot set custom Update Groups for new machines via Ignition Script. Also read something on here about custom group names being overwritten with "stable" after upgrade; want to make sure that the custom group name is in the container-linux configuration properly.

## Environment and steps to reproduce

Create YML file including a non-standard update group name:

update:
  group: testgroup

Feed file into ct and see error.

Change the YML file to have a standard group name:

update:
  group: stable

Feed file into ct and the error does not occur.

**Comment by MattCrum1** [comment]
Worth noting that manually updating the JSON afterwards with the custom group name works fine; the new Flatcar machine has the name in /etc/flatcar/update.conf

**Comment by pothos** [comment]
That should work and maybe we need to fix something in ct.
As workaround, you can directly use the file directive in CLC:
https://www.flatcar.org/docs/latest/setup/releases/update-strategies/#disable-automatic-updates
In the example you would replace `SERVER=disabled` with `GROUP=mygroup`.

Edit: Ah, the lines
```
update:
  group: testgroup
```
are the config you used but the whitespace didn't get displayed.

**Comment by pothos** [comment]
Yes, thanks for reporting, the update: group: directive doesn't allow custom group names 🙀:
https://github.com/flatcar-linux/container-linux-config-transpiler/blob/flatcar-master/config/types/update.go#L51

The spec says `group (string): the update group to follow. Most users will want one of: stable, beta, alpha.` which means that it's not exclusive.

**Comment by pothos** [comment]
Path forward is writing the file directly in the Butane config.
