### ISSUE TITLE
Packer can't SSH into stable-3139.2.0

### ISSUE THREAD

**Issue by alpana17** [flatcar/Flatcar#757]
Earlier I was using Flatcar 3033.2.4.
Now, my packer template is not able to login to launched instance. Error is:
Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

If I move to Flatcar 3033.2.4, it will start working properly.

**Comment by tormath1** [comment]
Hi @alpana17,

`stable-3139.2.0` comes with `openssh-8.8` so I think you're hitting this issue: https://github.com/hashicorp/packer/issues/11733 (https://groups.google.com/g/golang-announce/c/-cp44ypCT5s/m/wmegxkLiAQAJ for more details).

Upgrading Packer to [`1.8.1`](https://github.com/hashicorp/packer/releases/tag/v1.8.1) should fix the issue as it embeds the lib update.

Let us know how it goes !

EDIT: renamed the issue title to reflect the change and get a better referencing for other users

**Comment by tormath1** [comment]
Hi @alpana17, we're closing this issue for now - feel free to re-open it if the proposed suggestion does not work. Thanks!
