### ISSUE TITLE
Hard drives out of order after reboot

### ISSUE THREAD

**Issue by bignay2000** [flatcar/Flatcar#765]
## Description

I have a newer flatcar vm in VMWare ESXi that has 4 hard drives.  These drives have different size amounts.  df command correctly associates the Filesystem and Mounted on, but the Size of disk changes when I reboot.  Navigating to the the Mounted on path shows the wrong files and folders.  If I keep rebooting, eventually the drives are correct and return to the initial installed order.
Config is based off the https://flatcar-linux.org/docs/latest/setup/storage/mounting-storage/#use-attached-storage-for-docker documentation.  

Output of df -h at initial install
```
Filesystem       Size  Used Avail Use% Mounted on
devtmpfs         4.0M     0  4.0M   0% /dev
tmpfs             32G     0   32G   0% /dev/shm
tmpfs             13G  9.9M   13G   1% /run
/dev/sda9         14G  308M   13G   3% /
/dev/mapper/usr  983M  680M  253M  73% /usr
none             450M  259M  192M  58% /run/torcx/unpack
tmpfs             32G     0   32G   0% /media
tmpfs             32G     0   32G   0% /tmp
/dev/sdf         251G  7.2G  231G   4% /srv/dockerbackups
/dev/sde          20G  8.0K   19G   1% /srv/dockerlogs
/dev/sdc         974M  2.2M  905M   1% /srv/dockercompose
/dev/sdb          63G   16G   44G  27% /var/lib/docker
/dev/sdd          94G  3.8G   86G   5% /srv/dockervolumes
/dev/sda6        128M  6.6M  118M   6% /usr/share/oem
tmpfs            6.3G     0  6.3G   0% /run/user/500
tmpfs            6.3G     0  6.3G   0% /run/user/1001
```

Output of df -h after reboot (Size is wrong)
```
Filesystem       Size  Used Avail Use% Mounted on
devtmpfs         4.0M     0  4.0M   0% /dev
tmpfs             32G     0   32G   0% /dev/shm
tmpfs             13G  9.0M   13G   1% /run
/dev/sda9         14G  300M   13G   3% /
/dev/mapper/usr  983M  680M  253M  73% /usr
none             450M  259M  192M  58% /run/torcx/unpack
tmpfs             32G     0   32G   0% /media
tmpfs             32G     0   32G   0% /tmp
/dev/sdf          20G  8.0K   19G   1% /srv/dockerbackups
/dev/sdc          63G   16G   44G  27% /srv/dockercompose
/dev/sdd          94G  3.8G   86G   5% /srv/dockervolumes
/dev/sdb         974M  2.2M  905M   1% /var/lib/docker
/dev/sde         251G  7.2G  231G   4% /srv/dockerlogs
/dev/sda6        128M  6.6M  118M   6% /usr/share/oem
tmpfs            6.3G     0  6.3G   0% /run/user/500
tmpfs            6.3G     0  6.3G   0% /run/user/1001
```
## Impact
Severe.  Reboot or System Upgrades cause the drives to be mapped wrong and docker containers do not start after reboot OR they do start but are reading and writing to the wrong drives risking data loss. 

## Environment and steps to reproduce

1. Create a VM in VMWare ESXI via flatcar_production_vmware_ova.ova
2. Use a cloud-config with the following 
```
systemd:
  units:
    - name: var-lib-docker.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount docker disk to /var/lib/docker
        Before=local-fs.target
        [Mount]
        What=/dev/sdb
        Where=/var/lib/docker
        Type=ext4
        [Install]
        WantedBy=local-fs.target
    - name: srv-dockercompose.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount disk to /srv/dockercompose
        Before=local-fs.target
        [Mount]
        What=/dev/sdc
        Where=/srv/dockercompose
        Type=ext4
        [Install]
        WantedBy=local-fs.target
    - name: srv-dockervolumes.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount disk to /srv/dockervolumes
        Before=local-fs.target
        [Mount]
        What=/dev/sdd
        Where=/srv/dockervolumes
        Type=ext4
        [Install]
        WantedBy=local-fs.target
    - name: srv-dockerlogs.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount disk to /srv/dockerlogs
        Before=local-fs.target
        [Mount]
        What=/dev/sde
        Where=/srv/dockerlogs
        Type=ext4
        [Install]
        WantedBy=local-fs.target
    - name: srv-dockerbackups.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount disk to /srv/dockerbackups
        Before=local-fs.target
        [Mount]
        What=/dev/sdf
        Where=/srv/dockerbackups
        Type=ext4
        [Install]
        WantedBy=local-fs.target
    - name: docker.service
      dropins:
        - name: 10-wait-docker.conf
          contents: |
            [Unit]
            After=var-lib-docker.mount
            Requires=var-lib-docker.mount
            After=srv-dockervolumes.mount
            Requires=srv-dockervolumes.mount
            After=srv-dockerlogs.mount
            Requires=srv-dockerlogs.mount
storage:
  filesystems:
    - name: docker
      mount:
        device: /dev/sdb
        format: ext4
        wipe_filesystem: false
    - name: dockercompose
      mount:
        device: /dev/sdc
        format: ext4
        wipe_filesystem: falsee
    - name: dockervolumes
      mount:
        device: /dev/sdd
        format: ext4
        wipe_filesystem: false
    - name: dockerlogs
      mount:
        device: /dev/sde
        format: ext4
        wipe_filesystem: false
    - name: dockerbackups
      mount:
        device: /dev/sdf
        format: ext4
        wipe_filesystem: false
```
3. Upgrade to the latest stable build 
```
DISTRIB_ID="Flatcar Container Linux by Kinvolk"
DISTRIB_RELEASE=3139.2.2
DISTRIB_CODENAME="Oklo"
DISTRIB_DESCRIPTION="Flatcar Container Linux by Kinvolk 3139.2.2 (Oklo)"
```
## Expected behavior

/dev/sdb should always mount the same drive after reboot.
/dev/sdc should always mount the same drive after reboot.
/dev/sdd should always mount the same drive after reboot.
/dev/sde should always mount the same drive after reboot.
/dev/sdf should always mount the same drive after reboot.

## Additional information

This config used to work with older CoreOS vms (managed over 100 vms for several months) that worked as of 7/28/2019 stable versions.

ESXi 7.0 U2 virtual machine

**Comment by till** [comment]
I share your frustration. I think this actually works 9/10 times but that one time is really "something" when the order of the drives is wrong.

To overcome this you can add a label to each drive via ignition and then mount it by label via `/dev/disk/by-label`, vs `/dev/sdX`. This is the (reliable) way and also suggested somewhere in the flatcar docs.

**Comment by pothos** [comment]
This is not a bug but standard Linux behavior. The kernel detects the disks in not guaranteed order and will start with sda, then sdb etc. You should set up a partition/filesystem label when partitioning/formatting the disk and use this for the mount unit instead of `What=/dev/sdX`.

The example in https://flatcar-linux.org/docs/latest/setup/storage/mounting-storage/ is a bit special because it uses the EC2 ephemeral disk. But we should update it to also set up a label and use it in `What=/dev/disk/by-…`.

**Comment by bignay2000** [comment]
@till  @pothos  Thanks for the feedback.  I will test out this with a new fresh install and confirm by-label.  

While I realize Flatcar is intended to be ephemeral, any idea how to change this post deployment?

**Comment by bignay2000** [comment]
@till @pothos 
Updated my config to use by-label, but now the disks are out of order on the first time boot.  VMWare Disks do not match the order in the Container linux config yaml.   
While this may fix the drives changing on reboot, how do I associate a VWMARE disk # with a Systemd unit order? 

Specifically /srv/dockerlogs changed to Disk 4 96 GB and was Disk 5 20 GB in my original box.

VMWare Disks
```
Disk 1 16 GB  /sys/block/sda/device/scsi_device/0:0:0:0
Disk 2 64 GB /sys/block/sda/device/scsi_device/0:0:1:0
Disk 3 1 GB /sys/block/sda/device/scsi_device/0:0:2:0
Disk 4 96 GB /sys/block/sda/device/scsi_device/0:0:3:0
Disk 5 20 GB /sys/block/sda/device/scsi_device/0:0:4:0
Disk 6 256 GB /sys/block/sda/device/scsi_device/0:0:5:0
```
df -h

```
Filesystem       Size  Used Avail Use% Mounted on
devtmpfs         4.0M     0  4.0M   0% /dev
tmpfs             16G     0   16G   0% /dev/shm
tmpfs            6.3G  9.0M  6.3G   1% /run
/dev/sda9         14G   31M   13G   1% /
/dev/mapper/usr  983M  680M  253M  73% /usr
none             450M  259M  192M  58% /run/torcx/unpack
tmpfs             16G     0   16G   0% /media
tmpfs             16G     0   16G   0% /tmp
/dev/sdb         974M   24K  907M   1% /srv/dockercompose
/dev/sdf         251G   28K  239G   1% /srv/dockerbackups
/dev/sdd          94G   24K   90G   1% /srv/dockerlogs
/dev/sde          20G   24K   19G   1% /srv/dockervolumes
/dev/sdc          63G   24K   60G   1% /var/lib/docker
/dev/sda6        128M  6.6M  118M   6% /usr/share/oem
tmpfs            3.2G     0  3.2G   0% /run/user/500
tmpfs            3.2G     0  3.2G   0% /run/user/1001
```

```
  units:
    - name: var-lib-docker.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount docker disk to /var/lib/docker
        Before=local-fs.target
        [Mount]
        What=/dev/disk/by-label/docker
        Where=/var/lib/docker
        Type=ext4
        [Install]
        WantedBy=local-fs.target
    - name: srv-dockercompose.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount disk to /srv/dockercompose
        Before=local-fs.target
        [Mount]
        What=/dev/disk/by-label/dockercompose
        Where=/srv/dockercompose
        Type=ext4
        [Install]
        WantedBy=local-fs.target
    - name: srv-dockervolumes.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount disk to /srv/dockervolumes
        Before=local-fs.target
        [Mount]
        What=/dev/disk/by-label/dockervolumes
        Where=/srv/dockervolumes
        Type=ext4
        [Install]
        WantedBy=local-fs.target
    - name: srv-dockerlogs.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount disk to /srv/dockerlogs
        Before=local-fs.target
        [Mount]
        What=/dev/disk/by-label/dockerlogs
        Where=/srv/dockerlogs
        Type=ext4
        [Install]
        WantedBy=local-fs.target
    - name: srv-dockerbackups.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount disk to /srv/dockerbackups
        Before=local-fs.target
        [Mount]
        What=/dev/disk/by-label/dockerbackups
        Where=/srv/dockerbackups
        Type=ext4
        [Install]
        WantedBy=local-fs.target

storage:
  filesystems:
    - name: docker
      mount:
        device: /dev/sdb
        format: ext4
        wipe_filesystem: false
        label: docker
    - name: dockercompose
      mount:
        device: /dev/sdc
        format: ext4
        wipe_filesystem: false
        label: dockercompose
    - name: dockervolumes
      mount:
        device: /dev/sdd
        format: ext4
        wipe_filesystem: false
        label: dockervolumes
    - name: dockerlogs
      mount:
        device: /dev/sde
        format: ext4
        wipe_filesystem: false
        label: dockerlogs
    - name: dockerbackups
      mount:
        device: /dev/sdf
        format: ext4
        wipe_filesystem: false
        label: dockerbackups
```

**Comment by bignay2000** [comment]
VMWare uses a single SCSI controller and adds drives to it when you add additional drives to a VM.  So there needs to be a way to mount drives that honors the SCSI order.


Example when the drives are correct
```
ls -dl /sys/block/sd*/device/scsi_device/*
drwxr-xr-x. 3 root root 0 Jun  8 02:46 /sys/block/sda/device/scsi_device/0:0:0:0
drwxr-xr-x. 3 root root 0 Jun  8 02:46 /sys/block/sdb/device/scsi_device/0:0:1:0
drwxr-xr-x. 3 root root 0 Jun  8 02:46 /sys/block/sdc/device/scsi_device/0:0:2:0
drwxr-xr-x. 3 root root 0 Jun  8 02:46 /sys/block/sdd/device/scsi_device/0:0:3:0
drwxr-xr-x. 3 root root 0 Jun  8 02:46 /sys/block/sde/device/scsi_device/0:0:4:0
drwxr-xr-x. 3 root root 0 Jun  8 02:46 /sys/block/sdf/device/scsi_device/0:0:5:0
```

Example when the drives are out of order.
```
ls -dl /sys/block/sd*/device/scsi_device/*
drwxr-xr-x. 3 root root 0 Jun  8 03:23 /sys/block/sda/device/scsi_device/0:0:1:0
drwxr-xr-x. 3 root root 0 Jun  8 03:23 /sys/block/sdb/device/scsi_device/0:0:0:0
drwxr-xr-x. 3 root root 0 Jun  8 03:23 /sys/block/sdc/device/scsi_device/0:0:2:0
drwxr-xr-x. 3 root root 0 Jun  8 03:23 /sys/block/sdd/device/scsi_device/0:0:3:0
drwxr-xr-x. 3 root root 0 Jun  8 03:23 /sys/block/sde/device/scsi_device/0:0:4:0
drwxr-xr-x. 3 root root 0 Jun  8 03:23 /sys/block/sdf/device/scsi_device/0:0:5:0
````

**Comment by pothos** [comment]
You can use `/dev/disk/by-path/` entries if you are sure about their naming. There is no correct or wrong order of sda, sdb, sdc, as far as I know because the kernel assigns the next name to the fastest drive appearing which could also be a USB stick that gets detected in the middle of the two SCSI devices being detected, and it will get sdb as name then.

**Comment by jepio** [comment]
@Winnie81 do you know of any solutions to this issue?

**Comment by bignay2000** [comment]
> /dev/disk/by-path/

Going to test this tonight to see if this honors the SCSI order...

/dev/disk/by-path $ ls -alth
total 0
lrwxrwxrwx. 1 root root  10 Jun 13 02:36 pci-0000:03:00.0-scsi-0:0:0:0-part6 -> ../../sda6
lrwxrwxrwx. 1 root root  10 Jun 13 02:36 pci-0000:03:00.0-scsi-0:0:0:0-part1 -> ../../sda1
lrwxrwxrwx. 1 root root  10 Jun 13 02:36 pci-0000:03:00.0-scsi-0:0:0:0-part2 -> ../../sda2
lrwxrwxrwx. 1 root root  10 Jun 13 02:36 pci-0000:03:00.0-scsi-0:0:0:0-part4 -> ../../sda4
lrwxrwxrwx. 1 root root  10 Jun 13 02:36 pci-0000:03:00.0-scsi-0:0:0:0-part3 -> ../../sda3
lrwxrwxrwx. 1 root root  10 Jun 13 02:36 pci-0000:03:00.0-scsi-0:0:0:0-part7 -> ../../sda7
lrwxrwxrwx. 1 root root  10 Jun 13 02:36 pci-0000:03:00.0-scsi-0:0:0:0-part9 -> ../../sda9
lrwxrwxrwx. 1 root root   9 Jun 13 02:36 pci-0000:03:00.0-scsi-0:0:0:0 -> ../../sda
lrwxrwxrwx. 1 root root   9 Jun 13 02:35 pci-0000:00:07.1-ata-2 -> ../../sr0
lrwxrwxrwx. 1 root root   9 Jun 13 02:35 pci-0000:00:07.1-ata-2.0 -> ../../sr0
lrwxrwxrwx. 1 root root   9 Jun 13 02:35 pci-0000:0b:00.0-scsi-0:0:0:0 -> ../../sdf
lrwxrwxrwx. 1 root root   9 Jun 13 02:35 pci-0000:03:00.0-scsi-0:0:1:0 -> ../../sdb
lrwxrwxrwx. 1 root root   9 Jun 13 02:35 pci-0000:03:00.0-scsi-0:0:2:0 -> ../../sdc
lrwxrwxrwx. 1 root root   9 Jun 13 02:35 pci-0000:03:00.0-scsi-0:0:4:0 -> ../../sde
lrwxrwxrwx. 1 root root   9 Jun 13 02:35 pci-0000:03:00.0-scsi-0:0:3:0 -> ../../sdd
drwxr-xr-x. 2 root root 340 Jun 13 02:35 .
drwxr-xr-x. 9 root root 180 Jun 13 02:35 ..

**Comment by bignay2000** [comment]
Early testing of using /dev/disk/by-path/ is working!  Going to try a few more restarts, but so far is consistently mapping the drives correctly on first install and subsequent reboots. 

Not sure if VMWare ESXi/Workstation/Fusion would always uses "pci-0000:03:00.0-scsi-0:0:**#**:0" as their SCSI card.  

ls -d /sys/block/sd*/device/scsi_device/*

```
/sys/block/sda/device/scsi_device/0:0:0:0  /sys/block/sdd/device/scsi_device/0:0:3:0
/sys/block/sdb/device/scsi_device/0:0:1:0  /sys/block/sde/device/scsi_device/0:0:4:0
/sys/block/sdc/device/scsi_device/0:0:2:0  /sys/block/sdf/device/scsi_device/0:0:5:0
```
ls /dev/disk/by-path
```
pci-0000:00:07.1-ata-2               pci-0000:03:00.0-scsi-0:0:0:0-part7
pci-0000:00:07.1-ata-2.0             pci-0000:03:00.0-scsi-0:0:0:0-part9
pci-0000:03:00.0-scsi-0:0:0:0        pci-0000:03:00.0-scsi-0:0:1:0
pci-0000:03:00.0-scsi-0:0:0:0-part1  pci-0000:03:00.0-scsi-0:0:2:0
pci-0000:03:00.0-scsi-0:0:0:0-part2  pci-0000:03:00.0-scsi-0:0:3:0
pci-0000:03:00.0-scsi-0:0:0:0-part3  pci-0000:03:00.0-scsi-0:0:4:0
pci-0000:03:00.0-scsi-0:0:0:0-part4  pci-0000:03:00.0-scsi-0:0:5:0
pci-0000:03:00.0-scsi-0:0:0:0-part6

```

```
systemd:
  units:
    - name: var-lib-docker.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount docker disk to /var/lib/docker
        Before=local-fs.target
        [Mount]
        What=/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:1:0
        Where=/var/lib/docker
        Type=ext4
        [Install]
        WantedBy=local-fs.target
    - name: srv-dockercompose.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount disk to /srv/dockercompose
        Before=local-fs.target
        [Mount]
        What=/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0
        Where=/srv/dockercompose
        Type=ext4
        [Install]
        WantedBy=local-fs.target
    - name: srv-dockervolumes.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount disk to /srv/dockervolumes
        Before=local-fs.target
        [Mount]
        What=/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:3:0
        Where=/srv/dockervolumes
        Type=ext4
        [Install]
        WantedBy=local-fs.target
    - name: srv-dockerlogs.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount disk to /srv/dockerlogs
        Before=local-fs.target
        [Mount]
        What=/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:4:0
        Where=/srv/dockerlogs
        Type=ext4
        [Install]
        WantedBy=local-fs.target
    - name: srv-dockerbackups.mount
      enable: true
      contents: |
        [Unit]
        Description=Mount disk to /srv/dockerbackups
        Before=local-fs.target
        [Mount]
        What=/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:5:0
        Where=/srv/dockerbackups
        Type=ext4
        [Install]
        WantedBy=local-fs.target
    - name: docker.service
      dropins:
        - name: 10-wait-docker.conf
          contents: |
            [Unit]
            After=var-lib-docker.mount
            Requires=var-lib-docker.mount
            After=srv-dockervolumes.mount
            Requires=srv-dockervolumes.mount
            After=srv-dockerlogs.mount
            Requires=srv-dockerlogs.mount
```

**Comment by pothos** [comment]
Even with a more stable path like `/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:3:0` I would recommend to use `/dev/disk/by-label/dockercompose` when you already set a unique label in
```
    - name: dockercompose
      mount:
        device: /dev/sdc
        format: ext4
        wipe_filesystem: false
        label: dockercompose
```
This makes the config independent from changes in the way the disks are attached and instead you match by content which is stronger and probably what you intend to do in the end.
I'll file a [docs PR](https://github.com/flatcar-linux/flatcar-docs/pull/252) now where we call this out more explicitly.

**Comment by bignay2000** [comment]
> Early testing of using /dev/disk/by-path/ is working! Going to try a few more restarts, but so far is consistently mapping the drives correctly on first install and subsequent reboots.
> 
> Not sure if VMWare ESXi/Workstation/Fusion would always uses "pci-0000:03:00.0-scsi-0:0:**#**:0" as their SCSI card.
> 
> ls -d /sys/block/sd*/device/scsi_device/*
> 
> ```
> /sys/block/sda/device/scsi_device/0:0:0:0  /sys/block/sdd/device/scsi_device/0:0:3:0
> /sys/block/sdb/device/scsi_device/0:0:1:0  /sys/block/sde/device/scsi_device/0:0:4:0
> /sys/block/sdc/device/scsi_device/0:0:2:0  /sys/block/sdf/device/scsi_device/0:0:5:0
> ```
> 
> ls /dev/disk/by-path
> 
> ```
> pci-0000:00:07.1-ata-2               pci-0000:03:00.0-scsi-0:0:0:0-part7
> pci-0000:00:07.1-ata-2.0             pci-0000:03:00.0-scsi-0:0:0:0-part9
> pci-0000:03:00.0-scsi-0:0:0:0        pci-0000:03:00.0-scsi-0:0:1:0
> pci-0000:03:00.0-scsi-0:0:0:0-part1  pci-0000:03:00.0-scsi-0:0:2:0
> pci-0000:03:00.0-scsi-0:0:0:0-part2  pci-0000:03:00.0-scsi-0:0:3:0
> pci-0000:03:00.0-scsi-0:0:0:0-part3  pci-0000:03:00.0-scsi-0:0:4:0
> pci-0000:03:00.0-scsi-0:0:0:0-part4  pci-0000:03:00.0-scsi-0:0:5:0
> pci-0000:03:00.0-scsi-0:0:0:0-part6
> ```
> 
> ```
> systemd:
>   units:
>     - name: var-lib-docker.mount
>       enable: true
>       contents: |
>         [Unit]
>         Description=Mount docker disk to /var/lib/docker
>         Before=local-fs.target
>         [Mount]
>         What=/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:1:0
>         Where=/var/lib/docker
>         Type=ext4
>         [Install]
>         WantedBy=local-fs.target
>     - name: srv-dockercompose.mount
>       enable: true
>       contents: |
>         [Unit]
>         Description=Mount disk to /srv/dockercompose
>         Before=local-fs.target
>         [Mount]
>         What=/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0
>         Where=/srv/dockercompose
>         Type=ext4
>         [Install]
>         WantedBy=local-fs.target
>     - name: srv-dockervolumes.mount
>       enable: true
>       contents: |
>         [Unit]
>         Description=Mount disk to /srv/dockervolumes
>         Before=local-fs.target
>         [Mount]
>         What=/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:3:0
>         Where=/srv/dockervolumes
>         Type=ext4
>         [Install]
>         WantedBy=local-fs.target
>     - name: srv-dockerlogs.mount
>       enable: true
>       contents: |
>         [Unit]
>         Description=Mount disk to /srv/dockerlogs
>         Before=local-fs.target
>         [Mount]
>         What=/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:4:0
>         Where=/srv/dockerlogs
>         Type=ext4
>         [Install]
>         WantedBy=local-fs.target
>     - name: srv-dockerbackups.mount
>       enable: true
>       contents: |
>         [Unit]
>         Description=Mount disk to /srv/dockerbackups
>         Before=local-fs.target
>         [Mount]
>         What=/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:5:0
>         Where=/srv/dockerbackups
>         Type=ext4
>         [Install]
>         WantedBy=local-fs.target
>     - name: docker.service
>       dropins:
>         - name: 10-wait-docker.conf
>           contents: |
>             [Unit]
>             After=var-lib-docker.mount
>             Requires=var-lib-docker.mount
>             After=srv-dockervolumes.mount
>             Requires=srv-dockervolumes.mount
>             After=srv-dockerlogs.mount
>             Requires=srv-dockerlogs.mount
> ```

This no longer working on the latest production iso (3510.2.6)

**Comment by bignay2000** [comment]
Update butane config to /dev/disk/by-label/  
Successfully built 3510.2.6 the vm with all the disks in ESXi using the VMWare ovf. 
Successfully built 3510.2.6 the vm with all the disks on Proxmox machine hypervisor using the production iso.
So now my butane config is not custom to the hardware as an added bonus.

**Comment by maxiride** [comment]
Chiming in the conversation since I didn't found any other more adeguate.

How can you determine the prefix part `pci-0000:03:00.0`? 

--- 

When using the `/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:5:0` syntax the number of the controller `scsi-0:0:X:0` can easily be determined from VMware GUI since you can specifically choose the scsi controller location (in the New disk menu).

However for the prefix part `pci-0000:03:00.0` I am not understanding how to determine it **before** boot, which is the main objective to define the butane config.

I inspected other linux based VMs on the hypervisor and they all had `pci-0000:00:10.0` so I was confident to use `- device: /dev/disk/by-path/pci-0000:00:10.0-scsi-0:0:1:0` only to find out that after booting (with errors) the additional disk was instead under `pci-0000:03:00.0`.

Can we safely assume that specifically on VMware **all** disks are under the PCI address `pci-0000:03:00.0`? If not, is the only way to discover it to first launch a dummy Flatcar VM and inspect it?

**Comment by till** [comment]
I can't comment on your environment as I am not familiar, but on OpenStack it's similar that disks can be out of order.

I basically borrowed code from the k8s integration.

So in our case the disks are qemu disks and their IDs are the **first 10 or so** characters of the OpenStack volume ID.

I generate ignition for each instance we start and use this ID in ignition to label my disks and tell flatcar to also add a label and mount unit.

The label itself is not used yet, but I put it there because I want a human readable reference when I deal with the disks - especially because `/dev/sdX` is not predictable.

For your environment you'd have to boot a new VM with some disks and find out what's available in `/dev/disk/by-*` to find something predictable.

I hope that helps?

**Comment by till** [comment]
Maybe to add, the initial boot for me was always the order in which I attached the disks, but the problem came from reboots.
