### ISSUE TITLE
Move OEM mount point out of /usr

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#766]
## Current situation

The OEM partition is mounted under `/usr/share/oem/` which requires a workaround for systemd-sysext because the management of the overlay mounts on `/usr` results in the OEM mount point to be lost without the workaround.

## Impact

We had to add a special handling for the OEM mount point in the systemd-sysext service. Users manually invoking `systemd-sysext` will lose the partition mount - while we don't support manual usage of the CLI command for the reason that it doesn't reload and start new services, this is a lesser evil than a broken system because of the OEM partition being inaccessible.

## Ideal future situation

We can drop the special handling because the OEM partition is mounted elsewhere, e.g., under `/oem/` and a symlink from `/usr/share/oem/` exists for backwards compatibility.

## Additional information

`/usr/lib/systemd/system/systemd-sysext.service.d/10-mount-oem-partition.conf` is the workaround

**Comment by pothos** [comment]
Since we also mount the OEM partition from the initrd under `/sysroot`, something like `/oem` would be a good new mountpoint.

**Comment by krnowak** [comment]
> Since we also mount the OEM partition from the initrd under `/sysroot`, something like `/oem` would be a good new mountpoint.

Yeah, that's what I'm using.
