### ISSUE TITLE
Kubeadm init command failing due to conntrack issues

### ISSUE THREAD

**Issue by zeemba** [flatcar/Flatcar#77]
**Description**

Kubeadm init command failing due to conntrack issues

**Impact**

Unable to initialize a kubernetes cluster using "kubeadm init command

**Environment and steps to reproduce**

1. **Set-up**: Flatcar Container Linux by Kinvolk 2345.3.1 (Rhyolite) running in EC2 on AWS
2. **Task**: Ran the "kubeadm init --v=11" command. I have kubeadm, kubelet and kubectl on version 1.18.0
3.**Action(s)**: `kubeadm init --v=11`

4. **Error**: `ip-10-50-1-171 configs # kubeadm init  --v=11
I0408 15:51:53.955454   24457 initconfiguration.go:103] detected and using CRI socket: /var/run/dockershim.sock
I0408 15:51:53.955663   24457 interface.go:400] Looking for default routes with IPv4 addresses
I0408 15:51:53.955680   24457 interface.go:405] Default route transits interface "eth0"
I0408 15:51:53.955810   24457 interface.go:208] Interface eth0 is up
I0408 15:51:53.955876   24457 interface.go:256] Interface "eth0" has 2 addresses :[10.50.1.171/24 fe80::8b9:3ff:fe10:44e9/64].
I0408 15:51:53.955901   24457 interface.go:223] Checking addr  10.50.1.171/24.
I0408 15:51:53.955918   24457 interface.go:230] IP found 10.50.1.171
I0408 15:51:53.955931   24457 interface.go:262] Found valid IPv4 address 10.50.1.171 for interface "eth0".
I0408 15:51:53.955942   24457 interface.go:411] Found active IP 10.50.1.171
I0408 15:51:53.955987   24457 version.go:183] fetching Kubernetes version from URL: https://dl.k8s.io/release/stable-1.txt
W0408 15:51:54.190575   24457 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[init] Using Kubernetes version: v1.18.0
[preflight] Running pre-flight checks
I0408 15:51:54.190809   24457 checks.go:577] validating Kubernetes and kubeadm version
I0408 15:51:54.190833   24457 checks.go:166] validating if the firewall is enabled and active
I0408 15:51:54.206831   24457 checks.go:201] validating availability of port 6443
I0408 15:51:54.207010   24457 checks.go:201] validating availability of port 10259
I0408 15:51:54.207051   24457 checks.go:201] validating availability of port 10257
I0408 15:51:54.207113   24457 checks.go:286] validating the existence of file /etc/kubernetes/manifests/kube-apiserver.yaml
I0408 15:51:54.207133   24457 checks.go:286] validating the existence of file /etc/kubernetes/manifests/kube-controller-manager.yaml
I0408 15:51:54.207146   24457 checks.go:286] validating the existence of file /etc/kubernetes/manifests/kube-scheduler.yaml
I0408 15:51:54.207155   24457 checks.go:286] validating the existence of file /etc/kubernetes/manifests/etcd.yaml
I0408 15:51:54.207172   24457 checks.go:432] validating if the connectivity type is via proxy or direct
I0408 15:51:54.207203   24457 checks.go:471] validating http connectivity to first IP address in the CIDR
I0408 15:51:54.207232   24457 checks.go:471] validating http connectivity to first IP address in the CIDR
I0408 15:51:54.207254   24457 checks.go:102] validating the container runtime
I0408 15:51:54.306428   24457 checks.go:128] validating if the service is enabled and active
        [WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
I0408 15:51:54.395562   24457 checks.go:335] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0408 15:51:54.395620   24457 checks.go:335] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0408 15:51:54.395651   24457 checks.go:649] validating whether swap is enabled or not
I0408 15:51:54.395685   24457 checks.go:376] validating the presence of executable conntrack
I0408 15:51:54.395724   24457 checks.go:376] validating the presence of executable ip
I0408 15:51:54.395746   24457 checks.go:376] validating the presence of executable iptables
I0408 15:51:54.395765   24457 checks.go:376] validating the presence of executable mount
I0408 15:51:54.395785   24457 checks.go:376] validating the presence of executable nsenter
I0408 15:51:54.395809   24457 checks.go:376] validating the presence of executable ebtables
I0408 15:51:54.395827   24457 checks.go:376] validating the presence of executable ethtool
I0408 15:51:54.395844   24457 checks.go:376] validating the presence of executable socat
I0408 15:51:54.395862   24457 checks.go:376] validating the presence of executable tc
I0408 15:51:54.395879   24457 checks.go:376] validating the presence of executable touch
I0408 15:51:54.395899   24457 checks.go:520] running all checks
I0408 15:51:54.475812   24457 checks.go:406] checking whether the given node name is reachable using net.LookupHost
I0408 15:51:54.475845   24457 checks.go:618] validating kubelet version
I0408 15:51:54.531625   24457 checks.go:128] validating if the service is enabled and active
I0408 15:51:54.544345   24457 checks.go:201] validating availability of port 10250
I0408 15:51:54.544424   24457 checks.go:201] validating availability of port 2379
I0408 15:51:54.544463   24457 checks.go:201] validating availability of port 2380
I0408 15:51:54.544505   24457 checks.go:249] validating the existence and emptiness of directory /var/lib/etcd
[preflight] Some fatal errors occurred:
        [ERROR FileExisting-conntrack]: conntrack not found in system path
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
error execution phase preflight
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdInit.func1
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:147
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
k8s.io/kubernetes/cmd/kubeadm/app.Run
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357`

**Expected behavior**
The command should initialize the Kubernetes cluster on the node

**Additional information**
I noticed that the main error is `[ERROR FileExisting-conntrack]: conntrack not found in system path" which I found to be a new feature/bug fix for v1.18.0 (see below)`

During initialization phase (preflight), kubeadm now verifies the presence of the conntrack executable (#85857, @hnanni) [SIG Cluster Lifecycle]

So the question is that does Flatcar OS have the conntrack installed/initialized. and if not, how do I install/initialize it . Any pointer will be highly appreciated

**Comment by t-lo** [comment]
We will include the `conntrack` user space binary with our next Alpha release and will track stabilisation to Beta and Stable in the respective feature request in https://github.com/flatcar-linux/Flatcar/issues/78 . Please consider following the feature request for updates.

I'll close this bug report in favour of #78 ; please feel free to re-open if you continue experiencing this issue.

**Comment by zeemba** [comment]
Thanks @t-lo 

I'll test out the feature in the next alpha release and get back to you
