### ISSUE TITLE
[RFE] Document Flatcar build / release chain of trust / supply chain

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#771]
## Current situation

Flatcar supply chain security is not documented.

## Impact

Users and contributors are unable to educate themselves on how Flatcar ensures validity of the bits we ship.

## Ideal future situation

Input validation, secure build, output signing are documented on the producer end as well as image / update validation on the consumer end. 

## Implementation options

Write docs, reference from the entry page at flatcar.org/docs. Maybe add a few pretty flowcharts.

**Comment by ahrkrak** [comment]
See https://documentation.suse.com/sbp/server-linux/html/SBP-SLSA4/index.html for example
