### ISSUE TITLE
[RFE] Unmasking systemd units

### ISSUE THREAD

**Issue by thefirstofthe300** [flatcar/Flatcar#774]
## Current situation

I am in the situation currently where I am using Flatcar as provided by the K8s cluster-api-aws project. They are shipping flatcar-stable images that currently have Ignition/CLC v0.36.1 bundled with it. As a result, [this commit](https://github.com/flatcar-linux/ignition/commit/18ac09ab0f699f85dd253e688ae89ac6066be14a) isn't available.

This particular project has had issues with Flatcar updating itself in the midst of image builds so they mask both the locksmithd and update-engine services to prevent automatic updates from occuring.

Between the lack of the above commit and the masking of these units, it's non-obvious how to unmask the unit (I suspect I'm going to be writing a systemd unit to unmask and start the service on first boot ironically enough).

## Impact

Unable to enable auto-updates using FLUO for my k8s cluster.

## Ideal future situation

Have the ability to unmask units using the systemd config section in CLC

**Comment by pothos** [comment]
Support for Ignition spec version 3 is currently available in Beta and soon this will be the next Stable release.
For the old Ignition spec version 2 I wonder if you could overwrite the masking symlink with an empty file. Will have to test it.

**Comment by pothos** [comment]
Ok, what works is to replace the symlink to /dev/null with a symlink to the original unit file:

```
  "links": [
    {
      "filesystem": "root",
      "path": "/etc/systemd/system/update-engine.service",
      "target": "/usr/lib/systemd/system/update-engine.service",
      "overwrite": true
    }
  ]
```
You can use this as workaround for now. Locksmithd should remain masked (see https://github.com/flatcar-linux/flatcar-linux-update-operator/issues/110).
