### ISSUE TITLE
weekly testing failed on AWS

### ISSUE THREAD

**Issue by jepio** [flatcar/Flatcar#777]
## Description

Weekly all platform test run has failed on AWS. As far as I can tell, all instances failed to boot. I've managed to capture the following boot log (only the last 64KB is available): [m4.xlarge-boot.log](https://github.com/flatcar-linux/Flatcar/files/8910805/m4.xlarge-boot.log), which points at disk corruption.

## Additional information

Failing job: http://jenkins.infra.kinvolk.io:8080/job/os/job/kola/job/aws/124/
Please add any information here that does not fit the above format.

**Comment by jepio** [comment]
Initially thought this was m4 instance related, but t3 instances have the same issue. Re-running prerelease/aws job to see if it fixes the disk corruption.

**Comment by pothos** [comment]
Will close now as I think we will address any issues without this ticket - I wonder if it was related to the vmdk corruption we found a workaround for.
