### ISSUE TITLE
Support Kubernetes 1.18 (add conntrack binary)

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#78]
**Current situation**
Flatcar currently does not support running Kubernetes 1.18. Main blocker is a missing user space tool, `conntrack` for managing netfilter connection tracking (`nf_conntrack_*` family of kernel modules).

**Impact**
Kubernetes 1.18, released March 31st 2020, fails to install on Flatcar (via `kubeadm`)

**Ideal future situation**
Flatcar fully supports Kubernetes 1.18.

**Implementation options**
Add the `conntrack` binary (and possibly other required tools).

**Additional information**
This was originally raised by Azeem on our [Flatcar-Users mailing list](https://groups.google.com/forum/#!topic/flatcar-linux-user/KGaydknHv3k) as well as in bug #77 .

**Comment by iaguis** [comment]
The original bug was about running kubeadm on Flatcar: it now requires the conntrack binary because the kubelet requires it and kubeadm runs the kubelet directly as a systemd service.

Distros that, for example, use the hyperkube container like Lokomotive or Typhoon include the conntrack binary in the hyperkube image so k8s 1.18 works there.

**Comment by t-lo** [comment]
Flatcar Container Linux aims to be a minimal, container-centric distribution. Therefore, each addition to the distribution is put under adequate scrutiny to maintain a small OS image size as well as to minimise attack surface.

* CON: We expect the `conntrack` binary to increase the OS image by a few hundred kilobytes (exact data pending).
* PRO: We do not expect the attack surface to increase as `conntrack` uses kernel module APIs already present on Flatcar (`nf_conntrack_*` family of kmods).
* PRO: adding `conntrack` will add support for installing Kubernetes 1.18 via `kubeadm` and will work towards compatibility with Cluster API.

Following the discussion above we will go ahead and aim to include `conntrack` with an upcoming Alpha release (then stabilise via Beta and Stable).

**Comment by hakman** [comment]
Adding `conntrack` would also benefit the `kuberntes/kops` project.
At the moment, Kops is adding adding this as a static binary, which is not so simple and would become even more complicated for ARM64 support. So, this is great news.
@justinsb
