### ISSUE TITLE
[RFE] ci: Test dev container in new pipeline

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#786]
## Current situation

The existing CI pipeline uses something like `git -C flatcar-scripts checkout "${REF}"; flatcar-scripts/jenkins/systemd-run-wrap.sh flatcar-scripts/jenkins/kola/dev-container.sh` to validate the dev container.
The new pipeline under `scripts/ci-automation` doesn't have this yet.

## Impact

We can't switch to the new pipeline for releases.

## Ideal future situation/Implementation options

The prerequisite https://github.com/flatcar-linux/Flatcar/issues/623 is implemented.
We have a test of the dev container in `vendor-testing/` or maybe separate from it because it uses `systemd-nspawn` and should not run inside Docker itself - we could however document for users how to use Docker instead of systemd-nspawn for the dev container and then it's ok to only test with Docker but as far as I know this is not straightforward due to the emerge requirements (see the hacks in the container SDK).

**Comment by krnowak** [comment]
Initial work here: https://github.com/flatcar-linux/mantle/tree/krnowak/dev-container-test

**Comment by pothos** [comment]
Done in https://github.com/flatcar/mantle/pull/367
