### ISSUE TITLE
Add support for AWS IMDSv2 to coreos-cloudinit

### ISSUE THREAD

**Issue by hakman** [flatcar/Flatcar#787]
## Current situation

Partial AWS IMDSv2 support was added by https://github.com/flatcar-linux/Flatcar/issues/220 in v3227.0.0. 

## Impact

At the moment, the Flatcar instance boots but user-data is not processed due to lack of support for IMDSv2 in `coreos-cloudinit`:
```
Jun 25 04:47:12.309062 localhost bash[1715]: + /usr/bin/coreos-cloudinit --oem=ec2-compat
Jun 25 04:47:12.537609 i-0521929c4b27fd9ee bash[1715]: 2022/06/25 04:47:12 Checking availability of "cloud-drive"
Jun 25 04:47:12.537609 i-0521929c4b27fd9ee bash[1715]: 2022/06/25 04:47:12 Checking availability of "ec2-metadata-service"
...
Jun 25 04:52:03.772421 i-0521929c4b27fd9ee bash[1715]: 2022/06/25 04:52:03 Checking availability of "cloud-drive"
Jun 25 04:52:03.776615 i-0521929c4b27fd9ee bash[1715]: 2022/06/25 04:52:03 Checking availability of "ec2-metadata-service"
Jun 25 04:52:12.532478 i-0521929c4b27fd9ee bash[1715]: 2022/06/25 04:52:12 No datasources available in time
```
Full journal log can be found [here](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-distro-flatcar/1540556462403620864/artifacts/63.34.28.190/journal.log).

## Ideal future situation

IMDSv2 is fully supported by Flatcar.

## Implementation options

n/a

## Additional information

n/a

**Comment by tormath1** [comment]
Hi @hakman and thanks for opening this issue.

Looking at the codebase, we should update this file: https://github.com/flatcar-linux/coreos-cloudinit/blob/flatcar-master/datasource/metadata/ec2/metadata.go#L47 to add the IMDSv2 support and fallback on IMDSv1 in case of support is missing.

Something similar is already done on the Ignition side: https://github.com/coreos/ignition/commit/585c029f36cf7a027f22704759bb3c6600709b2d - the idea is to fetch a token and to use this token for later requests.

Out of curiosity, it that something that could interest you to contribute on ?

**Comment by jepio** [comment]
PR https://github.com/flatcar-linux/coreos-overlay/pull/2070 was merged, this will be available in beta soon (after v3277.1.1), and then later in stable.

**Comment by Tariq-dev** [comment]
Hi @jepio, Can you please share the expected date to Add AWS IMDSv2 support in stable version?

**Comment by jepio** [comment]
I would expect it to arrive in stable around end of October.

**Comment by hakman** [comment]
Until then, I can confirm that Beta works nicely and passes k8s e2e tests with IMDSv2 enabled:
https://testgrid.k8s.io/kops-distros#kops-aws-distro-flatcar

**Comment by Tariq-dev** [comment]
Thanks @jepio @hakman for the quick response.
