### ISSUE TITLE
Bug Smashing - July 8th, 2022

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#796]
The goal of this event is to go through the Flatcar [issues](https://github.com/flatcar-linux/Flatcar/issues) and try to:
- Check if they are still relevant
- Add steps to reproduce the issue
- Add the correct labels
- Ask for more information on the ticket
    ...

For more information, please follow the Github Discussion: https://github.com/flatcar-linux/Flatcar/discussions/795

Checklist for the 2nd Bug smashing day of the year

- [x] tweet announcement @miao0miao
- [ ] Add event to the Flatcar Community [Calendar](https://calendar.google.com/calendar/ical/c_ii991mqrpta9en8o7ofd4v19g4%40group.calendar.google.com/public/basic.ics) @t-lo
- [x] Create a document to track the on-going discussions during the event: https://hackmd.io/eYCdnFnfTyO3hUaxtse5wQ
- [ ] 1h before meeting: announce in matrix (w/ Zoom link) @miao0miao
- [ ] Add the YouTube link to the event
- [ ] Conduct the event https://github.com/orgs/flatcar-linux/teams/flatcar-maintainers

**Comment by tormath1** [comment]
Event is done - closing this. Here's the notes took during the day: https://hackmd.io/eYCdnFnfTyO3hUaxtse5wQ
