### ISSUE TITLE
"Running Flatcar Linux on EC2" page shows CoreOS AMIs

### ISSUE THREAD

**Issue by ialidzhikov** [flatcar/Flatcar#8]
Steps to reproduce:
1. Open https://docs.flatcar-linux.org/os/booting-on-ec2/
2. Click on `View as json feed`,
3. Ensure that the links refers to the CoreOS json feed (and respectively CoreOS AMIs) - https://coreos.com/dist/aws/aws-stable.json

**Comment by dongsupark** [comment]
Thanks for the report.
I can see the exact issue.
On the [main webpage](https://docs.flatcar-linux.org/os/booting-on-ec2/) of EC2 images, each `AMI ID` link points to a correct AMI.
However, the json feed link points to the coreos one.
Will soon working on a fix.

**Comment by dongsupark** [comment]
Fixed.
Links on https://docs.flatcar-linux.org/os/booting-on-ec2/ should be now correct.
