### ISSUE TITLE
ci: Don't upload oem-gce-aci pcrs rootfs torcx folders to bincache

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#801]
## Description

When building (all image formats) the following additional folders get stored in bincache:
`oem-gce-aci pcrs rootfs torcx`

## Impact

Publishing a release to Origin would need manual filtering

## Expected behavior

Only the folders we need get uploaded

## Additional information

Maybe the `torcx` folder has a valid case if we store it there instead of GCS, the I don't think we need the other folders

**Comment by krnowak** [comment]
torcx directory is uploaded on purpose here - https://github.com/flatcar-linux/scripts/blob/056752222eb167bd6713078594577d4f2ff0cae6/ci-automation/packages.sh#L181-L184

**Comment by krnowak** [comment]
rootfs and pcrs are created as a part of images job, oem-gce-aci comes from vms job.
