### ISSUE TITLE
Can't login via vault ssh to EC2 instance built from Flatcar 3227.2.0

### ISSUE THREAD

**Issue by Oleksii-Melnyk-UA** [flatcar/Flatcar#804]
Hi team,

I built an image based on Flatcar 3227.2.0 using Packer.
Then via Terraform created AWS EC2 instance using this image.
When try to connect to this EC2 instance via vault ssh command, receive an error:

failed to generate credential: failed to get credentials: Error making API request.
URL: PUT https://my_vault_url/path
Code: 500. Errors:
* 1 error occurred:
	* failed to add public key to authorized_keys file in target: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

I can successfully login via vault ssh to EC2 instances built on Flatcar 3033.2.2 image.
But received the same error, when tried to connect to instance, built on Flatcar 3139.2.3.

Do you know what can be the root cause?
I noticed that in 3139.2.0 openssh version changed to 8.8.
I have vault cluster v1.7.2, locally installed vault client 1.9.2, locally have ssh version OpenSSH_8.6p1 .

**Comment by jepio** [comment]
I'm not familar with `vault ssh`, could this be this issue: https://github.com/hashicorp/vault/issues/15488?
You might need to add the following to `/etc/ssh/sshd_config`:
```
PubkeyAcceptedAlgorithms +ssh-rsa-cert-v01@openssh.com
```

**Comment by Oleksii-Melnyk-UA** [comment]
I added the following configuration to /etc/ssh/sshd_config on the Flatcar server image, but it didn't help.
Received same error.

`PubkeyAcceptedAlgorithms +ssh-rsa-cert-v01@openssh.com`

**Comment by jepio** [comment]
Do you have instructions for how to recreate the problem to further investigate?

Blind suggestions: there is also another parameter (`HostkeyAlgorithms`), or you might need `+ssh-rsa` instead?
See this: https://github.com/flatcar-linux/coreos-overlay/commit/fb4af8fdce9df1c0c9f8217f691759fba2b273a6

**Comment by Oleksii-Melnyk-UA** [comment]
Thank you for help.
Issue fixed after I added 2 lines, as you mentioned in https://github.com/flatcar-linux/coreos-overlay/commit/fb4af8fdce9df1c0c9f8217f691759fba2b273a6
