### ISSUE TITLE
Ignition: Bad networkd translation

### ISSUE THREAD

**Issue by mickymiek** [flatcar/Flatcar#812]
## Description
One of our .network file had a little issue when launching flatcar. The ignition file looked fine, the problem occurs when installing flatcar with this file.
The problematic line is this one:  `Type=!vlan bond bridge`, it got translated as `Type=!vlan+bond+bridge` in the .network file.
We managed to work around it by moving our networkd units to the files section.

## Impact
The network interface in question didn't work at all.

## Environment and steps to reproduce
FlatCar version: `3227.2.0`

## Expected behavior
Spaces shouldn't be replaced by plus signs.

**Comment by tormath1** [comment]
Hi, thanks for the report!

It's actually an interesting one - in the translation, `url.QueryEscape` encodes the content of the networkd:
```
url.QueryEscape("!vlan bond bridge")
%21vlan+bond+bridge
```

Which is later decoded by Ignition to:
```
!vlan+bond+bridge
```

Space is encoded differently (`+` or `%20`) whether it's being in the path or in the query of an URL - Ignition seems to expect the URL to be encoded from the path. 

Will patch the converter and add the test case to our coverage.

**Comment by tormath1** [comment]
Thanks again @mickymiek for raising this issue. Fix should be available in the next batch of releases and a test has been added in our test suite.
