### ISSUE TITLE
gen2 flatcar image is missing gpu modules 

### ISSUE THREAD

**Issue by vickeyrihal1** [flatcar/Flatcar#816]
## Description

gen2 flatcar image is missing gpu modules (i2c_core)

## Impact

This is in reference to get NVIDIA GPU driver support for Gen 2 Flatcar images.
 
We recently tried to provision a GPU machine against “kinvolk:flatcar-container-linux:stable-gen2:3139.2.0”. When we tried to run the nvidia driver[1], it ended up in following errors:
 
[  115.965785] nvidia: Unknown symbol i2c_add_adapter (err -2)
 
 
When we went to gen1 image with the same flatcar version, the driver was working alright.
 
Upon further investigation, we found that a pre-requisite(i2c-core) for nvidia driver in gen2 images was missing. Things started working once we loaded the module using modeprobe utility in gen2 image.
 
So, the questions are:
Is this done deliberately? Can we get following module included in gen2 image as well – loop, i2c_core and ipmi_msghandler.
What else is disabled in gen2 image when compared to gen1 image?
As a workaround, if we load these modules explicitly, anything else we need to take care?

**Comment by jepio** [comment]
The gen1 and gen2 images have the exact same disk contents, but the gen1 hardware automatically probes the i2c module, whereas on gen2 hardware it is not used by default. You'll need to create a config in `/etc/modules-load.d` (https://www.freedesktop.org/software/systemd/man/modules-load.d.html) to have the modules loaded by default (recommend doing it for both generations). There is also some documentation here https://flatcar-linux.org/docs/latest/setup/customization/other-settings/#loading-kernel-modules-with-options.

You'll need to load these modules:
```
i2c_core
ipmi_msghandler
ipmi_devintf
```

We also recently merged https://github.com/flatcar-linux/coreos-overlay/pull/1840, which is part of alpha-3305.0.0 images (not yet in the marketplace), which takes care of loading the modules and has other improvements. Please check it out once it's available!

**Comment by vickeyrihal1** [comment]
Awesome! thank you @jepio for the information.
