### ISSUE TITLE
Flatcar Linux Azure Marketplace image

### ISSUE THREAD

**Issue by dghubble** [flatcar/Flatcar#82]
### Description

The Flatcar Linux Azure Marketplace image is using BYOL ("bring your own license") and lists no additional charges (but also doesn't say free). I wanted to ask for clarifications about both the license and pricing.

### Impact

**License**

Unlike CoreOS Azure Marketplace images, the Flatcar Linux Marketplace image requires accepting a license once before use. Showing the license with `az` yields a JSON blob linking to a personalized license that contains a link to https://kinvolk.io/legal/open-source/

```
$ terraform apply
Error message: 'Legal terms have not been accepted for this item on this subscription

az vm image terms show --publish kinvolk --offer flatcar-container-linux --plan stable
az vm image terms accept --publish kinvolk --offer flatcar-container-linux --plan stable
```

Is this needed? Also, the BYOL link on Flatcar Linux Azure Marketplace doesn't provide go to a description, so it sounds like something that needs to be obtained externally and loaded (although I believe that's not the case)

**Pricing**

The terms above enable a subscription that may have costs? The day I began testing Flatcar Linux Azure, a new separate Azure Marketplace invoice line item appeared (separate from Azure Service).

Azure's own detailed invoice is broken and the generic invoice PDF provides no details about even the name of the subscription, so its been difficult to confirm whether this is indeed coming from Flatcar Linux Azure. Its possible its something else. But for now I've cancelled my subscription to see if it goes away next month.

### Environment and steps to reproduce

1. Use Flatcar Linux Marketplace image on Azure through the UI or other means
2. See if you have to accept terms beforehand?
3. See if you get charged?

### Expected behavior

No charges and ideally no special step to accept a license that triggers Azure subscriptions.

### Additional information

Also filed at https://github.com/poseidon/typhoon/issues/703

**Comment by ahrkrak** [comment]
The license for Flatcar is the standard open source license. Pricing is free - so don't worry, there are no charges created as a result of accepting the terms.
However, clearly we should have published as a Free, not BYOL, image, and are working to fix this.

**Comment by dghubble** [comment]
Thanks for the info @ahrkrak, I've filed an issue with Azure to try to determine what caused the charge that day.

**Comment by t-lo** [comment]
Hello @dghubble ,

we have added a second Flatcar offer to Azure, using a $0 usage cost licensing model. The offer id is `flatcar-container-linux-free`. The new offer's SKUs use the naming scheme "Flatcar Container Linux (*channel*)". For backwards compatibility reasons the BYOL offer still exists; we renamed the respective  SKUs to "Flatcar Container Linux (*channel*) [BYOL]"

**Comment by dghubble** [comment]
Thanks, I'll give that a shot :+1:

**Comment by dghubble** [comment]
I'm still working with Azure support to find out why Azure Marketplace charges began March 9th and continue montly (they can't populate an invoice with details about the source).

That's still ongoing, so I've held off on accepting any new terms within Marketplace for worry they have some issue or are charging fees on their side. Its not fair to hold up your issue tracker on an my Azure support ticket so you can close if you like, I can report back if I learn something needing action.

**Comment by dghubble** [comment]
I tested the new free offering and it does indeed seem to be free and more clear and I haven't found charges so that checks out. The az accept terms are the same, but I think that must be expected.

The prior charge issue is being investigated as an unattributed billing bug in Azure that was somehow triggered before. Closing this out, thanks all!

**Comment by chrskhl** [comment]
It seems that in Azure that only goes away if you check the box to make your offer available under the standard MS agreement which does not seem 100% OSS compliant. But it seems like most of the other vendors are doing that and then linking or including their own licensing information. We may do that also in the near future to remove this annoyance.

I'm not sure at all what the charge thing is about. Hope the Azure folks help you resolve it.
