### ISSUE TITLE
System does not boot properly when using ignition config with dropin of provided unit

### ISSUE THREAD

**Issue by RyanSquared** [flatcar/Flatcar#820]
## Description

When given an Ignition configuration with a systemd unit and a separately configured dropin for that systemd unit, the machine doesn't properly boot. I am not able to SSH to the machine or perform any debugging.

## Impact

I believe the machine halts while applying the Ignition configuration and doesn't boot properly.

## Environment and steps to reproduce

1. **Set-up**: AWS AMI  Flatcar-stable-3227.2.0-hvm
2. **Task**: Booting up machine
3. **Action(s)**:
  a. Configured a systemd unit "vault.service"
  b. Configured a dropin for systemd unit "vault.service", "10-vault-fetcher.conf", with the following configuration:
    ```systemd
    [Service]
    Environment=COMMAND=vault/daemon/fetch.py
    ```
4. **Error**: Machine does not become accessible on boot

## Expected behavior

Machine boots and the systemd unit loads with the environment variable `COMMAND` set to `vault/daemon/fetch.py`

## Additional information

When testing, the machine would become accessible after about 30 seconds if I did not provide the dropin unit. However, if I did provide the dropin unit, the machine would not respond to pings and was unreachable via SSH.

**Comment by jepio** [comment]
Can you paste your ignition config? I just tried this out  on 3227.2.0 with the following:
```yaml
systemd:
  units:
  - name: vault.service
    enabled: true
    contents: |
      [Unit]
      Description=vault service
      [Service]
      Type=oneshot
      ExecStart=/usr/bin/env
      [Install]
      WantedBy=multi-user.target
    dropins:
    - name: 10-vault-fetcher.conf
      contents: |
        [Service]
        Environment=COMMAND=vault/daemon/fetch.py
```
and see no issues.

**Comment by RyanSquared** [comment]
This is the rendered config:

```json
{
  "ignition": {
    "config": {},
    "timeouts": {},
    "version": "2.1.0"
  },
  "networkd": {},
  "passwd": {},
  "storage": {},
  "systemd": {
    "units": [
      {
        "dropins": [
          {
            "contents": "[Service]\nEnvironment=COMMAND=vault/daemon/fetch.py\n",
            "name": "10-vault.conf"
          }
        ],
        "enabled": true,
        "name": "vault.service"
      },
      {
        "contents": "[Unit]\nDescription=Manage Docker control for Vault\nAfter=docker.service docker-ecr-login.service\n\n[Service]\nTimeoutStartSec=0\nExecStartPre=-/usr/bin/docker rm --force vault\nExecStartPre=/usr/bin/docker pull <hidden>.dkr.ecr.us-east-1.amazonaws.com/vault\nExecStart=/usr/bin/docker run --name=vault --env-file=/vault.env <hidden>.dkr.ecr.us-east-1.amazonaws.com/vault $COMMAND\nExecStop=/usr/bin/docker stop vault\nRestart=always\nRestartSec=5s\n\n[Install]\nWantedBy=multi-user.target\n",
        "enabled": true,
        "name": "vault.service"
      }
    ]
  }
}
```

It is listed as two components because this way I can define the "vault.service" unit once and reuse it for multiple instances, with each instance getting its own dropin.

**Comment by RyanSquared** [comment]
Closing as I have found a solution. In my Terraform, I use (basically) `jsonencode(merge(jsondecode(first_rendered_unit), jsondecode(second_rendered_unit)))`.
