### ISSUE TITLE
coreos-ct homebrew formula is outdated

### ISSUE THREAD

**Issue by kiyose** [flatcar/Flatcar#827]
## Description

The coreos-ct [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/coreos-ct.rb) tracks `coreos/container-linux-config-transpiler` and has been recently disabled with a `:repo_archived` tag.  Either this formula needs to be updated or a new one created and the [documentation updated here](https://github.com/flatcar-linux/container-linux-config-transpiler#macos-homebrew).

## Impact

Unable to install recent versions of flatcar-linux/container-linux-config-transpiler

## Environment and steps to reproduce

```
$ brew info coreos-ct 
==> coreos-ct: stable 0.9.0 (bottled)
Convert a Container Linux Config into Ignition
https://coreos.com/os/docs/latest/configuration.html
Disabled because it has an archived upstream repository!
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/coreos-ct.rb
License: Apache-2.0
```

## Expected behavior

```
$ brew info coreos-ct  
==> coreos-ct: stable 0.9.3 (bottled)
Convert a Container Linux Config into Ignition
https://flatcar-linux.org/docs/latest/provisioning/config-transpiler/
/usr/local/Cellar/coreos-ct/0.9.3 (7 files, 4.8MB) *
  Built from source on 2022-08-16 at 10:39:51
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/coreos-ct.rb
License: Apache-2.0
```

## Additional information

I started to update the formula but ran into an issue when running `brew audit --strict coreos-ct`.  My [changes can be seen here](https://github.com/kiyose/homebrew-core/pull/1/files) 

```
$ brew audit --strict coreos-ct
coreos-ct:
  * 7: col 5: `on_monterey` cannot include `homepage`. Only `depends_on`, `patch`, `resource`, `deprecate!`, `disable!`, `conflicts_with`, `fails_with`, `keg_only`, `ignore_missing_libraries`, `on_intel`, `on_arm`, `on_macos`, `on_linux`, `on_system`, `on_ventura`, `on_monterey`, `on_big_sur`, `on_catalina`, `on_mojave`, `on_high_sierra`, `on_sierra`, and `on_el_capitan` are allowed.
  * 8: col 5: `on_monterey` cannot include `url`. Only `depends_on`, `patch`, `resource`, `deprecate!`, `disable!`, `conflicts_with`, `fails_with`, `keg_only`, `ignore_missing_libraries`, `on_intel`, `on_arm`, `on_macos`, `on_linux`, `on_system`, `on_ventura`, `on_monterey`, `on_big_sur`, `on_catalina`, `on_mojave`, `on_high_sierra`, `on_sierra`, and `on_el_capitan` are allowed.
  * 9: col 5: `on_monterey` cannot include `sha256`. Only `depends_on`, `patch`, `resource`, `deprecate!`, `disable!`, `conflicts_with`, `fails_with`, `keg_only`, `ignore_missing_libraries`, `on_intel`, `on_arm`, `on_macos`, `on_linux`, `on_system`, `on_ventura`, `on_monterey`, `on_big_sur`, `on_catalina`, `on_mojave`, `on_high_sierra`, `on_sierra`, and `on_el_capitan` are allowed.
  * 11: col 3: `license` (line 11) should be put before `on_monterey` (line 6)
Error: 4 problems in 1 formula detected
```

**Comment by pothos** [comment]
Hello,
thanks for raising this. I don't think we have anyone active in this area at the moment and would recommend to use the Docker image instead, see https://www.flatcar.org/docs/latest/provisioning/config-transpiler/getting-started/

**Comment by kiyose** [comment]
Thanks for the quick response. If the recommended installation method on Mac is to not use `brew` then the instructions on this page need to be removed.
https://github.com/flatcar-linux/container-linux-config-transpiler#macos-homebrew

**Comment by tylerauerbeck** [comment]
@pothos I went ahead and updated this here: https://github.com/Homebrew/homebrew-core/pull/111401

This will at least prevent folks from stumbling upon this while going through the docs until a time that it is indicated that `ct` is deprecated / going away.

**Comment by tylerauerbeck** [comment]
This is resolved now: https://github.com/Homebrew/homebrew-core/blob/master/Formula/coreos-ct.rb . Homebrew now points to the flatcar maintained release of ct and pulls in the latest tagged version (v0.9.4).

**Comment by tormath1** [comment]
Hi @tylerauerbeck thanks a lot for this contribution, this is truly appreciated! I think we can close this issue for now. On a last note, we slowly start to recommend using `butane` instead of `ct` (see this issue: https://github.com/flatcar/Flatcar/issues/852)

EDIT: just seen this PR: https://github.com/flatcar/flatcar-docs/pull/260 great :smiley:
