### ISSUE TITLE
equinix metal s3.xlarge.x86 won't boot

### ISSUE THREAD

**Issue by krnowak** [flatcar/Flatcar#834]
## Description

CI fails recently on s3.xlarge.x86 instances with a timeout error. But the problem is not with the too short timeouts, but rather with the fact that for some reason the instance won't boot after ignition does its stuff and the machine reboots. Creating an instance through a website with OS option set to "flatcar stable" works fine - machine boots up and it's possible to SSH into it.

We are testing also other instances, but they don't seem to be affected.

## Impact

Most likely Flatcar won't work for people wanting to run it on s3.xlarge.x86 instances.

Here's the output from SOS console I managed to screenscrap:

```
Welcome to Neverland!
net0: b8:ce:f6:04:8b:2c using undionly on 0000:d8:00.0 (Ethernet) [open]
  [Link:up, TX:0 TXE:1 RX:0 RXE:0]
  [TXE: 1 x "Network unreachable (http://ipxe.org/28086011)"]
Configuring (net0 b8:ce:f6:04:8b:2c)... ok
net0: 136.144.49.55/255.255.255.254 gw 136.144.49.54
net0: fe80::bace:f6ff:fe04:8b2c/64 gw fe80::400:deff:fead:beef
Next server: 145.40.92.140
Filename: http://tinkerbell.fr2.packet.net/nonexistent
http://tinkerbell.fr2.packet.net/nonexistent... HTTP 5xx Server Error (http://ipxe.org/1d0c6539)
FlexBoot was shut down by NBP! Cleaning...

FlexBoot v3.6.102 (PCI D8:00.1) starting execution...ok
FlexBoot initialising devices...
Initialising completed.

FlexBoot v3.6.102
Features: DNS HTTP iSCSI TFTP VLAN ELF MBOOT PXE bzImage COMBOOT Menu PXEXT
net0: b8:ce:f6:04:8b:2d
Using ConnectX-4Lx on 0000:d8:00.1 (open)
[Link:up, TX:0 TXE:0 RX:0 RXE:0]
Configuring (net0 b8:ce:f6:04:8b:2d)............................................
................ No configuration methods succeeded (http://ipxe.org/040ee119)
No more ports. Exiting FlexBoot...

Reboot and Select proper Boot device
or Insert Boot Media in selected Boot device and press a key
```

## Environment and steps to reproduce

I just tried the following commands:
```bash
EM_METRO='FR' # tried DA and SV too, no difference
EM_PROJ_ID='…'
GCE_JSON_KEY='/path/to/the/key.json'
EM_API_KEY='…'
sudo /PATH/TO/kola spawn \
        --board=amd64-usr \
        --basename=krnowak-timeout-test-amd64 \
        --platform=equinixmetal \
        --equinixmetal-image-url=http://bincache.flatcar-linux.net/images/amd64/3340.0.0+nightly-20220823-2100/flatcar_production_packet_image.bin.bz2 \
        --equinixmetal-installer-image-kernel-url=http://bincache.flatcar-linux.net/images/amd64/3340.0.0+nightly-20220823-2100/flatcar_production_pxe.vmlinuz \
        --equinixmetal-installer-image-cpio-url=http://bincache.flatcar-linux.net/images/amd64/3340.0.0+nightly-20220823-2100/flatcar_production_pxe_image.cpio.gz \
        --equinixmetal-metro="${EM_METRO}" \
        --equinixmetal-plan=s3.xlarge.x86 \
        --equinixmetal-project="${EM_PROJ_ID}" \
        --equinixmetal-storage-url=gs://flatcar-jenkins/mantle/packet \
        --gce-json-key="${GCE_JSON_KEY}" \
        --equinixmetal-api-key="${EM_API_KEY}" \
        --log-level=TRACE
```

The machine shows up on EM website, and from there you can get access to the SOS console.

## Expected behavior

Well, it boots and gives me the bash prompt.

**Comment by pothos** [comment]
It could be that the captured error may not be the first error but a subsequent error that comes when the instance tries to PXE boot again but it wasn't configured for always-PXE-booting?

**Comment by krnowak** [comment]
I'll need to get mantle logs too, as I forgot to actually gather and paste them here.

But without that, the workflow at some point is that on mantle side we upload ipxe script and userdata to some bucket. On server side we open a discard port, install flatcar and reboot. On mantle side, we establish the connection to the discard port and wait for it to be closed. Closed connection means that the installation is finished, and at this point we set up the device to turn off the "always pxe" setting and remove the uploaded stuff from the bucket. Maybe setting "always pxe" to false is just racy and we update the device when it's too late, because the boot already started. At this point, we have removed ipxe script and userdata from the storage, so maybe this is what this ipxe error is about?

**Comment by krnowak** [comment]
So the issue is that flatcar is installed to some nvme disk (which the scripts finds as the smallest one of the all disks available on the host), from which the boot agent at startup can't boot. Or there needs to be some extra setup done to be able to boot it from them. I excluded these devices from installation and it worked when tested locally. PR filed: https://github.com/flatcar-linux/mantle/pull/364, now waiting for the tests to finish.
