### ISSUE TITLE
[TRACKING] [MAJOR CHANGE] Change the GitHub Org name from "flatcar-linux" to "flatcar"

### ISSUE THREAD

**Issue by miao0miao** [flatcar/Flatcar#836]
# Change GitHub org from https://github.com/flatcar-linux to https://github.com/flatcar.
## **The change will commence on Wednesday, 14th of September, 2022.**

We plan to rename our github organisation to "Flatcar" (without the -linux).

**There _should_ be automated forwarding for all repositories from `flatcar-linux/...` to `flatcar/...` (see https://docs.github.com/en/organizations/managing-organization-settings/renaming-an-organization#changes-that-occur-automatically). References / deep links to repositories / GO modules _should_ continue to work.**

However, given the size of the change, we'll update all internal references and ask folks to update their references, too.

Please feel free to add to this issue if you want us to have your dependency on our radar.

**Update - The org rename is complete. There's an empty org now at `flatcar-linux` to ensure the redirects to `flatcar` remain intact.**

**Comment by t-lo** [comment]
**Affected**
* https://github.com/search?q=org%3Aflatcar-linux+github.com%2Fflatcar-linux&type=code or now https://github.com/search?q=org%3Aflatcar+github.com%2Fflatcar-linux&type=code
* https://pkg.go.dev/search?limit=25&m=package&q=github.com%2Fflatcar-linux
* https://pkg.go.dev/github.com/flatcar-linux/container-linux-config-transpiler/config?tab=importedby
* https://cs.github.com/?scopeName=All+repos&scope=&q=github.com%2Fflatcar-linux+NOT+owner%3Aflatcar-linux+NOT+owner%3Ainvidian+
* https://archlinux.org/packages/community/x86_64/ct/ (maintainer contacted: https://github.com/flatcar/Flatcar/issues/540#issuecomment-1246506581)
* https://github.com/kubernetes-sigs/cluster-api/search?l=Go&q=flatcar-linux

**Related**
* https://github.com/flatcar-linux/flatcar-website/pull/232
* https://github.com/flatcar-linux/scripts/pull/453
* https://github.com/flatcar-linux/coreos-overlay/pull/2132
* https://github.com/flatcar-linux/coreos-overlay/pull/2133
* ~https://github.com/flatcar-linux/ign-converter/pull/8~
* https://github.com/kubernetes-sigs/cluster-api/pull/7200
* https://github.com/kubernetes-sigs/image-builder/pull/971
* https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3716
* https://github.com/flatcar-linux/torcx/pull/14
* https://github.com/flatcar-linux/mantle/pull/372
* https://github.com/flatcar-linux/locksmith/pull/16
* https://github.com/flatcar-linux/fleetlock/pull/4
* https://github.com/flatcar-linux/container-linux-config-transpiler/pull/21
* https://github.com/flatcar-linux/ignition/pull/40
