### ISSUE TITLE
Migrate GitHub actions to SDK or dev container

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#844]
## Current situation

The coreos-overlay GitHub Actions under `.github/workflows/*-releases-*.yml` make use of `.github/workflows/setup-flatcar-sdk.sh` to setup the SDK using cork. However, will not be supported anymore.

## Impact

GitHub Actions fail

## Ideal future situation

They don't use cork

## Implementation options

Use either the SDK container or the dev container

## Additional information

Maybe another container image could also work

**Comment by sayanchowdhury** [comment]
Assiging this to Dongsu as he was working on it.

**Comment by dongsupark** [comment]
PR https://github.com/flatcar-linux/coreos-overlay/pull/2136
