### ISSUE TITLE
The gettext package seems to have been removed by mistake

### ISSUE THREAD

**Issue by iaguis** [flatcar/Flatcar#849]
## Description

I was trying to use the `envsubst` tool on the latest Flatcar stable and it's not there.

## Impact

This breaks some of my automation.

## Environment and steps to reproduce

1. Boot Flatcar on any platform
2. Try to run `envsubst`
5. **Error**: `-bash: envsubst: command not found`

## Expected behavior

I expect the `envsubst` binary to be present.

## Additional information

It seems the gettext package was removed. See:

* Latest stable: https://stable.release.flatcar-linux.net/amd64-usr/3227.2.2/flatcar_production_image_packages.txt
    * Doesn't include gettext
* 3139.2.3 (from June 23rd): https://stable.release.flatcar-linux.net/amd64-usr/3139.2.3/flatcar_production_image_packages.txt
    * Includes gettext

**Comment by tormath1** [comment]
Thanks for raising this. It looks like the package is still in `::portage-stable` (https://github.com/flatcar-linux/portage-stable/tree/main/sys-devel/gettext).
I think one of the `coreos-base/coreos` dependencies pulling this package has been removed, so it's not anymore pulled in the OS. If we want to have it in Flatcar, we would need to add it explicitly in https://github.com/flatcar-linux/coreos-overlay/blob/main/coreos-base/coreos/coreos-0.0.1.ebuild

**Comment by dongsupark** [comment]
`sys-auth/realmd` 0.17.0-r2 changed the dependency on `sys-devel/gettext` from DEPEND to [BDEPEND](https://github.com/flatcar-linux/coreos-overlay/pull/1724/commits/4a06200e9d92dc8066425cfc18dd6b7c5aa99131). 

Looks like one of the relevant changes.

**Comment by tormath1** [comment]
Thanks @iaguis for the report. `gettext` (and `envsubst`) has been added back to the OS and should be available in the next batch of releases (including `stable`)!

**Comment by iaguis** [comment]
Awesome! Thanks a lot for the quick fix!
