### ISSUE TITLE
Use Butane in docs

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#852]
## Current situation

Flatcar Stable now uses Ignition v3 and the Butane transpiler has a Flatcar variant for it. The Flatcar docs however still use CLC.

## Impact

CLC is not maintained and has its shortcomings and traps. Also, it only generates a v2 Ignition config which has to be transpiled by ign-converter behind the scenes (that works and we fixed many bugs but it adds a layer of possible problems).

## Ideal future situation

The docs use Butane's Flatcar variant.
The CLC and ct docs section should stay around for reference as long as we have an LTS that only supports Ignition v2.

## Additional information

Ideally we would even have a transpiler action for each example to be able to get Ignition data from it

**Comment by tormath1** [comment]
Quick grep on the documentation (https://github.com/flatcar-linux/flatcar-docs/):
```
$ find docs -type f -exec grep -li "clc" {} +;
docs/container-runtimes/switching-to-unified-cgroups.md
docs/img/dev.jpg
docs/img/quay-robot-screen.png
docs/img/size.png
docs/installing/bare-metal/booting-with-ipxe.md
docs/installing/bare-metal/booting-with-pxe.md
docs/installing/bare-metal/installing-to-disk.md
docs/installing/cloud/digitalocean.md
docs/installing/cloud/azure.md
docs/installing/cloud/gcp.md
docs/installing/cloud/aws-ec2.md
docs/installing/cloud/equinix-metal.md
docs/installing/cloud/vmware.md
docs/installing/community-platforms/openstack.md
docs/installing/_index.md
docs/provisioning/cl-config/from-cloud-config.md
docs/provisioning/cl-config/_index.md
docs/provisioning/config-transpiler/_index.md
docs/provisioning/sysext/_index.md
docs/setup/customization/other-settings.md
docs/setup/releases/update-strategies.md
docs/setup/security/hardening-guide.md
```
and
```
$ find docs -type f -exec grep -li "yaml" {} +;
docs/container-runtimes/customizing-docker.md
docs/container-runtimes/getting-started-with-docker.md
docs/container-runtimes/registry-authentication.md
docs/container-runtimes/switching-to-unified-cgroups.md
docs/contribute/docs.md
docs/installing/bare-metal/booting-with-ipxe.md
docs/installing/bare-metal/booting-with-pxe.md
docs/installing/bare-metal/installing-to-disk.md
docs/installing/cloud/aws-ec2.md
docs/installing/cloud/using-google-cloud-launcher.md
docs/installing/cloud/azure.md
docs/installing/cloud/vmware.md
docs/installing/cloud/digitalocean.md
docs/installing/cloud/equinix-metal.md
docs/installing/cloud/gcp.md
docs/installing/cloud/hetzner.md
docs/installing/community-platforms/vultr.md
docs/installing/community-platforms/openstack.md
docs/installing/community-platforms/rackspace.md
docs/installing/vms/libvirt.md
docs/installing/_index.md
docs/provisioning/cl-config/examples.md
docs/provisioning/cl-config/from-cloud-config.md
docs/provisioning/cl-config/_index.md
docs/provisioning/config-transpiler/getting-started.md
docs/provisioning/config-transpiler/configuration.md
docs/provisioning/config-transpiler/_index.md
docs/provisioning/config-transpiler/dynamic-data.md
docs/provisioning/ignition/_index.md
docs/provisioning/ignition/specification.md
docs/provisioning/terraform/_index.md
docs/provisioning/sysext/_index.md
docs/setup/clusters/architectures.md
docs/setup/clusters/booting-on-ecs.md
docs/setup/clusters/discovery.md
docs/setup/customization/customize-etcd-unit.md
docs/setup/customization/network-config-with-networkd.md
docs/setup/customization/other-settings.md
docs/setup/customization/power-management.md
docs/setup/customization/ACPI.md
docs/setup/customization/adding-users.md
docs/setup/customization/configuring-date-and-timezone.md
docs/setup/customization/configuring-dns.md
docs/setup/debug/install-debugging-tools.md
docs/setup/debug/reading-the-system-log.md
docs/setup/releases/update-strategies.md
docs/setup/security/customizing-sshd.md
docs/setup/security/disabling-smt.md
docs/setup/security/fips.md
docs/setup/security/hardening-guide.md
docs/setup/storage/adding-swap.md
docs/setup/storage/iscsi.md
docs/setup/storage/mounting-storage.md
docs/setup/storage/raid.md
docs/setup/systemd/drop-in-units.md
docs/setup/systemd/environment-variables.md
docs/setup/systemd/timers.md
docs/setup/systemd/udev-rules.md
docs/_index.md
```

**Comment by ruuda** [comment]
Does this mean that https://github.com/flatcar/container-linux-config-transpiler is deprecated, and Butane is preferred? In addition to updating the docs, it may be helpful to add a note to the readme over there.

**Comment by till** [comment]
Along with suggesting butan, is there a list of what the major user-facing changes are? E.g., it seems that before there was a `networkd` entity, which is no longer and you have to use `files`.

I also find the "official" documentation of butan a bit hard to read (HTML list of possible attributes/objects/nested lists, etc.) as I literally had to scroll up and down to understand the level of indenting. I volunteer to send a PR with more samples if that's wanted. But let me know where you'd like to see that.

LBNL, saw there is an experimental version already. But what are the changes? And would it be okay to make suggestions? :D 

I am thinking:

```yaml
systemd:
  - name: foo
    contents: |
      [Bar]
```

vs.

```yaml
files:
  - path: /foo
     contents:
       inline: "bar"
```

Couldn't `systemd[*].contents` support what files does, or the other way around? To make them more similar. Also wondering if it would be possible to re-introduce `networkd` as a shorthand?

**Comment by ruuda** [comment]
Yeah, it would be nice to have some kind of update guide that explains how to move from CT to Butane, so far I haven’t found one. Differences that I did discover when updating:

* There is a new top-level key `variant`, which should be set to `flatcar`. There is also a new top-level key `version`.
* The `locksmith` section is no longer supported. Instead one can use the files section to write `/etc/flatcar/update.conf`.
* The `filesystem` key on `files` and `directories` has been removed.
* The `enable` key of `systemd.units` has been renamed to `enabled`.

**Comment by pothos** [comment]
The `ct` transpiler is still the way to go for Flatcar LTS.

More Butane examples would be great, yes, specially for a "migration guide".

**Comment by till** [comment]
Is it smart to tie Flatcar to Fedora? I mean, longer term. Just wondering what your thoughts are as they are leading development. Sounds like custom proposals won't make it as long as FCOS doesn't use something (e.g. locksmith, systemd-networkd).

**Comment by pothos** [comment]
Flatcar and FCOS have different variants in Butane, e.g., currently the Flatcar variant doesn't allow clevis because it's not supported

**Comment by pothos** [comment]
Differences were also discussed in https://github.com/flatcar/Flatcar/issues/968 and the last PR (:crossed_fingers:) is filed to complete the docs migration to Butane: https://github.com/flatcar/flatcar-docs/pull/299
