### ISSUE TITLE
Check Ignition Engine Version

### ISSUE THREAD

**Issue by alpana17** [flatcar/Flatcar#86]
I am using Flatcar AMI to launch instance.
How can I check ignition engine version and schema version supported

**Comment by pothos** [comment]
Hello,
good question. On https://www.flatcar-linux.org/releases/ you can find which Ignition release is in which channel. We have 0.34.0 everywhere now. You can see the supported specifications here: https://coreos.com/ignition/docs/0.34.0/index.html There you can find that 0.2.3 is the highest supported schema version for 0.34.0 but 0.2.4 available in experimental mode.
(For example, if you change the Ignition version in the selector on that web page to 0.35.0 you would see that 0.2.4 is supported officially there.)

P.S.: The overview of latest official AMIs is always here: https://docs.flatcar-linux.org/os/booting-on-ec2/

**Comment by alpana17** [comment]
I want to know Ignition engine and schema details for AMI version 2303

**Comment by pothos** [comment]
As said, we currently have Ignition 0.34.0 (https://coreos.com/ignition/docs/0.34.0/index.html) and the highest specification version you can use is v2.3.0, but v2.2.0, v2.1.0, and v2.0.0 are also available.

In case you want to use an AMI for an older Flatcar version then for example in Ignition 0.33.0 the same versions are available. Yet, as the instances will be updated directly anyway, I recommend that you use the current Stable AMIs which you can find on the given link (https://docs.flatcar-linux.org/os/booting-on-ec2/).

You can either use the Ignition JSON format or use the config transpiler (`cat cl-config.yaml | docker run --rm -i quay.io/coreos/ct:latest-dev > ignition.json`) to generate an Ignition config from a Container Linux Config (see https://docs.flatcar-linux.org/os/provisioning/ and https://docs.flatcar-linux.org/container-linux-config-transpiler/doc/overview/)

**Comment by pothos** [comment]
By the way, if you write the JSON by hand, I recommend you to validate it before you try to use it: https://coreos.com/validate/
