### ISSUE TITLE
ntpd service return not synchronised

### ISSUE THREAD

**Issue by alpana17** [flatcar/Flatcar#87]
![image](https://user-images.githubusercontent.com/8611615/79781933-e8d8b400-835b-11ea-9182-5110d04fae31.png)

Why systemctl status ntpd returns "Not synchronised"

**Comment by alpana17** [comment]
Also, not able to ping 169.254.169.123

**Comment by margamanterola** [comment]
Sounds like a network configuration issue. For ntp to work, the instance needs to be able to reach the ntp servers.

**Comment by alpana17** [comment]
yes,
but ping 169.254.169.123 is working for any other OS

**Comment by alpana17** [comment]
I have opened 123 UDP port in outbound.
What else do I need to make it work?

**Comment by pothos** [comment]
Did you disable `systemd-timesyncd.service`? You should not run both at the same time because they would fight over the clock.

**Comment by tormath1** [comment]
@alpana17 do you still facing this issue ? We also have some documentation about NTP here: https://www.flatcar.org/docs/latest/setup/customization/configuring-date-and-timezone/

As mentioned earlier, I think it's more a network configuration issue.

**Comment by tormath1** [comment]
@alpana17 hi, I'm going ahead and closing this issue - if you need further help on this topic, feel free to re-open the issue. Thanks!
