### ISSUE TITLE
[RFE] Publish Flatcar Linux Arm64 images to Azure

### ISSUE THREAD

**Issue by dghubble** [flatcar/Flatcar#872]
## Current situation

Flatcar Linux has alluded to arm64 images being available on Azure in #716 and https://twitter.com/flatcar/status/1580307641011576833

The [Flatcar Linux Azure docs](https://flatcar-linux.org/docs/latest/installing/cloud/azure/) don't mention arm64 offerings. Looking around, Kinvolk does have a `flatcar-container-linux-corevm` offering that is marked for `Arm64`:

```
az vm image list --all -p kinvolk --sku stable --architecture Arm64
[
  {
    "architecture": "Arm64",
    "offer": "flatcar-container-linux-corevm",
    "publisher": "kinvolk",
    "sku": "stable",
    "urn": "kinvolk:flatcar-container-linux-corevm:stable:3227.2.2",
    "version": "3227.2.2"
  }
]
```

However, its apparently not usable:

```
The Offer: 'flatcar-container-linux-corevm' cannot be purchased by subscription: 'REDACTED' as it is not to be sold in market: 'US'
``` 

I suppose what you folks mean by saying its supported is that the images are [released](https://flatcar-linux.org/releases) but I need to go through the manual upload / publish process myself?

## Impact

What's the deal here? Do you publish images for Azure Arm64? What are the recommended offerings and channels? Docs?

## Ideal future situation

Write some docs on where we can get your images.

**Comment by ahrkrak** [comment]
Please try: https://azuremarketplace.microsoft.com/de-de/marketplace/apps/kinvolk.flatcar-container-linux-corevm?tab=Overview

And let us know if this solves the issue.

**Comment by dghubble** [comment]
Can you show in the `az` CLI some of the Arm64 images that should be used? Which `offer`, `sku`, or `urn`? The marketplace marketing page doesn't seem to contain that info or link to it.

**Comment by jepio** [comment]
Hi @dghubble,
You're right, docs are missing, I apologize for that and we'll add them.

We do publish the images, and you should not need to upload/publish yourself. I think the likely source of your error is that you are still supplying plan information, though I don't really know why that wouldn't work :shrug:. We have finally found a way to reduce the burden on users and remove the need for separate plan info. We'll be looking at unifying this with amd64 image publishing which still use the old marketplace name.

To provision an arm64 instances the following steps are enough for me:
```
g=g$RANDOM
az group create -g $g -l eastus
az vm create -g $g -n vm01 --image kinvolk:flatcar-container-linux-corevm:beta:latest --size Standard_D2pls_v5
```

**Comment by dghubble** [comment]
Ok, I think I see the situation. So `flatcar-container-linux-corevm` is the intended Arm64 offering name.

* For Arm64, its important to **not** specify a plan otherwise you'll get the `is not to be sold in market: 'US'` error. 
* For x86, I **must** specify the `plan` and terms otherwise we get the `a Marketplace image requires Plan information in the request` error. And maybe in future you plan to reverse that.

It'd be great to see this stuff mentioned in official docs (at least that `flatcar-container-linux-corevm` is not just some errant debugging image). I don't think anyone would piece this together and have trust in it just on their own.

**Comment by jepio** [comment]
@dghubble better late than never: I've added a section to the docs documenting these offers: https://www.flatcar.org/docs/latest/installing/cloud/azure/#arm64
