### ISSUE TITLE
Document dependencies of flatcar-install script

### ISSUE THREAD

**Issue by invidian** [flatcar/Flatcar#88]
**Current situation**
One of the install method of flatcar is using `flatcar-install` script, which turns out depends on some binaries, which are not documented anywhere. Those binaries may not be available in all environments.

**Impact**
`flatcar-install` script may randomly fail when executed across different environments.

**Ideal future situation**
There should be a documentation of which binaries are used by the script.

**Implementation options**
Just a list of binaries (and possibly version requirements, if needed) in the documentation would be sufficient.

e.g. to run `flatcar-install` script from `alpine` Docker image, following packages needs to be installed (snippets in `Dockerfile` format):
```
FROM alpine

RUN apk add -U bash util-linux coreutils gnupg eudev
```

For Ubuntu, it is:
```
FROM ubuntu

RUN apt update && apt install -y udev gpg wget
```

**Comment by invidian** [comment]
NOTE: with https://github.com/flatcar-linux/init/pull/47/commits/637123672bbd9724e8416d679bebcdbf98353aa0, it now also require `btrfs-progs` on Ubuntu or `btrfs-progs-extra` on alpine.

**Comment by invidian** [comment]
BTW, this is sort of addressed by https://github.com/flatcar-linux/init/pull/50 ?

**Comment by krnowak** [comment]
Yeah, there are no version checks. I suppose that the documentation could point to the `toolset` variable in the script for the list of required tools.

**Comment by tormath1** [comment]
Hi @invidian, 

Requirements for `flatcar-install` have been documented by a Flatcar's contributor in here: https://github.com/flatcar-linux/flatcar-docs/pull/180: https://www.flatcar.org/docs/latest/installing/bare-metal/installing-to-disk/#required-dependencies

Thanks for opening this :)
