### ISSUE TITLE
AWS AMI catalog does not show later version of Flatcar LTS in its catalog page

### ISSUE THREAD

**Issue by kiich** [flatcar/Flatcar#887]
## Description

in AWS AMI catalog page, when you look for Flatcar LTS 2605 version, the latest as of November 2022 that show is 2605.27.1 which is from April 2022.
However on Flatcar's release page, we can see later version such as 2605.32.1 as of November 2022 at https://flatcar-linux.org/releases#release-2605.32.1

This prevents users from finding the right AMI id for these versions in AWS thus not able to upgrade to latest LTS 2605 version.

Could we please get information on whether these releases mentioned in flatcar releases page is coming to AWS or if 2605.27.1 AMI is the latest and possibly last 2605 version?

This is a key information for us as we can NOT go to 3033 which has deprecated use of rkt which, unfortunately, we still use.

**Comment by jepio** [comment]
HI @kiich,

This seems to be some kind of mistake, we'll need to check the AWS marketplace (@sayanchowdhury). `2605.32.1` is definitely available on AWS, for the time being I recommend looking up the AMI ID in the regions where you deploy and using that directly:
```
aws ec2 describe-images --owners 075585003325 --filters Name=tag:Version,Values=2605.32.1
```

**Comment by tormath1** [comment]
The AWS Marketplace was not supporting correctly the upload of two versions at the same time of the AMIs on the same offer (LTS-2022 and LTS-2021).
I'll have a look to add the missing AMIs to the marketplace then. :)

> This is a key information for us as we can NOT go to 3033 which has deprecated use of rkt which, unfortunately, we still use.

@kiich please also keep in mind that the LTS you're refering is about to be end-of-life, as mentioned in this release note: https://www.flatcar.org/releases#release-2605.31.1

**Comment by kiich** [comment]
> HI @kiich,
> 
> This seems to be some kind of mistake, we'll need to check the AWS marketplace (@sayanchowdhury). `2605.32.1` is definitely available on AWS, for the time being I recommend looking up the AMI ID in the regions where you deploy and using that directly:
> 
> ```
> aws ec2 describe-images --owners 075585003325 --filters Name=tag:Version,Values=2605.32.1
> ```

Thanks for this info @jepio - this cleared it up for me! The issue was, we were using owner ID `679593333241` and filter on the version - which brings me to next question... Are these 2 owners both `Flatcar`/`Kinvolk`

Also to add that the latest I could find from that owner was 2605.31.1 for HVM with no tags - is that correct?

**Comment by kiich** [comment]
> 

That's great to hear @tormath1 thank you for looking into the AMI catalog issue!
Your last statement made me think... Does this mean Flatcar release `2605.*` is going to be stopped as well? (Apologies, i am not up to date with LTS 2021/LTS 2022 channel differences)

If so, this is kind of show-stopper for us as we are heavily reliant on use of `rkt` - which from your chanelog indicates is deprecated in `3033` ?
(just to clarify, we are all for going to 3033 but would need to invest in some time to see how we can swap the use of `rkt` with `docker` and appreciate that `rkt` has been deprecated for quite some time!)

**Comment by pothos** [comment]
Yes, `rkt` is not shipped in Flatcar anymore, as alternative there is Docker/containerd and `systemd-nspawn`.
You can continue to use `rkt` if you copy it to, e.g., `/opt/bin` and the needed units directly to `/etc/`.
That said, if you want to migrate, here are two examples that use `systemd-nspawn`, once by downloading an OCI image and either extracting it with Docker or mounting it (with `ctr`), and once with using a local image:
https://github.com/flatcar/toolbox/blob/flatcar-master/toolbox
https://github.com/flatcar/coreos-overlay/blob/main/coreos-base/oem-gce/files/units/oem-gce.service

**Comment by kiich** [comment]
Thank you @pothos 
For this
>You can continue to use rkt if you copy it to, e.g., /opt/bin and the needed units directly to /etc/

Would you happen have example on how to do this in Flatcar? Is it something you build into the image?

thanks for the links on `systemd-nspaw` - i will take a look and see the work involved there. Appreciate your help!

**Comment by tormath1** [comment]
I'm going ahead and closing this issue. @kiich feel free to reach out on matrix or in the Kubernetes Slack if you need some help regarding the migration steps.
