### ISSUE TITLE
Run automatic tests for BPF before each Flatcar release

### ISSUE THREAD

**Issue by alban** [flatcar/Flatcar#89]
**Current situation**
As far as I know, we don't have tests for BPF integrated in the test/release pipeline.

**Impact**
Software using BPF might break if kernel bugs are introduced in new releases and it can more easily go unnoticed without automatic testing. As an example, [Inspektor Gadget](https://github.com/kinvolk/inspektor-gadget) uses various BPF tools (from traceloop, tcptracer-bpf, BCC). We've had an issue with the BCC opensnoop tool in a Flatcar Edge release (see https://github.com/iovisor/bcc/pull/2726).

**Ideal future situation**
Some basic tests of common BPF tools should be automatically executed before each release. Sometime, it can break because of a kernel bug, or because of a bug in the tool. It should be assessed to decide whether the release can go.

**Implementation options**
Some existing tests could be reused:
- [BCC tests](https://github.com/iovisor/bcc/blob/master/.github/workflows/bcc-test.yml). I would like additional tests for opensnoop and execsnoop because the previous regression bug was in those tools.
- [tcptracer-bpf test](https://github.com/weaveworks/tcptracer-bpf/blob/master/tests/test.sh)
- [traceloop manual test with systemd-run](https://github.com/kinvolk/traceloop#on-the-command-line)

**Comment by t-lo** [comment]
#91 alone is a good reason for adding BPF tests.

**Comment by tormath1** [comment]
Hi @alban,

Some tests have been added and more to come but the initial issue is solved:
>  As far as I know, we don't have tests for BPF integrated in the test/release pipeline.

We currently have:
```
bpf.execsnoop
bpf.local-gadget (dns gadget)
```

Thanks for submitting the issue :)
