### ISSUE TITLE
Use HTML formatting instead of markdown for RSS feed

### ISSUE THREAD

**Issue by invidian** [flatcar/Flatcar#896]
## Description

As a follow up to #210, right now this is how the feed looks like in Feedly:
![Selection_636](https://user-images.githubusercontent.com/16539896/201076576-ce0f30f7-26cf-4fd6-9e82-4ee7514d2209.png)

## Impact

RSS feed is hard to read by improper formatting.

## Expected behavior

RSS feeds links to be clickable and ideally text would be properly formatted.

**Comment by tormath1** [comment]
I'd be curious to see how HTML formatting would be rendered in in-terminal readers (like [gorss](https://github.com/Lallassu/gorss)) :thinking:

**Comment by sayanchowdhury** [comment]
This issue is duplicate of #211. Let's move the discussion there.

**Comment by invidian** [comment]
Oops, closing then, haha.
