### ISSUE TITLE
Kernel Panic since 3227.2.3

### ISSUE THREAD

**Issue by xcompass** [flatcar/Flatcar#898]
## Description

Since upgrade to 3227.2.3 (including 3227.2.4 as well), the VM starts to reboot itself when running with one particular container with NFS mounts and the container is under load. If there is no traffic to the container, VM won't reboot. There is no error/warning in either journald log or container log. But in VM console, there is a kernel panic message and it seems related to NFS. (Due to no support for pstore, I was only capture the panic with screen recorder for these two frames:
<img width="728" alt="Screen Shot 2022-11-15 at 2 04 39 PM" src="https://user-images.githubusercontent.com/465548/202058968-a1467c18-e761-478e-8a0f-edc63c84c484.png">
<img width="730" alt="Screen Shot 2022-11-15 at 2 04 49 PM" src="https://user-images.githubusercontent.com/465548/202058957-2f47eaa2-a036-453b-b16c-516a2e6e4560.png">

## Impact

VM reboots due to kernel panic

## Environment and steps to reproduce

1. **Set-up**: Flatcar 3227.2.3 with vmware (no sure if it happens in other environment as well). . Generate some traffic to the container. 
2. **Task**: N/A
3. **Action(s)**:
  a. A docker container with NFS mount using the following format: `--mount "src=webwork_courses,dst=/opt/webwork/courses,volume-opt=device=:/webwork/courses,\"volume-opt=o=addr=nfs.server.ca,vers=4,soft\",type=volume,volume-driver=local,volume-opt=type=nfs"`
  b. Generate some traffic to the container. May need to access files on NFS mount.
  c. After sometime (between 5 to 30 mins), it should trigger kernel panic.
4. **Error**: See above screenshot

## Expected behavior

No kernel panic

## Additional information

Was able to reproduce it with the beta channel image 3346.1.0, which has the same kernel version as stable 3227.2.3. Also it seems the next beta version 3374.1.0 fixed the issue.

**Comment by jepio** [comment]
Thanks for testing beta, stable will get the updated kernel this week. There was an NFS kernel panic issue (same?) reported yesterday as well: #897.

**Comment by xcompass** [comment]
Thanks! Will test out once the update is landed on stable.

**Comment by jepio** [comment]
Stable 3374.2.0 has been released, would you like to test again @xcompass ?

**Comment by xcompass** [comment]
Thanks @jepio. Yes, I've tested since the release. No reboot so far. I think it is fixed. Closing this now!
