### ISSUE TITLE
`chage` command not printing time of last password change

### ISSUE THREAD

**Issue by snikhil1998** [flatcar/Flatcar#904]
## Description

The command `chage -l <username>` command is printing the time of last password change as "%b %d, %Y" instead of actual time like "November 29, 2022"

## Impact

Password expiry check is failing when testing our product.

## Environment and steps to reproduce

1. **Set-up**: Flatcar
2. **Task**: Standard testing

## Expected behavior

Time of last password change should give the actual time like "November 29, 2022" instead of "%b %d, %Y".

## Additional information

This issue was fixed in the next release of `shadow`, i.e., 4.13. Please backport the fix.

**Comment by jepio** [comment]
The fix is this: https://github.com/shadow-maint/shadow/commit/e503fd574b7dbf6b21b1168e20938f0922807916, shadow-4.13 is not marked stable in gentoo yet.

**Comment by skshandilya** [comment]
this seems to be a concern because the software that checks expiry using chage is going to fail. what is the approach to take this forward, we are 2 minor releases out and the change is very trivial?

**Comment by jepio** [comment]
Hey @skshandilya, a ping is good. Shadow 4.13 was stabilized in Gentoo in the last days of 2022, and it's one of the packages that has Flatcar-specific customizations so we need to manually bump it. I've prepared a PR and will test that it fixes this issue.
