### ISSUE TITLE
Documentation - systemd enable

### ISSUE THREAD

**Issue by kallisti5** [flatcar/Flatcar#913]
## Description

Documentation mentions "enable: true" for systemd units...

https://www.flatcar.org/docs/latest/setup/storage/mounting-storage/

However:

```
warning at $.systemd.units.0.enable, line 22 col 7: Unused key enable
warning at $.systemd.units.1.enable, line 33 col 7: Unused key enable
```

## Impact

Warnings

**Comment by pothos** [comment]
With Butane it should be `enabled` https://www.flatcar.org/docs/latest/provisioning/config-transpiler/configuration/

The docs are now in a half-transitioned state of using CLC and Butane and we need to clean this up more.
