### ISSUE TITLE
Release Flatcar Container Linux 3374.2.1 not available on Azure Marketplace

### ISSUE THREAD

**Issue by obourdon** [flatcar/Flatcar#915]
Subject says it all

**Comment by tormath1** [comment]
Hello, we are facing some issues with Azure publishing. More information: https://github.com/flatcar/Flatcar/issues/910#issuecomment-1354746028

**Comment by obourdon** [comment]
@tormath1 Many thanks for the prompt answer Mathieu

**Comment by sayanchowdhury** [comment]
The releases are available on the Marketplace now. Closing this issue. Feel free to reopen if you still face issue.
