### ISSUE TITLE
CoreOS -> Flatcar migration docs misses /var/lib, /run/metadata migration

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#92]
**Description**

The documentation on migrating servers on CoreOS Container Linux to Flatcar Container Linux does not discuss migrating cloud-init data from `/var/lib/coreos-install` -> `flatcar-install` and migrating env metadata from `/run/metadata/coreos` to `/run/metadata/flatcar`.

**Impact**

Users may experience issues when migrating to Flatcar which requires them to invest effort into root causing and fixing.

**Environment and steps to reproduce**

- For `/var/lib/coreos-install` see https://twitter.com/zekjur/status/1253043324002480128
- For `/run/metadata/coreos` see https://medium.com/@swade1987/upgrading-to-flatcar-linux-746751e89ab4

**Expected behaviour**

Migration to Flatcar Container Linux happens without issues as Flatcar is a drop-in replacement.

**Comment by pothos** [comment]
For afterburn we already create the symlink automatically:

```
coreos-base/afterburn/files/coreos-metadata.service:
[…]
ExecStartPost=ln -fs /run/metadata/flatcar /run/metadata/coreos
```

**Comment by pothos** [comment]
The post about `/run/metadata/coreos` is talking about the situation in December, but the symlink just got added in January.

**Comment by pothos** [comment]
PR in https://github.com/flatcar-linux/docs/pull/74
