### ISSUE TITLE
Magnum support

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#922]
- [x] WIP PR: https://github.com/vexxhost/magnum-cluster-api/pull/44

**Comment by stefan-chivu** [comment]
Related PR: https://github.com/vexxhost/magnum-cluster-api/pull/225

**Comment by johananl** [comment]
Upstream PR is merged 🎉 Thank you @stefan-chivu!
I haven't personally tested. Should we mark this as closed @t-lo or is there anything left to do on our end?

**Comment by tormath1** [comment]
Upstream PR is merged, let's close this. Thanks again for the implementation @stefan-chivu !
