### ISSUE TITLE
Update strace package to 5.6 in Flatcar

### ISSUE THREAD

**Issue by alban** [flatcar/Flatcar#93]
**Current situation**

```
$ strace -V
strace -- version 4.9
```

**Impact**

Using strace with programs that use new syscalls that were introduced in Linux 5.2 (fsopen() etc.) is impossible:

```
syscall_430(0x4020ca, 0x1, 0x7f1d8bca8f47, 0, 0x7f1d8bd78500, 0x100000000) = 0x5
syscall_431(0x6, 0, 0x402112, 0, 0, 0x655e2820) = 0
```

**Ideal future situation**

Update strace package in Flatcar.

**Comment by dongsupark** [comment]
We should definitely update strace.
Question is which versions do we need.
As far as I understand from the [strace release notes](https://github.com/strace/strace/releases), each strace release is meant to be compatible with each major kernel release.
For example, strace [5.4](https://github.com/strace/strace/releases/tag/v5.4) is compatible with Kernel 5.4.

So I suppose, we need strace 5.6 for Edge, and strace 5.4 for Stable, Beta, and Alpha. Right?

**Comment by alban** [comment]
strace [release 5.6 (2020-04-07)](https://github.com/strace/strace/blob/7062c7324cc0b09809e72d7bc51a0e49b81fbf3e/NEWS#L13) should work with the kernel versions we have in Flatcar in all channels (>= 4.19). Even the restrictions below are for architectures that are not the ones supported by Flatcar:
```
* Portability
  * On hppa, linux kernel >= 4.7 is required.
    On sh and sh64, linux kernel >= 2.6.28 is required.
    Older versions without a decent PTRACE_GETREGS support will not work.
```

So I think it's better to pick the last version of strace for both the Edge channel and the Alpha->Beta->Stable channels.

**Comment by dongsupark** [comment]
Thanks! I am going to update to strace 5.6 for all channels.

**Comment by dongsupark** [comment]
Created PRs
- Alpha: https://github.com/flatcar-linux/coreos-overlay/pull/327
- Edge: https://github.com/flatcar-linux/coreos-overlay/pull/328

**Comment by dongsupark** [comment]
All channels including Stable have strace 5.6.
Closing.
