### ISSUE TITLE
Update Stable kernel to 5.4 (LTS kernel).

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#94]
**Description**
Update Stable kernel to 5.4 (LTS kernel).

**Impact**
Currently, we ship the LTS kernel 4.19 in Alpha, Beta, and Stable. This kernel lacks desired features only available in newer releases. Updating to the LTS kernel release 5.4 - which has seen wide adoption across Linux distros already - will make these features available to our Flatcar Container Linux users.

**Comment by dongsupark** [comment]
Alpha already has Kernel 5.4 since 2492.0.0.
For Beta, the PR https://github.com/flatcar-linux/coreos-overlay/pull/362 was merged.

**Comment by martin31821** [comment]
Any chance we see a beta release with the 5.4 LTS soon?

**Comment by margamanterola** [comment]
Funny that you would ask this today :) The beta release 2513.2.0 is in the process of going out and includes kernel 5.4. You should see it in your servers in the next few hours. Cheers.

**Comment by sayanchowdhury** [comment]
The Beta release 2513.2.0 is out, with the 5.4 kernel: https://www.flatcar-linux.org/releases/#release-2513.2.0

**Comment by hakman** [comment]
Big difference in stability when running Kubernetes e2e tests. Looking forward to see the changes in the stable channel.
https://testgrid.k8s.io/kops-distros#kops-aws-distro-flatcar
👍

**Comment by dongsupark** [comment]
Now all channels have Kernel 5.4 or newer.
Can we close?
