### ISSUE TITLE
CNCF TAG-Runtime Discussion/Presentation

### ISSUE THREAD

**Issue by nikhita** [flatcar/Flatcar#950]
Hi Flatcar maintainers,

I'm part of [CNCF TAG Runtime](https://github.com/cncf/tag-runtime). I think it would be great for you to present/discuss Flatcar at one of our meetings, especially also since you've applied for Incubation (https://github.com/cncf/toc/pull/991).

For example, it would be great to learn things like the roadmap, tech, community and the general overview of the project. The last time Flatcar was presented in TAG Runtime was in [September 2020](https://www.youtube.com/watch?v=FPH6LPxJ6PA&feature=youtu.be&t=2714). It would also be good to know how the project has changed since then.

Let me know if this is something you'd be interested in doing. Additionally, would 2nd February work for you to present this?

If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) or reach out to us in the [#tag-runtime](https://cloud-native.slack.com/messages/tag-runtime) channel on the CNCF slack.

Thanks!

cc @raravena80

**Comment by ahrkrak** [comment]
Hi Nikhita, very happy to do this (+ @miao0miao @t-lo)! However, I'll be traveling on Feb 2. We can schedule for the next meeting (Feb 16) if you are OK to squeeze two project updates into one meeting, otherwise Mar 2 would work too. Let us know!

**Comment by nikhita** [comment]
@ahrkrak great to hear! We typically don't do two projects in one meeting because each project usually ends up taking an hour.

We can also do a meeting on Feb 9th, but if you prefer March 2nd, that would work too. Let us know what you prefer!

**Comment by nikhita** [comment]
@ahrkrak 👋  Hi Andrew, just wanted to follow up to check if you'd like to present on Feb 9th or March 2nd.

**Comment by ahrkrak** [comment]
Hi Nikhita, sorry I didn't see the note, I had github notifications off...
I'd really like our engineering lead @t-lo to be involved, and he has been off work recovering from an accident, and we're not expecting him back until mid-February, so let's schedule for March 2.
Thanks and apologies again for the slow response. I need to re-enable my notifications!

**Comment by nikhita** [comment]
@ahrkrak no problem and thanks for confirming! I've added Flatcar to the March 2nd [agenda](https://docs.google.com/document/d/1k7VNetgbuDNyIs_87GLQRH2W5SLgjgOhB6pDyv89MYk/edit#) 👍

**Comment by nikhita** [comment]
> he has been off work recovering from an accident, and we're not expecting him back until mid-February

@t-lo that sounds rough, hope you feel better soon! 🙏

**Comment by ahrkrak** [comment]
Thanks @nikhita for the invitation. I updated the [meeting notes](https://docs.google.com/document/d/1k7VNetgbuDNyIs_87GLQRH2W5SLgjgOhB6pDyv89MYk/edit?usp=sharing) with a link to the [slides](https://drive.google.com/file/d/1h1kPbgHXOSBE_sk9NWDayTmTpn_2oaTK/view?usp=sharing).
