### ISSUE TITLE
crictl version outdated

### ISSUE THREAD

**Issue by chg-blau** [flatcar/Flatcar#951]
## Description

Flatcar and the installed crictl binary is not compatible with cri-o v1.26

## Impact

cri-o v1.26 can't be managed with the default crictl binary installed in /usr/bin/crictl

```
node1 ~ # crictl image
FATA[0000] listing images: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService
```

## Environment and steps to reproduce

```
node1 ~ # cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=3374.2.2
VERSION_ID=3374.2.2
BUILD_ID=2023-01-11-0143
SYSEXT_LEVEL=1.0
PRETTY_NAME="Flatcar Container Linux by Kinvolk 3374.2.2 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar.org/"
BUG_REPORT_URL="https://issues.flatcar.org"
FLATCAR_BOARD="amd64-usr"
CPE_NAME="cpe:2.3:o:flatcar-linux:flatcar_linux:3374.2.2:*:*:*:*:*:*:*"
```
```
node1 ~ # crictl -v
crictl version 1.19.0
node1 ~ #
```
```
node1 ~ # which crictl
/usr/bin/crictl
```
```
node1 ~ # crio -v
crio version 1.26.1
Version:        1.26.1
GitCommit:      69945ab622a70ab01f4b0df10b107bc48e38dc9e
GitCommitDate:  2023-01-10T21:20:34Z
GitTreeState:   dirty
BuildDate:      1980-01-01T00:00:00Z
GoVersion:      go1.19.4
Compiler:       gc
Platform:       linux/amd64
Linkmode:       static
BuildTags:
  static
  netgo
  osusergo
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies:
```

## Expected behavior

crictl supports the up2date cri-o version

## Additional information

see also:
https://github.com/cri-o/cri-o/issues/6554
https://github.com/kubernetes-sigs/cri-tools/issues/1069

**Comment by jepio** [comment]
I think we could update cri-tools to v1.24 because that version has some tweaks to support both v1 and v1alpha2 cri APIs.

**Comment by dongsupark** [comment]
+1 for updating to v1.24.

FYI, in the past we did not update cri-tools to 1.20 or newer because of its bigger binary size.
However, as we currently have some free space in /usr, size increase of ~10MiB would not be that big issue.
