### ISSUE TITLE
Production AMI JSON feeds are missing

### ISSUE THREAD

**Issue by adamnovak** [flatcar/Flatcar#962]
## Description

There used to be a file at https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_ami_all.json that lists the Flatcar-uploaded AMI IDs of Flatcar releases in AWS. Since #959 got patched up, this file hasn't existed. The AMI IDs are also not in the docs at https://www.flatcar.org/docs/latest/installing/cloud/aws-ec2/#choosing-a-channel

## Impact

This breaks all current releases of our [DataBiosphere/toil](https://github.com/DataBiosphere/toil/) project, which access the JSON feeds to deploy Flatcar-based clusters automatically on AWS.

## Environment and steps to reproduce

1. Go to https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_ami_all.json
2. Get a 404 and no content

## Expected behavior

We should get an actual JSON document, like the one at https://beta.release.flatcar-linux.net/amd64-usr/current/flatcar_production_ami_all.json but listing more regions.

## Additional information

I also haven't been able to find through other sources what the AMI IDs that *should* be in the file actually are. This makes it hard to override our automatic fetch code with the right AMI IDs, because we don't have them.

**Comment by pothos** [comment]
Thanks for the report, the files are correct for LTS but broken/missing for the other channels: https://lts.release.flatcar-linux.net/amd64-usr/current/flatcar_production_ami_all.json

**Comment by pothos** [comment]
We had to fix an issue with AWS publishing but then forget to that we also had to sync the new AMI files over. Should be fixed now, thanks again for reaching out.
