### ISSUE TITLE
New Package Request: pigz

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#965]
**Package name and purpose**
The parallel gzip implementation is useful to speed up the decompression time spent for large container image imports/exports.

- Package upstream repo: https://github.com/madler/pigz
- Gentoo ebuild: https://packages.gentoo.org/packages/app-arch/pigz

**Impact of adding this package to the Flatcar OS image**

The package improves on the following core values:
  - [ ] Secure by default
  - [ ] Always up to date
  - [x] Improve container experience
  - [x] Operate at scale / automation / telemetry

The package will increase the image size by: [estimated] 128 KB

How might this package increase the attack surface:
- not really because pigz is well maintained

**Benefits of adding this package**
The speedup is quite large and we make use of pigz in the Flatcar build pipeline to import huge Docker images faster, currently we do this by building and pulling a custom Docker image that provides pigz but that means we rely on an external container registry to be reachable which is sometimes not the case (at the very moment for us this is due to downtime but I could also imagine that others have constrains like not wanting to pull external binaries for supply chain security)

**Additional information**

**Comment by krnowak** [comment]
Just to be sure, this issue is about making pigz a part of production image, right? Because we already have pigz in SDK.

**Comment by pothos** [comment]
Yes

**Comment by krnowak** [comment]
We also have an option of making pigz a default implementation of gzip. Basically pigz package installs `/usr/bin/pigz`, gzip package installs `/usr/bin/gzip-reference` and `app-alternatives/gzip` decides which one of them gets picked for being a target of the `/usr/bin/gzip` symlink. Do we want to make `/usr/bin/gzip` a symlink to pigz?

**Comment by krnowak** [comment]
Also, if we want pigz to be available through `/usr/bin/gzip` symlink, we could consider dropping the gzip package from production image. Although this sounds a bit too adventurous. :)

**Comment by pothos** [comment]
I would first say no to be on the safe side

**Comment by krnowak** [comment]
PR: https://github.com/flatcar/coreos-overlay/pull/2504

**Comment by krnowak** [comment]
Will be available in the next alpha release.
