### ISSUE TITLE
Butane vs ct

### ISSUE THREAD

**Issue by nhi-vanye** [flatcar/Flatcar#968]
## Description

The documentation seems ambiguous on which to use.

It seems that butane is the future, but it also seems to be missing support for some documented container config objects (`networkd`)

If the answer is that butane is the long term approach, but you need to use systemd units or write_files today. That's okay, just tell tell me.

## Impact

I've been using butane until now, but now want to support static IP addresses, so need to decide whether to switch transpilers

## Environment and steps to reproduce

1. Add a `networkd` block into an otherwise valid yaml file.
2. run butane

```warning at $.networkd. line X col 1. Unused key networkd.```

**Comment by pothos** [comment]
Yes, this the switch to Butane is half-done and needs the be finished…

The networkd section isn't supported by Butane, we could specify it in the Flatcar variant, thought. For now you can create them  as `files:` with the path `/etc/systemd/network/myunit.(network|link|netdev)`

**Comment by nhi-vanye** [comment]
Perfect, thanks for the quick response.

**Comment by pothos** [comment]
Besides fixing this networkd difference in the examples we also have to migrate the `etcd:`/`flannel:`/`docker:`/`update:`/`locksmith:` magic sections to the Butane equivalent of the resulting ct-transpiled Ignition.
Edit: it's also `enabled:` now instead of `enable:` https://github.com/flatcar/Flatcar/issues/913 and the `filesystem: root` is maybe also not used anymore

**Comment by pothos** [comment]
One more thing to look out for is that `overwrite` for files is not true by default

**Comment by pothos** [comment]
Final PR: https://github.com/flatcar/flatcar-docs/pull/299

**Comment by pothos** [comment]
Actually it would be nice to also add migration docs based on the comments above and in https://github.com/flatcar/Flatcar/issues/852.
