### ISSUE TITLE
Ship Beta, Stable images for ARM

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#97]
**Description**
Ship Beta, Stable images for the ARM64 architecture (QEmu UEFI, AWS, and Packet platforms).

**Impact**
Currently, ARM64 support is still in the Alpha phase. This prevents using Flatcar Container Linux on ARM servers in production. Shipping Beta and Stable images would remove this impediment.

Tracking issue for release test breakage: https://github.com/kinvolk/Flatcar/issues/474

**Comment by shift** [comment]
Does this mandate a requirement for uBoot with UEFI support for booting? As the original CoreOS required this for rkt signed images to run correctly (I may not have that correct but I do remember trying to remove it to get it running on ARM64 machines for a dev cluster).

**Comment by pothos** [comment]
The requirement is to run somehow run GRUB. This works quite well with the UEFI support that many machines have. The main blockers we encounter are missing kernel config settings for various boards and some system service failures.

**Comment by shift** [comment]
I've managed to get Raspberry Pi 4's to iPXE boot flatcar via UEFI, no GRUB involded. And submitted a kernel config change to the overlay to enable the BCM7XXX PHY to get the NIC working. My guess would be the ARM64 initramfs will need as much set as modules as possible to support the widest range of boards, unless you want to focus specifically on only a few. Then there needs to be an easier option to build your own kernel and initramfs for different hardware, which is currently a bit of a chore.

**Comment by vbatts** [comment]
@shift nice! I was recently looking at building https://github.com/tianocore/edk2-platforms/tree/master/Platform/RaspberryPi/ for testing the UEFI bootloader approach. Do you have a write-up on how you're doing this?

**Comment by shift** [comment]
@vbatts I've created a quick gist here outlining what was done, let me know if you need more details https://gist.github.com/shift/98f43d98ce5e47e374fa46bf67b6a3b1

**Comment by scottmalkie** [comment]
Hi @sayanchowdhury - Is there anything y'all need to get arm64 images working for the beta and stable channels? What is the remaining work to be done here? How can we help?

**Comment by pothos** [comment]
The remaining things are updating Polkit/spidermonkey (there is a PR for that), including SELinux libraries in the image, and tweaking the kernel config to support more targets.

**Comment by scottmalkie** [comment]
@pothos Awesome! Thank you so much. We'll take a look.

**Comment by t-lo** [comment]
Thanks for reaching out @scottmalkie  - as @pothos mentioned there are a number items to address which currently cause some of our release tests to fail. While our test suite is reasonably complex, it would actually be a good place to get started with ARM64 work at this time.

We'll have a spotlight on release testing / the release process in our upcoming community meeting (tentatively planned for Tuesday next week; announcements will go out later this week) - that would be a good opportunity to engage with the team on what's failing and on the progress made / work left to do for ARM64 Stable support.

**Comment by scottmalkie** [comment]
Fantastic - thank you so much @t-lo and @pothos - I'll definitely attend the meeting next week. Eager to assist however possible. Thanks again!

**Comment by vielmetti** [comment]
Looking forward to hearing more on this at the community meeting.

**Comment by der-eismann** [comment]
For anyone curious like me, that doesn't have the time to watch the community meeting: Last blocker was resolved, current timeline is end of October/November for the Beta and Stable release in December, if nothing unforeseen happens :partying_face:

**Comment by tormath1** [comment]
I think we can close this issue now. ARM64 has landed in stable by the end of 2021 (https://www.flatcar.org/releases/#release-3033.2.0).

Thanks everyone involved in this effort :partying_face:
