### ISSUE TITLE
Ignition not being applied on qemu vm

### ISSUE THREAD

**Issue by der-ali** [flatcar/Flatcar#972]
## Description
I created the following ignition config with ct
```
cat config.yaml | podman run --rm -i ghcr.io/flatcar/ct:latest | jq > config.ign
```
```
{
  "ignition": {
    "config": {},
    "security": {
      "tls": {}
    },
    "timeouts": {},
    "version": "2.3.0"
  },
  "networkd": {},
  "passwd": {
    "users": [
      {
        "name": "myuser",
        "passwordHash": "$1$khzAkSQB$HdrGKwZGjIFvsRJuUR3oT0",
        "sshAuthorizedKeys": [
          "key1"
        ]
      }
    ]
  },
  "storage": {
    "files": [
      {
        "filesystem": "root",
        "group": {
          "id": 501
        },
        "path": "/opt/foo",
        "user": {
          "id": 500
        },
        "contents": {
          "source": "data:,Hello%2C%20world!",
          "verification": {}
        },
        "mode": 420
      }
    ]
  },
  "systemd": {}
}
```
and executed the qemu wrapper:
```
/flatcar_production_qemu.sh -i config.ign -- -nographic
```
When the operating system boots i am neither able to find the foo file under /opt/foo or the user "myuser".

I went through the steps mentioned in the [documentation](https://www.flatcar.org/docs/latest/installing/vms/qemu/)

Am i missing something?

**Comment by jepio** [comment]
Hi @der-ali,

It works when I try it. Could you answer the following questions:

What platform are you trying this on?

Are you re-using the VM image multiple times? Ignition only runs on the first boot of a VM/guest image. So if you are experimenting with ignition, you need to use a fresh VM image each time. Personally, I preserve the compressed version of the guest image when I play with Flatcar: `lbunzip2 -kvf flatcar_production_qemu_image.img.bz2` (`-k` for keep).

**Comment by der-ali** [comment]
Hi @jepio ,
indeed i was re-using the VM image. Thanks for the tip to preserve the compressed image.
I am trying on Fedora 37.
Wish you a nice day man!

**Comment by tormath1** [comment]
Hello @der-ali, as a side note, we now recommend using Ignition v3 for Flatcar provisioning and it can be generated with Butane. We're in the process of moving the documentation to use v3 (https://www.flatcar.org/docs/latest/provisioning/config-transpiler/) so let us know if you found this configuration example from our documentation. :)

**Comment by der-ali** [comment]
Hallo @tormath1,
thanks i tried it out. Works pretty well :) 
The [getting started](https://www.flatcar.org/docs/latest/provisioning/config-transpiler/getting-started/) section is still using Ignition v2.
