### ISSUE TITLE
Raspberry pi not reachable after a few minutes / reboot

### ISSUE THREAD

**Issue by darox** [flatcar/Flatcar#975]
## Description

I have installed flatcar to a Raspberry PI CM4 according to https://www.flatcar.org/docs/latest/installing/bare-metal/raspberry-pi/. The machine is reachable for ca. 2 minutes, but then it's not, and after 10 minutes, it reboots automatically and then the same procedure again. 

## Impact

Machine not usable. 

## Environment and steps to reproduce

Setup according to https://www.flatcar.org/docs/latest/installing/bare-metal/raspberry-pi/

## Expected behavior

The machine is continuously reachable, and ssh login works. 

## Additional information
-

**Comment by pothos** [comment]
Hi, can you provide us with logs from the journal? `sudo journalctl --no-pager` is maybe a bit huge but would have everything, `sudo journalctl -u update-engine` would be good to know if it was a update with a rollback reboot.
Also, please show `df -h` output to see if `/boot` is filled (Maybe the Beta or Alpha release helps in case of size problems).

**Comment by darox** [comment]
I need to figure out how I can log in, because SSH isn't working at all. So, the console is the only option.

**Comment by darox** [comment]
That's the layout as seen by raspi-os
```
nvme0n1      259:0    0 232.9G  0 disk 
├─nvme0n1p1  259:1    0   128M  0 part 
├─nvme0n1p2  259:2    0     2M  0 part 
├─nvme0n1p3  259:3    0     1G  0 part 
├─nvme0n1p4  259:4    0     1G  0 part 
├─nvme0n1p6  259:5    0   128M  0 part 
├─nvme0n1p7  259:6    0    64M  0 part 
└─nvme0n1p9  259:7    0   2.1G  0 part 
```

/var/log/journal is empty
