### ISSUE TITLE
Allow passing a custom devcontainer URL to kola (and/or ideally allow using a local file)

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#976]
In mantle/kola's `devcontainer` tests, Kola currently [calculates the image URL of the dev container based on a restricted pattern](https://github.com/flatcar/mantle/blob/flatcar-master/kola/tests/devcontainer/devcontainer.go#L102). This makes it harder to run the dev container test  in local builds and in [GH action CI](https://github.com/flatcar/scripts/pull/684#issuecomment-1469248575).

This issue requests a change to kola to optionally take an arbitrary URL as a command line option to pull the dev container image from.

A stretch goal of this feature request is to enable kola to use a local file (stored on the host kola runs on) at least for QEMU tests (which run locally).

**Comment by tormath1** [comment]
I'm not familiar with the `devcontainer` test but having a customizable URL makes totally sense.

Two things:
* What would be the default value? According to the current value, we could set it to: `http://bincache.flatcar-linux.net/images/$ARCH/$VERSION`
* Here's an example to pass a flag from command line to the test itself: https://github.com/flatcar/mantle/pull/398/files

**Comment by krnowak** [comment]
This could follow the steps of the `--torcx-manifest` flag, which was created only to be used in one test (if I remember correctly). The new flag could just set the [ImageDirectoryURLTemplate](https://github.com/flatcar/mantle/blob/flatcar-master/kola/tests/devcontainer/devcontainer.go#L55) member of the [scriptTemplateParameters](https://github.com/flatcar/mantle/blob/flatcar-master/kola/tests/devcontainer/devcontainer.go#L38-L41) type to some custom value. That would mean that we would need to pass something else than [defaultScriptTemplateParameter](https://github.com/flatcar/mantle/blob/flatcar-master/kola/tests/devcontainer/devcontainer.go#L53-L56) in [test runners](https://github.com/flatcar/mantle/blob/flatcar-master/kola/tests/devcontainer/devcontainer.go#L231-L237).

**Comment by pothos** [comment]
For releases that are already published the release server works but that doesn't cover release testing where we should use bincache. So maybe a fallback to `https://CHANNEL.release.flatcar-linux.net/amd64-usr/VERSION/flatcar_developer_container.bin.bz2` would be good to keep tests passing even if we clean up bincache.
