### ISSUE TITLE
Make upstream systemd-sysext reload the units by default

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#984]
Make upstream systemd-sysext reload the units by default: `systemd-sysext refresh` should also issue a daemon-reload as done by `systemctl enable X`, this allows us to drop this line https://github.com/flatcar/init/blob/fbb1ec8e9d95598d65e4eac408dbc5f75b9b6138/systemd/system/ensure-sysext.service#L14

Since this will start units through `Upholds=` as upstream-supported way, document that mechanism in the systemd-sysext manpage.
@tormath1 mentioned that we should also look for any downsides compared to `Wants=`.
Edit: Filed https://github.com/systemd/systemd/issues/26896 for that.

**Comment by tormath1** [comment]
Upstream PR is merged.

**Comment by tormath1** [comment]
As the issue concern the upstream feature, I guess we can close this one?

**Comment by pothos** [comment]
Yes, thanks a lot!
Do we want to backport this when we update to 254?

**Comment by tormath1** [comment]
@pothos patch can be applied correctly against [`v254-stable`](https://github.com/systemd/systemd-stable/tree/v254-stable) - there is a trivial conflict on the `test/test-functions` but it can be cleanly solved by backporting this commit too: https://github.com/systemd/systemd/commit/b856f1dfc5bca0fbe60c37b7d0132a396c991270.
So yes, we can backport this during the update to 254 (and merge this: https://github.com/flatcar/init/pull/96)
