### ISSUE TITLE
*.release.flatcar-linux.net doesn't deliver whole certificate chain anymore

### ISSUE THREAD

**Issue by Thor77** [flatcar/Flatcar#988]
## Description

Since the renewal of the certificate on March 25 the webserver behind `*.release.flatcar-linux.net` doesn't deliver the whole certificate chain anymore which causes cert verification problems on clients.

## Impact

Clients might not be able to verify the certificate for stable/alpha/beta.release.flatcar-linux.net if they don't have the chain in their cache.

## Environment and steps to reproduce
```
$ openssl s_client -connect beta.release.flatcar-linux.net:443  
CONNECTED(00000003)
depth=0 CN = stable.release.flatcar-linux.net
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = stable.release.flatcar-linux.net
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN = stable.release.flatcar-linux.net
verify return:1
---
Certificate chain
 0 s:CN = stable.release.flatcar-linux.net
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Mar 25 11:41:09 2023 GMT; NotAfter: Jun 23 11:41:08 2023 GMT
---
```

## Expected behavior

Webserver delivers whole chain or at least the Let's Encrypt Intermediate CA in addition to the certificate.

**Comment by pothos** [comment]
Hello, thanks for creating the issue. A workaround is deployed and I hope to have it fixed in the next minutes.

**Comment by pothos** [comment]
Please tell if you still see problems, thanks again

**Comment by till** [comment]
@pothos Is it possible to get some alerting setup? Like a http check could serve as a monitor and a cheap test.

**Comment by Thor77** [comment]
@pothos looks good again, thanks!

**Comment by pothos** [comment]
There is a Prometheus setup, it needs some fixes for the alert sending…

**Comment by till** [comment]
> There is a Prometheus setup, it needs some fixes for the alert sending…
> 
> 

Like a blackbox exporter? Happy to send a PR too or help.
