### ISSUE TITLE
Publish new Alpha release 2492.0.0

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#99]
**Description**
We finished a number of improvements - inclusion of `conntrack` (#78 ) and the 5.4 kernel (#73 ) - which we want to stabilise and to make available to Flatcar Container Linux users. Releasing a new Alpha will start the stabilisation process for those features and make them available to Flatcar users.

Bug fixes:

- Support both guestinfo.ignition.config and guestinfo.coreos.config in coreos-cloudinit (https://github.com/flatcar-linux/coreos-cloudinit/pull/4)
- Fix VMware guestinfo variable retrieval and add missing variables in ignition (https://github.com/flatcar-linux/ignition/pull/11)
- Use flatcar.autologin for the console in oem-vmware (https://github.com/flatcar-linux/coreos-overlay/pull/308)
- Log list of coredumps with coredumpctl in mayday (https://github.com/flatcar-linux/mayday/pull/8)

Updates:

- Linux [5.4.35](https://lwn.net/Articles/818569/)
- Go [1.13.10](https://go.googlesource.com/go/+/refs/tags/go1.13.10)
- containerd [1.3.4](https://github.com/containerd/containerd/releases/tag/v1.3.4)
- conntrack-tools [1.4.5](https://git.netfilter.org/conntrack-tools/tag/?h=conntrack-tools-1.4.5)
- linux-firmware [20191022](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tag/?h=20191022)

**Comment by sayanchowdhury** [comment]
We would be doing the Flatcar Container Linux Alpha release `2492.0.0`

**Comment by dongsupark** [comment]
Updated the description to make it include the changelog.
